### ISSUE TITLE
Improve development of higher resolution games in AGS

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1009]
Recently, many different developers have looked into AGS with the expectation of using it for developing high resolution games - 1600x900 and 1920x1080 games. At the same time, they have reported different problems when using AGS regarding performance, either sprite loading is slow, or they hit memory limits, or they get stuttering animation.

At the same time, it's apparent AGS developers lacks a minimal game, even better if the project is open sourced, that uses high resolution assets where all these reported problems reproduce so profiling and testing can help trace bottlenecks. Note that this game project will be very big in size because of not only the assets, but also spritecache.

This issue is for gathering these reports so there can be discussion around this goal and linking related issues that already exist can be linked here and smaller tasks that enable reaching the goal of using AGS with high resolution assets and making high resolution games.

This issue is not about fundamental changes in how AGS works (no discussion on skeletal animation or vectorial games). Also issues with AGS Scripting or other possible performance issues, not related to these specific high resolution assets should not go here either.

forum posts: [1](https://www.adventuregamestudio.co.uk/forums/index.php?topic=57632.0), [2](https://www.adventuregamestudio.co.uk/forums/index.php?topic=57577.0), [3](https://www.adventuregamestudio.co.uk/forums/index.php?topic=54788.0), [4](https://www.adventuregamestudio.co.uk/forums/index.php?topic=50475.0), [5](https://www.adventuregamestudio.co.uk/forums/index.php?topic=53998.0), [6](https://www.adventuregamestudio.co.uk/forums/index.php?topic=51974.0).

Editor side:

-  [#702](https://github.com/adventuregamestudio/ags/issues/702) . Editor crashes when importing a large number of sprites 

Engine side: 

- [#969](https://github.com/adventuregamestudio/ags/issues/969) . Persistent "render data" for each drawable object in game 

**UPDATE:**

This issue was written a long time ago, these are some changes that happened in the meanwhile:

- Editor can now recreate the acsprset.spr file from sources, which means you don't need to push it to your git remote #1594
- Additional sprite compression based on palette is in, and LZW compression too #1461
- Hardware Accelerated GUIs has been added #1393
- Buffered streams for reading resources has been added too #756

**Comment by ivan-mogilko** [comment]
only a small note -
#702 will probably become obsolete, if we remake Editor to get sprites from disk directly, and only build sprite file as a part of assembling the game.
#969 is probably not much related, since it's more about data organization.

**Comment by ivan-mogilko** [comment]
**Only to outline basic directions (!!)**, following seem to be three main problems when dealing with high-res (and generally "resource-heavy") games:

* Disk space.
* Runtime memory.
* Runtime speed.

---

In regards to **disk space**, improving compression seem to be a natural choice, but at the same time it increases the speed problem, because for every compression there has to be a decompression (duh), unless we are talking about lossy compressions (but then this is something that AGS should not probably do on its own, and let user decide before importing an item into a project).

An alternate approach could be in finding ways of reusing assets and avoiding duplicate data where possible. This involves giving game developer both tips and instruments of doing so (I am just noting this as an abstract idea, because I don't have a practical example ready... ok, maybe something like #996, but in larger scale).

---

Regarding **runtime memory**, the primary idea is to keep as little in memory at once as convenient, but at the same time this has to be balanced with ability to load it up again when needed.
Creating runtime caches may reduce a need to keep alot of things in memory (e.g. see my old proposal here: #731), which may be also important if the game generates lots of data dynamically. Of course such caches increase disk space requirements...

There's an interesting idea discussed in the past on forums, where developer makes a graph for the game, defining connected areas, and when player moves around the game, the engine loads up data from neighbour areas and unloads/saves in temp files what has been left behind. This may not be a big priority here, but perhaps something to consider after we have a proper resource streaming system in the engine.

Again, there has to be no unnecessary duplicates. For example, right now the raw sprites (bitmaps) are shared between objects, but DDBs (textures) converted from a sprite *are not*, which is pretty silly and suboptimal (a ticket is a due).

---

For runtime speed, the solutions are in
a) decreasing number of steps between resources on disk and final form of said resources;
b) improving i/o operations times;
c) doing most load & preparations in background threads;
d) being able to prepare resources preliminarily, either automatically by analysing the game, or letting game developer to set up certain rules, for example, telling which items should be prepared for particular room in its script.

**NOTE:** I heard that @sonneveld was experimenting with buffered input streams and threaded resource loading, so probably there's already something being work on from the above list.

**Comment by ericoporto** [comment]
Regarding disk space, my main concern is the spritecache size for the developer making the game and the fact that he must store that in his/her source version control system, because it can't be rebuilt from the source images and an index in the Game.agf alone.

**Comment by rofl0r** [comment]
> the spritecache size for the developer making the game and the fact that he must store that in his/her source version control system

agsutils' agsprite tool can build sprindex.dat from input files in the FS

**Comment by ivan-mogilko** [comment]
> Regarding disk space, my main concern is the spritecache size for the developer making the game and the fact that he must store that in his/her source version control system, because it can't be rebuilt from the source images and an index in the Game.agf alone.

Rebuilding sprite cache was in plans for 3.5.0 development, but we did not fully implement this due to few internal workflow problems in the Editor. Eventually, @morganwillcock had a plan to remove sprite file from the project sources and only have it as an output. That should solve this problem.

**Comment by ericoporto** [comment]
Hey, since many pain points have since been solved, and it's hard to act without specifics, I am closing this one.
