### ISSUE TITLE
Custom say function option does not work as expected

### ISSUE THREAD

**Issue by ERolfi** [adventuregamestudio/ags#1020]
When defining a custom say function for dialog scripts in General Settings, the custom function applies only to the text defined inside the dialog script. But when marking the "options text" lines with the "say" checkbox, it's still printed using the original say function.

**Comment by ericoporto** [comment]
This is known and was written in the forums on the release page.

**Comment by ivan-mogilko** [comment]
@ERolfi Unfortunately I was not able to make the "Say" checkbox work yet, because it is processed differently from the script and requires special approach. Maybe this will be updated in the future.

For the time being, the workaround is to not use "say" checkbox, but duplicate the option text as the first cue in script.

**Comment by ivan-mogilko** [comment]
> This is known and was written in the forums on the release page.

It is not written on the release page... I forgot to add this information. Also need to check if it's correctly noted in the manual.

**Comment by ERolfi** [comment]
I checked the Dynamic help and it's not noted
