### ISSUE TITLE
8-bit sprites imported with wrong palette on Editor

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1030]
**Describe the bug**
Below is the description as reported by a user on Discord:

> Opening up AGS 3.5.0 for the first time in a while since I have a project to work on now and I need the custom resolution:
> - Palette is not updated until you exit and reload the game.
> 
> As in, sprites will be imported with the default palette with the wrong colours and the editor will treat the game like it had the previous palette until you close and reopen it.
> 
> It's doing something on opening the project its not doing after you import a palette.
> 
> It occurs even in guis where the colour of the default buttons is still the previous palette.
> 
> There is some function that is run on startup that needs to be run after every palette change and room opening.

**AGS Version**
3.5.0.23

**Expected behavior**
After changing palette, importing a sprite should use current palette on subsequent sprite imports.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 7

**Comment by ivan-mogilko** [comment]
NOTE: Scavenger said he was using AGS 3.2.1 for his projects, so it's not yet clear when the error was introduced.

**Comment by ivan-mogilko** [comment]
After discussing this with the user, here's the updated information and reproduction steps.

The problem is that **the palette changes done during an editor's session are not, _as it seems_, applied to the sprite import** until you reopen project. Sprites told to remap their colors to game palette _seem_ to remap not to latest palette, but to previous one instead. Unfortunately, due to how preview works with paletted images, it's not visible until you close and reopen a project.

Steps to reproduce:
1. Download provided 8-bit image: 
[HEADS.zip](https://github.com/adventuregamestudio/ags/files/4149740/HEADS.zip)
(I had to zip it, because github does not support attaching BMPs...)
2. Create a new empty project and set game to 8-bit colour depth.
3. Go to palette tab and import new palette (right click on color table, choose "Replace palette from file").
4. Select all the palette slots, by shift + clicking on first and last slot, and change their ColourType property to "Gamewide".
5. Go to the sprite manager and import same image with following settings:
  * Remap to game palette
  * Transparency from top-left pixel
6. Observe, at first glance, sprite was imported correctly.
7. Save the project, close editor, then reopen and load same project again.
8. Observe that the sprite now looks broken.
9. Import same sprite again (2), with the same settings.
10. Again, save the project, close editor, then reopen and load same project again.
11. Observe that the second sprite looks correct, as opposed to the first one.

Supposedly, this happens because first time the palette, although modified on the editor panel, was not applied to the internal table which is used when remapping sprite. It was only applied when reloading a project, and thus second sprite was imported correctly.

**NOTE:** I was able to reproduce this in AGS 3.2.1 as well, which means this is a very old bug, not a 3.5.0 regression.

**Comment by ivan-mogilko** [comment]
Made a pr: #1042

**Comment by ivan-mogilko** [comment]
#1042, will need confirmation from user.
