### ISSUE TITLE
Opening media files from big files (>2GB) still fails

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#1039]
The big file support was implemented in 3.5.0 (#493), but apparently there is still a case when it fails: when engine tries to get a media stream (audio or video) from CLIB pack (such as *.ags, *.exe, *.vox or else).

The reason for this, from what I could gather so far, is that the method relies on Allegro 4's packfile_open, which default implementation stores total file length as `long`, being 32-bit if built for 32-bit system (and this is what we use always on Windows btw) (**EDIT:** and actually iirc `long` is always 32-bit for MS compiler). I did not have a chance to test this on 64-bit Linux yet.

The possible solution might be to write a custom PACKFILE implementation, following Allegro's guidelines (afaik one should fill in [its virtual table](https://github.com/adventuregamestudio/lib-allegro/blob/allegro-4.4.3.1-agspatch/include/allegro/file.h#L127)).

**Known workarounds**

Editor supports splitting main game pack into number of partitions, which probably solves this problem so long as a partition with sounds is less than 2 GB.

Also, sounds and music may be played from standalone files in the game dir if audio.vox is not present.

---

Test game: 
[test-big-audiovox.zip (625 KB)](https://github.com/adventuregamestudio/ags/files/4969094/test-big-audiovox.zip)
**Warning:** contains a 500 MB file, but it's compressed very well because it has only zeroes inside.
Above game features 6 x 500 mb audio clips (these are invalid so don't try playing them) + 1 small valid clip.
Small clip is played by a key press.
Note that if you run from editor with F5, the clips will be read from AudioCache and sound will play. If you run a fully compiled game with audio.vox then the sound will not play.

**Comment by ericoporto** [comment]
I had a thought about adding CLIB package support on PhysFS and use it instead.

**Comment by ivan-mogilko** [comment]
I'd rather find a more conservative workaround for 3.5.1.

**Comment by ivan-mogilko** [comment]
In my opinion, moving to PhysFS is beyond the scope of 3.5.1, and that may also bring more changes to the engine.
For 3.5.1 I'd rather try if a more conservative workaround is possible.

**Comment by ericoporto** [comment]
> Like, in this case, it's not so much about CLIB itself, but about how sound-playing libraries work (how they access and read data).

Ah, this explains why this was done like you said instead of how I thought:
https://github.com/adventuregamestudio/ags/blob/51c20dcb2949de8f0ee7b647a28cee39429ce8d5/Common/util/stream.cpp#L252-L308

> For 3.5.1 I'd rather first try if a more conservative workaround is possible.

It's alright, just making more Allegro4 dependant increases the chances we keep patching Allegro4 for longer which reduces portability.

**Comment by ivan-mogilko** [comment]
Test game: 
[test-big-audiovox.zip (625 KB)](https://github.com/adventuregamestudio/ags/files/4969094/test-big-audiovox.zip)
**Warning:** contains a 500 MB file, but it's compressed very well because it has only zeroes inside.
Above game features 5 x 500 mb audio clips (these are invalid so don't try playing them) + 1 small valid clip.
Small clip is played by a key press.
Note that if you run from editor with F5, the clips will be read from AudioCache and sound will play. If you run a fully compiled game with audio.vox then the sound will not play.

**Comment by ivan-mogilko** [comment]
Opened pr: #1112
