### ISSUE TITLE
Unified configuration-reading routines

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#104]
There are several routines that read config file, one in the main engine code, others made for each mobile platform separately, and they read from differently named config file.
These files and functions should be unified as much as possible to avoid code duplication.

**Comment by ivan-mogilko** [comment]
Somehow I missed the comment above.
To elaborate, this issue is not about making single config for multiple games, it is about making single code for reading config file.
I will rename the issue to avoid further confusion.

**Comment by sonneveld** [comment]
Related to https://github.com/adventuregamestudio/ags/issues/106 in that the different ports could pass in a config tree instead of reading/writing psp_ variables.

**Comment by ivan-mogilko** [comment]
As an update: years later engine gathers all config options into ConfigTree map before applying it. Filling the ConfigTtree is done in multiple steps, and may include reading key/values from file or adding hard-coded values per platform, but IMHO the goal should be that in the end engine only applies values that are in this map.

**Comment by ericoporto** [comment]
Should `clear_cache_on_room_change` be added as a config under `misc` in acsetup.cfg?

**Comment by ivan-mogilko** [comment]
> Should clear_cache_on_room_change be added as a config under misc in acsetup.cfg?

Do you know what "cache" is this refering to? I suspect it might be the sound cache which is no longer present in the current code. If so, this option may be removed, until a cache is reintroduced.

**Comment by ericoporto** [comment]
ok, looks like this: https://github.com/ericoporto/ags/commit/f61566c859b608580475da54c2fdf2cc4aac4322

now, the missing things are
- **`[misc][rotation]`** : should we actually add this or just let it automatically figure out (find the better fit game resolution -> screen)
  - pros: if we ever do dynamic game resolution to screen size a thing it could be useful
  - cons: it's one more thing the game developer has to remember to properly configure
- **`[sound][cache_size]`** : we haven't implemented this yet, so it's easier to just remove it
- **`[midi][preload_patches]`** : I have no idea what this should do, currently does nothing, so will just remove
- **`[debug][logging]`** : originally made to write to Android logcat or not, I think we can assume the stdout in newer log config is logcat.
- **`[controls][mouse_method]`** : already currently implemented as `[mouse][control_enabled]` in acsetup, sets relative or direct mouse movement.
- **`[controls][mouse_longclick]`** : we haven't implemented yet in the Android port, this will require a manual translation from touch to mouse controls instead of using current SDL2 defaults. Can probably be removed and we add new things once touch->mouse is figured out.

**Comment by ivan-mogilko** [comment]
I don't have any opinion about rotation atm; but I think it should be in [graphics], where the display modes etc are.

Any additional log settings should go into [log] perhaps.

Not sure what "mouse method" means, could you elaborate on a difference between "relative" and "direct"?

**Comment by ericoporto** [comment]
right, in Android it can be either one of these two:

- **relative**, meaning the mouse is controled by touch and move finger to move cursor, and taping for click where the cursor is

![](https://i.imgur.com/bkJrXmp.gif)

- **direct**, touching the screen both move cursor and counts as mouse clicked, tapping clicks where the finger hit (and moves cursor there)

![](https://i.imgur.com/Eddb58m.gif)
