### ISSUE TITLE
Feature request: Room Overlays

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1044]
Room Overlays work exactly like Overlays in AGS, the difference is they exist in Room Space. Their transformations (coordinates, scaling, ...) are relative to the room, meaning, they are affected by Camera/Viewport. Overlays are the most thin and simple and direct elements in AGS, that are closer to a texture on the screen, so at the same time, there's a balance to not add more things to them to keep them simple, which is relevant to whether this should or should not be implemented.

Previously @ivan-mogilko has made [an experiment for Room Overlays](https://github.com/ivan-mogilko/ags-refactoring/commit/e91dbe5ad74861a9d39589e0d01433169d49a687) by using a property that when set would make the Overlay be in the room. I linked the code above because there are unanswered questions in the code comments that I believe are relevant. 

My usage of Room Overlays would be use them for particles and objects that have no animation but are created dynamically with the agsbox2d plugin.

I wonder if it's better to solve #967 before introducing these.

**Comment by ivan-mogilko** [comment]
Making overlays in rooms was trivial (as may be seen in linked code), but I was and still am reluctant about whole thing, because they are not matching the use intent:

> My usage of Room Overlays would be use them for particles and objects that have no animation but are created dynamically with the agsbox2d plugin.

Main issue here is that "overlays" have no control over their z-order, and they are only grouped together, and not sorted along with the other objects, would be GUI, or room objects (since we are discussing room overlays here). Actually, term "overlay" pretty much defines that this is something that is drawn above everything else.
My concern is that as soon as these "room overlays" are enabled, someone will ask to be able to put overlay between room objects.
If we agree that overlays are strictly above everything else, then this feature may be added, as a temporary solution. But proper flexible solution would probably require redefining entity class, if not whole scene structure in AGS (and then reimplementing overlay API using that new class for backward compatibility).

**Comment by ericoporto** [comment]
I am not opposed at changing something else structural before. Think on this issue as possibility enabled by this change.

**Comment by ivan-mogilko** [comment]
> let's talk about what we need to fix before it.

It's not about "fixing", it's more about "overhaul". AGS does not have an object type that would be as simple as overlay, created dynamically, but would have z-order and be able to integrate into same sorting and interaction stack as room objects or guis at the same time. Having such type would be one task.

On another hand, in current system there's no proper scene tree, similar to other engines. Without such tree support such new entity would be integrated using more hard-coded (and maybe hacky) behavior, which is possible but not good. This may be task number two.
But, ideally, all the AGS object management should be remade, at least internally, into being represented as a scene tree capable of having generic items. That could be task number three (unrelated to the order of execution).

**Comment by ivan-mogilko** [comment]
There was another ticket opened for room overlays since, with more detailed description: #1209, so I'll close this one as a duplicate.
