### ISSUE TITLE
Rename psp_* variables

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#106]
There's a whole bunch of global variables in the engine named with "psp_" prefix after PSP port. Since most of them is used generally now, they should be renamed, with this prefix removed, to avoid confusion.

**Comment by ericoporto** [comment]
https://github.com/adventuregamestudio/ags/blob/efa89736d868e9dfda4200149d33ba8637746399/Engine/gfx/gfx_util.cpp#L122-L128

this is one of the few `psp_` var on the outside of config and platform specific stuff, unfortunately it's in a hack. I tried to remove and run in a few android devices and it seems to not cause any disturbance, unfortunately I am not sure any of the games I tested could cause the need for such hack.

**Comment by ivan-mogilko** [comment]
> https://github.com/adventuregamestudio/ags/blob/efa89736d868e9dfda4200149d33ba8637746399/Engine/gfx/gfx_util.cpp#L122-L128
> 
> this is one of the few `psp_` var on the outside of config and platform specific stuff, unfortunately it's in a hack. 

Lol, reading this hack, it makes no sense whatsoever. Because `surface_depth = ds->GetColorDepth();`, so it basically compares `ds->GetBPP() < ds->GetColorDepth()` which is *always true*, as GetBPP returns number of bytes, while ColorDepth returns number bits.

So I say, remove this. If there are any problems, they likely may be fixed differently.

**Comment by ericoporto** [comment]
Some floating around psp_variables have been axed in recent commits

psp_gfx_renderer : https://github.com/adventuregamestudio/ags/commit/083d8496f2d7c0eedc31c068ddf27720dee4ff2b

psp_clear_cache_on_room_change : https://github.com/adventuregamestudio/ags/commit/7abbd673e910289511bcca3101abd03101599eb0

psp_video_framedrop: https://github.com/adventuregamestudio/ags/commit/6c10e6e5e16ec70f5d5986b23217dc5ebf13a70c 

I wonder if it makes sense to place the remaining ones in an object instead of using individual global vars since most of the remaining use cases is contained somewhat in their own platform driver code.

**Comment by ivan-mogilko** [comment]
> I wonder if it makes sense to place the remaining ones in an object instead of using individual global vars

I think they may be put into GameSetup struct.

**Comment by ericoporto** [comment]
> I think they may be put into GameSetup struct.

There are two TO-DOs in the GameSetup header that made me unsure if that's where these should go.

**Comment by ivan-mogilko** [comment]
It's the most logical place in this version of the code.

**Comment by ivan-mogilko** [comment]
I've looked into this quickly, and imo it might be possible to make a bigger change. Right now these variables are used practically as a medium to pass values from some ports' platform drivers (Android etc) into the engine. But we already have ConfigTree for that. So, I'm thinking, maybe we could add a platform driver method, like, ReadConfuration, and pass ConfigTree there from the engine to fill in directly.
