### ISSUE TITLE
Feature suggestion: Set Player Starting Position button in Room Editor

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1109]
[![player_begins_here](https://user-images.githubusercontent.com/2244442/88409453-819c2700-cdc4-11ea-836b-51395f17fc2b.gif)](https://streamable.com/cpkzxk)

Basic implementation: https://github.com/adventuregamestudio/ags/compare/master...ericoporto:feature-set-player-here-btn

**The problem:** When editing a game with many rooms you have to have build a reasonably good "level jumper" to be able to change the level when debugging the game. For most use cases (the ones where initial state of the room is fine), it is sufficient to simply change the player character starting level in the editor. For these cases, it would be even faster if it was possible to move the player character into the room editor directly instead of clicking to open it's properties, finding the room property in it, and then setting the initial room for the player character by browsing the combo box.

**Proposed solution:** a button that places the player character in the room loaded in the editor. The details on how this should work I have no idea.

**Alternate solution:** I have no idea how to implement, but would be dragging the player character from the Project Explorer and dropping in the room editor. The advantage of this method is it would be fairly easy to do this same way with other characters.

*Note:* essentially it's just to save some clicks but the idea is to make easy to click a room in editor and quickly reach being able to test it under debug (f5).

**Comment by ivan-mogilko** [comment]
Idk if possible, but I like the "alternate solution" much better. In fact, I'd call it the proper solution, as it's more consistent and does not require having an exclisive UI for one casual operation.

**Comment by persn** [comment]
The proposed solution would be a proper solution if it solved a more generic use case instead of explicitly player characters. Let's say we instead added 2 buttons, one for adding characters to the room, and one button for removing characters to the room, similarly there could be an equivalent button for objects. Also if we ever changed hotspots, walkable, walkbehinds and regions to be added and removed dynamically instead of as a prefixed list they could also have add/remove buttons (but that's probably a discussion for another day).

The add character button could open a dialog that shows a dropdown box with all characters not already added to the room, the default item would be the player character, and it would also have options for selecting x and y coords as shown in the video. The remove button would open a dialog that shows the characters already added to the room.

The alternate solution could also be implemented as a convenience feature, no reason to not have both, except time and willpower.

**Comment by ivan-mogilko** [comment]
Imho, if it's about universal solution for adding/removing everything, then it should not be made as a casual button on the panel, but as a part of a more convenient overview UI, which would allow to see the list of existing objects, add and remove them.
For example, new navigation bar had + and - buttons initially, but I removed them for the time being, for various reasons.

Also, I doubt if coordinate fields are necessary there, as you may drag and drop newly added character/object in the room editor itself.

**Comment by persn** [comment]
> For example, new navigation bar had + and - buttons initially

That's also a good place to have the buttons, I don't have strong opinions about where the buttons should go at this time

> Also, I doubt if coordinate fields are necessary there, as you may drag and drop newly added character/object in the room editor itself.

Good point, then let's not have them at the dialog to make it simpler.

**Comment by ivan-mogilko** [comment]
@ericoporto something I forgot to ask, do you know about "Debug(3,0)" script command that teleports to any room at runtime?

**Comment by ericoporto** [comment]
> @ericoporto something I forgot to ask, do you know about "Debug(3,0)" script command that teleports to any room at runtime?
A combination of Debug(3,0) and player.PlaceOnWalkableArea called at some keypress may be used as a workaround too

Yes, I actually use a variation of it I built myself in my main game. I have around 100 rooms so I built a more visual that jumps between "game regions" and have a function to preset "appropriate conditions" for each room (like, inventory items you are supposed to have at that point in time).

But I recently made a new game project and was curious if something from the editor would be possible. This is actually from old RPG Maker 2000, where you could right click anywhere on the map (the room) and select "set party starting position" in the context menu to set that tile (the point) as the player starting position.
