### ISSUE TITLE
Unexpected behaviour when using hotspot walkTo feature

### ISSUE THREAD

**Issue by ERolfi** [adventuregamestudio/ags#1129]
**Describe the bug**
When a walkTo point for an hotspot exists, and also an "Any click on hotspot" event function is defined, the player will walk to the WalkTo point in blocking mode (walking cannot be halted). 

**AGS Version**
3.5.0.22

**Game**
9verbs template game

**To Reproduce**
0. Define a walkTo point fot the door Hotspot and an "any click on Hotspot" event function
1. The player clicks the Hotspot
2. on_mouse_click() triggers 
3. Room.ProcessClick (x, y, GSagsusedmode) is called

**Expected behavior**
It would be desirable to have an option to walkTo an Hotspot in non-blocking mode.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Linux

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ivan-mogilko** [comment]
This is not a bug but actually an expected behavior, how this feature was originally planned: if WalkTo point is set then any interaction with hotspot would make player walk to it.

If you think this is undesirable, could you elaborate on your use case? How are you trying to use WalkTo property if you don't want player to walk there?

**Comment by ivan-mogilko** [comment]
This is not a bug, but actually is the expected behavior, how the feature is originally planned: if WalkTo property is defined, then **any** interaction with hotspot makes player walk to it.
The only exception is "Look" verb, it's controlled by a switch in General Setting "Automatically walk to hotspots in Look mode".


UPDATE:
After investigating little more I found there's actually a script variable `game.auto_use_walkto_points` that turns auto walking off. Maybe you could use that.

**Comment by ERolfi** [comment]
Thank you for your deep analysis. I thought that it was easy to add such an option. In the end, I was able to code the described behaviour in my script.
