### ISSUE TITLE
winsetup always writes resolution specific config changes

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#1153]
Initial configuration in the game directory:
```ini
[misc]
game_width=320
game_height=200
gamecolordepth=32
antialias=0
notruecolor=0
cachemax=131072
user_data_dir=
shared_data_dir=
titletext=BASS Setup
[graphics]
driver=D3D9
windowed=0
screen_def=max
game_scale_fs=proportional
game_scale_win=max_round
filter=stdscale
vsync=0
render_at_screenres=0
[sound]
digiid=-1
midiid=-1
threaded=0
usespeech=1
[language]
translation=
[mouse]
auto_lock=0
speed=1
```
Open winsetup, press save, now look at the user config file:
```ini
[graphics]
driver=D3D9
filter=StdScale
game_scale_fs=proportional
game_scale_win=max_round
refresh=0
render_at_screenres=0
screen_def=explicit
screen_height=1200
screen_width=1920
vsync=0
windowed=0
[language]
translation=
[misc]
antialias=0
cachemax=131072
user_data_dir=
[mouse]
auto_lock=0
speed=1.0
[sound]
digiid=AUTO
midiid=AUTO
threaded=0
usespeech=1
```
The differences being:
```
-digiid=-1
+digiid=AUTO
-filter=stdscale
+filter=StdScale
-gamecolordepth=32
-game_height=200
-game_width=320
-midiid=-1
+midiid=AUTO
-notruecolor=0
+refresh=0
+screen_def=explicit
-screen_def=max
+screen_height=1200
+screen_width=1920
-shared_data_dir=
-speed=1
+speed=1.0
-titletext=BASS Setup
```
So 5 of them have been modiied:
```
digiid
filter
midiid
screen_def
speed
```
One of these is not representative of the previous value:
```
-screen_def=max
+screen_def=explicit
```
...and the two additional values (which might be argued to make the change be equivalent) have made the config be specific to the display/desktop resolution that was in use at the time.
```
+screen_height=1200
+screen_width=1920
```

Tested with 3.5.0.27

**Comment by ivan-mogilko** [comment]
This is a known issue, and has been since this new gfx setup was introduced. This is because some of these settings were wrong idea and should not be there and/or do not have proper equivalents in winsetup.

**Comment by ivan-mogilko** [comment]
@morganwillcock I spent few days pondering at this.

There's definitely a number of option combinations that winsetup does not cover. Having fullscreen mode set to "max" is perhaps the most important, because it's the only way to tell "use current desktop resolution". Adding this to winsetup would be very easy: just another option in resolution list.
(arguably "max" is not the best way to describe the option, as desktop resolution is not necessarily the "maximal" possible with user system, but this is probably remains of some other idea which I did not fix in time)

Still there are multiple other variants missing, most of which are probably redundant, like fullscreen mode defined by game scaling factor.
One of them is using "max" to define windowed mode. Right now winsetup does not let create windowed mode where game image would be less than window. For example: make maximal possible window on current desktop, but have game scaled up to only max round factor with black borders around. I left it out because did not believe users would intentionally like to have something like that in windowed mode.
In order to support this I'd have to adjust winsetup more, add explicit selection of windowed mode, for example, between "max" and "by scaling". Which in current setup will also enable weird combinations like "max window" + "game not scaled".
So, I have strong doubts this makes any sense to add now.

I was planning to change the way gfx mode is set to disable silly combinations and also make it faster to type by hand in config file. But now it seems it might be better to leave it for version 3.6.0 (sdl2-based), where we have resizable window support and where it will be more needed and give more benefit.

**Comment by ivan-mogilko** [comment]
A notable consequence of adding such option is, though, loading existing configs will switch these to explicit resolution setting in winsetup.

**Comment by ivan-mogilko** [comment]
I pushed a commit b1e506932c7c9f2192e2254604146ae775283642

**Comment by ivan-mogilko** [comment]
@morganwillcock , could you tell if above fix is resolving this particular problem?

**Comment by morganwillcock** [comment]
`screen_def` now keeps the original value 'max' although `screen_height` and `screen_width` are still set to the desktop resolution. I imagine this is what you intended?

**Comment by ivan-mogilko** [comment]
>  although screen_height and screen_width are still set to the desktop resolution. I imagine this is what you intended?

Yes, as I was not going change that it saves these two options at all the time. But I also was not sure whether other approaches are better. If it leaves those then the config will have "max" and then irrelevant "width, height" values. If it removes these someone may argue that it should not remove data that someone else could've put there by hand.

I think the best solution would be to merge these multiple options into one, then each change would naturally replace one value with another, but I'd leave such change for version 3.6.0, as it will require certain changes in gfx config anyway (because it supports resizable windows).

**Comment by ivan-mogilko** [comment]
Well, guess I'll close this when, assuming there will be more improvement done for 3.6.0.
