### ISSUE TITLE
--tell-config returns undocumented values for [misc]

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#1154]
The following values are not documented in https://github.com/adventuregamestudio/ags/blob/master/OPTIONS.md but are returned as part of the configuration data when using `--tell-config`:

```ini
[misc]
defaultres
game_height
game_width
gamecolordepth
letterbox
notruecolor
```

Presuambly the values which begin with 'game' are not actually configuration values?

Tested with 3.5.0.27

**Comment by ivan-mogilko** [comment]
These values are sent into setup program as hints, they were added to config because that was easiest thing to do at the time (or maybe they were written by editor into config file in the past too).
The possible solution may be to split them out into separate parameter for winsetup. But then we also need to make sure they are available as part of another "tell", because they may be useful for an external setup program.

**Comment by ivan-mogilko** [comment]
For the reference, here's full list of values added to config tree by the engine:
https://github.com/adventuregamestudio/ags/blob/master/Engine/main/engine.cpp#L1354

Because these may be interesting for setup program, I believe they should be printed as a dedicated --tell command instead.

**Comment by ivan-mogilko** [comment]
@morganwillcock opened #1160, please test if that works for you
