### ISSUE TITLE
android dockerfile: required file no longer exists

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1187]
for the file mentioned here
https://github.com/adventuregamestudio/ags/blob/master/ci/android/Dockerfile#L72 i get a 404.

+ wget https://www.apache.org/dist/ant/binaries/apache-ant-1.10.7-bin.tar.gz
HTTP request sent, awaiting response... 404 Not Found
2021-01-25 18:53:37 ERROR 404: Not Found.

the oldest version on that ftp directory is 1.10.9

it's odd that CI still works with that failing in the dockerfile...

**Comment by rofl0r** [comment]
thinking about it, i could imagine that cirrus has the image of the docker container cached, since it would take a long time to regenerate this for every commit. would be interesting to know whether it would still work with ant 1.10.9, though as it appears that apache is removing downloads of older binary releases, this file should be hosted somewhere else ASAP in case it is compatible.

**Comment by ericoporto** [comment]
It's indeed cached, but it should work 1.10.9, if you want to try, you can change that version number to the one that produces the valid URL, and do a PR, this should trigger a rebuild of the Docker. Don't worry, even if something else fails this won't invalidate the cache of our current Dockerfile. The caching uses a hash of the Dockerfile as it's index and you can also pull images locally for inspection - if you look into the Cirrus-CI screen you can see the URL for the hash image used. Cirrus doesn't drop cache usually - unless we ask for.

Android through Ant though is unsupported by AOSP, Google and our CI provider - you can look into Cirrus-CI documentation for Android and it explains how Android apps should be built there. It's useful to migrate the build tools because this allows taking advantage of proper test runners and following modern Android practices are required to get apps accepted in Google Play store, which is a source of income for game developers.

**Comment by rofl0r** [comment]
> Android through Ant though is unsupported by AOSP, Google and our CI provider - you can look into Cirrus-CI documentation for Android and it explains how Android apps should be built there. It's useful to migrate the build tools because this allows taking advantage of proper test runners and following modern Android practices are required to get apps accepted in Google Play store, which is a source of income for game developers.

lol, i was actually looking into that to create my own suckless toolchain to create android apps without java for my own use (without app store), and was positively surprised that ags uses a custom framework setup that supports old android versions, unlike most other ci docker files.

> Don't worry, even if something else fails this won't invalidate the cache of our current Dockerfile.

cool, will file a PR then.

**Comment by ericoporto** [comment]
If you haven't done anything in Java, all tools suck. And development for Google is like this: they release some beta code, and they are terrible, and then once you learn the workaround they switch in a way that everything is obsolete and repeat it to infinity. Also if anything is stable and good they will just stop working on that at some point and not tell anyone. But ant is terrible, when Google shoved people to use it in Android everyone was on Maven - which is terrible too, but Google ignored it. And now the tool is Gradle. Don't get your hopes up with Android. There's a project called F-Droid that tries to make things happier. In the future I think it should be possible to move the settings app in the cpp part of the code to avoid having to keep up with Android Java parts - since things were single activity, then they moved to multi-activity, and now they moved to single activity again. Google also doesn't like Java since the Oracle debacle, Oracle decided to move Java in one direction, and Google has their own jvm (why not, right???), called Dalvik. The documentation on all of this is terrible and often contradictory so I may have miss written something. The only good thing is they have a new language now called Kotlin that is a lot nicer than Java to use - it's very similar to Rust, which is my favorite language. Kotlin also tries to give errors at compile time, and it compiles in a way that is interoperable with Java - like if someone wrote a new language that built for AGS Assembly. 

I cannot wait until Linux phones are a thing - I use Android and all the tools but everything suck. And Google has the Play Store to force their hand.

**Comment by rofl0r** [comment]
my toolchain idea was basically to extract the bionic libc from google's website and then build an own gcc-based C/C++ toolchain, and disassemble the java stub needed to run native code as created for a random app, e.g. ags, and then write a smali assembler in C so one can modify the java loader using bytecode/asm and a C-based toolchain instead of all the java crap. it's interesting to have a toolchain for this OS as there are tons of used devices on the market which one can buy as cheap as $5, and could be turned into a mediacenter or something like that (android devices seem to have huge battery capacity once you turn off wifi, 3g, etc, additionally good resolution and quite fast cpus)

**Comment by ericoporto** [comment]
Your idea reminds of this project: https://github.com/cnlohr/rawdrawandroid

**Comment by rofl0r** [comment]
thanks, that link is very interesting and will probably help with my project...i wonder why i didn't find it myself when i spent almost a day investigating whether there are existing alternative approaches to building android apps...

**Comment by ericoporto** [comment]
I think that person did a write up somewhere explaining more, I don't remember much. If you do use his "framework" you will probably get it going very fast. I also think his code was very lean. It's the most updated project I know.

One thing interesting is that Google Play Games has a cpp API, so you could even get achievements, save sync and other things from Google without Java if you wanted. 

The hard part (in C) is Play Services - needed to fetch the game assets. Google Play makes you have an app with minimum size, nowadays an .aap bundle, which the store process and generates device tuned apk that are available for each device, this is what one installs and can be at most 100MB but they really want smaller - for an AGS game this is just the runtime. Then the assets, which are divided in two parts, an obb package that goes to a location only writeable by playstore and a patch, which can be used to modify this asset and provide incremental updates. For AGS .ags files and .vox packages and all, they go there. Assets are unlimited in size. This is one of the features that the single game launcher needs - I already have this stuff written for old Android and use but I need to update now for the changes that happened in the API - it's on my teafortwo repository. I want to try packing this and the runtime in two .aar file and figure the minimum things to squish the two libraries, wrap in a new manifest and package a game from this, including game icon and all.

Anyway, for the "official" AGS Engine, I do believe sticking with SDL2 and the existing Java/Kotlin parts is a better bet for long term - Google just changes their minds too much... But the pure C/C++ route is interesting and you should go for it too! Android can be very rewarding experience when other people are installing and running your things!

**Comment by rofl0r** [comment]
closing as PR #1189 was merged.
