### ISSUE TITLE
New compiler: issues with `string`

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1203]
@fernewelten 

The old-style `string` type has some issues with the new compiler. It seems that it disables creation of `string` variables in script, however this type is still used within script API, and may be used as function type or argument.

I think it's internally equivalent to `const char*`, and its use as a function argument for instance is a way to pass string literals without allocating managed String object. (Same goes for using `string` as return type, even though it's not used alot in contemporary script API)

1. First of all, when I try to create a `string` variable, compiler throws following error:
`Error: Type 'string' is no longer supported; use String instead`
I understand what this means, but at the same time think it would be better to clarify that allocation of variables of this type is not supported, as the type itself seems supported, and even used in script API.

2. `const string` is not properly recognized as a function return value, it seems to be parsed as simply `string`.

Example:
<pre>
const string GetLiteral()
{
    return "string literal";
}
</pre>
This results in error: `Error: Type mismatch: cannot convert 'const string' to 'string'`

Curiously enough, following works though:
<pre>
import void UseLiteral(const string s);

function game_start()
{
    UseLiteral("string literal");
}
</pre>

Another consequence of this is that it's actually possible to pass `const string` into function that requires non-const `string` argument:
<pre>
import const string GetConstString();
import void UseString(string s);

function game_start()
{
    UseString(GetConstString());
}
</pre>
This is compiled without errors, which is incorrect.
Although in ags4 API we no longer have functions that can modify old `string`, but since type is supported I think it would be proper to make it consistent.

**PS.** The reason I brought this up is that there's at least one function in script API that returns `string` by mistake (#830), and I want to replace it either with `String` or `const string`. Latter would save some managed memory so may be preferrable, considering there are still a number of functions that accept `const string` as arguments (Display, etc).

**Comment by fernewelten** [comment]
Nothing is hard-coded here. There's a compile-time flag, namely `SCOPT_OLDSTRINGS` defined in `Common/script/cc_options.h` that forbids or allows the type "string". This is the same mechanism as the one that sometimes forbids overrides of imports. The caller is supposed to call `ccSetOptions(SCOPT_OLDSTRINGS, true)` before calling the compiler if they want `string` to be allowed.

As far as I remember, I copied the logic exactly from the other compiler, even the exact error message. This was a long time ago; I might not have noticed some changes that happened in the meantime, or I might have made a copying mistake..

In any case, it's easy to take out the logic that forbids `string`.

**Comment by ivan-mogilko** [comment]
I did not realize this is because of SCOPT_OLDSTRINGS, now it makes more sense. Ofcourse I wont be able to test this in ags4 branch, because this switch was removed from the user settings, but I confirmed that this is how old compiler works in 3.5.0.

>  So what logic do we want?

It's fine to keep SCOPT_OLDSTRINGS working as it is now, but I wonder if it would be possible to fix compiler confusing `string` and `const string` function return types, because these still may be used.

**Comment by rofl0r** [comment]
> there's at least one function in script API that returns string by mistake (#830), and I want to replace it either with String or const string

btw, the usual way to do this in a backwards compatible way (e.g. in system libraries like libogg) is to add the new/changed API under a different name, e.g. if the API was called "StringFunc" a new API "StringFunc2" would be added, so instead of having a lot of if(new_script_api_v352) splattered in the code the old func would stay identical and old code would continue working without intervention by the game designer. however this is now kinda moot since it was done wrong right from the start (already long before AGS3 came out), and backwards-compatible ags3 branch is no longer receiving updates as far as i know. but maybe something to keep in mind for ags4.

**Comment by ivan-mogilko** [comment]
@rofl0r I very well aware of that convention, but majority of changed functions so far iirc had only arguments added to the end of the list, so it was possible to keep using same function name, and keep old script working. The engine has a mechanism that allows to link different implementations to same name but with different number of arguments - for this particular reason.
Another concern which I usually have is that I worry how regular users of AGS would react to having functions with names like Func2, FuncEx and so on. We may try this ofcourse if there would be more significant changes in the future.

In the above case however, my point is that the function must not be allowed to return non-const string at all, because, as explained in the ticket, this would allow to corrupt engine's internal memory.

**Comment by fernewelten** [comment]
When the compile-time flag `SCOPT_OLDSTRINGS` is unset, then the compiler specifically forbids __variables__ of type `string`. __Parameters__ of type `string` are fine, no matter how the compile-time flag is set. At least that's the current logic AFAICS.

That said, if `SCOPT_OLDSTRINGS` is unset then it is impossible to __use__ any function that has a non-`const` `string` parameter -- because it's impossible to pass anything for that parameter. You can neither pass a `string` literal nor a `String` variable nor a 'string' variable (because the last one can't be defined) . Thus the function is forbidden in practice. That goes for `StrCopy()` and similar functions.

**Comment by ivan-mogilko** [comment]
I'm very well aware of above rules. But I am reporting a compiler bug...

**Comment by ivan-mogilko** [comment]
> then it is impossible to use any function that has a non-const string parameter -- because it's impossible to pass anything for that parameter. You can neither pass a string literal nor a String variable nor a string variable

But in my first post in this ticket I've illustrated that it *is possible* to do, without getting any compiler error.

**Comment by fernewelten** [comment]
Addressed in #1207,

I'm also changing the error message to make it a bit more specific.

**Comment by ivan-mogilko** [comment]
Fixed by #1207.
