### ISSUE TITLE
Allow chaining functions in AGS Script

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1210]
There are times that we know a function cannot return a null object, and in this use cases, it's useful to do method chaining.

Below is valid AGS Script code:
```AGS Script
String s = "Hello ";
s = s.Append("World");
s = s.Truncate (5);
```

Now with method chaining:
```AGS Script
String s = "Hello ";
s = s.Append("World").Truncate (5);
```

This is sometimes a useful interface to provide in objects when designing Script modules. But for now method chaining won't compile.

If functions have no parameters, we can do method chaining by hiding them in attributes, so it appears it would be alright having this being a valid usage.

**Comment by ivan-mogilko** [comment]
Are you saying this does not work?

**Comment by ivan-mogilko** [comment]
Ok, so, old compiler has number of bugs related to chaining functions. I found at least 2 different errors. In addition to the one described above, following code:
<pre>
managed struct MyStruct
{
	import void Test();
};

MyStruct* GetMyStruct()
{
	return new MyStruct;
}

GetMyStruct().Test();
</pre>

causes error: `expected semicolon after ')'`


The new compiler in ags4 branch works fine with either scripts, and chained String functions produce correct result at runtime.

**Comment by ericoporto** [comment]
Ah, cool, so it's solved already! I didn't knew it was solved. I haven't tested ags4 in a while, is the autocomplete aware of this?

**Comment by fernewelten** [comment]
I haven't tried changing the autocomplete; I don't know how it is configured and I haven't found much information about that online. But AFAICS, the configuration file begins with some nebulous comment claiming that something has gone out of whack (or a similar description), so it would be nice if that got fixed.

The thing that I did notice on AGS3 is that autocomplete doesn't grok `readonly` properly. When you do `int myvar;` in the editor, then the variable `myvar` will be found and offered for autocomplete below that point in code. When you do `readonly int myvar`, however, `myvar` won't be recognized.

**Comment by fernewelten** [comment]
As concerns function calls, or expressions in general, the approaches of the compilers are a bit different, although the ideas are still quite similar.

The other compiler copies the symbols of the expression and then works on the copy. When it looks up variables and functions in an access term such as `a.b()`, it copies the whole sequence again, breaking it apart at the `.` and copying the individual parts into an array. Then afterwards, it processes the array.

The new compiler keeps track of partial expressions without making physical copies of them; and it processes access sequences such as `a.b.c().d()` in a loop, by scanning ahead to the next respective `.` and processing what's in between the `.` without keeping the rest of the expression around. 

One small consequence that might perhaps be noticeable is that when an erroneous expression spans several lines, then the new compiler will halt on individual lines within an expression to point out errors. The old compiler can't do that because the expression is copied before it is parsed and so the information is lost as to what symbols are on what source lines.

**Comment by ericoporto** [comment]
Since it's solved in the new compiler, for me this issue can be closed. Thanks for the explanation @fernewelten !
