### ISSUE TITLE
Native resolution misdetected

### ISSUE THREAD

**Issue by HunterZ** [adventuregamestudio/ags#1211]
**Describe the bug**
When trying to run the released version of Infamous Adventures/Quests King's Quest 3 remake using the AGS v3.5.0.30 engine, it misdetects the game's native resolution as 320x200x16bpp instead of also supporting 640x400x16bpp. As a result, higher-resolution character talking portraits are not displayed.

**AGS Version**
Original game: v2.71.
Attempting to run with: v3.5.0.30.

**Game**
https://infamousadventures.itch.io/kings-quest-iii-vga-remake

**To Reproduce**
1. Unpack the game
2. Copy AGS3 runtime to game folder
3. Run AGS3 setup
4. Run game
5. Watch intro or walk into house to trigger a conversation

**Expected behavior**
640x400 resolution based character speech portraits are used with otherwise 320x200 assets.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Also tried "upscale mode" but it was a disaster: Sprites were misplaced and incorrectly scaled, and my character wouldn't move at the start of the game.

**Comment by ivan-mogilko** [comment]
Since resolution switch was removed somewhere around early 3.* versions, "upscale" mode was added later to replicate old behavior, but I undestand so that it's currently broken. There were number of code refactor done over the old-style native coordinate handling, so something could be broken there too.

Either existing upscale mode should be fixed, or another method to switch between low-res and high-res assets invented for these old games.

**Comment by ivan-mogilko** [comment]
Fixed "upscale mode" (900f47bddd7ca6aa953b58d6b7f3d56fbb7e2c4c, 3ed4b74afbe24f902391198bd19c7fd8144dd130).

The engine build may be downloaded from the ci server for now (after it's done building):
https://cirrus-ci.com/build/6605008209707008

**Comment by ivan-mogilko** [comment]
Perhaps it's possible to read deprecated values "defaultres" and "screenres" from config and use them as a hint to run upscale automatically. I'd have to check these out again because don't remember how they work anymore.

Maybe "upscale" parameter could be renamed into something more obvious too, just dont know what yet.

**Comment by ivan-mogilko** [comment]
Added detection of upscale mode in legacy game's config: 14609109451d19cacbe7df5c78dd5dd92c50b961
