### ISSUE TITLE
3.5.* engine fails to play avi videos (xvid, indeo5) in fullscreen on win10x64

### ISSUE THREAD

**Issue by necros2k7** [adventuregamestudio/ags#1225]
**Describe the bug**
Latest nightlies don`t support avi videos playback (xvid, indeo5) win10x64
Black screen just sound

**AGS Version**
Latest nightly

**Game**
http://www.wseas.us/e-library/conferences/2007istanbul/papers/Diamonds%20in%20the%20Rough%20Demo.exe

**To Reproduce**
1. Run above game with latest runtime
2. See no picture with intro video

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Win
 - Version 10x64

**Comment by ivan-mogilko** [comment]
SDL version does not support AVI files anymore.

Original AGS only supported them where they are supported by system codecs. This was actually a reason I had to cut it out in SDL branch, as it's non portable and is relying on very particular OS interfaces, basically OS and what's installed there.

Legacy branch still suppose to play them, but again it's important to find out if reasons it fails are not related to codecs not installed / not working on system.

**Comment by ivan-mogilko** [comment]
Tested this will the master branch, and it works for me on Windows 7.

**Comment by necros2k7** [comment]
It plays fullscreen OK with original exe
I got https://cirrus-ci.com/task/4800094710005760 and you were right it plays OK in window mode but black picture in fullscreen

**Comment by ivan-mogilko** [comment]
Please tell, which graphics driver to you set in config?

**Comment by necros2k7** [comment]
D3D

**Comment by ivan-mogilko** [comment]
Well, I honestly don't know, I tested this with master branch and video works in fullscreen for Direct3D. It skips with error with OpenGL driver, because avi support is done through DirectX interface. And I cannot test software (DirectDraw) mode because it no longer works in fullscreen on my system (or maybe it depends on my video card).

I also don't know what could be a reason this works in windowed d3d but not fullscreen.

Could you double check that it's direct 3d running? You may do this by pressing Ctrl + Alt + V during game - that prints some engine info on screen.

Can anyone else test this?

**Comment by necros2k7** [comment]
Can you direct link to binary you used to run? (master branch)

**Comment by necros2k7** [comment]
![run](https://user-images.githubusercontent.com/16452453/109933359-cd825780-7d27-11eb-87f0-005664f01c6f.png)
black screen fullscreen during into (sound playback is OK)

**Comment by ivan-mogilko** [comment]
> Can you direct link to binary you used to run? (master branch)

I am building it myself, but any recent build from <https://cirrus-ci.com/github/adventuregamestudio/ags> which sais "master" should work

**Comment by necros2k7** [comment]
Now downloaded binary from https://cirrus-ci.com/task/5116591182446592 still black screen. Maybe i`ts win10 codec problem you mentioned earlier? If so, how to fix it? My vid-  Nvidia GTX 950 461.40 driver

**Comment by ivan-mogilko** [comment]
If it were codec problem then you would not be able to have video in fullscreen when running old exe. I doubt you will see video at all even in windowed mode. No, something else is wrong.

**Comment by necros2k7** [comment]
Software rendering video playback is OK, OpenGL - Video playback error window

**Comment by ivan-mogilko** [comment]
Could never reproduce or find what the problem is here. In any case, avi videos are a little priority for us.
Current support is discontinued since [3.6.0](https://github.com/adventuregamestudio/ags/releases/tag/v.3.6.0.47) (please see issue #1758 for some more information on this).
The workaround is to convert video file to OGV, while keeping its full file name - that would allow 3.6.0 to run it instead.
