### ISSUE TITLE
Crash in The Adventures of Fatman (2003 version or 2004 demo)

### ISSUE THREAD

**Issue by dreammaster** [adventuregamestudio/ags#1257]
I got a reported crash during the introduction sequence for The Adventures of Fatman, just after the goon is blown up by an explosion. I was able to replicate it in the demo (handy, since I don't have the full game), and then verified it also crashed the current stand-alone interpreter.

To work around it, I applied the commit d430a9295b20ea27ec6b8bbc8ed35bcd09fcc0eb
Which basically changes the two quitprintf in _displaySpeech for "invalid view frame" and "invalid speech frame" to returns (with an #if wrapper to make it easier to find it in the future if I ever update the codebase but want to identify workarounds to keep).

**Comment by rofl0r** [comment]
got a link to that demo handy ?

**Comment by ivan-mogilko** [comment]
I have an impression of already fixing something along these lines, this was because function was checking for speech view while the speaking character was invisible (and therefore speech view was not necessary). Either this was in another function, or code was lost somehow... Wonder if Fatman has the similar reason.

**Comment by ivan-mogilko** [comment]
The demo may be found in agsarchives torrent, as "games/2004/fatman_demo.zip" (29.3 MB).

**Comment by rofl0r** [comment]
> The demo may be found in agsarchives torrent, as "games/2004/fatman_demo.zip" (29.3 MB).

oh thanks for digging that up. i do actually have that entire archive, and if my upload speed was sufficient i'd actually just attach it to a comment here for convenience, as the owner of github seems to have tons of perma storage available for our pleasure :)

**Comment by ivan-mogilko** [comment]
@dreammaster sorry for such a long delay, after looking into this it seems like there's already has been a "fixup" few lines above both of these `quitprintfs`:

https://github.com/scummvm/scummvm/blob/master/engines/ags/engine/ac/character.cpp#L2382
https://github.com/scummvm/scummvm/blob/master/engines/ags/engine/ac/character.cpp#L2624

What seems to be a good solution is to also move a frame count check there, so that if the speech view loop has no frames, engine will also switch to loop 0. This way the speech line will still be displayed: 
08aef03ac693c28cc632f566d0a3a17dba48e157

(there's some nasty code duplication, but the whole function is nasty...)

**Comment by dreammaster** [comment]
Thanks for the cleaner fix. I've since verified that it fixes the problem, and reverted my own older workaround.
