### ISSUE TITLE
Character.z does not scale

### ISSUE THREAD

**Issue by messengerbag** [adventuregamestudio/ags#1304]
**Describe the bug**
`Character.z` defines the point where the character "connects with the ground" (measured from the bottom of the sprite). In other words, how many pixels above/below the bottom of the sprite the character's Y-position is. Typical use-cases:

-When the feet of the character are not at the bottom of the sprite (e.g. character has a shadow)
-To make a character levitate or even sink into the ground (combined with a suitable walkbehind)

However, AGS does not scale `Character.z` when the character scales. This means that the z-offset is too large when the character is scaled down, and too small when it is scaled up. See [this thread](https://www.adventuregamestudio.co.uk/forums/index.php?topic=57776.0)

I hold that this is _never_ the appropriate behavior, and therefore an AGS bug.

**Expected behavior**
`Character.Z` should scale proportionally with the size of the character.

**Additional context**
Because of rounding, there might potentially be some jittering in the vertical positioning of the character that is moving vertically while scaling gradually.

**Comment by ivan-mogilko** [comment]
I think this may be merged with view offsets (Character.LockViewOffset, etc), because they are also not scaled for some weird reason.

**Comment by messengerbag** [comment]
Ah yes, good point. I had forgotten about that.

**Comment by ivan-mogilko** [comment]
> I hold that this is never the appropriate behavior, and therefore an AGS bug.

So, I've been thinking about this today, and I am in doubts. You say this is never a correct behavior to not scale these offsets, but I may imagine a situation where I'd like to manually scale a sprite, but keep offsets (z, and/or x,y offsets added by LockViewOffset) not scaled automatically, because that will allow me to set more offsets with a pixel precision.

**Comment by messengerbag** [comment]
> Like, with scaling, you may like to temporarily change the sprite size for a visual effect, while keeping position of the sprite's "origin".

But this is what the failure to scale `Character.Z` does _not_ do. If you scale the sprite but not the offset, the "origin" will effectively move to a different position on the sprite.

I still cannot see a case where this is desired behavior.

**Comment by ivan-mogilko** [comment]
> But this is what the failure to scale Character.Z does not do. If you scale the sprite but not the offset, the "origin" will effectively move to a different position on the sprite.

What do you mean? The origin will be on the same position on sprite, at the mid-bottom of the sprite, and will stay on exact same position relative to screen too (y + z).

**Comment by AlanDrake** [comment]
Maybe we can add another property to turn on/off Z offset scaling according to zoom.

**Comment by ivan-mogilko** [comment]
> Maybe we can add another property to turn on/off Z offset scaling according to zoom.

Erm, I would not like to have a "scale this" option per individual property.

IMO it's a matter of defining the consistent rules for object parts. Like, there's a sprite, which has some properties adjusting its looks. Then there's a character itself, which has additional properties, such as a point where it touches walkable area, a "collider" (or blocking rect in AGS), and so forth. Each of these parts may be scaled and rotated separately.

Then, if we have such rules, we have to decide which part do these offsets belong to, and that will define how the transformation is applied to them.

**Comment by messengerbag** [comment]
> What do you mean? The origin will be on the same position on sprite, at the mid-bottom of the sprite, and will stay on exact same position relative to screen too (y + z).

Consider this sprite (adapted from _Mudlarks_ by Cloak & Dagger Games/shaun9991; CC BY 4.0):

![Winston from Mudlarks](https://i.imgur.com/ilRT4su.png)

I've highlighted the pixel that is supposed to be the origin as a red dot between his feet. At 100% scaling, making this the origin is achieved by setting `Character.z` to -36. But if you scale the character up or down, because the z value is not scaled, a _different_ pixel of the sprite now becomes the origin. IOW, if you scale the character up/down, the red dot moves.

The effect of this in-game, if this is your player character, is that the character will not move to the position you click, but to a point below it if scaled down, and to a point above it if scaled up.

> Erm, I would not like to have a "scale this" option per individual property.
> 
> IMO it's a matter of defining the consistent rules for object parts.

I agree with this. Configurability should be avoided unless necessary. See [The Problem with Configurability](https://blog.codinghorror.com/the-problem-with-configurability/), particularly the Jacob Nielsen quote: "Leaving the design to the users is the ultimate abdication of the designer's responsibility to provide a quality product"

**Comment by ivan-mogilko** [comment]
Coincidentally, there was a short conversation on ags discord earlier, and @AlanDrake mentioned another use of `Character.z`: shifting character up and down as he walks over an uneven ground.
I may think of another, similar case: if user wants to make a character "float" up and down, like in the water, or air.
In such scenarios, z property must not be scaled, because it is related to the room (terrain) "pixels", and not on character image pixels. If it would be scaled along with the character, it will be not possible to make a smooth movement.

In my opinion, this example illustrates that z property has many uses, not all of which require scaling, and some would actually be impossible to implement well if there would be an automatic scaling. Indeed, right now one has to script scaling of z parameter in script if there's a need to scale it, but on another hand this lets keep pixel-precise assignment available.

I guess, that the problem here may originate from either undefined role of Character.z, or lack of other properties that would let achieve the wanted effect, without conflicting with other methods.

For instance, in the case of that *Mudlarks* sprite, the intention is to configure sprite's *origin*: that is a relative point on sprite which would correspond to the object's position in the room. Therefore, the true solution, in my opinion, would be to have a distinct property called Origin (or OriginX, OriginY).

By the way, I suspected that the LockViewOffset may already serve as a origin setting. Unfortunately, I found following note in the manual:
> You should only use this command for minor adjustments, since the offsets **do not affect the clickable area** of the character, what walkable area he is in, and so forth
The statement in bold makes the purpose of this "offset" rather questionable, imo.

But, getting to the point, I suggest that instead of scaling the z property (and thus disabling one of its potential uses), we should rethink the properties that Character has for adjusting the sprite position and looks instead, and make sure there's enough distinct settings to do everything necessary.

note: I will also remove the "bug" label from this ticket, because the more I think about it the more I doubt that it's a bug, and see this situation rather as a "incomplete design".

**Comment by messengerbag** [comment]
Well, I completely disagree, but what's the point in arguing?

**Comment by AlanDrake** [comment]
Years ago there were talks of having a separate Transform property, where all sort of offsets and rotation could be applied with matrixes and/or helpers.
Ideally, we'd have both Sprite and Character/Object offsets, because they have different behaviors and meaning.

Character might autoscale z according to zoom which is then applied to sprite's own transform.

**Comment by ivan-mogilko** [comment]
> Well, I completely disagree (in each of the cited cases, I think scaling would be more appropriate), but what's the point in arguing?

Very well, maybe I'm seeing this wrong.

I can apply the zoom to both z property and offsets added to LockViewOffset/Aligned.
But this has to be done under condition that the game data is new, because in older games the zoom was likely applied to these properties by user script.

Hopefully the situation with sprite transformation will be improved in ags4.

**Comment by ericoporto** [comment]
I hope in ags4 there's no more "z" property as it's very confusing **name** - the baseline is the z and the z is the offset... About origin, things have different origin rules - bottom left, center bottom, top left. The biggest amount of work would be adapting the editor for whatever is changed.

**Comment by ivan-mogilko** [comment]
@messengerbag No, sorry, i've been thinking this over and over, and i am still in doubts.

I made a test game to illustrate my concerns, because maybe my former explanation of the problem was not good enough.
Full project:
[test--360trying-zproperty.zip](https://github.com/adventuregamestudio/ags/files/12619919/test--360trying-zproperty.zip)
Runnable:
[test--360trying-zproperty-build.zip](https://github.com/adventuregamestudio/ags/files/12619936/test--360trying-zproperty-build.zip)

In this "game", the room has a "pond" in the middle. The character is scripted to get deeper in water the closer it is to the middle of the pond. This is done by combining Character.z and walk-behind.

There are buttons that
- scale character down
- scale character up
- toggle the scaling of z property along with the character's scaling. (this is done in script of course, but uses same formula as with the sprite scaling)

As may be seen, if the z-scaling is enabled, the character appears to be "less" in the water the smaller it is, and "deeper" in water the larger it is, as if pond becomes more shallow or more deeper depending on the character's scale.

So, I'd like to understand your view on this case, as you said that in every case *"scaling would be more appropriate"*. Is there anything I'm missing? Perhaps this should be done differently in AGS, not the way I'm doing this?

**Comment by ivan-mogilko** [comment]
>  About origin, things have different origin rules - bottom left, center bottom, top left.

This is default origin, each object type has its own default. But we had an idea to have custom origin which user may set freely.
There have been my conversation with @AlanDrake about this somewhere, but I forgot where. The idea was to let both set origin in relative terms (0.0- 1.0 on both x and y axis), and in pixels (for pixel-precise adjustments).

> The biggest amount of work would be adapting the editor for whatever is changed.

Could you elaborate on this, why do you think so, what will have to be changed in the editor?

> I think if this is something to be changed in 3.6.1, it's better to introduce a new OffsetY property

Strictly speaking there's already a offset y, set by LockViewOffset, it's just that it does not act fully correct still...

But I am coming to a thought to not do anything in 3.6.1, because
- this has to be done with a very clear design plan on paper, and with some plan for the future in mind;
- i thought to stop adding game features in 3.6.1 in particular, as it was supposed to be a minor version.

**Comment by ericoporto** [comment]
> Could you elaborate on this, why do you think so, what will have to be changed in the editor?

The Room Editor is always a bit hard to adapt. :/

**Comment by ivan-mogilko** [comment]
I was trying to remember where I've seen Character.z used to simulate terrain noise, and finally found it:
https://www.adventuregamestudio.co.uk/site/games/game/1426-of-the-essence-mags-/

In this arcade game by WHAM there are craters, where player walks up and down the slope. I think this is a better example overall than my test game, because unlike my game, there's a wide walkable area that you can cross in any direction, and the slopes use generic algorithm.

**Comment by ivan-mogilko** [comment]
I did a draft PR for this, at least to have something to try out: #2136
