### ISSUE TITLE
OSX 3.5.1: in windowed mode game starts in the bottom-left 1/4 corner of the window

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1334]
**Describe the bug**
Two users reported that the mac port from 3.5.1 release branch has this issue: when they launch the game in windowed mode the window appear resized well, but the game itself is rendered in native resolution (it seems) unscaled in the bottom-left corner of the window.

According to one user, they have an external monitor attached, and the game is scaled properly when launched on the external monitor (1920x1080). It does have this problem on macbook monitor (1440 x 900) though. It does not matter whether the external monitor is primary or secondary.

It does not matter whether the "raw" mac binary is run from the terminal, or proper mac app is made and run.

Same users confirmed that 3.5.0 port works well.

**EDIT:**
More info from the user:
>- external monitor connected
>- launch the game: it opens on the macbook monitor (1440x900) in the usual 1/4 corner
>- I drag the window on the external monitor (1920x1080) and the game looks perfect, no longer on the 1/4 corner
>- I drag back the window to the macbook monitor and the game ... looks perfect!

**AGS Version**
3.5.1

**Game**
Any game supposedly.
Tested one game of 320x200 resolution, and another of 640x480.

**Expected behavior**
The game should be scaled to fill the window.

**Screenshots**
<img width="644" alt="Zrzut_ekranu_2021-06-29_o_14 57 28" src="https://user-images.githubusercontent.com/1833754/123811617-13c57d00-d8fc-11eb-9d9f-d4f661541d66.png">

**Desktop:**
 - OS: macOS
 - Version: ?

**Additional context**
This may be important to mention that in 3.5.* mac port works somewhat similar to mobile ports: the engine only draws game in native size using software renderer, then this image is passed into the patched Allegro library, where its own graphic or system driver uses OpenGL to display a scaled texture.

**Comment by morganwillcock** [comment]
> the game is scaled properly when launched on the external monitor (1920x1080). It does have this problem on macbook monitor (1440 x 900) though

I would guess it is related to display scaling for HiDPI screens. 1440x900 looks to be a resolution that is a default on a Retina Display ® so that might be half the resolution of the native panel, which renders to a quarter size of the screen. So texture scaling for the final display is probably missing scaling checks.

**Comment by ivan-mogilko** [comment]
My biggest question is what have changed since 3.5.0 that is causing this. Because both users claim that 3.5.0 works well in this regard.

I've checked the diff, and the mac related changes are minimal and not related to gfx. There were some changes to config parsing, but nothing that would seem relevant.

**Comment by morganwillcock** [comment]
Where did the builds that were being compared come from?

The CI environment potentially changes when the OS and tools get phased out and the build jobs are automatically run on the next newest versions, so potentially that could be it, although it would be a little strange to get such a fundamental change in behaviour.

I've not tried to build the macOS version in a while (my Mac is nearly out-of-support in terms of OS version and I don't plan to replace it) but I'll try to build and compare them later today. It is possible to force the display scaling on the primary monitor so so hopefully that is a good enough test...

**Comment by morganwillcock** [comment]
I've tried on 3.5.0.32 and 3.5.1.8 with display scaling turned on and they both work the same way for me. Game scaling specified on the command line always seems to be ignored and whatever I do it always reports `screen size: 0 x 0`, but I couldn't get it into a situation where the game didn't fill the window.

Maybe it is related to having a mismatch of display scaling between multiple monitors and only the primary monitor is considered.

**Comment by ivan-mogilko** [comment]
Mac port works differently from other desktops, it initializes real graphic mode in the patched allegro library. TBH I don't know if it even checks for the config. That is very bad, but this is how it was done originally...

**Comment by ivan-mogilko** [comment]
I set up a mac virtual machine (Catalina), and this problem does not reproduce for me either, regardless of the emulated display resolution.

**Comment by hobbesjaap** [comment]
**Confirmed issue on Mac here too**
I can confirm this issue happens on my Macbook Pro M1 as well, when I use the internal display. Going fullscreen fixes it.

When I start the game on my Macbook Pro M1 with an external monitor, then it runs fine in the window. When I go fullscreen, it becomes stretched and aspect ratio is ignored.

**The issue also happens on Windows 10**
I can also confirm that, when running on OpenGL, this issue happens on my AMD 3400G Windows 10 machine, using the 3400G on-board chipset (Vega 11) with latest Radeon drivers. Even in fullscreen this issue appears. There is a resolution issue there at play, since that PC is hooked up to a 4K TV. So I try to run the game at 720p in fullscreen, hoping it will scale. No matter what settings I choose, it won't scale. I need to change the actual render resolution to 3440x2160 for it to run properly in full screen. However, that brings a performance hit (which SDL2 will probably solve).

I hope I described it all well enough. Happy to try out different things to see if that makes a change?

**Comment by ivan-mogilko** [comment]
After [3.6.0](https://github.com/adventuregamestudio/ags/releases/tag/v.3.6.0.47) is released with SDL2 backend, we recommend using it to run games on OSX instead.
