### ISSUE TITLE
can't comment on any issues or PRs created by @ericoporto

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1357]
since a couple hours, i get the following in any issues or PRs that were openend by @ericoporto , even in ones where i commented on in the past.

![2021-07-10-003007_1322x653_scrot](https://user-images.githubusercontent.com/341425/125144562-24ed6580-e116-11eb-98ec-674788e00777.png)

additional to that, i can't auto-complete his nick, and his ags repo fork has become invisible to me - looks as if he somehow added me to his banlist or something like that.
i don't think his being angry about me adding a PR with some goto's in them justifies blocking me out from any conversation.

**Comment by ivan-mogilko** [comment]
Well I definitely made a mistake letting these gotos in, if they may break his web port, that I did not realized in time.

**Comment by rofl0r** [comment]
they don't break his port, see the comment about kripken - emscripten supports goto just fine.
therefore he didnt respond to your question because there's no rational explanation for his hate against goto.

**Comment by ivan-mogilko** [comment]
Was not the problem that wasm does not suport goto and it's the part of the port? Tbh reading through the discussion did not clear it up for me, as I don't understand most of what they were talking about.

**Comment by rofl0r** [comment]
the wasm bytecode itself doesn't support it, yeah, but emscripten has code that transform gotos into another control construct. this is only an issue if you want to emit plain wasm bytecode yourself (which is only something a programming language backend would do).

**Comment by rofl0r** [comment]
apart from that, emscripten doesn't support filesystem accesses, so he would need to find a different solution for that anyway - the code in question would have to be ifdeffed out..

**Comment by ivan-mogilko** [comment]
I do not know much about the emscripten, but I've read recently that it creates a virtual filesystem, where one should upload necessary files, and emscripten maps all file access functions to this virtual system.

**Comment by rofl0r** [comment]
why did you close this? the issue isn't resolved yet.

**Comment by ivan-mogilko** [comment]
How can I resolve this issue?

**Comment by rofl0r** [comment]
dunno, maybe he modified some settings here in the repo. or ping him ? he's probably not even aware what the consequences of his actions are. tbh, i'm getting tired of this childish behaviour and him throwing a tantrum whenever something to his disliking happens. i wish he really disappeared back when he said so, because all he does is bitching around and opening low-quality PRs.

**Comment by ivan-mogilko** [comment]
He does not have moderating rights in organization or "ags" repository in particular. There are no blocked users atm here, I may look more into this later, but this may be also a github issue.

On a side note, I'd really like to ask to not do these personal attacks here, because I may end up having to redact comments.
This is not true that he does not do anything, he was working on certain ports, managing build scripts and CI, and helping users with porting their games.

On the other hand, I might be too stressed up or tired sometimes to properly weight everyone's arguments, and definitely could've contributed to this problem.

**Comment by rofl0r** [comment]
> I'd really like to ask to not do these personal attacks here, because I may end up having to redact comments.

understood. i have bitten my tongue dozens of times when interacting with him and stayed polite despite his behaviour, but in this case it went too far imo.

> On the other hand, I might be too stressed up or tired sometimes to properly weight everyone's arguments, and definitely could've contributed to this situation.

no, you did everything correctly - you based your decisions based on rationality and technical merit, just like when you initially rejected the SDL2 android port due to multiple issues pointed out back then.

**Comment by ivan-mogilko** [comment]
> just like when you initially rejected the SDL2 android port due to multiple issues pointed out back then.

To be precise, I did not reject the new android port, as I did not (and still don't) have a full picture of how android projects work and what are modern requirements for them; I simply was not in position to judge that. What happened was that I was taken by surprise by the amount of simultanous additions, which we not explained in advance.

> no, you did everything correctly - you based your decisions based on rationality and technical merit, 

To be frank, there was a good point in rewriting this function with C++ strings. I simply did not bother about it too much as that seemed like a little problem atm, like I'm not bothered with keeping C-style code around until better times.

But the problem is, that my perspective is affected by years working on a very old and dirty C++03 code, so I have very high tolerance to these things. At times I am not even sure if I know how a good C++ code should look like. This is very different from perspective of people who learnt this language in the recent decade or so, with new standards and new popular guidelines. Naturally our views clash so often.

**Comment by rofl0r** [comment]
> To be precise, I did not reject the new android port, as I did not (and still don't) have a full picture of how android projects work and what are modern requirements for them

i'm aware; i probably didn't put this into the proper words. thanks for clarification anyway.

> that my perspective is affected by years working with a very old C++ code often mixed with C, so I have very high tolerance to these things. At times I am not even sure if I know how a good C++ code should look like. This is very different from perspective of people who practiced this language in the recent decade or so, with the new standards and new popular guidelines. Naturally our views clash so often.

usually a good guideline is "don't fix what isn't broken". rewriting working code just to make it look more idiomatic usually creates more new issues than it solves.

tbh i don't really see the point of this C++-ificiation mindset, it makes the code harder to read and to debug. for example, when trying to print the members of a class in gdb, you often get 5 screenpages full of std::whatever spam so you can't even see struct members, or trying e.g. "p scri.numsections" doesn't work because pscript is some sort of template around ccScript.
