### ISSUE TITLE
Editor: Check event name mismatch at compile time instead of runtime

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1363]
**Describe the problem**
When you edit a room,  you need to configure what function will handle an event such as "Walks off bottom edge", or "Examine object".  If you configure a function that isn't actually defined in the room file, this will only be detected at runtime.

**Suggested change**
This should be already detected after the project has compiled without programming errors. 

- Compiling entails compiling the rooms. When a room is compiled, the Editor knows what events are configured for the room proper and its hotspots, and objects.  One of the results of a compiling run is the list of exports. So the editor can check whether all the event function names are in the exports list and error out when they aren't.

- In the same vein, character and inventory item events must have functions in the GlobalScript. So the editor can check whether the compiled GlobalScript exports the functions that are configured for character and inventory item events.

**Comment by ivan-mogilko** [comment]
To clarify, you suggest to test that the names entered on the "events" panel actually have matches in the script exports?

**Comment by ivan-mogilko** [comment]
There's a potential problem with this, similar to an existing one mentioned in #1454: in order to know which events have script functions linked to them the editor must preload a room into memory before compilation, at least partially.

**Comment by ivan-mogilko** [comment]
I think that this should not be too difficult, as there's already a method in the Editor that searches for a function when you press "..." button. Same method may be utilized here.

This check may be done as an extra pre-step right before compiling a corresponding game part:
- Character, Inventory and GUI events checked prior compiling script modules.
- Room and room object/hotspot/region events checked after room is already loaded for compilation, but prior to running room script compilation.

These checks will report found mismatches as warnings.

---

Besides above, I suggest following change:
1. Do not error at runtime if room's event function is missing. No other object events seem to have this behavior. I suggest to report a warning in the game log (for any missing function), but let game continue, because running a script callback is not required for the game to function.
2. In the Editor, when pressing "..." button on event, if a function is missing, this button should create one. Right now it just opens the script file.

**Comment by ivan-mogilko** [comment]
On a side note, investigating the "zoom to file" function shows that it's done in a very unreliable way.

The editor searches not for the function name, but for *exact* text `function FunctionName(`, using plain string comparison (String.IndexOf). This means that any non-critical difference will make this search fail: extra spaces, having type and name on separate lines, having `void` or `int` instead of `function`, and so on.

I would address this as a separate issue, but it may be worth to plan or adjust the code in such way that will make it easier to replace this with a better kind of search later.

**Comment by ivan-mogilko** [comment]
Hmm, I ended up with a thought that the function searcher must act over a **preprocessed** script. That's the only complete solution to skip functions of the same name but put under comments or inactive `#ifdef` blocks. These seems like edge cases, but are still possible...
