### ISSUE TITLE
Android Launcher: Preferences crash the app if android.cfg does not exist

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1471]
**Describe the bug**

If `android.cfg` does not exist in the current directory selected by the launcher, trying to open Preferences will crash the app.

**AGS Version**
3.6.0

**To Reproduce**
1. Run the Android AGS Launcher ("AGS Player");
2. Open the settings menu ("..." in the top-right corner);
3. Choose "Select game folder" and setup a directory that either does not exist, or does not contain android.cfg.
4. Now choose "Preferences" from the same menu.
5. Observe the app crash.

**Expected behavior**

Preferences should not crash the app regardless whether android.cfg exists in the selected dir or not. If it's not readable, then Preferences should reset to defaults.

**Comment by ericoporto** [comment]
OK, the problem is this, at this point in time, SDL hasn't initialized yet.

`File::OpenFile` is called to open the file, and it can't find it in the filesystem, so it then tries to find it in the AAssetStream, but at this point in time we haven't yet called OnCreate on the AgsRuntimeActivity, so SDL is not initialized yet.

It then tries to call `GetAAssetManager`, and it will call `InitAndroidFile`. This relies in SDL2 functions to get the necessary environment stuff from Android. `SDL_AndroidGetJNIEnv` causes the crash.

**Comment by ivan-mogilko** [comment]
Oh, sorry, I did not notice this comment first, and commented in the PR instead. I will copy a part of my reply here:

I believe that there has to be some rule: do we expect that SDL is initialized before we use our file functions, or not.
In the first case we may ensure that SDL has passed the minimal initialization at the start of the native library.
In the latter case all the relevant utility functions (GetAAssetManager, and so on) must test if it's okay to perform these actions.

**Comment by ericoporto** [comment]
> we must ensure that SDL has passed the minimal initialization at the start of the native library.

There's no way to initialize SDL easily before the AgsRuntimeActivity boots up, and once it boots up the game starts.

> In the latter case all the relevant utility functions (GetAAssetManager, and so on) must test if it's okay to perform these actions.

This would lower runtime performance for the benefit of the rarer case of the native library usage before the game starts.

Since this is just for handling an ini file, I prefer to load up a kotlin/Java ini library and handle things there.

**Comment by ivan-mogilko** [comment]
I don't have a knowledge of why SDL cannot be initialized without RuntimeActivity; but then, like with the game list, having whole engine library initialized for a small action is also excessive.

> Since this is just for handling an ini file, I prefer to load up a kotlin/Java ini library and handle things there.

This is indeed an option. I was similarily wondering if testing for game file may better be done on Java side, except in that case there's more to sync with the engine behavior (various types of old formats too).
Tbh I again lack full knowledge of why Android reads these configs in the native code; and from the quick glance it even init some global variables there...

I agree that it's best to assume that SDL and everything is initialized, because otherwise utility funcs will be filled with extra tests. Even if perfomance is not an issue, that will still complicate their code.

**Comment by ericoporto** [comment]
I think there's another option, not relying on SDL to get the jnienv and other stuff. Then it would be possible to get the AAssetManager at that time. I am not sure yet how that would work.
