### ISSUE TITLE
"Go to definition" feature in dialog editor 

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1480]
**Describe the problem**
Often when I'm coding, I want to zap myself to the definition of a function I created. To do this, I right-click the function name and select "Go to Definition of XXX".

In most circumstances, this works fine. Like from this room script here:
![image](https://user-images.githubusercontent.com/2244442/148598755-a7795a64-bef4-4c1b-861e-6f4ce764b09c.png)

But if I want to do the same thing from the dialog editor, I see this instead:
![image](https://user-images.githubusercontent.com/2244442/148598763-6ccc5a6c-53b4-454e-96ba-5cfb29d7ac92.png)

Would it be possible to enable this feature from the dialog editor?

**Suggested change**
Add the Go to Definition of XXX left click option from the Script Editor on the Dialog Editor.

Originally from the forums here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=59680.0

**Comment by ivan-mogilko** [comment]
I had a look at this recently, and found that the full and proper support of autocomplete, keyword highlighting and "go to definition" in dialogs would likely require to copy about half of the ScriptEditor class into DialogEditor. But that's not all.

Right now the dialog editor is made like a very stripped copy-paste version of the script editor, with some essential things not implemented. It seems to be more or less possible to share most menu and context menu commands, and have a basic support for "Go to definition", but that won't work for all symbols. Namely, it won't work for any local variables and their members, and maybe something else. The reason is that Dialog scripts *do not support local autocomplete cache* for some reason (their AutoCompleteData member is not created).

For example, if you have a struct "MyStruct" declared somewhere, with members "int a" and "int b", and in dialog script you type:

    MyStruct ms;
    ms.a = 10;
 
then "Go to definition" will work on "MyStruct", but won't work neither on "ms", nor "a".

Local variables are also not working with autocomplete at all in dialog. For example, typing "player." will open autocomplete list for Character's members, but having "Character *ch;" and typing "ch." won't open any autocomplete.

I did a PR draft #1743, where I pick out common functionality into the base class, and let both ScriptEditor and DialogEditor inherit that, but these changes are still not enough because of the mentioned AutoCompleteData problem. When realizing that I stopped, as the code changes became too big for the 3.6.0 (which is approaching a final release). But that work may be continued for any future version.
