### ISSUE TITLE
No audio device causes AGS to not initialize audio core on Windows

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1487]
If there are no speakers or headphones connected to the PC, audio core from the master branch won't start. 

In the #1485 it has been made so that it at least doesn't block the startup of the engine, and disables the audio device. In the allegro build of the engine it causes AGS to open a window message saying it could not initialize the device and the game keeps going.

This is not really a bug but it's more to keep track of this in case this is a problem. It may even not be a problem.

I originally discovered this because I had no speakers connected and had just disconnected my headphones and tried to launch a game.

I also am thinking now, would this affect an audio clip `aClip.Play()` returning null instead of the Audio Channel?

**Comment by ivan-mogilko** [comment]
> I also am thinking now, would this affect an audio clip aClip.Play() returning null instead of the Audio Channel?

Yes of course, if the audio is disabled, all Play() will return null. But that will also happen if user explicitly disables audio in config.

Personally I am worried about this problem, for a few reasons. As I mentioned in the comment to #1485, this made me wonder how AGS engine behaves if the sound output device is toggled on and off during the game play. Theoretically, imo, the game should continue playing sounds, so that if the player turns the headphones etc in, they will hear exactly what they suppose to hear in this moment of the game.

I think we need to investigate: what exactly, which function, is having this trouble to perform during audio init, if the headphones are disconnected for example, and if there's a workaround for this to keep audio system working.
Secondly, find out what happens if player unplugs and later plugs-in their speakers.

**Comment by ivan-mogilko** [comment]
So, perhaps I misunderstood the context of this issue. Trying to reproduce this I found that i may plug speakers on and off without causing any troubles, which is actually expected. The only way to trigger an exception in `audio_core_init` is either to pass an ID of non-existing device, or not have any ready device on the system.

It's hard to tell how the situation described in #1485 took place, but maybe it was something system-specific. In any case, the sound init failure is now correctly handled. I'd rather close this ticket now.
