### ISSUE TITLE
Remove hardcoded animation speed modifier for idle views and cursors

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1517]
In the engine there are two obscure hardcoded modifiers to the animation speed:

1. Idle views, when animating their animation speed (frame delays) is actually calculated as `Character.AnimationSpeed + 5`.
as mentioned in this old forum thread: https://www.adventuregamestudio.co.uk/forums/index.php?topic=36779.0
and seen in this code: https://github.com/adventuregamestudio/ags/blob/v.3.6.0.15/Engine/ac/characterinfo_engine.cpp#L376-L379

2. Mouse cursors, when they have assigned views, increase each frame delay also by 5.
as seen in this code: https://github.com/adventuregamestudio/ags/blob/v.3.6.0.15/Engine/ac/draw.cpp#L2519

I don't know if these are coincidence, or both a part of some ancient design idea; but these are causing problems and may be a source of immense frustration to users, as these are obscure behavior modifiers, and cannot be directly changed (and not documented, i presume).

The proposal is to remove both of these mods and make idle view and cursor animations follow actual animation parameters.

For backward compatibility we may have a setting enabled for older games.

**Comment by messengerbag** [comment]
If the goal is to simplify things, wouldn't it make more sense to target this change for 4.0 and avoid any kind of backward compatibility switch?

**Comment by ivan-mogilko** [comment]
> If the goal is to simplify things, wouldn't it make more sense to target this change for 4.0 and avoid any kind of backward compatibility switch?

I would love to, but i'm getting these requests from users, where they cannot setup proper animation speed for the idle view without doing obscure hacks, like mentioned in end of the forum thread.

**Comment by fernewelten** [comment]
The clean thing would probably be to introduce `int Character::IdleAnimationSpeed` so that the speed of the walking animation needn't be computationally linked to the speed of the idle animation. And analogously with the Think view etc.

For AGS4, we should also rename things according to a consistent and intuitive (!) terminology. When we use the term such as “speed”, we imply that things go proportionally faster the higher the speed is. This doesn't seem what AGS really does when it adds or subtracts various offsets to delay.

`Mouse.Speed` is a `float` (!) whereas `Character.AnimationSpeed` is an ìnt`. 🙄

**Comment by ivan-mogilko** [comment]
> So why didn't it **happen**? It would have been as easy as deleting '+5' out of one line of code. There must be a use case **somewhere** that stopped CJ from going that way. (?)

That could be simply because he did not have spare time, and did not want to bother about the old code. The forum thread is from 2009, CJ left the project completely in 2011, and probably stopped updating it earlier.

**Comment by fernewelten** [comment]
Perhaps the thing that stopped CJ was that he thought, too, that an attribute such as `Character::IdleAnimationSpeed` would be needed as a replacement. It's a matter of seconds to take `+ 5` out of one line of code, but providing for a new attribute is more work.

**Comment by messengerbag** [comment]
> I would love to not touch this now, but i'm getting these requests from users, where they cannot setup proper animation speed for the idle view without doing obscure hacks, like mentioned in end of the forum thread.

There are simple workarounds discussed in the thread that *should* work (namely, adding a delay adjustment to each frame). If they don't, that's a different problem, and just dropping the constant modifier isn't going to fix it, because there are no doubt other cases where people *want* it to run slower… or faster! (Another separate point is that it might be nice to be able to set the delay for multiple frames at the same time.)

Otherwise I agree with fernewelten that it should be a separate setting anyway, and I don't think it makes sense to complicate a feature (by introducing different behavior depending on version/backwards compatibility) for something that is a dead end.

**Comment by ivan-mogilko** [comment]
Very well, I will remove this from 3.6.0 milestone.

**Comment by ivan-mogilko** [comment]
No, I have to do this, because this causes people to suffer, and the problem is in plain sight. There's a hidden and undocumented modifier to already existing parameter.

If adding a new "animation speed" property is necessary, then I will add one.

**Comment by ivan-mogilko** [comment]
Opened a PR: #1519
