### ISSUE TITLE
AGS doesn't handle dead keys (accents) anymore

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1561]
**Describe the bug**
AGS 3.5.1 which was Allegro based, could handle [dead keys](https://en.wikipedia.org/wiki/Dead_key), meaning on Windows 10, I could type `'` and then `e` and get the `é` character with my keyboard configured for **English International**. 

After the SDL2 conversion, any dead key usage results in keycode 195 - after configuring the keyboard, type \` and `space` to load the console and try any combination of accent + vogal, and see it reported as keycode 195.

**AGS Version**
current master (https://github.com/adventuregamestudio/ags/commit/230795414b676a2c1e84ae72488af18b90f71692)

**Game**
[ags_dead_key_test.zip](https://github.com/adventuregamestudio/ags/files/8193302/ags_dead_key_test.zip)

**To Reproduce**
Type in the textbox in the above game any key using accents with English International using the 3.5.1 engine and verify it works.
Now use any build of the engine from current master and see it doesn't work anymore.

**Expected behavior**

**Screenshots**
Both screenshots are pressing `'` and `e` (é), `'` and `a` (á), `'` and `u` (ú), `'` and `o` (ó), `'` and `i` (í).

AGS 3.5.1
![image](https://user-images.githubusercontent.com/2244442/156938149-571ebeb1-127a-4b3f-81a7-0dca7adad7ec.png)

AGS master
![image](https://user-images.githubusercontent.com/2244442/156938172-d5e1dbfe-4461-46d3-8139-506d493e2aeb.png)

**Desktop:**
 - OS: Windows
 - Version 10

**Additional context**
Text input in the example above is handled through `on_key_press`, the simplified version of the code is something like:

```AGS Script 
String input_text;
void on_key_press(eKeyCode keycode)
{
  input_text = input_text.AppendChar(keycode);
}
```

So it appears the keycode before was the ascii final key emitted by the OS.

- [3.5.1 `sys_events.cpp`](https://github.com/adventuregamestudio/ags/blob/release-3.5.1/Engine/ac/sys_events.cpp)
- [master `sys_events.cpp`](https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/sys_events.cpp)

Curiously `^` key in my keyboard requires shift+6 to reach, and then an additional space after, since it's a dead key, so it's curious it's appearing above (keycode 195).

**Comment by ivan-mogilko** [comment]
Firstly, i was not able to fully reproduce dead-keys combinations in AGS 3.5.1 on my system (using test game); it worked in other programs such as Notepad++, but in AGS it caused different letters.

In 3.6.0, upon investigation, SDL sends SDL_KEYDOWN event for each separate pressed key, and then SDL_TEXTINPUT event for the final letter. The problem is that the text contains multibyte utf-8 character, but our code only uses the first byte to pass as key parameter further. The proper text is used only by the TextBox control, and in unicode mode.

**Comment by ivan-mogilko** [comment]
@ericoporto so, i pushed a very dumb test, where the SDL's text input is converted to ascii and the result is used to pass a key code to the "on_key_pressed" event. It seems to resolve the issue on my side. But it uses current system locale, so results may be different elsewhere. May you try it out?
https://github.com/ivan-mogilko/ags-refactoring/tree/test--convertSDLTEXTINPUT

I'm currently researching a proper C++11 way to convert text, because current solution uses libc function that use global locale setting, and one allegro4 function (tbh I don't remember why i had to do it this way).

**Comment by ericoporto** [comment]
I honestly don't understand the code, but I built and tested and yes, it does work!

**Comment by ivan-mogilko** [comment]
I did this differently in the end, pr: #1562

At first I thought to use C++11 codecvt feature, but to my embarassment was not able to understand how to use it correctly yet in our situation. This still may be looked into later. For now I added basic utf-8 utils (planned for other issue anyway), and rewrote existing utf8->ascii converter without allegro4 functions to reduce dependencies.

**Comment by ivan-mogilko** [comment]
Also, forgot to mention earlier; one don't have to use "US International" layout, but any non-latin layout; these will have similar problem.
