### ISSUE TITLE
Heroine's Quest intro shows portrait bug

### ISSUE THREAD

**Issue by criezy** [adventuregamestudio/ags#1698]
**Describe the bug**
Midway through the intro, Thrivaldi shakes his fist in the foreground. A second after, instead of the sprite walking off, his portrait appears as if he was talking (without text) and travels over the screen, apparently on top of the thrivaldi sprite.

**AGS Version**
AGS master commit eb86c73460376253eef3c5fa2fed6c687fed74b4

**Game**
Heroine's Quest (tested with Windows version from Steam: https://store.steampowered.com/app/283880/Heroines_Quest_The_Herald_of_Ragnarok/)

**To Reproduce**
1. Start the game
2. Select any character type and skills.
3. Watch intro
4. During the intro, Thrivaldi (a green troll) will appear in the bottom right of the screen and shake his fist. After this he should walk back out of the screen, but instead his portrait appears and moves across the screen.

**Expected behavior**
Thrivaldi should walk of the screen instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/552105/174499895-f98d38e4-0a07-4226-8288-e4a9194bf8a1.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.6

**Additional context**
The intro works fine in AGS 3.5. So this is a regression that occurred between the 3.5 release and current master code.

The bug was initially reported in the ScummVM bug tracker: https://bugs.scummvm.org/ticket/13477
There the game developer had this to say:
> Normally, AGS characters have walking animation in four directions. If the character moves diagonally (e.g. southwest), the interpreter picks either the south animation or the west animation. Expectation: if horizontal distance to destination is greater than vertical distance, play the west animation; otherwise, play the south animation. I confirm that this works normally when playing the game through AGS.
>
> Relevant code is MoveCharacterBlocking (THRIVALDI, character[THRIVALDI].x - 185, character[THRIVALDI].y + 100, 1); 
In this case, AGS picks the west animation (loop 1) and SCUMMVM picks the south animation (loop 0). It so happens that loop 0 contains portraits, since this is a special animation view and not Thrivaldi's normal walking view.
>
> This will very likely affect other AGS games as well.

**Comment by criezy** [comment]
After testing a few versions I can confirm that:
* Tag `v.3.6.0.4` works properly
* Tag `v.3.6.0.5` exhibits the bug

I will try to narrow that further with a git bisect.

**Comment by criezy** [comment]
2ac1b258db203b62ba0613c979d7a092b51e441f is the first bad commit
Author: Ivan Mogilko <ikm_spb@yahoo.com>
Date:   Mon Jul 12 04:54:09 2021 +0300

    Engine: fixup character's view loop in update, prevent having no frame

 Engine/ac/characterinfo_engine.cpp | 14 ++++++++++----
 1 file changed, 10 insertions(+), 4 deletions(-)

**Comment by criezy** [comment]
The issue is caused on the check on the `frame` added in that commit.
For the animation that has the issue, `loop = 1`, `frame = 19` and `numFrames = 7`. With the new test in place it ends up using `loop` 0 instead of 1.

**Comment by ivan-mogilko** [comment]
> The issue is caused on the check on the `frame` added in that commit. For the animation that has the issue, `loop = 1`, `frame = 19` and `numFrames = 7`. With the new test in place it ends up using `loop` 0 instead of 1.

Yes, this looks strange. Probably the frame should instead be fixed up separately after the view or loop was fixed up.
I'd also try to find an issue i've been fixing around same time, as i could have a reason to add this condition (even if it were done incorrectly), and double check that it won't resurface as well...

**Comment by Crystal-Shard** [comment]
Analysis from my side: The last thing this character did was an animation on loop 2. This is why his frame is at 19. The move command sets his loop to 1 (west) but doesn't update his frame.

Prior to this change, this would hit the check at line 218, "if (frame > framesInLoop)", and reset the frame to 1 normally.
Because of this change, it is considered an invalid frame, so the new code resets loop to the first loop that has frames in it, which is 0.

Suggested quick fix: the line "(loop >= views[view].numLoops || frame >= views[view].loops[loop].numFrames))" should check only the loop and not the frame, which more-or-less matches what it did before.
Suggested long-term fix: the move function should not just change the loop, but also set frame to 1.

**Comment by Crystal-Shard** [comment]
Something that may be related: in REALLY old versions of AGS, it was valid to leave loops 0 and 3 empty, and have a character view with only loops 1 and 2 in it. This means that the character would always be seen from the side, even when walking vertically. I'm reasonably sure this gives an error in AGS 3.X, but it may explain some of the weird corner cases.

**Comment by ivan-mogilko** [comment]
One of the problems is that the latest 3.* engine tries to be compatible with both 3.x and 2.x engine generations, and there has been numerous changes in behavior in between. Because we do not have an access to the older engines codes, I often had to make test games in old editors to emulate some case and guess how the engine behaved. Some of the "strange" conditions may be a result of such experiments; although I cannot tell that this condition in question was one or not without investigating the history of my changes and issues I've been working on at the time first.

**Comment by ivan-mogilko** [comment]
Okay, I found the history of this change:

https://github.com/adventuregamestudio/ags/commit/08aef03ac693c28cc632f566d0a3a17dba48e157#commitcomment-53337336

**Comment by ivan-mogilko** [comment]
@criezy I pushed ac73a555d737fb3f759cc7da9eeaf488a3bdcb2f

This fix seem to work both for HQ and the old game I've been trying to fix with the previous "fix" (LS Larry 2 remake).
The proper solution is to simply test for an empty loop, rather than frame being higher than the loop's frame range.

**Comment by criezy** [comment]
Thank you. That indeed makes sense, and I varied that this fixes the issue for me as well.
