### ISSUE TITLE
[3.6.0>] No AVI/MPG playback on Windows

### ISSUE THREAD

**Issue by necros2k7** [adventuregamestudio/ags#1758]
**Describe the bug**
Game : (room:0)[R 59] PlayVideo: file 'terminus' is an unsupported format.

**AGS Version**
3.6.0.34

**Game**
Donna: Avenger of Blood

**To Reproduce**
Run game

**Expected behavior**
Run OK

**Desktop (please complete the following information):**
 Win11

**Comment by ivan-mogilko** [comment]
This game's intro has AVI format. AGS was always playing AVI/MPG through a Windows interface (DirectShow), and only on Windows os. This feature was discontinued in 3.6.0.

You won't be able to see AVI/MPG game videos unless their playback is reimplemented in the engine in a platform-independent way.

**Comment by ivan-mogilko** [comment]
So, I pushed a change that will let engine to try opening any video using Apeg library regardless of its filename (we may change it to use extension as a hint later when/if more video formats are supported).

This opens a workaround for users to convert avi files to ogv using some converter tool, and thus see these videos in games.
For example, I tested with this online converter: https://convertio.co/avi-ogv/

**Comment by necros2k7** [comment]
Sadly it would be lossy, so it`s only advisable for non Windows players as a workaround

**Comment by i30817** [comment]
Uh. I never noticed this game had that video. Not much of a loss here. Got to report to scummvm that it's broken there though, afaict.

**Comment by i30817** [comment]
Eh. If you rename the video (it's external) you can go in the game in scummvm. So we know that it's this that is sabotaging scummvm, only instead of skipping the video, it's just failing.

**Comment by ivan-mogilko** [comment]
> And by the way why avi support was discontinued?

Several reasons, but primarily because the video playback was implemented using Windows-only interface, and also required that users have codecs installed on system. Thus it's not a portable feature, so we wanted to discourage people using that. AGS users mostly use OGV format today anyway, as it may also be played on Linux etc.

At the time we were focused on porting the engine to SDL2, and avi videos is a rarely used function, so we left it aside for a time being. In the future we'll have to decide whether we like to support avis, and if yes, reimplement it using a cross-platform solution.

**Comment by necros2k7** [comment]
Reimplement is a good idea cause people are cut off with this of old games. They are cut off from pre 2.5 engine games now. (

**Comment by ivan-mogilko** [comment]
> Reimplement is a good idea cause people are cut off with this of old games.

Since there's a ScummVM port, supporting old games is less priority for us now; so if avi support is going to be reimplemented, then not for this purpose, but for the purpose of using it in the new games.

**Comment by i30817** [comment]
^ This is true. I have a 'respectable' collection of ags games and i can remember 4 using video, including this one - which frankly works better without it.

One about a first person thief where the videos were transitions, one that worked anyway (so probably not avi) but very very slow in the video (i think it's 'bustin' the bastille'), and this one that i learned about now and played to completion before twice and didn't even notice that there was a video, and some others where the videos have no problem (commercial games).

The common thread is 'AGS games mostly don't use AVI'. Because of the obvious reason that when gamemakers test it with a recent AGS it won't work.

**Comment by ivan-mogilko** [comment]
I am inclined to close this with *won't fix* for the time being.

Added a note to README which sais that we dropped AVI support, and which potential workaround exists (convert the file to OGV).
