### ISSUE TITLE
Possible exception while deleting and changing a View ID

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1774]
**Describe the bug**
View IDs are not recalculated after deleting a view, this can cause an exception if someone tries to changed a view with higher id to that number.

**AGS Version**
3.6.0 and above

**To Reproduce**
1. Create a few views
2. Delete a middle view (not the latest)
3. Change view id to the now deleted number

**Expected behavior**
Upon deleting a view, any id above that one should be decreased by one.

**Workarounds**
~~a) Saving and reloading the project will correctly renumber every entry~~ nope, it was the change id taking effect, despite no indication
b) Create new view, to fill the hole, and change the id

**Comment by messengerbag** [comment]
Hmm, I have some concerns about this one. I am not sure this _is_ a bug, or that the "expected behavior" is desired.

-In the first place, there seems to be few good reasons to trigger the "bug": why would you change the view ID to a view that doesn't exist? And if you do, why _wouldn't_ it crash?
-Second, some people refer to views by their numeric IDs (rather than by name) in script. Bad practice, sure, but it's done. Renumbering views if one is deleted would break their scripts.
-Third, consistency. The thing in AGS that works closest to views are probably sprites, and sprites do not get renumbered when one is deleted. Also, view names in AGS are all in uppercase, which suggests they are constants. (Personally I don't like this, but that's how it is.) Should constants be redefined automatically in this way?

On the other hand, there is a `Game.ViewCount` property, and the manual states "This is useful for script modules if you need to iterate through all the views for some reason. Valid views are numbered from 1 to ViewCount." Clearly this is not currently accurate.

**Comment by AlanDrake** [comment]
Although I'm not sure about the expected behavior, it should at the least not throw an exception.
And today that I try again, the trick of saving/reloading doesn't work anymore... looks like it only works by saving after an attempted id change..

**Comment by ivan-mogilko** [comment]
> Expected behavior
> Upon deleting a view, any id above that one should be decreased by one.

Like @messengerbag said, current is an intended behavior; AGS intentionally kept View IDs untouched, similar to sprite IDs.
This is what makes Views and Sprite behavior inconsistent with other game items, but it's what it is. So, this should remain unchanged at least in 3.* branch.

For ags4, it's a big question, personally I think the AGS has to come to some consistent system for every list of items it has.

**Comment by ivan-mogilko** [comment]
> On the other hand, there is a Game.ViewCount property, and the manual states "This is useful for script modules if you need to iterate through all the views for some reason. Valid views are numbered from 1 to ViewCount." Clearly this is not currently accurate.

It is accurate, as views are refered by their editor ID +1 in the script. This is a legacy behavior, which original purpose is unknown to me.

**Comment by messengerbag** [comment]
@AlanDrake 
> 3. Change view id to the now deleted number
...
> Although I'm not sure about the expected behavior, it should at the least not throw an exception.

Ah, I misunderstood what you meant by step 3. I thought you were referring to setting an Object, Character, Button, etc. to the missing view in a game, not to changing the ID of a different view to the missing one in the editor. No, of course that should not happen.

@ivan-mogilko
> It is accurate

I was referring to the statement that views numbered 1 to ViewCount are valid (and the implication that it is safe to iterate through them). If some of them can have been deleted so that the number is not valid, the statement is not accurate.

> Yes, all VIEW etc constants are redefined whenever the script is recompiled, to sync with the project contents.

We seem to mean different things by "redefined." If you have 100 Views and delete View 50 (for example), and Views 51-100 keep their old number, I would not call that "redefined" even if technically the compiler pulls them from the project again. Only if the value actually changes.

What I'm seeing in the editor currently is that the numbers are _not_ updated to fill any gaps, but stay as initially set whether or not you recompile, save the project and reload, or what have you. That is expected behavior, IMO, but seems to contradict this, unless I'm again misunderstanding:

@AlanDrake 
> a) Saving and reloading the project will correctly renumber every entry

**Comment by AlanDrake** [comment]
I forgot to edit that statement. It was the "change id" having an effect, despite not looking like it did while changing to the missing id and throwing an exception.

**Comment by ivan-mogilko** [comment]
> I was referring to the statement that views numbered 1 to ViewCount are valid (and the implication that it is safe to iterate through them). If some of them can have been deleted so that an ID <= ViewCount is not valid, the statement is not accurate.

It should be safe to iterate them. The missing views will be present as valid views with 0 number of loops.

**Comment by ivan-mogilko** [comment]
The steps should be clarified: you should change ID of the *last* View to cause the crash.

**Comment by ivan-mogilko** [comment]
Alright, I'm coming to an understanding that the fix is as simple as removing the Swap command for ViewComponent code here:
https://github.com/adventuregamestudio/ags/blob/96770282d619c01fcda25eb8561e8317e3e20379/Editor/AGS.Editor/Components/ViewsComponent.cs#L81

It was added by commit 8c1d9b778cd8e2c83633a904d03576883a1f08f1, but the comment itself sais that it's not strictly necessary, as the flatlist's item order is ignored when saving Views, and their actual ID properties are used instead.

**Comment by ivan-mogilko** [comment]
Pushed 65e44f95718291f73a33f825f414391772a2f570
