### ISSUE TITLE
Access to Custom Properties from Plugins

### ISSUE THREAD

**Issue by WallucePinkham** [adventuregamestudio/ags#1830]
**Describe the problem**
I would like to be able to read / write custom properties from a c++ plugin.

**Comment by ivan-mogilko** [comment]
Similarly to solution posted in #1829, this may be done by retrieving script functions that deal with the custom properties.
`GetScriptFunctionAddress` lets you to receive a script function's pointer.
The functions that deal with the custom properties are: `GetProperty`/`GetTextProperty` and `SetProperty`/`SetTextProperty`, the full names likely are: `Room::GetProperty`, `Object::GetProperty`, `Character::GetProperty`, and so forth.

**Comment by ivan-mogilko** [comment]
I realized that Set(Text)Property script functions were not registered for plugins by oversight; pushed the hotfix just now (96d52b258dd226bc8c2243c1a5bc95a9ceeecd2a). This will be included with the next update.

@WallucePinkham do the mentioned script functions cover your needs though?

PS. There's a general problem with multiple script functions not exported for plugins for some reason, and I'm currently considering a more generic way to fix this. But I'm in doubts whether to apply it to 3.6.0 or wait until next patch / version update like 3.6.1, because this way involves changing the script exports code, and this is prone to errors when done by hand. (3.6.0 is 99% complete, and I would not want to risk adding bugs that might break scripts). So, I guess, I will resort to adding wanted functions for plugin by hand at the moment, if more missing ones are found.

**Comment by WallucePinkham** [comment]
Hi,

Set(Text)Property and Get(Text)Property should cover my immediate needs 
perfectly. Thank you.

-- 
Regards,
Walluce Pinkham
