### ISSUE TITLE
3.6.0.38 "All the way down" 1st dialogue frame text corruption

### ISSUE THREAD

**Issue by necros2k7** [adventuregamestudio/ags#1842]
@ivan-mogilko 
**Describe the bug**
Garbled text in 1st text window

**AGS Version**
3.6.0.38 autobuild

win11 

3.5.0.12 is ok

**Comment by ivan-mogilko** [comment]
This is again a problem with the spritefont plugin.

**Comment by ivan-mogilko** [comment]
Using our own spritefont plugin fixes the issue: 
[AGSSpriteFont.zip](https://github.com/adventuregamestudio/ags/files/10148512/AGSSpriteFont.zip)

**Comment by necros2k7** [comment]
Can these "fix" plugins be integrated in main exe in future?

**Comment by ivan-mogilko** [comment]
> can these "fix" plugins be integrated in main exe in future?

Currently the plugins may be compiled in two ways:
* as standalone dlls;
* integrated in the engine.

Our build server makes engine with integrated plugins as a part of some tasks, for some platforms, but I do not remember how this is organized overall.

Perhaps it makes sense to open a ticket to discuss this, as this relates more to the project organization, rather than bugs etc.
