### ISSUE TITLE
SnowRain plugin draws particles only on part of the screen

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1843]
Our reimplementation of the SnowRain plugin seem to draw particles only on the part of the screen. This was mentioned on forums at least once in the past, but I did not pay attention back then.

It's not clear whether this is a general issue, or depends on the game's resolution or other factors (I've never looked into the plugin's code before). One example where this happens is ["I Can't Sleep in Silence"](https://www.adventuregamestudio.co.uk/site/games/game/2031/) game (you have to either use an engine with embedded plugins or replace plugin dll with our own). The problem is mentioned in comments to #1840.

**Comment by ericoporto** [comment]
It looks like the problem is that `InitializeParticles` runs before the `AGSE_PRESCREENDRAW`, which is the event where the plugin queries the screen dimensions, so it uses the predefined value of height is 200 instead of 400.

There is actually a curious thing in ScummVM here: 
https://github.com/scummvm/scummvm/blob/master/engines/ags/plugins/ags_snow_rain/ags_snow_rain.cpp#L114-L120

But this exact code won't actually work for this game in AGS.

**Comment by ivan-mogilko** [comment]
There have to be a way of retrieving screen dimensions from AGS game, or from the size of the virtual screen (MemoryBuffer).
The latter may not work for Direct3D/OpenGL renderers though.

**Comment by ericoporto** [comment]
I may be an idiot, is there any reason we can't use Screen.Width and Screen.Height directly from script?
