### ISSUE TITLE
Android: AGS Player does not remember "Mouse-to-touch emulation" setting (in Global Preferences)

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1871]
**Describe the bug**
Each time you restart AGS Player and run any game, it seems like "Mouse-to-touch emulation" setting from Global preferences is ignored, and default value is used instead. User has to go into Preferences, and explicitly apply the setting again. It's worth noting that Preferences table displays a correct value remembered from the last time.

**AGS Version**
3.6.0

**To Reproduce**
1. Run "AGS Player", open Global preferences by touching ("...") button at the top-right corner.
2. Set "Mouse-to-touch emulation" to anything but default value.
3. Run any game and confirm that the setting works correctly.
4. Quit the game and close "AGS Player".
5. Run "AGS Player" again, open Preferences, see that "Mouse-to-touch emulation" displays the correct remembered value, but do not touch anything.
6. Run any game and notice that the setting is instead reset to default ("One finger" mode).

**Expected behavior**
Game should be run using last set preferences values.

**Comment by ivan-mogilko** [comment]
So, this also happens with the "Screen orientation" setting.

**Comment by ericoporto** [comment]
Need to check how it works in the single app build, but in the AGS Player, the `android_app_directory` points inside the apk, and in the `android_base_directory` we get the top ags directory (like `"/storage/emulated/0/ags"`). In the `setup.game_file_name` we get the full path. 

It looks like this line always fails in the AGS Player
https://github.com/adventuregamestudio/ags/blob/b1611316632ae4193634d05d59444f273d0c4bb8/Engine/platform/android/acpland.cpp#L349

I think for it to work, we would need to either be in the `android_base_directory` or prefix the filename with it.

There needs to be a check on how does it work in the single game, because I think in that case it either reads the config in the first step or read it twice.

**Comment by ivan-mogilko** [comment]
To clarify, I was talking about Global preferences in this report. I did not realize (or forgot) that there are also individual preferences for each game, because there's no visual indication that you may open them for a particular game (no preferences icon besides the game title).

**Comment by ericoporto** [comment]
Just noting from my comment in #1908

> I am not 100% sure but I think the problem is this here: https://github.com/adventuregamestudio/ags/blob/e069c3f51c08c163df023157e99e14bbcefd317a/Engine/platform/android/acpland.cpp#L101
> 
> So it would be using different directories as base dir, need to think a bit on how to properly fix in a way that is good for the single game player too.
>
> Looking at the original code, I think it was done this way for the writing of the config values to be done without specifying the directory, but I think this is not needed here.
> 
> So in theory one could just pass the directory in both cases and then acpland would just concatenate both without changing the directory. Now later, when the engine starts, it would use the concatenate path as I described in the issue - but I need to just do a minor check for the way it works in the single game project.

As an additional note, we probably would have detected this earlier if we had done #1473 , so the benefit of that would be also simplifying the states the engine could be. Unfortunately that specifically is a bit harder so I am just going to focus on this issue at this point.
