### ISSUE TITLE
Compiler Inconsistency: Default value for float 0.0 needs to be integer 0

### ISSUE THREAD

**Issue by edmundito** [adventuregamestudio/ags#188]
Better to explain with an example:

In a global script/module header, let's say you declare a function with a default float value:

``` C++
import function FadeOut(float delaySeconds = 0.0);
```

The compiler will error out completely with the message:

>  Parameter default value must be literal

It turns out that the default value must be expressed as integer:

``` C++
import function FadeOut(float delaySeconds = 0);
```

Which is fairly inconsistent with the rest of the complier who is really strict about using decimals for the rest of the variables.

This is a really old error, perhaps there since the introduction of modules to the scripting system. I just forgot about it until I ran into it recently. :)

**Comment by sonneveld** [comment]
Currently default values for parameters are only stored as integers in the symbol table.  Might require some rejigging there and where default values are used.

**Comment by AlanDrake** [comment]
AGS is taking integer numbers for float defaults, it's literally passing the raw bytes of the integer which will be later cast to floats.
I guess it's missing a rule somewhere to understand that a float is a float inside defaults declarations.

By correctly forming a float binary value and using the integer interpretation it's possible to actually define valid float defaults, e.g:
```
import function fun(float x=1125918310);.
```
That integer will store the value "156.149994" inside x, which is what I was expecting from those 32 bits.

**Comment by ericoporto** [comment]
I think the place it's getting the default value is here:
https://github.com/adventuregamestudio/ags/blob/d39ca06a63b22f6f3ab18caa30fab615c0c3a653/Compiler/script/cs_parser.cpp#L606-L633

You can see it uses `accept_literal_or_constant_value` to extract the value after the equal sign.

https://github.com/adventuregamestudio/ags/blob/d39ca06a63b22f6f3ab18caa30fab615c0c3a653/Compiler/script/cs_parser.cpp#L554-L593

Now, `accept_literal_or_constant_value` can only parse either integers or a constant, and it's called in more places. If the other places it's called are ok, it can be modified to also recognize floats.

This would enable writing `import function fun(float x=156.15);` , but it later on it should emit a warning if the default value type and the symbol it's assigning to type doesn't match. In the future, it could emit an error for mismatches. The actual build should not care since floats are stored as integer in the engine.

**Comment by AlanDrake** [comment]
I prepared a commit to allow float values and show some errors where the values used make no sense.
0 (null) is always allowed (even for floats, so nothing breaks), but now you can't assign non-zero ints to String or pointers, because they can only be mistakes.
