### ISSUE TITLE
Add a warning when the dynamic sprite is deleted while still assigned to game objects

### ISSUE THREAD

**Issue by jumpjack** [adventuregamestudio/ags#1880]
In case a script tries to access a non-existing sprite slot, engine automatically uses sprite slot n.0 without any warning to developer; it could be useful to write a message in error panel and/or in warnings.log file.

**Comment by ivan-mogilko** [comment]
To clarify, the switch to sprite 0 happens not when it tries to access a non-existing sprite, but when the dynamic sprite gets deleted: in that case it runs a full check on all active game objects, and sees which still reference the sprite. This may be a place to put these warnings.

**Comment by messengerbag** [comment]
As discussed in the forum thread, there can be valid reasons for game entities to still have references to the sprite IDs of deleted dynamic sprites (e.g. because they are now hidden/inactive, or because the sprite was deleted exactly because it was about to be replaced by a new sprite), and in some cases logging all those instances as warnings would clutter up the logs tremendously.

If a warning is really needed, I think the best conceptual approach would be something like:

1. When the sprite ID reference is rewritten, use a placeholder value instead of 0, e.g. -1
2. At the next attempt to display the sprite, catch that it is an illegal value, write a warning in the log, and replace by 0

This would ensure that the warning is only written if there is ever an attempt to actually display the entity without first updating the invalid sprite ID.

Drawbacks of this approach:

1. It would not help to identify the dynamic sprite that was deleted to cause the issue, or the place in the code it happens, so the warning would not be very helpful
2. Having to sanity-check the sprite ID of every object every time it is displayed might incur a serious performance hit

**Comment by ivan-mogilko** [comment]
@messengerbag this is commonly done by accumulating a list of objects for processing, this way they may be paired with additional information, such as the sprite ID they had.

**Comment by ivan-mogilko** [comment]
> As discussed in the forum thread, there can be valid reasons for game entities to still have references to the sprite IDs of deleted dynamic sprites (e.g. because they are now hidden/inactive, or because the sprite was deleted exactly because it was about to be replaced by a new sprite), and in some cases logging all those instances as warnings would clutter up the logs tremendously.

By the way, for the same reasons the replacement of a sprite ID to 0 is currently also done suboptimally. I believe then the reaction on a sprite's deletion (whatever that reaction is) should not follow immediately. Instead engine might store the list of deleted sprites, and handle the situation once the script passed execution into the engine (during next game update, before the redraw).

There's another problem along the way here: newly created dynamic sprites may occupy IDs of recently deleted ones. If engine does the "situation check" after the script, then it may get incorrect picture, as some of the "deleted IDs" may already be taken by new valid sprites, which may also be assigned to objects.
Right now, I see only one potential way to workaround this: "lock" certain IDs until the next game update, so that if script creates more dynamic sprites right after deletion, these sprites would use different ones.

**Comment by AlanDrake** [comment]
A common approach I've seen often is having a `deleted` property to *soft* delete an object until the next safe flush.

**Comment by ivan-mogilko** [comment]
> A common approach I've seen often is having a `deleted` property to _soft_ delete an object until the next safe flush.

Right, this is also a good way to handle these situations when objects reference each other.

**Comment by ivan-mogilko** [comment]
A note: I looked into the solution that I myself proposed above, and briefly - it's doable, but I don't like it, because it postpones the property reset. This property reset is already bad (here I agree with @jumpjack , but it's currently the only safe method without bigger change to the system), but making its timing *random* looks even worse from the scripting pov. I tried to speculate on troubles that it may cause, and I can see at least few potential ones.

At first I thought that gathering the records of deleted sprites and running update over them once per frame would at least make things faster, but now I think that this is likely not the case, as number of checks is still going to be the same. We will only save on *marking some object changed* extra time, but that will likely save a minuscule amount of time. And the object will have to be marked "changed" anyway if it's assigned a new sprite afterwards, so nothing is saved in terms of redrawing it.

If the property change is *not* postponed, then recording notes to make a warning later would be troublesome, as the objects may be reassigned in between. Theoretically, we may follow @messengerbag's proposal which is basically to tag certain objects as "invalid" somehow, gather their list to possibly speed these checks up, and then test them all in a single pass right before the render.
That's doable, but with the current engine codebase that we have the implementation will be ugly (because of the lack of proper object type inheritance, and other reasons).

This is why I come to doubts whether all this is worth it.

It may be much better to invest into designing a better solution for the sprite referencing. One thought that I had is to make sprite index assignment to any object properties coupled with the *reference counting*. Except it won't be a counter of DynamicSprite object as in script, but some kind of an internal counter of a sprite slot.
Supposedly, when the image itself is disposed, the engine could test whether there are still references remaining to it, and keep the slot occupied by a dummy entry, which remaps to sprite 0, or another placeholder (this method is already implemented, it's used when the sprite failed to load for some reason).

**Comment by ivan-mogilko** [comment]
Ermmm,
actually, in this regard:

> It may be much better to invest into designing a better solution for the sprite referencing. One thought that I had is to make sprite index assignment to any object properties coupled with the reference counting. Except it won't be a counter of DynamicSprite object as in script, but some kind of an internal counter of a sprite slot.

I've been toying with some ideas, and then it suddenly came to me that it's possible to just return a placeholder sprite's pointer from the sprite cache if it was requested a sprite that does not exist. Spritecache already tests for sprite's validity since it has to load it from file if it's not present, so that won't add any overhead whatsoever.

This is one of those amazing situations when I am surprized, why this trivial solution did not come to me years ago, as it should solve everything, including cases when user set non-existing sprite ID in script.

I will think this over more, and maybe make a pr, but so far I don't see any problems with this...

**Comment by ivan-mogilko** [comment]
Changed to not resetting Graphic properties to 0 in #2104; so the situation changed, also, it's going to be complicated to make these warnings consistently now, for the reasons explained in #2104.
