### ISSUE TITLE
Sprite not flipped

### ISSUE THREAD

**Issue by jumpjack** [adventuregamestudio/ags#1882]
Using AGS 3.6.0 RC 4 on Windows 10, this code, placed into room_Load() function, should copy into roomOverlay[overlayIndex] and show on screen a flipped sprite:
```
      DynamicSprite* flipped = DynamicSprite.CreateFromExistingSprite(tileIdNorm,  true); 
      flipped.Flip(eFlipLeftToRight); 
      roomOverlay[overlayIndex] = Overlay.CreateRoomGraphical(x, y,  flipped.Graphic);
```
Instead, the dafult sprite at slot 0 is shown on screen:

![image](https://user-images.githubusercontent.com/1620953/210742129-f88e8c9c-55cd-4219-92f7-2f8b32aa239f.png)

Adding following line immediately after last one:

`background.DrawImage(x, y,  flipped.Graphic);`

result in flipped sprite being properly shown on screen:

![image](https://user-images.githubusercontent.com/1620953/210742229-c7cf7edb-b5a4-498e-8e62-300d44cc3fac.png)

Removing the overlay statement:

![image](https://user-images.githubusercontent.com/1620953/210742337-8ac5e907-e8d7-4801-907d-0966920af1d7.png)

Issue does not occur enabling cloning of the sprite:

`Overlay.CreateRoomGraphical(x, y,  flipped.Graphic, 0 /*transparency*/, true /*clone*/);`

![image](https://user-images.githubusercontent.com/1620953/210742646-d9247415-7bf6-422f-a3a4-1fd87bf972fe.png)

Reference thread:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=60499.0

**Comment by messengerbag** [comment]
I would suggest not opening a bug report until we have ruled out a bug in _your_ code. It is quite presumptuous to assume that the mistake is in engine code that have been successfully used by many others, rather than something you, as an AGS novice, haven't correctly grapsed.

As already explained in the forum thread, the code you've posted here would not work because the `flipped` variable goes out of scope as soon as the function exits. You claim Khris's corrected version also does not work, but I would like to see you present your implementation of that in full.

**Comment by ericoporto** [comment]
Once `}` is met, local variables go out of scope. `flipped` is a local variable, so it will be removed. As the DynamicSprite created has no other places holding references to it, it gets Garbage Collected. As the DynamicSprite contains the actual sprite that was locked, it gets destroyed from there. 

Please always ask in the forums before opening an issue. If you decide to open an issue, follow the bug report template. The issues you are opening are just not actionable as they are written.

Overall, it's better to make a simpler game in AGS to understand the Adventure concepts in it before trying to use the engine for a different purpose.

**Comment by jumpjack** [comment]
Note: as I already explained both in forum and in this issue, the sprite slot DOES still exist when code execution arrives to next statement `background.DrawImage(x, y,  flipped.Graphic);` . All those statements are consecutive and inside same function.
I group them here:

```
DynamicSprite* flipped = DynamicSprite.CreateFromExistingSprite(tileIdNorm,  true); 
flipped.Flip(eFlipLeftToRight); 
roomOverlay[overlayIndex] = Overlay.CreateRoomGraphical(x, y,  flipped.Graphic); // here sprite slot is not available
background.DrawImage(x, y,  flipped.Graphic); // here sprite slot is available
```

Full code (full of rubbish...) follows; please note as both roomOverlay and flipped are declared outside any function, as I was suggested to do in the forum; indeed I decided to open the issue after implementing suggestion and reading in the forum "This does not sound normal, I expected Khris's code to work"; after the issue analysis, if it will result that it's not actually an AGS bug, it will be just closed with "wontfix".

```

Overlay* roomOverlay[100];
DynamicSprite* flipped;

int YFACT = 20;
int XMARGIN = 5;
int YMARGIN = 5;
int isoXcalc,  isoYcalc;
int cartXcalc,  cartYcalc;


struct tilesRow {
 String elements[10];
};

struct tilesRowInt {
 long elements[10];
};

tilesRow map[10];
tilesRowInt mapTiled[10];


function populateArray(int width,  int height,  String contents) {
   for (int y=0; y < height; y++) {
    for (int x=0; x < width; x++) {
      String val = contents.Substring(x + y*width, 1);
//debugPrint(String.Format("Assigning value %s to element x,y %1d, %1d", val, x, y), false);
      map[x].elements[y] = val;
//debugPrint(String.Format("Result: %s",map[x].elements[y] ), false);
    }
  }
}


function populateArrayTiled(int width,  int height,  String contents) {
   bool ex = false;
   for (int y=0; ((y < height) && (ex == false)); y++) {
    for (int x=0; ((x < width) && (ex == false)); x++) {
      int  pos = 0;
      int length = contents.IndexOf(",");
     if (length>0) {
        int startPos = length + 1;
        int newLength = contents.Length - length - 1;
//debugPrint(String.Format("%s / %1d, %1d, %1d, %1d",  contents, pos,  length,  startPos,  newLength), false);
        String val = contents.Substring(pos,  length);
        //val = String.Format("%s.0", val);
        //val = val.Replace(" ", ""); 
        long finalVal = val.AsInt;
        mapTiled[x].elements[y] = finalVal;
        contents = contents.Substring(startPos,  newLength   );
//debugPrint(String.Format("String value %s  turned into int %d and assigned to element x,y %1d, %1d, new string:\n%s", val, finalVal,  x, y,  contents), false);
     } else {
        length = contents.Length;
        String val = contents.Substring(pos,  length);
        val = String.Format("%s", val);
        //val = val.Replace(" ", "");
        long finalVal = val.AsInt;
        mapTiled[x].elements[y] = finalVal;
        ex = true;
// debugPrint(String.Format("Assigning LAST value %s to element x,y %1d, %1d", val, x, y), false);
     }
      
//debugPrint(String.Format("Result: %d",mapTiled[x].elements[y] ), false);
    }
  }
}


 
function room_Load(){
    player.Baseline = 0;
  /*
  // Tiled JSON data:
           "data":[0, 53, 53, 53, 53, 53, 53, 53, 53, 0,
            2147483701, 2147483684, 0, 43, 43, 43, 0, 0, 0, 2147483674,
            2147483701, 0, 0, 0, 0, 0, 0, 0, 2147483658, 0,
            2147483669, 0, 0, 0, 43, 43, 43, 0, 0, 2147483676,
            2147483701, 0, 25, 0, 43, 43, 43, 0, 0, 2147483675,
            2147483669, 0, 0, 0, 43, 43, 43, 0, 0, 2147483675,
            2147483701, 0, 0, 0, 0, 0, 0, 0, 0, 2147483674,
            2147483701, 2147483691, 0, 0, 0, 0, 0, 0, 2147483658, 0,
            2147483701, 2147483691, 2147483691, 0, 10, 0, 2147483691, 43, 0, 2147483676,
            0, 28, 27, 26, 0, 28, 27, 27, 27, 0],
            */
            

// Note: AGS does not support numbers as large as the ones used by Tiled to define a tile as "flipped",  obtained by adding 2^32/2 to tile id.
    String mapStrTiled= "";
    mapStrTiled = mapStrTiled.Append("0,53,53,53,53,53,53,53,53,0,");
    mapStrTiled = mapStrTiled.Append("32821,32804,0,43,43,43,0,0,0,32794,");
    mapStrTiled = mapStrTiled.Append("32821,0,0,0,0,0,0,0,32778,0,");
    mapStrTiled = mapStrTiled.Append("32789,0,0,0,43,43,43,0,0,32796,");
    mapStrTiled = mapStrTiled.Append("32821,0,25,0,43,43,43,0,0,32795,");
    mapStrTiled = mapStrTiled.Append("32789,0,0,0,43,43,43,0,0,32795,");
    mapStrTiled = mapStrTiled.Append("32821,0,0,0,0,0,0,0,0,32794,");
    mapStrTiled = mapStrTiled.Append("32821,32811,0,0,0,0,0,0,32778,0,");
    mapStrTiled = mapStrTiled.Append("32821,32811,32811,0,10,0,32811,43,0,32796,");
    mapStrTiled = mapStrTiled.Append("0,28,27,26,0,28,27,27,27,0");    
    
/*    
    mapStrTiled = mapStrTiled.Append("0, 53, 53, 53, 53, 53, 53, 53, 53, 0,");
    mapStrTiled = mapStrTiled.Append("2147483701, 2147483684, 0, 43, 43, 43, 0, 0, 0, 2147483674,");
    mapStrTiled = mapStrTiled.Append("2147483701, 0, 0, 0, 0, 0, 0, 0, 2147483658, 0,");
    mapStrTiled = mapStrTiled.Append("2147483669, 0, 0, 0, 43, 43, 43, 0, 0, 2147483676,");
    mapStrTiled = mapStrTiled.Append("2147483701, 0, 25, 0, 43, 43, 43, 0, 0, 2147483675,");
    mapStrTiled = mapStrTiled.Append("2147483669, 0, 0, 0, 43, 43, 43, 0, 0, 2147483675,");
    mapStrTiled = mapStrTiled.Append("2147483701, 0, 0, 0, 0, 0, 0, 0, 0, 2147483674,");
    mapStrTiled = mapStrTiled.Append("2147483701, 2147483691, 0, 0, 0, 0, 0, 0, 2147483658, 0,");
    mapStrTiled = mapStrTiled.Append("2147483701, 2147483691, 2147483691, 0, 10, 0, 43, 43, 0, 2147483676,");
    mapStrTiled = mapStrTiled.Append("0, 28, 27, 26, 0, 28, 27, 27, 27, 0");   
 */   
    
    populateArrayTiled(10, 10, mapStrTiled);

  String mapStr = "";
  // debug: map should be loaded from Tiled TMJ file:
  mapStr= mapStr.Append("0111111110");
  mapStr= mapStr.Append("1101110001");
  mapStr= mapStr.Append("1000000000");
  mapStr= mapStr.Append("1000111001");
  mapStr= mapStr.Append("1010111001");
  mapStr= mapStr.Append("1000111001");
  mapStr= mapStr.Append("1000000001");
  mapStr= mapStr.Append("1100000000");
  mapStr= mapStr.Append("1110001101");
  mapStr= mapStr.Append("0111011110");
//debugPrint(mapStr, false);
  populateArray(10, 10, mapStr);
  

  long FACTOR =  32767; // 2147483647; // debug overflow
  
/////// Load tilemap:
/*
DynamicSprite* sprite = DynamicSprite.CreateFromFile("CustomAvatar.bmp");
sprite.Flip(eFlipLeftToRight ); // in case the tiles need to be horizontally flipped
DrawingSurface *surface = Room.GetDrawingSurfaceForBackground();
surface.DrawImage(100, 100, sprite.Graphic);
surface.Release();
sprite.Delete();
*/


CL_Console.Log(String.Format("Player Position: (%d;%d)", player.x, player.y));

/////// Create walkable area:
  int tileIdNorm;
  DrawingSurface *walk = GetDrawingSurfaceForWalkableArea();
  DrawingSurface *minimap = Region.GetDrawingSurface(); // Used to allow reading map from other scripts
  DrawingSurface *background = Room.GetDrawingSurfaceForBackground();
  
  // Make everything walkable:  
  walk.DrawingColor = 1;  
  walk.DrawRectangle(0, 0, walk.Width, walk.Height);
  
  int overlayIndex = 0;
for (int isoX = 0; isoX < mapwidthTiles; isoX++) {
  for (int isoY=0; isoY < mapheightTiles; isoY++) {
    isoToCartesian(isoX, isoY,  tilewidth * (mapwidthTiles/2));
    String tileId =  "--";//mapTiled[isoX].elements[isoY];
    long tileIdInt = mapTiled[isoX].elements[isoY];
    if (tileIdInt > FACTOR) { // Tiles to be flipped  
      tileIdNorm = tileIdInt - FACTOR - 1; 
      flipped = DynamicSprite.CreateFromExistingSprite(tileIdNorm,  true); // clone the sprite to flip it
      flipped.Flip(eFlipLeftToRight); 
      roomOverlay[overlayIndex] = Overlay.CreateRoomGraphical(screenx - tilewidth/2, screeny - 2*tileheight + YFACT,  flipped.Graphic,  0,  true);
      roomOverlay[overlayIndex].ZOrder = (isoX + isoY + 1)*6 + YFACT ;
      //background.DrawImage(screenx - tilewidth/2, screeny - 2*tileheight + YFACT,  flipped.Graphic); // for debugging
//debugPrint(String.Format("FLIPPED Overlay n. %d is located at ISO %d, %d, has normalized id %d (original id: %d, flipped slot: %d) and Z=%d", overlayIndex, isoX,  isoY,  tileIdNorm, tileIdInt,  flipped.Graphic, roomOverlay[overlayIndex].ZOrder), false);
      overlayIndex++;  
    } else { // Don't flip tile
      if (tileIdInt !=0) { // Regular tile
        tileIdNorm = tileIdInt;// - 1;
        //DynamicSprite* normal = DynamicSprite.CreateFromExistingSprite(tileIdInt,  true);
        //background.DrawImage(screenx - tilewidth/2, screeny - 2*tileheight -3, normal.Graphic);
        roomOverlay[overlayIndex] = Overlay.CreateRoomGraphical(screenx - tilewidth/2, screeny - 2*tileheight + YFACT, tileIdNorm);
        roomOverlay[overlayIndex].ZOrder = (isoX + isoY + 1)*6  + YFACT;
debugPrint(String.Format("Overlay n. %d is located at ISO %d, %d, has id %d and Z=%d", overlayIndex, isoX,  isoY,  tileIdNorm, roomOverlay[overlayIndex].ZOrder), false);          
        overlayIndex++;  
      } else {   // Empty tile (=walkable area)
        tileIdNorm = 0;
     }
    }

    if ((tileIdNorm != 0) && (tileIdNorm != 10)) { // 0 = walkable,  !=0 = not walkable
      walk.DrawingColor = 0; // Drill non walkable areas

      int x1 = screenx;                           int y1 = screeny + YFACT;
      int x2 = screenx + tilewidth/2;             int y2 = screeny + tileheight/2 + YFACT + YMARGIN/2;
      int x3 = screenx - tilewidth/2;             int y3 = screeny + tileheight/2 + YFACT + YMARGIN/2;

      int x4 = x2; int y4 = y2 + YMARGIN/2; 
      int x5 = x3; int y5 = y3 + YMARGIN/2; 
      int x6 = screenx;                           int y6 = screeny + tileheight + YFACT + YMARGIN;
      
      ///// drill nonwalkable holes in walkable area:
      // debug 
      walk.DrawTriangle(x1, y1,   x2, y2,   x3, y3);
      walk.DrawRectangle(x3,  y3,    x4,  y4);
      walk.DrawTriangle(x4, y4,   x5, y5,   x6, y6);
      
      /////////
      
      minimap.DrawingColor = MINIMAP_WALKABLE_COLOR;
      minimap.DrawPixel(isoX,  isoY);
//debugPrint(String.Format("x,y, val = %1d, %1d, '%s', '%s' IS WALKABLE", isoX,  isoY, tileId,  tileIdNorm), false);
    } else {
      // not walkable
      if (tileIdInt < 64) {
        minimap.DrawingColor = 1;
      } else {
        minimap.DrawingColor = 0;
      }
      minimap.DrawPixel(isoX,  isoY);
//debugPrint(String.Format("x,y, val = %1d, %1d, '%s', '%s'  - NOT", isoX,  isoY, tileId, tileIdNorm), false);
    }
  }
}

      walk.Release();
      minimap.Release();
      Debug(5, 0); // show path of player
      
     
}

function room_FirstLoad()
{
  

}



```

**Comment by jumpjack** [comment]
Game attached:

[004-2.zip](https://github.com/adventuregamestudio/ags/files/10351207/004-2.zip)

**Comment by messengerbag** [comment]
Just post all this on the forum thread. As @ericoporto says, this is not an actionable engine development issue, and does not belong here.

**Comment by messengerbag** [comment]
I know at least one reason why your code doesn't work, but the discussion belongs in the forums, not here.

**Comment by ericoporto** [comment]
You still ignored what I said, there's a lot that happens when `}` is met.

**Comment by jumpjack** [comment]
can you post a supposedly working snippet of code?

**Comment by khrismuc** [comment]
I thought we had already moved past this? The issue isn't that the local pointer stops existing and the overlay reverts to sprite #0, it's that even moving the DynamicSprite declaration outside the function doesn't fix it.

However the crucial part is that these overlays are created **in a loop**.

You're using a single DynamicSprite pointer, which means these overlays keep using the same two sprites. You'll get unexpected results naturally, and setting clone to true fixes this, because now each of the _multiple_ overlays uses its own (correctly flipped) sprite.

**Comment by ivan-mogilko** [comment]
@jumpjack, first of all I also would like to ask, please do not duplicate conversations. If you already have an active ongoing conversation on forums, which did not come to a conclusion whether this is a scripting mistake or an engine bug, there's no point at all in opening a duplicate topic in github repository, as the people who would reply here are more or less the same people who use the forums.

Secondly, when having errors like that, I always advise to reproduce the problem with a smaller piece of code. For example, extract it from a large game script into a dummy game, have only variables and commands you need for the problem's replication. This helps to narrow down the issue, and also makes reading your code easier.

---

*In regards to this ticket*, the script you posted in the very first post does not work, because you are storing DynamicSprite in a local variable, which gets destroyed as soon as the function ends, which also destroys the DynamicSprite itself, because it has no other pointers refering it. Default sprite (0) is displayed, because when dynamic sprite is deleted, all the objects that still reference it will switch to sprite 0 for safety.
We have already discussed that in the forum thread, so the reasons you are opening a ticket with the same question is unclear to me.

But later on in comments you posted a different code, where you're using a global variable to store DynamicSprite instead, and also clone it when creating overlays. So which code are you really asking about, the first or the second?

By the way, if you are cloning a sprite when creating overlays, then you don't really have to store DynamicSprite in a global variable. It's either one or another:
1) If you `clone`, then there's no need to store DynamicSprite further, and you may simply have it in a local (temporary) pointer.
2) If you *do not* `clone`, then you have to store it further, in a global variable.

**Comment by ivan-mogilko** [comment]
> I decided to open the issue after implementing suggestion and reading in the forum "This does not sound normal, I expected Khris's code to work"; after the issue analysis, if it will result that it's not actually an AGS bug, it will be just closed with "wontfix".

But the code you posted is not the same code as Khris suggested on forums.

**Comment by ivan-mogilko** [comment]
I would close this, as nothing in the above suggests there may be an engine bug, and every non-working script sample may be explained. Judging by the forum thread, there had been a bit of misunderstanding mainly because the essential parts of the script were omitted (the fact that sprites and overlays are created in a loop).

I may reiterate a recommendation to test "strange" cases separately from the main script. For example, create a separate room, and test how a single Overlay works there first. Then test how multiple overlays in array would work, and so on. This approach helps to narrow down the problem.

**Comment by jumpjack** [comment]
This screenshot shows that out of 21 overlays drawn, once is right (the one at the bottom) and 20 are set to "sprite 0":

![image](https://user-images.githubusercontent.com/1620953/211145895-54b88d2f-2807-47fc-8244-e358a9e0ba3f.png)

It is the tile number 32796, which means "flipped 28" in my script:

![image](https://user-images.githubusercontent.com/1620953/211146013-c6c19474-59a7-43c4-825a-c24e9530cb3c.png)

![image](https://user-images.githubusercontent.com/1620953/211146028-401cdb94-1787-4adf-9301-146bd80b619e.png)

It is the last to be drawn, because for this test I disabled drawing on non-flipped tiles, i.e. with id < 32768.
