### ISSUE TITLE
AGS 4: Script editor triggers "modified externally" warning right after Undo

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1925]
**Describe the bug**
Under certain condition the script editor triggers "file was modified externally" warning, even though it was modified strictly from the editor itself.

**AGS Version**
AGS 4.
Was not able to reproduce in 3.6.0.

**To Reproduce**
1. Launch the Editor.
2. Open any script.
3. Type anything, then immediately **undo the typing** (this is important!) by pressing Ctrl+Z or Edit->Undo menu command.
4. Save.
5. Observe "script was modified externally" popup, displayed twice in a row.

**NOTE:** this always happens for the first edited script, right after you launched the editor. Sometimes it no longer happens if you try to repeat same operations within same script, but on some occasions it does. Also, it may or not repeat in other scripts. I was not able to understand whether this depends on a coincidence, timing, or else. The error only reliably occurs the first time you open and edit a script.

**Expected behavior**
"Script was modified externally" warning should not trigger if a script is modified only from the editor.

**Comment by AlanDrake** [comment]
Scintilla's modified state was not being correctly synced.
The undo/redoed script that arrived to the saved checkpoint, which should be considered unmodified, was saved again due to this mismatch, and the filewatcher was then catching the "unmodified" file being modified by the editor and triggering the dialog.

It was not happening in room scripts only because the save code is wrapped into a block that disables the filewatcher.
