### ISSUE TITLE
Different uses of Relative vs Direct in Touch vs Mouse input

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1930]
Currently (AGS 3.6.0.43 8dce503b05728edabe6205e7fbf3f660ed31e957), we can set the cursor movement to be direct or relative using `[mouse] control_enabled=0` or `1` (it also requires `[mouse] control_when=always` and defaults to `[mouse] control_when=fullscreen`). 

- When using **direct** and **touch**, the input is _usually_ for a game with hidden cursor, where the user tap directly where it's intended in the screen, in a game that has been properly designed for this - bigger hotspot areas and such to take into account finger size.
- When using **relative** and **touch**, the input is _usually_ for a game with visible cursor, where the user controls this cursor and keeps it near but not under the finger, so it can be used with more precision, either because the mobile port was rushed or because a vocal part of the userbases asks for this mode. Usually this works better also with `[touch] emulate_mouse=2`
- Using **direct** and **mouse**, is the expected default for most AGS games.
- When using **relative** and **mouse**, this is _usually_ intended for some infinite mouse implementation, that can be useful for FPS-like games and other non-point and click adventure like games. This also can be used simply for a game controlled mouse speed.

The platforms available are mostly used with one type of input device - most desktop platforms (Windows, Linux, macOS) are used with Mouse input and most mobile platforms (Android, iOS) are used with Touch input. But the Web platform exists in both desktop and mobile platforms, so you can use a game built for web with either mouse or touch input.

This is more a consequence of the existing logic and how it manifests on the two different types of input, not sure what can or should be done about this, but it looks like a game can be intended to use `relative` cursor control in touch input and `direct` cursor control in mouse input.

**suggested change**

I would suggest ignore `control_enabled` and `control_when` for input _originated_ from touch and use a new `[touch] emulate_mouse_relative=0` or `1` to decide if that would be direct or not. Not sure how possible this is in code though and also what this means for `Mouse.ControlEnabled` in the game.

**Comment by ivan-mogilko** [comment]
It's very worth noting, that the "touch" in question (currently) is in fact a touch-to-mouse emulation, which means that the touch input is converted to mouse events. This in turn raises a question whether mouse settings should be applied. They are now, e.g. mouse "speed" parameter is also used in t2m.

I had one idea about potential solution, but as I think this problem over again, I begin to doubt myself.

It's possible that the root of this problem is not in conjunction between mouse and touch-to-mouse controls, but in the fact that the engine utilizes SDL2's relative mouse mode for mouse speed. I did experiment with other ways, but forgot what happened.
Need to refresh my memories on the code, and think this over once more...

**Comment by ivan-mogilko** [comment]
Supposing we consider touch-to-mouse a separate "device" with its own options; in such case the solution seem to be to imagine we have 3 components:
1) mouse device that sends SDL mouse events; and may be either abs or relative.
2) touch-to-mouse device that sends SDL mouse events; and may be either abs or relative.
3) internal engine's mouse handler that receives mouse events, as either abs or relative motion commands.

In this scenario, the "internal" component *must not* know anything about the abs/relative config options, because they are applied to particular devices (or rather device types). Instead it should rely on the motion event to tell, whether this is an absolute or relative movement. If there are multiple events in the queue, coming from more than 1 device, then I'd imagine that absolute movement has a priority and overrides anything relative.

What remains is a question of how to detect that motion event means absolute or relative move. Thing is, SDL2 fills in both absolute pointer coords and relative fields in the event's struct regardless. For consistency, our touch-to-mouse implementation does the same.

The simpliest solution, it seems, is to rely on the device ID, which is written in event (the `which` field in `SDL_MouseMotionEvent`). When handling the mouse we may probably always accept absolute coords, since SDL2 does the calculation for us even if we utilize its "relative" mode in order to adjust cursor speed. The touch-to-mouse "device" has a separate ID (`SDL_TOUCH_MOUSEID`). If we see that ID we might check what is a t2m's config setting and handle the event correspondingly.

Alternatively, we may probably find some reserved/user field in the event struct, or attach a kind of a flag to the existing field. Maybe even have a separate custom device IDs for relatively or absolutely moving t2m device.

**Comment by ivan-mogilko** [comment]
I have a (probably) working solution here: https://github.com/ivan-mogilko/ags-refactoring/tree/360--touch2mouse-separateconf

But my doubts are related to the script API. Right now there's Mouse.ControlEnabled and Mouse.Speed properties. ControlEnabled is a silly thing, added mostly for compatibility with "Clifftop Games" custom engine (titles like "Kathy Rain" and "Whispers of a Machine"). The fact that it works like a absolute/relative motion switch is a coincidence, related to the internal implementation of mouse speed in a SDL2-based engine (maybe it's not optimal and there are other ways to do this, btw). In practice it should not be seen as one.

If we make separate config settings for mouse and touch input, and handle these options separately in the engine, should the script API also be separate? Right now you may use Mouse.Speed to also adjust touch input speed, and Mouse.ControlEnabled to switch between abs and relative touch modes (although the latter is wrong). If I separate the config, should I also separate the script API? For instance, I could keep Mouse.Speed to work for both for now.

**Comment by ericoporto** [comment]
I tested your PR and your solution is indeed working. Tested on Both Android and Web builds, there is just the small issue I mentioned directly in the PR.
