### ISSUE TITLE
Command line scaling options no longer apply

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#1946]
**Describe the bug**
Command line options to configure scaling no longer apply.

**AGS Version**
3.6.0.44-RC9

**To Reproduce**
```sh
<game> --windowed --gfxfilter stdscale 1
<game> --windowed --gfxfilter stdscale 2
<game> --windowed --gfxfilter stdscale 3
```
And observe no difference in the size of the game window.

**Expected behavior**
Honour requested scaling.

**Comment by ivan-mogilko** [comment]
Ah, the window scaling setting now works differently in config. The OPTIONS.md has an obsolete information about this. And the help printed by --help also has some obsolete info.

Now the filter scaling has only scaling style options ("round", "stretch", "proportional").

The window scaling is defined by setting `window=` in config, which may have following values:
```
WxH - explicit window size (e.g. 1280x720);
xS - integer game scaling factor (e.g. x4);
etc
```

Unfortunately, it seems, there's no command line alternative for that now. So that may be a problem.

**Comment by ericoporto** [comment]
About adding things to `--windowed`, it's used in webport because a browser tab doesn't start in fullscreen, and in the editor  to launch a debug game in a window

https://github.com/adventuregamestudio/ags/blob/2d7cbd03d89bded4c5155716f0ff7964e34d0a2f/Editor/AGS.Editor/Tasks.cs#L508

I particularly use `--windowed` in both my VS and CLion options when debugging AGS, because I only have one monitor.

> Alternative could be to have a separate argument

The change in scaling options assumes mode/sizes differently for window and fullscreen, I can't comeup with a good name right now, but I think this would work best.

**Comment by ivan-mogilko** [comment]
@ericoporto my meaning was an optional subargument, that may be omited.

**Comment by ericoporto** [comment]
ahn, OPTIONS.md has `windowed` for the same behavior as is in the command-line, and `window` for the size options. Could we use `<game> --window=x1 --gfxfilter stdscale` ?

**Comment by ivan-mogilko** [comment]
Well, the first question then is whether command line needs arguments for setting separate windowed/fullscreen modes, or it's enough to have an arg for starting mode.

**Comment by ericoporto** [comment]
let's assume we only need to use arguments for the starting mode, it seems saner for a command line interface.

But looking back at OPTIONS.md, I see a there's `game_scale_fs` and `game_scale_win`, and both also can receive a number as scaling factor. I am not too sure what is the difference from the other, but `--game-scale` looks like a good name for a command line option.

**Comment by ivan-mogilko** [comment]
> But looking back at OPTIONS.md, I see a there's game_scale_fs and game_scale_win, and both also can receive a number as scaling factor. 

Like I mentioned in my comment above, this is an obsolete information. game_scale_fs and game_scale_win no longer accept numbers as scaling factor in 3.6.0.

**Comment by ivan-mogilko** [comment]
Erm... the OPTIONS.md actually have correct info about `--gfxfilter` command (maybe I've been looking in the wrong place..?), it's the `--help` output that was not updated.

**Comment by ivan-mogilko** [comment]
@morganwillcock after overlooking the current situation, `--gfxfilter` command has kind of a dubious functionality, as it combines both filter type, and game scaling which is not directly related to the filter. While in config all this is now separated into different options.

As a **quick fix** I might add back support for having numeric values in `gfxfilter` command arg. It will work like this:
- if a number is met, then it will set it as `window=xN` config option, and `game_scale_win=round`;
- if anything else is met, then it will set it only as `game_scale_win=value`.

Will this work for now? We may think about separate command args later if necessary.

**Comment by ivan-mogilko** [comment]
Pushed a28160b24a2f27b59cbb12a1de358cc9ec9c19ef

**Comment by ivan-mogilko** [comment]
Oops, realized there were still missing cases. Pushed f19043d902ff9a7e7d6478f51093ef3c807dd258

Now it acts, as explained in comment:
> // we make an assumption here that if user provides scaling
                // multiplier, then it's meant to be applied to windowed mode only;
                // Otherwise the scaling style is applied to both.

**Comment by ivan-mogilko** [comment]
Also updated the manual (config and cmd line articles).

**Comment by ivan-mogilko** [comment]
Well, I think it should be working now, @morganwillcock if you meet other related problems please reopen this ticket, or open a new one.
