### ISSUE TITLE
AGS4: 16-bit sprites don't get rendered

### ISSUE THREAD

**Issue by dkrey** [adventuregamestudio/ags#2107]
**Describe the bug**
When importing an older project with 16-bit sprites and 32-bit sprites, only the 32bit a being rendered. E.g  mouse cursors with 16bit sprites are invisible.

**AGS Version**
3.99.106.0

**Game**
If applicable, link or attach an example game (with optional source) to demonstrate the issue.

**To Reproduce**
1. Import a project with 16bit sprites and 32bit sprites.
2. Set the mouse courser to a 16 bit sprite and it's gone
3. Set the mouse courser to a 32 bit sprite and it's visible again.

This also applies to dynamic sprites and so on.

**Expected behavior**
16bit sprites should be converted to 32bit at least during the import of the project.

**Screenshots**
![32bitvs16bit](https://github.com/adventuregamestudio/ags/assets/11175831/727cdc07-00cb-4a8c-82eb-aaa12c80ebbb)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
Please clarify, are they not visible in the editor, or in game?

**Comment by dkrey** [comment]
> Please clarify, are they not visible in the editor, or in game?
Just in the game. The screenshot is from the editor - the cursor with the pink background is not rendered in the game, the one with the white background is rendered correctly.

**Comment by ivan-mogilko** [comment]
I may be wrong, but iirc the imported sprites are converted to the game's color depth automatically, at least since AGS 3.5.0.
But they were never converted on project load (regardless of the version diff).

I don't remember if this adjust the color depth, but the potential workaround is to do "replace from source(s)" on these sprites (or "Recreate spritefile from sources"). Of course this may work so long as you have the sources.

I believe there are two questions here:
- automatic conversion of sprites to game's default format in the Editor;
- automatic conversion at runtime (because sprites may also be loaded from files).

We need to decide if we want to support sprite color depth mix in one game. Probably not for 16/32 bit? Also @AlanDrake was suggesting to remove 16-bit support altogether.
OTOH, as I mentioned few times before, the 8-bit sprites may still be useful as masks. I even made a related ticket for dynamic sprites (#2027), but wanted to make similar suggestion concerning the sprite import.

**Comment by ivan-mogilko** [comment]
Okay, I found what is wrong, the 16-bit sprites converted to 32-bit game's depth on load at runtime, but they are missing proper alpha channel. I'm working to fix this now.

**Comment by ericoporto** [comment]
> The solution is to either disable new script API (lower it down to v3.6.1), or to update the scripts to work with the real joystick.

I think the solution on ags4 is to update your code to work with the joystick API. In the future, if we are comfortable with the joystick API (once we figure the other things) MAYBE it's possible to have backported joystick API to 3.6.X branch, along with a ported agsjoy version that uses the internal joystick handling behind the scenes as a built-in plugin option - I think this is a lot of work and I would like to simply focus on getting ags4 done.

**Comment by dkrey** [comment]
I already downloaded the Alpha3 with Joystick support  before, so getting rid of agsjoy was planned anyway. No need to take the plugin into account.
Since agsjoy is also very dated, the better solution to my mind is to just updating the code.

**Comment by ericoporto** [comment]
@dkrey the latest merge binaries are here https://cirrus-ci.com/task/5356729207095296 !

**Comment by dkrey** [comment]
Yay, the issue has been fixed. Feedback for the joystick plugin will be given in the PR. Currently I'm still working on getting it to work properly.
