### ISSUE TITLE
Inventory scroll buttons don't work in King's Quest 3 VGA remake

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2121]
**Describe the bug**
The arrow buttons that should allow inventory scrolling don't seem to work. This makes the game harder to play
and possibily unwinnable.

**AGS Version**
3.6.1.6 / 3.6.0.51

**Game**
King's Quest 3 (Infamous Adventures)
https://infamousadventures.itch.io/kings-quest-iii-vga-remake

**To Reproduce**
1. Load save
[agssave.zip](https://github.com/adventuregamestudio/ags/files/12499010/agssave.zip)
2. Use bed to recover all items
3. Open inventory and try scrolling

**Desktop (please complete the following information):**
- Windows 10

**Comment by ivan-mogilko** [comment]
From my preliminary tests, the button click is registered, but it does not have any event handlers (?), so "interface_click" callback is called instead. What happens then is not clear yet.

Also, this problem is easier to test without a save. If you run game with `--test` cmd arg, you may then press Ctrl+S in game which will give you all items (this has been a game cheat in old game templates, which is present in many games of the era).

**Comment by ivan-mogilko** [comment]
The situation is quite strange. Tested this in 3.5.1 (release-3.5.1 branch), and the scroll buttons work, but not reliably: it looks like they act with 1 click delay, where you have to click 2 times on down arrow to make it scroll down, and if you click on up arrow after, it will scroll down again first.

**Comment by ivan-mogilko** [comment]
Pushed a fix: a526a401cbf716ac7c0fc09eed92d24d60b54471

**Comment by tag2015** [comment]
Thanks a lot for the fix and the explanation! Confirmed working
