### ISSUE TITLE
AGS launches other exe file

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2189]
**Describe the bug**
Something weird that came up during version upgrade testing. If I place in the same folder Game.ags, AGS33.exe (which is a 3.3 executable that runs Game.ags) and AGS36.exe (which is a 3.6 executable that runs Game.ags) then opening AGS36.exe will end up loading AGS33.exe and then run the game in 3.3.

**AGS Version**
3.6.0.52

**To Reproduce**
As above

**Expected behavior**
Opening AGS36.exe should run the game in 3.6.

**Desktop (please complete the following information):**
Windows 11

**Additional context**
This is really not urgent or important, but it's weird enough that I thought I should let you know.

**Comment by ivan-mogilko** [comment]
Engine exe itself has no connection to a game, as there's no indication is embedded in it. The game is searched as following:
- attached to exe;
- any compatible file found in the dir, whichever is found first.

**Comment by Crystal-Shard** [comment]
It appears that if it finds data attached to another EXE, it will run that EXE (even if that's an older version of AGS).

**Comment by ivan-mogilko** [comment]
> It appears that if it finds data attached to another EXE, it will run that EXE (even if that's an older version of AGS).

It does not run another exe, it loads up the game data if it's attached to that exe. And yes, it can load game data compiled by older versions of AGS if engine supports it.

**Comment by ivan-mogilko** [comment]
I think that one way to improve this situation is to embed a textual resource into the prepared game.exe, similarly to how editor embeds icon and author's name there. This resource would contain an instruction, and engine would use this instruction when looking for a game file.

The instruction could be a *.ags name, or it could even be a game's GUID, in which case the binding will be more strict.

**Comment by morganwillcock** [comment]
I wonder if making each game's executable be different would make the anti-virus situation worse, and I think it would make it impossible for the executable to ever be centrally code-signed and then distributed with the Editor.

If wanting to launch a specific game using a specific data file, I think the engine behaviour already accommodates this by taking the game data path as an argument. So I would suggest just documenting the search behaviour instead of trying to dynamically modify executables.

**Comment by ivan-mogilko** [comment]
> I wonder if making each game's executable be different would make the anti-virus situation worse, and I think it would make it impossible for the executable to ever be centrally code-signed and then distributed with the Editor.

Please, elaborate on the second? What about the resources that we already embed, such as icon and fileversion, do they also prevent this?

**Comment by ericoporto** [comment]
I don't think we want to **ever** be centrally code signed - the game is the responsibility of the game developer. If one game developer makes a malware with a game or something that lowers the confidence of the exe it should not affect the others (think plugins or some ags vulnerability exploited). Each person should sign their own games if they want it.

**Comment by morganwillcock** [comment]
> Please, elaborate on the second? What about the resources that we already embed, such as icon and fileversion, do they also prevent this?

Essentially I think that the signing is a guarantee that the executable has not been modified since it was signed, so embedding extra data into it or modifying existing data will invalidate the signature. I hadn't considered the icon and the file version, and I'm not saying it should be signed, but it removes the option if it was ever required (an example might be that AGS binaries delivered through the Windows Store may need to be signed if signing ever becomes mandatory, all store applications always run in a sandbox, and may stop working if the binaries are modified).

> This works, but only when user launches by using a link or a script (e.g. batch file on Windows).

> My concern was that it looks strange when the Editor produces a game.exe that goes not guarantee to run the game data it was built for.

I don't think the Editor is creating the problem of mixing files between games, it is someone's choice to do it. For platforms like Steam I would think that the the full command to launch the game could be specified for each version of the game, so the player can have two launch options.

> I don't think we want to ever be centrally code signed - the game is the responsibility of the game developer. If one game developer makes a malware with a game or something that lowers the confidence of the exe it should not affect the others (think plugins or some ags vulnerability exploited). Each person should sign their own games if they want it.

Yes, I agree that it isn't a good idea to run it this way right now (and there is also no-one who will pay for the certificate to centrally sign it), but I think the problem described here (of mixing files between games) is not a strong enough reason to have to implement the dynamic change to the binary and the loading restriction.

As a side note, I've always though it would be a good idea that the game builds are signed with a developer certificate which confirms that all files that are part of the game have not been modified - not to prevent it running, but to indicate the difference between the original game (as released by game author) and unofficial repacks, ports, or translations.

> (In my head the solution would be simply attaching an agslnk that is simply a text file with the filename it should execute and maybe it's guid)

I think anything external would be fine, as that leaves the paths open and would also allow the game developer to fiddle with it. Personally I am more interested in knowing when something was fiddled with, rather than systems which stop the fiddling. Perhaps a game developer would not have the same view, although whether they might have to pay again for re-signing game updates, to load a different file, could be the biggest risk if signing ever becomes mandatory.

**Comment by Crystal-Shard** [comment]
To be clear, I have absolutely no problem with the AGS executable running a different _game_, in the unlikely event that you have two games stored in the same folder.

What this ticket is about, is the AGS executable running a different _executable_ (i.e. opening the 3.6 EXE instead loads the 3.3 EXE and then plays whichever game in AGS 3.3 instead of 3.6). That's not a particularly big deal either but it was weird enough that I felt I should report it.

**Comment by ericoporto** [comment]
I don't think paying per re-signing is a thing? Also certificates aren't valid only for like a year? In any case if there is a file that works as a link that is uniquely named it will work the same regardless it's attached or not.

Anyway, @Crystal-Shard it doesn't run a different exe it finds the attached ags file to that exe and runs that. It has been this way for idnk, ten years or more.

**Comment by morganwillcock** [comment]
> I don't think paying per re-signing is a thing? Also certificates aren't valid only for like a year? In any case if there is a file that works as a link that is uniquely named it will work the same regardless it's attached or not.

I am hypothetically looking into the future as to how it might work (macOS is probably the closest to being there if restricts are tightened further), but previously I think Sony and Microsoft would charge the developer to certify a newer build of a console game before distributing it through their online stores. Although this was described as re-certification, rather than as re-signing, so presumably they were doing some kind of quality control tests on it.

> My general feel is the issue mentioned here is a non-issue and nothing has to be done.

I agree. The search order for the data might be platform specific because of differences in the enumeration order of files, but I think just documenting that is enough.

**Comment by ericoporto** [comment]
For steam I think @morganwillcock solution is good, just add the game path on the launcher command execution.

**Comment by ivan-mogilko** [comment]
Opened a ticket for documenting game data search by engine:
https://github.com/adventuregamestudio/ags-manual/issues/223

I will close this now, as suggested.

**Comment by ivan-mogilko** [comment]
By the way, this problem means that the multi-game collections won't work reliably, unless you either:
- have primary game data attached to exe, or
- have a explicit launch script/executable
