### ISSUE TITLE
(long-term) Winsetup simplification

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2199]
**Describe the problem**
Winsetup contains a few options that
- should be a decision of the game developer or artist, and not the player (because they impact the game's visual style; notably: smooth scaled sprites; render sprites at screen resolution; scaling method); or
- appear to be debugging options that players have no need to use (notably: custom saves path and custom shared data path; I'm not aware of any games outside of AGS that let players decide this); or
- are long obsolete (the one about CRT monitors, and given current memory sizes, the one about maximum sprite cache).

**Suggested change**
Remove all these from winsetup and move them to the General Settings panel in the AGS editor.

Aside from that, the 'fullscreen as borderless window' checkbox disables the 'fullscreen mode' pulldown, leading me to think that 'borderless window' should simply be one of the options in the list of this pulldown.

Finally, the pulldowns 'fullscreen scale' and 'windowed scale' appear to be redundant, in that they offer the same options and it strikes me as highly unlikely that any player will want to set two different options here.

**Comment by ericoporto** [comment]
Lots of mentioned options have been discussed a lot in the past. My recommendation is to simply not ship winsetup if you disagree and ship your own config GUI - it's just really easy to build one.

**Comment by ivan-mogilko** [comment]
This is not an easy issue, it is true that these options were discussed in the past multiple times, some of them were added by users request who would likely oppose their removal, and I believe in the end it's nearly impossible to please everyone at once.

For this reason making your own setup program to run along with AGS could be the best solution. In such case embedded setup application may remain a default or fallback choice. Since certain version (3.5.1 probably) engine can return a number of information about itself and the found game by printing into the stdout (see `--tell` commands in the list of cmdline args). This feature may be used by the external setup application.

I would also strongly recommend posting this on forums, as that will gather feedback from other active game devs and players easier than here (not many of them ever post here, and I do not know if many read this issue tracker at all).

---

Couple of notes regarding the mentioned options:

> should be a decision of the game developer or artist, and not the player (because they impact the game's visual style; notably: smooth scaled sprites; render sprites at screen resolution; scaling method)

"Render sprites at screen resolution" has an option in General Settings which allows to lock it, or leave for player's discretion. Same may be done for other mentioned settings. (Now that I mention this, I noticed that it's located in a wrong category)

> notably: custom saves path and custom shared data path; I'm not aware of any games outside of AGS that let players decide this

These were added by *players request* too. Some people wanted to have saves in the game folder as opposed to the user documents, where AGS stores them by default.

> given current memory sizes, the one about maximum sprite cache.

32-bit engine does not allow to use more than 2 GB on Windows. In addition some systems may simply have small RAM. This option works as a fallback. But also as a way to improve the gameplay speed if game uses alot of high-res animations (then having higher cache may improve performance). This option may probably be deprecated from this dialog only if AGS engine provided more fine tuning for the memory use, both automatic and in script API.

**Comment by Crystal-Shard** [comment]
Fair enough, this needs a forum discussion and not a github ticket. Thanks for the feedback.
