### ISSUE TITLE
Enabling legacy upscale mode (and hires fonts) in MM Deluxe

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2235]
**Describe the bug**
MM Deluxe (version 1.4) uses the old `screenres`parameter to enable the upscaled mode, which also enables hires fonts.
When AGS checks the config file to enable such mode, it also looks for the `defaultres` parameter which is not present (or added by winsetup). In short, the mode is never enabled (unless `defaultres=1` is manually added to the config file).
In addition, saves are not interchangeable. When playing using the game executable, it refuses to load a save created in the other mode. Using the standalone interpreter, it loads but the screen is messed up and unusable.

**AGS Version**
latest 3.6.0 / 3.6.1

**Game**
https://archive.org/details/Maniac_Mansion_Deluxe_14

It's enough to add `kGameResolution_Default` to the condition in `read_legacy_graphics_config`, but I don't know if this is correct or can have other repercussions.

**Comment by ivan-mogilko** [comment]
@tag2015 I apologize for the delay, this issue completely fell of my mind.

Your suggestion seems correct, I added kGameResolution_Default to a condition: c3e2f58dfd8c6b8e42c514afc74c2ec2365e9af4

In regards to non-interchangeable saves, that's a known problem with this resolution switch and never worked (that's why engine refuses to load saves made in different resolution). The reason is that this resolution setting affected the coordinates saved in certain object memory (gui, etc). Some data in the engine was always saved in "native resolution" which means 320x200, and some saved in visual resolution if the upscale mode is used. There's a chance this may be resolved by converting coordinates between resolutions after restoring a save, but this has to be investigated carefully.

---

On a side note, I randomly found another bug playing this game in 3.6.1 interpreter: when you enter a library, in original game it's supposed to be darkened until you turn the lights on. However in the most recent engine it's bright at all times. This is purely a visual effect, and does not affect the game logic.

**Comment by tag2015** [comment]
Hi, no problem, thanks for looking into this! I haven't tested the game extensively but everything seems to work
Feel free to close
