### ISSUE TITLE
GUI labels not saving properly

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2278]
**Describe the bug**
The position and text of several (but not all) GUI labels are not stored properly in a saved game.

**AGS Version**
3.6.0.52

**Game**
Heroine's Quest, download e.g. [here](https://store.steampowered.com/app/283880)

**To Reproduce**
1. Load this saved game, [agssave.013.hqthor.zip](https://github.com/adventuregamestudio/ags/files/13771229/agssave.013.hqthor.zip)
2. Save the game in a new slot.
3. Quit to desktop.
4. Start Heroine's Quest again.
5. Load the saved game made in step 2.
6. Press ESC to show the control panel, note how the top two labels (which should be "Difficulty" and "Speed") are in the wrong position with the wrong text (label 11 and 12 on GUI 10). The other labels on the GUI are fine, though.
7. Load the saved game from step 1.
8. Open the control panel, note how everything is fine.
9. Load the saved game made in step 2 (_after_ having loading the saved game from step 1).
10. Open the control panel, note how everything is fine.

**Desktop (please complete the following information):**
Windows 10 and 11.

**Additional context**
Aside from the control panel, this also affects the custom text GUI (visible when you click the eye icon anywhere, this is label 12 on GUI 11); and the command bar (visible when you move the mouse to the top of the screen and get help text for hovering over the icons; label 14 and 15 on GUI 0). Possibly other GUIs as well.
Note also that this version of the game was released in early October and nobody else has reported this problem, so there appears to be something fairly unusual going on with this particular player.

**Comment by ivan-mogilko** [comment]
This is of course another old save with mismatching gui controls:

> AGS: WARNING: restored save may be incompatible: Mismatching number of GUI Buttons (game: 335, save: 330).
AGS: WARNING: restored save may be incompatible: Mismatching number of GUI Labels (game: 82, save: 78).

The thing is that old save system saved GUIs as a full structure, as if it were saved in game data. This included things that could not theoretically change at runtime: such as references between parent guis and their controls.
But the new save system saves only dynamic data, only something that can change at runtime.

So when you restore old save format, and it has mismatching GUIs, the guis are capable to reorganize themselves based on that save.
But when you restore new save format, that data is lost, and the one from the game itself has to be used.

So when you first load old save, the game in program memory is adjusted, and each next save loads well because its structure corresponds to the old save.
But when you start the game and load newly made save, the guis order becomes mismatched, and controls may even appear on different GUIs.

I do not see how this may be fixed.

**Comment by ivan-mogilko** [comment]
I wonder if this GUI saving the full structure was an intentional feature; whether there was an actual intent to let users add more guis for existing games and keep saves loading. But this was not documented anywhere. I do not know if this behavior was ever mentioned or discussed. Maybe this may be searched on forums. Could be I made a mistake when writing a new save format, and unknowingly dropped a feature? I wish I knew.

**Comment by ivan-mogilko** [comment]
I have got one small idea. I will try it, but if it does not work, then there's likely nothing I can do about this.

**Comment by ivan-mogilko** [comment]
No, that idea did not work.

I had thought that it should be possible to match controls by their **Name**. Unfortunately, the gui control's script name is not a required property in AGS, and there are controls in HQ that are not named, so it's not possible to match everything correctly.

I am more persuaded now that it was a mistake to add this "legacysave_let_gui_diff" option. I'd really rather erase it, because it's not reliable.

**Comment by Crystal-Shard** [comment]
Thanks for your input! To be fair, the legacysave_let_gui_diff works for 99% of users and this is the 1% where it doesn't.
And without requiring any engine changes, if I know what the problem is then I can possibly fix it in scripting.
I don't know what CJ's plans were back then; but I would say that adding a GUI control should not invalidate existing saved games. There has to be some amount of leeway to bugfix a game after release without requiring all players to restart.
________________________________

**Comment by ivan-mogilko** [comment]
> To be fair, the legacysave_let_gui_diff works for 99% of users and this is the 1% where it doesn't.

I now have strong doubts that it does. The result must be the same for everyone who has saves from particular older version of the game, as it depends on data order, and it's always the same for one game version. More likely either they have saves with matching amount of guis, or they did not notice or report problems yet.

When I was adding this option somehow I did not think about an important thing. In AGS game data the gui controls are saved not per GUI parent, but in global arrays, while GUIs have references to those through indexes. I had a wrong thought that the newer controls are in the end of these arrays, but this is not true, they may as well end up in the middle if you add them to already existing GUI.

In other words, when the mismatching save is loaded, the newer controls *might get overwritten* and get lost, while some controls (that are shifted towards the end of array) *are getting duplicated*. I noticed this is what happening while running the engine under debugger.

So this option may only work reliably under one condition: if you add a completely new GUI to the end of GUI list, and put new controls only on them. Which is not your case, it seems.

> but I would say that adding a GUI control should not invalidate existing saved games. There has to be some amount of leeway to bugfix a game after release without requiring all players to restart.

I agree that they should not, but neither version of AGS supported this. Even with older saves, as you can see from the above explanation, this did not work reliably, unless you follow very certain rule of adding new gui.

**Comment by ivan-mogilko** [comment]
I guess one of the simpliest options would be to provide an option that tells not to put certain things into save at all, not get them from save on restore. Like, don't save GUI and View frames, because these may be readjusted in script based on the game state (script variables).

**Comment by ericoporto** [comment]
> I guess one of the simpliest options would be to provide a setting that tells not to put certain things into save at all, not get them from save on restore.

And if the person changed such option in the Editor or at runtime?

**Comment by ivan-mogilko** [comment]
> And if the person changed such option in the Editor or at runtime?

Then the engine will either start or stop writing and reading this data in saves.
If each type of object is stored in its save component with meta info, then it's possible to skip this component safely if told not to read it, or ignore its absence if told to read but it's not present.
