### ISSUE TITLE
Escape of `[` character no longer possible in Label

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2288]
**Describe the bug**
Using `\[` should escape a `[` character when used in a label. Instead, we get a new line. This can be seen directly in the Editor but it will also show as the same when running the game.

**AGS Version**
v3.6.1.16

**To Reproduce**
1. Create a game from a template
2. Either use an existing GUI or create a new GUI and add a Label
3. In the Label, set it's text property to something like `Test \[ a ]`
4. See it will instead show as
```
Test
 a ]
```

**Expected behavior**
It should read as `Test [ a ]` in the label.

**Screenshots**
![image](https://github.com/adventuregamestudio/ags/assets/2244442/de8449d0-a469-499f-bb67-478734dc6637)

**Desktop:**
 - OS: Windows
 - Version: 10

**Additional context**
I noticed this in my Don't Give Up the Cat game, because I use `[ ]` and `[x]` as checkbox in the menu options for selecting either Windowed or Fullscreen.

**Comment by ivan-mogilko** [comment]
The `\\` character is discarded during conversion between managed and native object here:
https://github.com/adventuregamestudio/ags/blob/3d6e90b3dd0c4ed2af7a1094b8eace036721363a/Editor/AGS.Native/agsnative.cpp#L2630
where `ConvertTextProperty` calls `StrUtil::Unescape`. StrUtil::Unescape does not have any knowledge of the `[` hack, and removes any '\' that does not match a escaping sequence, so `\[` becomes '['.

(A call to StrUtil::Unescape is required in order to deal with standard escaping sequences like `\n`).

**Comment by ivan-mogilko** [comment]
This is worse, for the same reason the '[' will not work in translations if using standalone translation compiler, because it also uses same StrUtil::Unescape there.

**Comment by ericoporto** [comment]
Uhm, It looks like before that change the text was passed as is. Was the escaping dealt later by the Engine?

**Comment by ivan-mogilko** [comment]
> Uhm, It looks like before that change the text was passed as is. Was the escaping dealt later by the Engine?

It was not for standard sequences like `\n`. Engine expects the '\n' to be present as a single character in strings already.
The only thing engine deals with is "\[" sequence for wrappable strings.

**Comment by ivan-mogilko** [comment]
I was very curious about how the translations worked within the editor before, since I don't remember that. While in standalone tra compiler we use StrUtil::Unescape, the C# code in the editor uses Regex.Unescape. Its documentation sais that "unrecognized sequences" cause exceptions.

I tested this with the following translation entry:
```
You rub your hands \[up] and down your clothes.
```

The result was:
```
You rub your hands [up] and down your clothes.
```

Which in game is displayed naturally like
> You rub your hands
> up] and down your clothes.

So, there's exactly same problem there with translation, and for much longer.
Here's where it started: 6fd5d0396f6c59d132c3789fd819e8d1c3abc24a
so this problem is in 3.6.0 too.

**Comment by ivan-mogilko** [comment]
Hmm... so this change to unescaping in translations was introduced quite long ago - in AGS 3.5.1.

My memories of this are not clear, but maybe the idea was that from now on the people should be using double-backslash if they want to keep a backslash. And "\\[" sequence is a sort of a special case of double-escaping: you escape `[` with a backslash, but you also have to escape a backslash with the second backslash?

I must now check how the scripts work (and worked before). Because besides everything else, this unescape rule must be consistent in all text sources.

**Comment by ivan-mogilko** [comment]
So, old script compiler has a special treatment for "\\[", where it knows that as a special sequence. I did not check new one in ags4, but that's a separate topic.

This is an unfortunate situation, where escaping is inconsistent:
- Script compiler lets "\\[" through as-is in strings, but also unescapes things like "\\\\", "\\n" and "\\r".
- Since 3.5.1 translation compiler uses standard unescaping, so in order to have "\\[" in game you must escape slash itself as "\\\\[".
- Properties never had unescaping, this is new to them.

I do believe that things must be consistent, but at the same time suppose that some things may be tolerated if changes to them will be too annoying to fix when upgrading a project.

For ags4 I'd insist on having "\\[" *not* treated as a escape sequence, so "\\\\[" required always. But in ags4 we already removed support of "[" as a linebreak character afaik, so that's not a problem anymore.

For 3.6.1, I suppose, it's too late to do any changes for script compiler.
Thus the remaining question is which behavior to keep for properties:
1) Support "\\[" non-standard sequence,
2) Ignore "\\[", and require users to escape a backslash, so write "\\\\[" if they want a "[" as a printable character.

**Comment by ericoporto** [comment]
From what you explained, for me, this should work (in `DataFileWriter.cs`)

```C#
        public static string TextProperty(string text)
        {
            // Escape backslashes before brackets
            string escapedText = text.Replace("\\[", "\\\\[");
            return Regex.Unescape(escapedText);
        }
```

Yet, it doesn't, so there is something I did not understand.

**Comment by ivan-mogilko** [comment]
> From what I understood, this should work (in `DataFileWriter.cs`)
> 
> ```cs
>         public static string TextProperty(string text)
>         {
>             // Escape backslashes before brackets
>             string escapedText = text.Replace("\\[", "\\\\[");
>             return Regex.Unescape(escapedText);
>         }
> ```
> 

This actually worked for me, at runtime.

Although I am not sure if this is a fully correct fix, because there may already be double backslash, so inserting another one may create a triple.

**Comment by ericoporto** [comment]
> This actually worked for me, at runtime

Wait, really? Like, it didn't in the GUI work in the GUI Editor but it did in the built game? This is weird.

**Comment by ivan-mogilko** [comment]
> Like, it didn't in the GUI work in the GUI Editor but it did in the built game? This is weird.

The function you were changing is not used for GUI preview in the Editor.
This function is used instead:
https://github.com/adventuregamestudio/ags/blob/3d6e90b3dd0c4ed2af7a1094b8eace036721363a/Editor/AGS.Native/agsnative.cpp#L2630
