### ISSUE TITLE
Backwards Compatibility: comparison between Character pointer and `character` array can "incorrectly" fail

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2296]
**Describe the bug**
A comparison like `character[0] == cEgo` will always work, but any succeeding character will fail, like `character[1] == cOne`

**AGS Version**
This started to happen in 3.6.1.14, and it did not happened in 3.6.1.13. The issue appears to be this commit https://github.com/adventuregamestudio/ags/commit/4be15565755bc54f5d8f48be0e6aebc6eee117c1

**Game**
[TestCharacterArray.zip](https://github.com/adventuregamestudio/ags/files/13928630/TestCharacterArray.zip)

**To Reproduce**
You can run the test game with 3.6.1.13 and see no error with
```
./acwin_3.6.1.13  --no-message-box --console-attach --log-stdout=all:all
```
```
Script : C: cEgo C*: cEgo Equal: 1 - 1
Script : C: cCharOne C*: cCharOne Equal: 1 - 1
Script : C: cTwo C*: cTwo Equal: 1 - 1
Script : C: cThree C*: cThree Equal: 1 - 1
Script : C: cFour C*: cFour Equal: 1 - 1
Script : C: cFive C*: cFive Equal: 1 - 1
```

And then run in 3.6.1.14 and see the error in the logs
```
./acwin_3.6.1.14  --no-message-box --console-attach --log-stdout=all:all
```
```
Script : C: cEgo C*: cEgo Equal: 1 - 1
Script : C: cCharOne C*: cCharOne Equal: 0 - 0
Script : C: cTwo C*: cTwo Equal: 0 - 0
Script : C: cThree C*: cThree Equal: 0 - 0
Script : C: cFour C*: cFour Equal: 0 - 0
Script : C: cFive C*: cFive Equal: 0 - 0
```
Note the equals should all be true (1), but are false (0).

**Note:** this only errors for characters other than the 0 index.

1. Create a new game from Sierra template and add a new character `cOne`.
2. Go to the room and create a new function in After Fade-in
3. Write it as 
```
function room_AfterFadeIn()
{
  Display("equality: %d \n\n 1 is error,\n 0 is not.",  cOne != character[1]);
}
```
5. Build and run and see the error 

**Expected behavior**
Equality should work (look into additional context below!!!)

**Desktop:**
 - OS: Windows
 - Version: 10

**Additional context**
Note that this code should probably give an error when compiling, because we are freely comparing or casting as pointer a struct that isn't a pointer (the element from character, as that array is an array of characters and not readonly pointers of characters), something like: `Character * cWhatever; import character[]; cWhatever == character[1]`.

A good fix for this is probably https://github.com/adventuregamestudio/ags/issues/2273 , but we can't do that in a backwards compatibility manner (in ags3)

**Comment by ivan-mogilko** [comment]
So, to clarify, this is happening because compiler precalculates the address of a element's pointer taken as `character[n]`, using assumptions from the script struct `Character`. If engine returns a different address for any reason, then it won't match assumptions and any direct address comparisons will fail.

This is something I did not realize, and this also means that the StaticObjectArray logic is wrong and could never work:
https://github.com/adventuregamestudio/ags/blob/d07367d2c8ad704c97c5638f0784d0a05f2314bf/Engine/ac/dynobj/cc_staticarray.h#L15-L19
(well, it was never really used until now)
It won't work in ags4 either, the only way to get rid of this problem in ags4 is #2273 (although that will break backwards compatibility completely).

**Comment by ivan-mogilko** [comment]
This may be fixed relatively simply, by moving two new "unrestricted names" fields out of CharacterInfo struct. The question is only where, and how to adjust data reading code. This may be either CharacterExtras, which stores runtime fields, or GameSetpStruct, which already stores scriptnames for some objects (like dialogs, views and inventory items), and is located in Common lib, closer to the CharacterInfo.

**Comment by ivan-mogilko** [comment]
I might have an idea of a different way to make this work. But I won't try this right now, maybe in some future update past 3.6.1, because I do not want to risk making more silly mistakes at this moment.

The engine could expose a dummy struct with only an ID for characters, similar to how most of the other objects are exported.
Except, in order to keep the relative address correct, this dummy struct must be filled with "padding" to match the size of CharacterInfo.
