### ISSUE TITLE
Script compiler: register static function imports as "name^argnum" symbol

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2300]
Script compiler registers imported struct member functions using a "name^argnum" notation. This helps engine to link different versions of API function with extended argument list.

But for some reason same is not done for static functions, which do not belong to a struct. Although it is a common idea that we should move towards having all functions belonging to some type, like under a namespace, there are still a lot of those which are not, and sometimes there's a need to extend their arg list.

Need to investigate if there's any technical reason not to use same registration method for static functions, and if not then register them as "name^argnum".

This problem refers to both new and old compiler, new one is a priority but old should be adjusted to if possible.

**Comment by fernewelten** [comment]
Could you please check this again?

Because as far as I can see, both the compilers do export all functions, static and otherwise, with the expected number of parameters appended (after a `$`, not a `^`).
- For the new compiler, cf. function `AddExport()` in file `Compiler\script2\cc_compiledscript.cpp`.
- For the old compiler, cf. function `add_new_export()` in file  `Compiler\script\cc_compiledscript.cpp`.

It seems that this might be a purely Engine matter, pertaining to how predefined (`C++`) functions are linked. The compilers seem to be out of it.

It might even be that at the time that the `function$parametercount` convention was introduced, nobody felt like touching the signatures of the functions that already existed at that time, and so it's simply the ‘old’ functions that don't have the parameter count, not the ‘static’ functions.

**Comment by ericoporto** [comment]
Looks like this is only used here

https://github.com/adventuregamestudio/ags/blob/6baad09f555d9dd98ea26c48cc02b54f7515f4e9/Engine/script/systemimports.cpp#L83

**Comment by ivan-mogilko** [comment]
@fernewelten these are not *exports*, these are *imports*, compilers treat these separately. They append ^N during some kind of a post-step, after all imported functions have been gathered.

Here's what the old compiler is doing:
https://github.com/adventuregamestudio/ags/blob/282cf917e151450dc271c6a26a7e38ba1c957fad/Compiler/script/cs_parser.cpp#L1095-L1101

Here's what the new compiler is doing:
https://github.com/adventuregamestudio/ags/blob/282cf917e151450dc271c6a26a7e38ba1c957fad/Compiler/script2/cs_parser.cpp#L1401-L1407

As you may see, for some reason (which I cannot tell) both only add "^N" part if this function is a member of a struct.

**Comment by ivan-mogilko** [comment]
Okay, I just fixed it,
commits in ags4 branch: fb327d1135532152e433fff082132e59668ddce9, 5f471456ba31d0cef2b53bf17abecd410dc2f11c
in master branch: 12ce08a0d61540810b677f26241c3de0f68539d9, 1d6ec8a227e2bddc568c45e4d37895af9ae01516

Static functions now may have variants with different number of args.
Although, we must keep old variants registered *without args* for backwards compatibility.

**Comment by ivan-mogilko** [comment]
Ah, there are some mistakes in tests, I will have to handle that.

**Comment by fernewelten** [comment]
> Ah, there are some mistakes in tests, I will have to handle that.

Probably no biggie: There are bound to be some tests in the suite that check what the compiler should return as exports or imports. When that changes then the tests will fail, of course, but that's kind of the point of the tests.

**Comment by ivan-mogilko** [comment]
So, besides obvious need to fix tests, I did not realize that there may be multiple import declaration of the same function. The existing compiler code does not reset import's name in such case, so after my changes it was appending ^N twice (or more) to the same string.

Not sure what would be the optimal solution here, but I fixed this by checking whether ^ symbol is present in the import's name already:
d2f010184deaad7570035f056d02d15845023d78
