### ISSUE TITLE
Script editor collapsable block matching problems lead to the blocks collapsing incorrectly or not at all.

### ISSUE THREAD

**Issue by edmundito** [adventuregamestudio/ags#2323]
**Describe the bug**

There are a couple of areas in the script editor that don't collapse correctly. Described below.

**AGS Version**
Editor 3.6.0.56

**To Reproduce**
1. Open a script editor
2. Paste the code below

```agsscript
void bug(int value) {
  if (value == 0) {
  } else { // Not collapsable
    Display("Not zero");
  }

  if (value < 0) {
  }
  else {
    // if (value > 10) {
    //  Display("Greater than 10");
    //  return;
    //} // Collapses here. Notice that // } is fine, but when without space //} it breaks
    Display("Greater than 0");
  }
}
```

3. Try collapsing the statements.

**Expected behavior**
* `} else {` should be collapsable
* Should ignore commented out code

**Screenshots**
![image](https://github.com/adventuregamestudio/ags/assets/168664/19e858a8-24fd-40a0-b4ca-942cbcc52179)6f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
Folding is something that Scintilla control does. So either there's something missing in our Scintilla setup, or a bug in Scintilla itself.

In 3.6.0 we upgraded to the newer version of Scintilla .NET (primarily for the better unicode support). It might be there's an update available, but not certain, because iirc this was not the latest version (the latest version had incompatible API). OTOH the Scintilla has 2 parts - C# and C++, and C++ part may be patched separately.

**Comment by ericoporto** [comment]
Need to check this in the lexer

https://github.com/adventuregamestudio/ags/blob/0f8ef52a60b54fc8db0ea89cf15569ba8b876611/Editor/scintilla/lexers/LexCPP.cxx#L1434

It looks like there's some option to ignore folding in comments.

**Comment by ericoporto** [comment]
Hey, what's the feeling on this one, should we switch the behavior and be done or do we need some option in preferences for this? (and perhaps default to the other)

Afaict it's just turning `foldCommentExplicit` to `false`.

https://github.com/adventuregamestudio/ags/blob/bfc99b00879abefd426880dcfa1def0ad96c964b/Editor/scintilla/lexers/LexCPP.cxx#L434-L435

There are a series of scintilla cop lexer options there too btw.
