### ISSUE TITLE
Logging system is not thread-safe

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2339]
Somehow I missed this, but we don't have much logging done on separate threads yet, and audio polling coincidentally is performed not at all times, but is triggered by certain "sync" actions on main thread, and then halts again; so likely this was not causing trouble in practice.

Existing logging is not designed with thread-safety in mind. Initialization is done before more threads are created, yet there's no reason to not make it safe as well. But besides that the two general concerns are:
1. Output implementations; if these use any non-local data.
2. "Supress" mechanism, see this: 
https://github.com/adventuregamestudio/ags/blob/84ab2b592f5611b22380ed52a3b42080c9c68487/Common/debug/debugmanager.cpp#L218-L220
I suspect that the code in p2 may be reviewed, and possibly a rule enforced that a output implementation must not print to log itself.

A solution is likely to introduce a mutex in the DebugManager class, and guard either PrintMessage call or external call that iterates all outputs. As well as any modification to the output list and settings.

**Comment by ericoporto** [comment]
> I suspect that the code in p2 may be reviewed, and possibly a rule enforced that a output implementation must not print to log itself.

It appears it's like this for a long time (https://github.com/adventuregamestudio/ags/commit/75727c54be527316cb745e6d9a56ea6a7436af3b). There was a different, but similar suppression mechanism that was done in https://github.com/adventuregamestudio/ags/pull/2303.

Trying to understand the problem here, is one would add a [`std::lock_guard<std::mutex> lock(debugOutMutex);`](https://en.cppreference.com/w/cpp/thread/lock_guard) there for thread safety but this would lock the program since it calls itself? The mutex would be necessary then because the log output is a shared resource among all the threads that only one should write to (otherwise you would get a confusing output).
