### ISSUE TITLE
Running games fullscreen on Raspbian (Debian + Raspberry Pi) is very slow

### ISSUE THREAD

**Issue by jagiella** [adventuregamestudio/ags#235]
Running the game on its native 320x240 resolution works quiet fast, but already scaling it just to double image size results in a tremendous slowdown. Furthermore, all kind of image fadings (in or out) are extremly slow...even on the lowest resolution.

So making OpenGL support run on Debian/Raspbian to benefit from hardware acceleration would be a great improvement.

**Comment by morganwillcock** [comment]
I've tested this on what is the current version of Raspbian with the OpenGL driver enabled, since AGS 3.5 on Linux will now use OpenGL for rendering by default. Scaling no longer increases the CPU load and I could run a game in fullscreen mode with x5 scaling with no slowdown.

@jagiella do you want to give it a try?
