### ISSUE TITLE
Earl Mansin error on game start

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2365]
**Describe the bug**
Earl Mansin - The Breakout crashes when starting a new game with:
NewRoom: Cannot run this command, since there was a RestartGame command already queued to run in "Room script", line 31!

Seems like a bug in the old interpreter queue logic?

**AGS Version**
Latest 3.6.0 / 3.6.1

**Game**
https://archive.org/details/Earl_Mansin

**To Reproduce**
Start new game

**Desktop**
Win10

**Comment by ivan-mogilko** [comment]
This problem reproduces since 3.3.0 (the first open source version released)...

**Comment by ivan-mogilko** [comment]
Sorry for delay, I was distracted by the recent 3.6.1 release and other things...

Since this is an old game, and happen to contain room script texts inside the room file, I managed to extract room scripts using our [crmpak tool](https://github.com/adventuregamestudio/ags/tree/master/Tools/crmpak).

The room10's script has this:
```
function hotspot1_a() {
  // script for hotspot1: Any click on hotspot
RestartGame();
PlayVideo("data/r00m0.cfg", 1, 1);
NewRoomEx(1, 180, 160); 
EnableCursorMode(0);
EnableCursorMode(1);
EnableCursorMode(2);
EnableCursorMode(3);
EnableCursorMode(4);
EnableCursorMode(5);
EnableCursorMode(7);
EnableCursorMode(8);
EnableCursorMode(9);
EnableCursorMode(10);
}
```

So, there's completely unnecessary RestartGame() call, which is supposed to reload a previously made restart point, followed by playing a intro video, and then a NewRoom call, changing to room 1.

I suppose the old interpreter could either schedule and execute both RestartGame and NewRoom in the same order, or overwrite previously scheduled action if a new one is logically overriding.

**Comment by ivan-mogilko** [comment]
I did an experiment, started a game in a very old AGS editor:
1. Room 1 had an initially disabled object.
2. In Room 1 add an exit, which calls following script upon walking on it:
```
ObjectOn(1);
RestartGame();
NewRoom(2);
```
3. In Room 2 add an exit which leads back to room 1.

After starting the game, going to room 2 and then back to room 1, one can see that the object is now visible. This means that RestartGame() was not called, because that would reset object's state to initial (disabled).

Here I am making an assumption that the RestartGame is skipped in this case.

Curiously, two NewRoom commands cause an error.

**Comment by ivan-mogilko** [comment]
@tag2015 I tried to emulate the pre-2.70 behavior by removing all scheduled RestartGame calls in case there's a NewRoom call:
0711b6fdc0f1c71c341716a20de0d90a75f1ec92

**Comment by tag2015** [comment]
Thanks for looking into this! I'll try your fix

**Comment by tag2015** [comment]
Confirmed working, thanks!
