### ISSUE TITLE
Support triggering AnyClick when Mouse.Mode is Walk

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2372]
**Describe the problem**
When you set an AnyClick event, by the NAME one kinda expects it to trigger with any click... But it can only be triggered if the mouse mode is not walk. So if you want the character to walk but you want that a click on something to that supports AnyClick to override the walk, you need to script your way out of it.

This is noticeable if you are trying to quickly write a Single-Click interface for an AGS game. I had to do the following workaround:

```AGS Script
function on_mouse_click(MouseButton button)
{
  // ...
  if (button == eMouseLeft)
  {
    CursorMode mode = eModeWalkto;
    if(Character.GetAtScreenXY(mouse.x, mouse.y) != null || Object.GetAtScreenXY(mouse.x, mouse.y) != null || Hotspot.GetAtScreenXY(mouse.x, mouse.y) != hotspot[0]) 
    {
      mode = eModeInteract;
    }    
    Room.ProcessClick(mouse.x, mouse.y, mode);
  }
}
```

**Suggested change**
Just let AnyClick trigger ignoring the CursorMode and let the developer handle the mode that is passed. Will probably require an option somewhere to switch the behavior.

**Comment by ivan-mogilko** [comment]
My first reaction is against this, because walk implies walking somewhere, not interacting with something.

What exactly is the problem here, is it that name is misleading, or that there's a use case for object to react on "walking" onto it?

**Comment by ivan-mogilko** [comment]
My first reaction was against this, because "Any Click" event is meant for handling "any interaction", not walking on. Then, I understand there may be a need for a general "object was clicked on" event, as game engines normally have that. But I feel like if done, then someone will want to have another event, which is "any click except walk", as many scripts and templates depend on that.

From the engine's design perspective, in AGS there is a mix of *general* game engine and *specialized* engine, where verbs are a part of specialized subsystem (so to speak). Therefore it may be wanted to have events for general use and specialized use. For example, "OnClick" event for general case, for handling virtually any clicks on objects, like any clicks on a gui are handled, and then "OnAnyInteraction" event for handling any "interaction verb" (except walk).

Then, following may be not exactly related to the proposal, but I might mention questions about use case, because I found explanation unclear.
Why do you need this in Single-Click interface, where you may simply lock mouse mode to e.g. Pointer or Interact mode, and do a simple script like:
```
if (GetLocationType(mouse.x, mouse.y) == eLocationNothing)
    Room.ProcessClick(mouse.x, mouse.y, eWalkTo);
else
    Room.ProcessClick(mouse.x, mouse.y, eInteract);
```
This is trivial to do, and does not look like a "forced" workaround.

Another thing that comes to a mind, suppose you enabled "any click" working in Walk mode, then how do you differentiate between an object that handles walk in "Any Click" and an object that does not, in script? What if some object does not need it, how do you detect that ProcessClick did not handle it, and handle Walk afterwards?
This likely will have to be done by checking custom properties, or some other way, so also complicating the code.

**Comment by ericoporto** [comment]
Alternatively, could things have a WalkTo interaction?

**Comment by ivan-mogilko** [comment]
To be honest, I'm still confused about what the actual issue is here. Is it that the "AnyClick" event not clearly documented and misleading, or is it that there's a use case for having WalkTo interaction on objects?
It's true that right now you have to script that yourself if you like objects to react on "Walk" verb, but I suppose that's a problem in case you have verb selections in your game. In case of single-click or two-click interfaces usually you just select mode depending on what the cursor is above (this may refer to both cursor image and action).

**Comment by ericoporto** [comment]
> Is it that the "AnyClick" event not clearly documented and misleading

Yes, it's more that. It took me way to long to remember that it didn't handle Walk and I don't even remember how I learned it originally, I think trial and error messing with the engine.

There's a text that appears in the property grid when an entry there is selected, it would be nice if it simply mentioned that it doesn't trigger on WalkTo interaction.

**Comment by ericoporto** [comment]
Closing as not planned but will try to come up with some text on the AnyClick description.

**Comment by ivan-mogilko** [comment]
I suppose that AnyClick's displayed name may be changed in the Editor too.
