### ISSUE TITLE
Doesn't find agsgame.dat by default when starting a game

### ISSUE THREAD

**Issue by eriktorbjorn** [adventuregamestudio/ags#239]
Lately there have been Linux versions released of some AGS games. In the ones I've seen, the main data file has been called agsgame.dat so it would be nice if it looked for that file name by default, even though there are other ways of telling it to use that file.

From what I can see, all that's needed is two slight changes to find_game_data_in_directory(), where it's already looking for ac2game.dat.

**Comment by ivan-mogilko** [comment]
I am not sure I understand the situation; could you give a link to such game?

**Comment by eriktorbjorn** [comment]
There weren't as many as I first thought when I wrote the bug report, but the ones I've come across so far are Gemini Rue and Quest For Infamy, sold at Good Old Games. I have Linux versions of some other commercial AGS games that were included in Humble Indie Bundles, and I assumed they would be the same, but other than the aforementioned Gemini Rue they all use ac2game.dat instead.

**Comment by ivan-mogilko** [comment]
I apologize for delayed answer.

There is a slight difference between Linux and Windows search rules in the engine, which should be removed; but "agsgame.dat" was never searched for on any platform. That is a custom name, invented by someone.

"ac2game.dat" is a very old name for game package from some ancient versions of AGS. I suppose original Linux port maintainer used it by misunderstanding, and this caused few other people using it as well.

The name format we currently suggest to use is *"*.ags"* (e.g. 'GeminiRue.ags'). The new version of Editor in development (see 'develop-3.4.0' branch) now has an option to produce a game package for Linux, and this is the name format it uses.

I would not like to add new "standard" names into code (let aside making it default), because this would be redundant in the presence of the standard name format we already have; and I would not like to support game publishers randomly renaming game files.

What I can propose is to make engine search for *any* file that contains game format signatures, *if* standard file names were not found. This would cover those occasional situations when the game file was renamed to something else.

**Comment by ivan-mogilko** [comment]
Branch release-3.3.4 now has the game file search that works similarily on Linux and Windows, and it searches through all files in the directory when the game file is not explicitly defined (from command line or in acsetup.cfg). The files with standart names are given higher priority though.
