### ISSUE TITLE
Compile error when using static variables/methods inside non-static expressions

### ISSUE THREAD

**Issue by cellproductions** [adventuregamestudio/ags#242]
Static variables/methods being used/called in non-static expressions causes compile errors.

e.g.
`int date = DateTime.Now.Hour; // must have an instance of the struct to access a non-static member`
`int i = array[Game.GetColorFromRGB(0, 0, 0)]; // parse error after '['`

**Comment by gurok** [comment]
The second one can be fixed pretty easily. It's just overly strict validation:

https://github.com/gurok/ags/commit/af77529c47e93fa3e1a5cc7f00b2ddaa97a0087e

**Comment by ivan-mogilko** [comment]
@gurok make a pull request when you are ready with this fix.

**Comment by ivan-mogilko** [comment]
Second case is fixed with ba08a32

**Comment by ivan-mogilko** [comment]
I added this for 3.5.0 milestone because this bug makes it inconvenient to address newly added camera API, e.g. you cannot write `Room.Camera.X = 100;`, you have to do store Camera pointer in a variable first.
Not critical, since for a workaround you can write a helper function, but if someone has spare time it will be very good to have this fixed.

**Comment by sonneveld** [comment]
This is definitely on my list.

**Comment by ivan-mogilko** [comment]
@sonneveld , please set yourself as "assignee" in the issues you are working on, don't want someone to occasionally do duplicate work.

**Comment by ivan-mogilko** [comment]
Should be fixed by #768.
