### ISSUE TITLE
Automatically lose inventory in old AGS games

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#246]
There appears to be a default option which makes character to automatically loose inventory items after use in old versions of AGS (found in 2.5). According to editor messages during older game import, this feature was considered dangerous and removed in later versions (2.72 does not have it).

I could not yet find out which actions precisely cause automatic loss of an item in 2.5 games. This should be investigated more.

**Comment by ivan-mogilko** [comment]
This is silly, but I randomly found it in the engine code:
https://github.com/adventuregamestudio/ags/blob/99eb74a9da01231058946c3daa636f57bd5a030f/Engine/script/script.cpp#L865-L868

Apparently this option was only ever used when running "interaction scripts", not regular scripts.

For the reference, here it is in the AGS 2.55 editor:
![ags-255-useinventory](https://github.com/adventuregamestudio/ags/assets/1833754/52654c74-ac09-4868-8277-ae0ebee09f5f)

Since it is present in the code, then likely it's working; at least no related problem was reported in all the years.
