### ISSUE TITLE
Preprocessor gets infinite loop meeting a non-latin unicode char in script

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2480]
**Problem**
If the game project is configured into Unicode mode, and there's a non-latin character met in plain script (except comments or character string literals in single or double quotes respectively), then the script preprocessor would stuck in an infinite loop while trying to process the scripts.

**Steps to reproduce**
1. Create a project in Unicode mode.
2. Open a script and place a random non-latin char on a new line.
3. Run game build.
4. Observe that the process is stuck at the script compilation forever.

**Expected behavior**
I suppose it's expected that preprocessor should produce a warning or error about invalid character found in script.

**Additional**
That would be a good idea to also test compilers with the same case, as both old and new one were written back when scripts were strictly ASCII.

On a side note, we might plan adding a "Abort/Cancel" button to a BusyDialog that runs a working process. It's weird how this was not featured from the start.

**Comment by ericoporto** [comment]
I think the place to put the check that would give the error message would be here:

https://github.com/adventuregamestudio/ags/blob/d790aeabd193168f2ee9cfad576b82459978ed5f/Editor/AGS.CScript.Compiler/Preprocessor.cs#L390

Not sure how it would break from here. Does any character puts it in infinite loop or is there one specific that you verified?

**Comment by ivan-mogilko** [comment]
> Does any character puts it in infinite loop or is there one specific that you verified?

Multiple characters were reported by different users, and i tried with a random one, so I assume that any character which unicode index exceeds either 127, or 255 (to make it safe).

**Comment by ericoporto** [comment]
OK, I understand why the infinite loop, it happens because of [`GetNextWord`](https://github.com/adventuregamestudio/ags/blob/d790aeabd193168f2ee9cfad576b82459978ed5f/Editor/AGS.CScript.Compiler/Preprocessor.cs#L158-L175), instead of it going until the next break or dot, to retrieve the word, it uses the valid ascii characters as check and breaks on everything else.

I think it's best that GetNextWord just use breaks and then we can have an additional function that does the required validation.
