### ISSUE TITLE
Script API: add "startIndex" parameter to String.IndexOf

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2487]
Reasoning: String.IndexOf will only find the first instance of a "needle". If you like to keep finding further instances, you must create substrings of original string, which slows things down.

Proposal therefore is to add a "startIndex" to IndexOf, which lets to keep searching for the "needle" after the first instance.

EDIT: amended with "endIndex" and "caseSensitive" from proposals below.

```
int String.IndexOf(const string needle, bool caseSensitive = true, int startIndex = 0, int endIndex = -1);
```

Example of a use case:
```
int found_at = -1;
int found_count;
do
{
    found_at = input_str.IndexOf(find_what, true, found_at + 1);
    if (found_at >= 0)
        found_count++;
}
while (found_at >= 0);
```

**Comment by messengerbag** [comment]
In that case I would also throw in an optional endIndex or length parameter, so that the search can be run on any defined substring of the string.

**Comment by ivan-mogilko** [comment]
I suppose then "caseSensitive" may be an addition too.

**Comment by ericoporto** [comment]
Since we are talking about other things in string split, I am thinking... Is there a case where a string is split in character that is escaped? I think not because the escaping happens at compile time. Don't know if there is any "escape" that makes sense to be written to a text file (?) that would be messed at read. Anyway, probably this is not an issue just wanted to check.

**Comment by ericoporto** [comment]
So this function has a global equivalent called [`StrContains`](https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/global_api.cpp#L2664) that is actually using the same exact function. My suggestion would be to write StrContains in the global API and focusing on writing a proper String_IndexOf in `string.cpp` and then just have StrContains call it with whatever are the correct parameters for the legacy behavior.

**Comment by ivan-mogilko** [comment]
Oh, right, this fell out of my head, there's already `enum StringCompareStyle`:

https://github.com/adventuregamestudio/ags/blob/e5ee226f58d4f4b77ac361cf0a68ef71ac461368/Editor/AGS.Editor/Resources/agsdefns.sh#L470-L474

And in fact it's already used in String starting with v3.5.0:

https://github.com/adventuregamestudio/ags/blob/e5ee226f58d4f4b77ac361cf0a68ef71ac461368/Editor/AGS.Editor/Resources/agsdefns.sh#L531-L538

**Comment by ericoporto** [comment]
I think that the default being case sensitive is best too, but the old function was always case insensitive.

**Comment by ericoporto** [comment]
What is better? endIndex or length ? I went with endIndex in the PR but I honestly couldn't tell which would be more convenient.

Btw, about the example code for Counting occurrences, do anyone want a count for it? I have my own version I use for myself in script but I wonder if others find it useful too.

**Comment by morganwillcock** [comment]
Specifying a start index and an end index coud potentially support negative values for positions relative to the end of the string being searched.  A negative length (or negative count) doesn't really make sense.  If you think that string operations could eventually end up supporting negative indices I would suggest using `endIndex`.

(But I am also wondering exactly what the use case is for these new parameters.  I can find [one language](https://www.php.net/manual/en/function.strpos.php) which supports a single offset for the start position but not one that also supports a search limit.  Is there some common problem where substrings need to be counted and creating additional strings is so slow that there is a performance problem in a game?)

**Comment by ericoporto** [comment]
It's the same of the rest of the String API, directly from C#: https://learn.microsoft.com/en-us/dotnet/api/system.string.indexof?view=net-8.0#system-string-indexof(system-string-system-int32-system-int32-system-stringcomparison)

**Comment by ivan-mogilko** [comment]
> Specifying a start index and an end index coud potentially support negative values for positions relative to the end of the string being searched.

This may be done by specifying startIndex as (string.Length - N).

**Comment by morganwillcock** [comment]
For the C# version the count parameter is effectively optional because you can just call the version which doesn't take that parameter.  Having to always specify the count to set the case-sensitivity seems pretty awkward, especially because the most common usage will be to search to the end of the string and 0 (or -1, or however you request no stop position) doesn't make sense as a count.

I can see that specifying the intial offset will be a lot a lot more efficient when compared to generating a new string per search, but wouldn't it be feasible to just create one new string intially which removes the trailing part that you aren't interested in, and then search that new string, instead of specifying a count?

> Parsing a very long string and searching for repeated sequences is a case which made me suggest this.

I saw your initial example, but this is what you were doing and I was more interested in why you were doing it.  Was data encoded as a string?

**Comment by messengerbag** [comment]
> But I am also wondering exactly what the use case is for these new parameters.

It came up on the Discord, where it was about finding multiple instances of some substring. Currently you would have to Substring the search string to skip past each subsequent hit (or, as @ivan-mogilko recommended, instead loop through the .Chars[] array).

For the endIndex/count parameter, one use case where this would be relevant is for line wrapping. (For example the module I wrote a while back that does pseudo-RTL linewrapping.)

Being able to specify both end-points lets you do things like binary search without creating copies of parts of the string, and in general to operate on a section of the string in isolation.

Or let's say you've loaded a very long string from a text file, which holds some kind of coded map data. You can then limit the search to the part of the string that represents a particular chunk of the map.

**Comment by ivan-mogilko** [comment]
> For the C# version the count parameter is effectively optional because you can just call the version which doesn't take that parameter. Having to always specify the count to set the case-sensitivity seems pretty awkward, especially because the most common usage will be to search to the end of the string

For that reason my initial suggestion was to have "caseSensitivity" as a second parameter.
This version was not released yet, so it's still possible to swap it to the second place again.

Of course, ideally, AGS script should support function overloading, that would solve a lot of trouble inventing good parameter order and good default values.

**Comment by ivan-mogilko** [comment]
@ericoporto @morganwillcock , I moved "caseSensitive" parameter to second place again, following morganwillcock argument about "count" parameter being less important (it has less use cases).

@ericoporto if you have already made tests for IndexOf, then these will have to be adjusted; sorry for this trouble.

In addition I added extra optimization to searching starting offset, using secret internal counter in string header, same as was used for Chars[] iteration: 61c2a69889deb689a87609fbbecb3414417df1cd

**Comment by ericoporto** [comment]
That's alright, I am still working on the tests. I guess this can be closed now?

**Comment by ericoporto** [comment]
Actually you made the move of parameters wrong, you need to adjust the script api header too.

**Comment by morganwillcock** [comment]
(Note: I wrote this before the above changes. Maybe reordering the parameters fixes in the short term, but people tend to start using builds as soon as they appear, and adding function overloading is probably not being worked on.)

> For the endIndex/count parameter, one use case where this would be relevant is for line wrapping.

I guess the use case here is operating on words and so you would only need the start offset?

> Or let's say you've loaded a very long string from a text file, which holds some kind of coded map data

I think this is part of the problem because when treating strings as data it doesn't neccesairly make sense for do anything regarding case sensitivity, but the functions being used are trying to accomodate all possible usages.

Personally, I don't think it is positive step for majority of people using the scripting language to be forced to call a function with parameters which logically do not make sense.

i.e. In the C# version this doesn't make sense:
```c#
 "HELLO".IndexOf("el", 0, 0, StringComparison.OrdinalIgnoreCase)
```

...doing this in AGS makes it more confusing and inconvenient for people using strings as text in their game to accomodate the people treating strings as data. Is it not feasible to just store/read the data in chunks?

> Of course, ideally, AGS script should support function overloading

I don't know your exact plans for when the version which contains the changes would be in general use, but without the overloading ability I think it would be a step backwards for the majority of people who just want to find a substring.

**Comment by ericoporto** [comment]
@ivan-mogilko another error is the StrContains call was not changed too.

**Comment by messengerbag** [comment]
> > For the endIndex/count parameter, one use case where this would be relevant is for line wrapping.
> I guess the use case here is operating on words and so you would only need the start offset?

It might be something like "find the first space, if any, between index a and index b" (where a and b define the start and end of a certain line in the string). (Conveniently, with pseudo-RTL, where the string is "reversed," the first space in that chunk actually represents the _last_ space before the EOL, so will be the breakpoint if the line doesn't fit.)

If the string is _not_ reversed, it demonstrates that it can be useful to search backwards as well as forwards. If that isn't available in the API, you can also use a range to do a more efficient search for the last instance of a substring before index i (rather than just doing a forward search from 0).

> I think this is part of the problem because when treating strings as data it doesn't neccesairly make sense for do anything regarding case sensitivity, but the functions being used are trying to accomodate all possible usages.

I'll note that I didn't request case sensitivity. I can see the use case for it, but personally I haven't really encountered them, while I _have_ encountered cases where I've wanted to be able to search within a string range. And not just with String-encoded data.

Another use case is for parsing. For example, you've located a start and end-delimiter in the string, and now you're trying to decode the bit in between, searching for matches to a particular pattern.

**Comment by ericoporto** [comment]
@messengerbag about delimiters for parsing I found this at some point: https://github.com/JujuAdams/string_split_moreso?tab=readme-ov-file#string_split_open_close

**Comment by ivan-mogilko** [comment]
@morganwillcock so what do you suggest, to remove the new parameters?
Another option is to make a new function with different name, at least until overloading is not supported.

**Comment by morganwillcock** [comment]
> so what do you suggest, to remove the new parameters?

I guess it depends which branch these changes end up in and why they are added. If you just want to keep the existing behaviour then using the function with the previous defaults seems fine in the short term, but I would consider using the new case-sensitivity parameter to be awkward, and (for me) specifying an end position for the match crosses the point where the usage is no longer intuitive.

If you can dispatch to alternative functions with parameter overloading then it isn't a problem, and the C# way seems fine, but otherwise I think it depends on whether the default values stay the same in AGS 4 and how the majority of people use the function. Again, there seems to be clash in how the function is designed and used - the case-sensitivity defaults to something that probably makes little sense for scanning data but makes more sense when doing something like checking user input.

I do not want to come across as antagonistic or as blocking changes for no reason. I definitely do not want to steer someone to work on new string features which were not being worked on before. I decided to post comments because I saw a question:

> What is better? endIndex or length?

(One can logically support negative values and the other cannot.)

...and I saw a usability issue when having parameters for both a matching range as well as case sensitivity. To me, the use cases of those parameters are very different and what makes it easier for one use case makes it more awkward for the other. If there is no parameter overloading, and you are looking for a "final" design rather than a stop-gap, my gut feeling would be to split the functionaility between two separate functions.

> What would it be a step backwards? The common use is still simply "string.IndexOf("substring")", the rest of parameters are optional and have default values that match old behavior.

This is a mistake on my part because I've assumed that checks are case-sensitive by default in this new version because this is something eventually bound for AGS 4. This is because of the general expectation (from other programming languages) that string comparisons would be case-sensitive by default for performance reasons. If the case-insensitivity is preserved and it is considered that this is the correct thing to in all future versions of AGS, then there is no backwards step for anyone using the function as they used it before.

**Comment by ivan-mogilko** [comment]
It is possible to split the function into the two if wanted, that would mostly be a matter of adjusting script api, because both may call same implementation internally (providing default parameters if necessary).

For instance, something like:
```
String.IndexOf(string needle, caseSensitive);
String.IndexOfInRange(string needle, int start, int count, caseSensitive);
```

It is also possible to swap the default values for "case sensitivity" in all related functions in AGS 4, if that's considered a more suitable default. This was never brought up (or at least I don't remember seeing such request), but this seems to be reasonable compared to other string libraries.
The engine will retain a potency to handle old defaults in case of loading older games, as there is a way to compare both "game data" and "Script API" indexes, so if a need ever arises, one will be able to conditionally register backward compatible functions that remap parameter values.

**Comment by messengerbag** [comment]
Case-sensitive comparison as a default makes more sense, IMO, and case-insensitivity by default is probably a gotcha in the current AGS API. (This is especially the case now that AGS strings are Unicode, where the uppercase/lowercase correspondence is not well-defined without specifying a locale. For example, I/i are corresponding uppercase/lowercase versions of the same letter in most European languages, but in Turkish the uppercase version of i is İ, while the lowercase version of I is ı.)

> The engine will retain a potency to handle old defaults in case of loading older games, as there is a way to compare both "game data" and "Script API" indexes, so if a need ever arises, one will be able to conditionally register backward compatible functions that remap parameter values.

I really think we should strive to avoid complicating things in order to cater to backwards compatibility in AGS 4. Isn't half the point of the new major version to be able to make breaking changes without worrying about those things? (Though admittedly, changing such a basic part of the API without renaming the functions would risk introducing bugs in a lot of modules.)

**Comment by ericoporto** [comment]
Case Sensitivity per locale is something most languages don't support either and I believe it adds more complications when very few languages are affected (this so answer gives a library that has a solution for it https://stackoverflow.com/a/78520571). I would be cautious there because I don't think that OS case sensitivity for file path works the same.

**Comment by ericoporto** [comment]
Can we close this issue and move on from this nonsense?

**Comment by ivan-mogilko** [comment]
Very well. But now I regret opening it.
