### ISSUE TITLE
Feat. req. Pre 2.5 version games support (DOS, 3.11) for Windows runtime engine

### ISSUE THREAD

**Issue by necros2k7** [adventuregamestudio/ags#2492]
@ivan-mogilko @ericoporto @jjsat 
**Describe the problem**
A lot of AGS history are not accessible to general public

**Suggested change**
Implement support in any form of this history slice, maybe in another branch or fork if you want to drop legacy code

**Comment by ivan-mogilko** [comment]
I recall such request was already opened in the past. And I may say the same thing as I said earlier.

1. We do not have an access to the original engine source code prior to v3.2. Therefore, any legacy functionality that was not present in that code have to be reverse engineered.
2. We have a very small number of people working on the engine at the moment at their spare time. Virtually 1-3 people in different periods.
3. We currently prioritize advancing AGS forward as a more modern tool, rather than add backwards compatibility support.

These factors combined make me deny this request. I do not want to bother existing team of contributors with this.
If there are people willing to work on reverse engineering pre-2.5 engine, they may do so on their own. I suppose it's better to do this for ScummVM ags port too.
