### ISSUE TITLE
Skip Cutscene and fade inconsistency

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2571]
**Describe the bug**
If a cutscene plays over multiple rooms, then skipping it will still play the fadeout between rooms, but not the fadein. So the first room fades gradually to black, and the second room snaps in instantly without a fade.

**AGS Version**
3.6.0.53

**Game**
n/a

**To Reproduce**
1. Set room transition to fade in / fade out.
2. Have a cutscene that contains a room change, e.g. StartCutscene() in room 1, NewRoom(2), EndCutscene() in room 2.
3. Press ESC during the cutscene to skip it

**Expected behavior**
Both fadeout and fadein should play.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by ericoporto** [comment]
I tested this, but I think the expected behavior is that neither fade-out or fade-in should play, the player character should instantly be where it should when skipped.

**Comment by ivan-mogilko** [comment]
UPDATE: I did a test in AGS 3.2.1 out of curiosity, and it **does not play fade out** when rooms are changed during skipping a cutscene. So not displaying transition effects was an original intent.

**Comment by ivan-mogilko** [comment]
Fixed this,
and also fixed another bug which was not noticed at least since 3.2.1: FadeOut and FadeIn functions are skipped when skipping cutscene, but they do not mark screen state as changed, so skipping a cutscene with only 1 FadeOut or FadeIn inside may lead to a different visual state compared to same cutscene running normally.

release-3.6.1 branch:
a18d94a61d698aeb4fba39330d4194ca5410d696
14bc225fb64bef8aae56c2f791194d515d7a664b

master branch:
3b5ec67d44d9196e6ae16ce51fd3e70e000ec121
522081662c2bc338242052afbca49ee4615390e4

**Comment by Crystal-Shard** [comment]
Wow, that was fast :)

And it's a fair point that skipping both fades is the more consistent approach.
