### ISSUE TITLE
Merge iOS changes from Wadjet Eye fork.

### ISSUE THREAD

**Issue by monkey0506** [adventuregamestudio/ags#278]
Janet was kind enough to supply me with the following list of commits which could be cherry-picked back into the main source (her iOS branch is littered with project-specific changes that are not fit for merging). I believe this will require some more delicate review, however, as not all of the changes seem appropriate.

e0a7673ee7945e5d402d132cb451de580daa2817 - Possibly a memory leak
c1754b9d0a601f2aaad38a06ee0a80a0f1552c3f - Memory leak in ReadString
144df214b1ab8cc3f212e70c48d27c12818e2d25 - Sound crash bug fix
46b50dcf8c8cf814126ceb0c9b7348b9226cd2fd  - Added Allegro library project
57856c6950b1e25db6dfac39579546f567563376 - Added multi-architecture liballeg.a
11a4077c4c4b5d7237d6c19b809f82896df9b909  - Patched and created "dumb" project.
630b383434e015388d196c6152a3fa2adca7ead9 - Dumb project builds
3b84d21f37954ab8af66fcb9102651eddd5a1491 - Added compiled libdumb to AGS project.
aa498cf89398148e8b0a6eefe9ef201f3c74070d - Downloaded Freetype
b02380aaf0c588ffed0f58173896258712536af7 - Added cdave1's Freetype project
9793b08a3b9e6924a3e6b0805faa70d6225ddfc7 - Ogg downloaded
df663f84e6c6e2b5988767fee55d83484c839d53 - Added OGG project
47f20b96b238b0d6f74d55361c8c2c001978b0da - Set up OGG project
ec4a55e7411cf312922fe597cca0980146cfb71b - Rearranged Ogg project
bd9569ffd45a6d652b562a23cf35e9ccca8ce8d6 - Added compiled Ogg library
647a56d83e0c7de76b1a1c2a4063706977f47dfb - Updated scripts for theora
e53a123194852e4f12fa62c421d781c18cfbf7bf - Updated and patched Theora
4bb7a394d704f3039ca95b9d9a7979dd1ccf1f26 - Theora compiles
d6280409a5b7607b9dc0fcfff7ab102395a26c29 - Added compiled theora library.
6e5498cff21630c5f8176c971ef7d75692b711fd - Removed MAKE from tremor script
ae7a16cbffd3cb8a2c75e2c825799a22d4c5b573 - Updated Tremor from svn
8ec21f61ff144f55d5c326d76f9b453ac2ee3c4c - Added tremor project
d4a4a96485bcc29f50ebfe5e6c0690016e94d838 - Compiled tremor
fa77a5484fe227a8c6361c9fd7c20143410e18e2 - Added libaldmb target to dumb project
44eb08df07b524f053841639190a4a833d214736 - Plugin system updated to 64-bit
93113f72c5d563870c75deab4c1ef12b7b75c371 - Restore audio after phone call
ac070d335327bcf01d1674a4975dd93d1faad4ca - Crude hack to restore audio after answering phone call

**Comment by ivan-mogilko** [comment]
I could take a look, although it seems to me that most of these changes are applied to xcode project?

PS. this cannot be labeled as "pull: wip" - that is a tag we created for pull requests that need to be reworked after code review.

**Comment by JanetGilbert** [comment]
Most of the changes are to add xcode projects for the libraries that ags 
needs to be able to compile on iOS. These libraries used to compile 
using cmake, but the method was obsolete and no longer worked. The 
libraries needed to be recompiled to add a 64-bit slice, because 
32-bit-only apps are no longer accepted in the app store.

Janet Gilbert

**Comment by rofl0r** [comment]
since this is a source code repo, it's a bad idea to add precompiled libraries, especially considering that these are all standard libraries which are usually shipped with all major linux distros. binaries increase the size of a source code repo a lot, and they need to be checked out by everyone, even ppl not interested in them. additionally, they will eventually need to be recompiled and further increase the bloat of the repo since every change is forever saved in the git history.
a smarter approach would be to add another independent project that gathers the prerequisite libraries via a script and compiles them with the users compiler with the right settings for his target platform.
later, the directory containing the libraries and its headers can be passed via the usual mechanisms to ags' makefile infrastructure, for example
```make CPPFLAGS+=-I/path/to/headers LDFLAGS+=-L/path/to/libs```

**Comment by sonneveld** [comment]
I wouldn't mind a little time to test this on my machine and also add a
part time build job on team city.  Still away but back next week.
Last time I tried to build these libraries I had a lot of trouble with the
newer xcodes clang compiler.  Plus you need third party tools like cmake.
So compromise for pre built lib might be to build via team city and make
avail via other means.

**Comment by sonneveld** [comment]
Phew, I got the buildlib scripts working against xcode 7.0. (in another branch) so I can finally test @JanetGilbert 's changes.

**Comment by JanetGilbert** [comment]
So we don't need the Xcode projects anymore? How did you do it?

Janet

**Comment by sonneveld** [comment]
Too many things had changed by xcode 7 so I dredged up an old copy of osx lion and installed the earliest xcode I could.  Once I figured out how to build in that old environment, I was confident enough to fix the issues that came up with 7.  Adding the new 64 bits platforms was actually pretty easy.  There was some extra tidying up where we ask xcode to give us the paths for the sdks and binaries instead of fixed paths so we don't need to keep updating them.

I still want to tidy it up and test, but current fixes are here https://github.com/sonneveld/agscommunity/commits/ios-project-fixes
