### ISSUE TITLE
Experiment: embed manual into the Editor

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#285]
In discussion around #284 @tzachshabtay suggested:

> can't we just embed the help file as a resource in the solution? I think windows won't have any issues with opening the file if it's embedded (but maybe I'm way off due to misunderstanding the issue).
Any file can be embedded by "adding existing file" from the solution, then in the file properties selecting "embedded resource". Loading the resource to a stream is then performed by Assembly.GetManifestResourceStream.

I may also add that if the manual is embedded, then its presence will always be guaranteed.

In sake of experiment following needs to be tested out:

1. Is it possible to open embedded manual in Help Viewer?

2. Will that still work if the Editor binaries are marked with untrusted zone identifier?

**Comment by ivan-mogilko** [comment]
I am not sure I understand the complications this may cause for automated building process. Is not that possible to simply change the building order? @sonneveld , can you elaborate on that?

**Comment by morganwillcock** [comment]
I think you will also have to identify somewhere to write a temporary help file from the stream, so that the Help Viewer can open it. Path.GetTempPath() seems the logical option but now you are dealing with a file that is outside the program directory and may or may not be removed whilst the Editor is running.

**Comment by rofl0r** [comment]
a disadvantage of embedding resources into executables is that they will always be mapped into RAM (i.e. they waste RAM even if they're not used).

**Comment by ivan-mogilko** [comment]
> a disadvantage of embedding resources into executables is that they will always be mapped into RAM (i.e. they waste RAM even if they're not used).

Yes, that's true.
Another thing is that we won't be able to patch manual file only, we would need to distribute whole executable.

**Comment by sonneveld** [comment]
Build order can be changed but I'm just not convinced that it's worth doing just for this problem.  _Especially_ since we already have the zone identifier fix and an installer.  Plus it makes building the editor annoying for development/testing if I have to also build a manual as well.  I don't tend to have the user manual (and all it's artifacts) lying around in my workspace.

**Comment by ivan-mogilko** [comment]
Alright, since the idea is not very popular, and would causing more problems (e.g. a need to create temporary files without being able to delete them in time afterwards), I will close this.
