### ISSUE TITLE
Switch to C++11?

### ISSUE THREAD

**Issue by JIghtuse** [adventuregamestudio/ags#320]
I tried to built engine with GCC6 (which uses C++14 by default) and apart from a few tiny issues, it builds fine.
So, the question is - would you accept patches to support C++11? If so, which branch should it go to? I can send a few right now.

**Comment by monkey0506** [comment]
We cannot do this until the Visual Studio project files can be upgraded to
VS2015. Because AGS is primarily developed as a Windows engine (C++) with a
Windows IDE (C#), moving away from Visual Studio is not viable at this
time. Versions of VS prior to 2015 have extremely limited support for core
C++11 features. Currently AGS is built for Windows using VS2008 which has
no direct support for C++11 except some "experimental" STL support.

**Comment by JIghtuse** [comment]
That's shame. How soon will it be possible to upgrade project files? I have no VS, so I can't help here..

**Comment by rofl0r** [comment]
that's not a shame, that's good. by starting to use the latest bleeding-edge features of your latest bleeding-edge compiler, you would force anyone to use the latest bleeding-edge compiler as well. i'm glad i can still compile AGS on a LTS linux distribution with gcc 4.5.

**Comment by monkey0506** [comment]
Something that's been standard for five years with several years of drafts
prior to formal ratification (for most features, often without changes) is
not even remotely bleeding edge.

**Comment by ivan-mogilko** [comment]
> That's shame. How soon will it be possible to upgrade project files?

This is not just a question of upgrading project files, but also reorganizing build process for Windows. For instance, Windows version still uses some prebuilt static libraries, that have to match certain version of Visual C++.

The general plan was to get rid of prebuilt binaries, but that may take time and effort, because these libraries were actually patched by original author of AGS; so we might need to set it up in such way that  those patches still apply, or AGS could work without them.

In any case, this is something that *should* be done (regardless of whether we move to C++11 or not), but could not be done in just few days.

I would not also want to do this in one of the active development branches, because we are trying to create a new stable beta version now (develop-3.4.0 branch), and adding such changes may complicate things.

**Comment by rofl0r** [comment]
@monkey0506 the first compiler that implements C++11 fully is GCC 4.8.4, released December 19, 2014. so it's just little more than a year that it also *implemented*, not just *documented*.

**Comment by JIghtuse** [comment]
@monkey0506 @ivan-mogilko thanks for your answers! I guess, we can return to this issue some day. Feel free to close it or mark as low-priority.
