### ISSUE TITLE
Editor crashes on start

### ISSUE THREAD

**Issue by CisBetter** [adventuregamestudio/ags#336]
# Editor crashes on start
Every time I start the AGS Editor *(3.3.5 or newer; downloaded from adventuregamestudio.co.uk; BOTH - ZIP and Installer)* it crashes showing the following message:
![ags-openbug](https://cloud.githubusercontent.com/assets/17952058/16744088/b554af08-47af-11e6-980a-cb38fc769392.PNG)
This didn't happen until version 3.3.5 was released. I don't know whether it's caused by a dependency I haven't installed or something else.
My system:
Win7 x86_64 
![mysystem](https://cloud.githubusercontent.com/assets/17952058/16744178/22e40f8c-47b0-11e6-8018-734dce50cff1.PNG)
I've installed a recent version of VisualStudio with all it's dependencies.
## Steps to reproduce the error:
- Open the AGS Editor via 'Microsoft Explorer' or equal.
- Error message will show up.

The same problem occured using a new virtual pc running Win7.
As this is keeping me from using AGS newer than 3.3.4 I am looking forward to hearing from you :smiley: 
-CisBetter

**Comment by ivan-mogilko** [comment]
This is usually because you do not have proper VisualC Redistributable installed. It has to be **precise** version, because those redistributables are usually **not** compatible with each other.

The important thing about AGS 3.3.5 is that we now use automatic build server, but so far we had no reports about differences in behavior.

When you install AGS 3.3.5 using installer, do you have "Install VC Redistributable" option (checkbox) available there, and if yes, do you check it?

**Comment by CisBetter** [comment]
> This is usually because you do not have proper VisualC Redistributable installed. It has to be **precise** version

Indeed, I had Microsoft VisualC++ 2010 installed on both machines. After reinstalling AGS 3.4 ***with*** VisualC++ 2008 it runs.
