### ISSUE TITLE
AdjustVolumeWithScaling not working

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#359]
As it is now the Character's property AdjustVolumeWithScaling is not working.
Basically the volume handling is initiated by
"void CheckViewFrameForCharacter(CharacterInfo *chi)"  from character.cpp
which sets "play.sound_volume" to the desired value then calls the following
> CheckViewFrame()
>> play_audio_clip_by_index()
>>> AudioClip_Play()
>>>> play_audio_clip()
>>>>> play_audio_clip_on_channel()

and ultimately restores the previous "play.sound_volume" value

This is my naive fix: #358 
I'm applying the value inside play_audio_clip_on_channel(), but is there a better way to handle it ?

Also, I saw you've added a set_volume_override(), am I correct in assuming I don't need to check if play.fast_forward is negative ?

**Comment by ivan-mogilko** [comment]
First of all, regarding your last question: at some point I had to clean up volume adjusting code around the engine, because there were multiple glitches related to its behavior in cutscenes. Since things were quite messy there, I added inlined functions for all possible cases of volume change, and made game code use these instead of directly touching SOUNDCLIP variables.
Speaking of this I have to note that those variables are still not private, but I do not remember why I left them so... maybe that would require do more refactoring and I decided not to go too far. But absolutely they should be made private whenever possible.
Here's the related commit, for the reference: 58cfe41e02712a3dd5498b902e07505da34b5b0a

Now, if we assume your fix (regardless whether it is correct or not), setting volume must be done BEFORE any conditional adjustments, such as checks for "play.crossfading_in_channel" and "play.fast_forward", probably right after we get a clip from load_sound_clip(). Because load_sound_clip() it is where the volume is set initially, and the latter code can modify either "origin" volume, or set temporary "override".

**Comment by ivan-mogilko** [comment]
Now, speaking of proper fix. I would make a guess that the code found in CheckViewFrameForCharacter was some kind of quick-hack made at times when *play.sound_volume* was actually used to start playback. That might have changed around AGS 3.2.0, with the new Audio system, which completely revamped volume settings, and so this functionality was lost.

Anyway, using global variable like that is a really bad idea, and the only reason I can think of it was made so was lack of time and/or lack of will to clean up the dirty code.

In my opinion the proper fix should be following:
* Make all the functions in the stack you noted in your post (starting with **CheckViewFrame()** and down to **play_audio_clip_on_channel()**) take an additional *optional* parameter for custom volume. Its default value should probably be -1, because volume cannot be negative.
* Inside play_audio_clip_on_channel(), right after getting **soundfx** from **load_sound_clip()** (and check that it is not NULL), apply this custom volume (if it is not -1).
* In the *CheckViewFrameForCharacter()* get rid of any reference of play.sound_volume (this function should not change it at all), and make a local variable which will be calculated according to the character scale (all algorithm stays the same), and then passed into CheckViewFrame.

At the first thought that should work.

**Comment by ivan-mogilko** [comment]
Hmm, there is one thing though, **AudioClip_Play** is exported as part of script API. Adding an extra parameter may require replacing it with backwards compatible function in the table of exports, which seem too much for this fix.

Maybe skipping AudioClip_Play and calling more generic play_audio_clip straight away instead would be better idea? Or writing another function similar to AudioClip_Play but with 1 more parameter.

**Comment by AlanDrake** [comment]
Hmmm, what if we made so the whole call stack returns the audio channel right back to CheckViewFrameForCharacter ?
Then it would be trivial adjusting the volume, and whatever might be needed in the future.

**Comment by ivan-mogilko** [comment]
This idea sounds interesting.
The problem is that channel's volume can be adjusted right inside play_audio_clip_on_channel - in case there is cutscene skipping, or crossfade is going on.

Although... what *could* work (not very sure yet), is if there were another function in SOUNDCLIP to set volume "origin" without modifying currently playing volume.

**Comment by ivan-mogilko** [comment]
Another case is that the sound can be queued if the channel is busy, in such case it won't return audio channel immediately.

**Comment by AlanDrake** [comment]
Well, the audio played from there never gets queued and I doubt there would be cases where it needs crossfading, since it's only played by the view frame.
But yes, this feels messy no matter what path I'd like to take. I'll take a better look tomorrow.

**Comment by ivan-mogilko** [comment]
Hmm, yes it is true, this path always has "queue" set to false, and it is never set to crossfade channel.
Actually in such case your suggestion could work.

What has to be solved is the case when the sound gets adjusted while skipping cutscene.
I think the possible way to solve that is to change the way sound gets muted, by not using "set_volume_override" and "reset_volume_to_origin", but instead making some kind of a new "muted" flag  in soundclip and enable/disable it: that would also change real volume and keep real volume from being immediately applied when "set_volume" is called.

**Comment by ivan-mogilko** [comment]
I did this: ae064f73428bcfe5c290b27ad5b445d38d61e4bd

Basically, you can now use "set_volume_percent" (former set_volume_origin) without fear that it will break sound mute imposed by cutscene clip: the sound will stay muted until cutscene end, because there is now separate "muted" flag.

**Comment by ivan-mogilko** [comment]
Oh, there is an important thing. You really should use "set_volume_percent", not "set_volume" here, keeping in mind that it uses 0-100 units, as opposed to 0-255 units. "set_volume" is an old style way to change soundclip's volume level.
The whole situation around clip's volume is still complicated, because the public interface exposes both new and backward-compatible ways to change it. Bringing all this to consistency should be in todo list.

**Comment by AlanDrake** [comment]
I've implementing with "set_volume_percent", but wouldn't it better to use the full range value 0-255 with these inner functions ?
Doesn't make a difference in this particular case. but a potential loss of more than half the range is not good IMHO.

**Comment by ivan-mogilko** [comment]
Internally sound clip implementations are using 0-255 range. But this range is Allegro-specific and relevant to how it works internally.
The new audio system uses 0-100 range, which represents percents, rather than fractions of 255. This is how scripts work with Audio Channels now.

In the case of scaling sound volume with zoom, you are going to scale volume that is already set in 0-100 range (you may read it with get_volume).
