### ISSUE TITLE
startgame script and directory names

### ISSUE THREAD

**Issue by SilasMortimer** [adventuregamestudio/ags#365]
I was trying to troubleshoot an AGS game that I have on Steam, because it wasn't starting. What it boiled down to was that they were using the default `startgame` script (renamed), which has this line at the beginning:

`SCRIPTPATH="$(dirname "$(readlink -f $0)")"`

The game's directory has spaces in it and for some reason I still am not sure about, that line does not parse the path name with quotes. However, when the outer quotes are removed, like this:

`SCRIPTPATH=$(dirname "$(readlink -f $0)")`

... it works just fine. Steam user flesk pointed out that this line would be more robust:

`SCRIPTPATH=$(realpath "$(dirname "$0")")`

Which I've also tested with the game and it works. I should also note that other games based on AGS that didn't have spaces in their path work just fine with the original version of the line; only when there are spaces (and presumably other characters that require an escape) does it not work.

**Comment by SilasMortimer** [comment]
I forgot to say that this issue exists in Linux.

**Comment by ivan-mogilko** [comment]
I believe you are speaking about this file:
https://github.com/adventuregamestudio/ags/blob/master/debian/ags%2Blibraries/startgame

@tobihan and @monkey0506 were working on that kind of installation before, I think it would be better if either of them took a look into this.

**Comment by SilasMortimer** [comment]
Yes, that is the file I'm talking about. Sorry about that - I forgot to link.

**Comment by monkey0506** [comment]
Honestly, my experience with Linux is pretty localized to the use-cases I've had with building and deploying AGS games. Is the "more robust" script in some way preferable to removing the outer quotes? My personal thought would be that those outer quotes would actually *prevent* this problem, rather than *creating* it.

The `startgame` script has really only been touched by @tobihan, and it seems that this was his intention with 3960672.

**Comment by monkey0506** [comment]
[This article](http://unix.stackexchange.com/questions/136494/whats-the-difference-between-realpath-and-readlink-f) (dated more than 2 years ago) suggests that `readlink -f` is better (and more consistently) implemented across Linux flavors, particularly noting that Debian has its own `realpath` that is inconsistent with the GNU implementation. I have no context for whether this has changed over the last two years.

**Comment by SilasMortimer** [comment]
I think I might understand why removing the quotes works. It's because of this line: 

`ALLEGRO_MODULES="$SCRIPTPATH/data/lib64" "$SCRIPTPATH/data/ags64" "$@" "$SCRIPTPATH/data/"`

... and the other similar one. This (or the other one) is the line that actually executes the game. The $@ is the key here: It has quotes around it. Thus, if SCRIPTPATH already has quotes, the fact that they are doubled negates them. So instead of:

`"/path/to/a game"`

... you get:

`""/path/to/a game""`

... so they're cancelled out.

**Comment by SilasMortimer** [comment]
Oh, and you might be right about `realpath`.

**Comment by SilasMortimer** [comment]
I garbled the reply before the last one. I hope it made some kind of sense.

**Comment by monkey0506** [comment]
Ah, that does make sense. I'm assuming that the script interpreter is expanding the quotation marks as part of the symbol, yes? So, `"$SCRIPTPATH/data/lib64"` would expand as `""path/to/game"/data/lib64"`?

**Comment by SilasMortimer** [comment]
That's what it seems like, yes.

**Comment by monkey0506** [comment]
In that case, I'm guessing that it's also doing some C-style string concatenation, and still treating the path as unescaped text, so whitespace breaks it, but paths without whitespace function normally.

It would be helpful to know if this is standard or specific to Debian. I don't want to make assumptions and needlessly create commits.

Removing the quotations where `$SCRIPTPATH` is assigned seems the optimum route for now, though.

**Comment by SilasMortimer** [comment]
Oh, I can tell you that it's definitely standard. It's a standard of the SH shell (and the BASH shell, which has replaced SH in recent years), which is standard across all Linux distributions.

**Comment by rofl0r** [comment]
the standard SH shell is called "POSIX/bourne shell" btw.
BASH has not replaced SH in recent years, it is the other way round: POSIX sh compatible shells like dash have now replaced bash in debian based linux distros, because many people assumed bash behaviour when invoking /bin/sh.

+1 for "Removing the quotations where $SCRIPTPATH is assigned seems the optimum route for now, though."

**Comment by SilasMortimer** [comment]
Good catch. I had no idea I had it backward.

**Comment by morganwillcock** [comment]
This should be fixed by #518. It just needed quoting on the argument to readlink, otherwise you are potentially assigning a multi-line string as the return value.

<pre>$ readlink -f "System Volume Information"
/mnt/d/System Volume Information

$ readlink -f System Volume Information
/mnt/d/System
/mnt/d/Volume
/mnt/d/Information</pre>
