### ISSUE TITLE
Can't compile the engine under Linux with the current master

### ISSUE THREAD

**Issue by eriktorbjorn** [adventuregamestudio/ags#410]
When I try to compile the engine under Linux, using the current git master, I get the following error:

~~~~
gfx/gfxfilter_ogl.cpp: In member function ‘virtual void AGS::Engine::OGL::OGLGfxFilter::SetFilteringForStandardSprite()’:
gfx/gfxfilter_ogl.cpp:34:21: error: ‘GL_TEXTURE_2D’ was not declared in this scope
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
                     ^~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
Makefile:45: recipe for target 'gfx/gfxfilter_ogl.o' failed
make: *** [gfx/gfxfilter_ogl.o] Error 1
~~~~

This appears to be because ogl_headers.h doesn't have any case for defined(LINUX_VERSION). I'm attaching a patch that Works For Me(tm), but I don't know if it's sufficient.
[compile-fix.txt](https://github.com/adventuregamestudio/ags/files/1040354/compile-fix.txt)

**Comment by ivan-mogilko** [comment]
Yes, that's an oversight.

Including OGL headers on Linux does not have much sense right now because the renderer itself is turned off. As a quick patch I will disable particular lines for Linux. But OpenGL renderer was rewritten to work properly on desktop systems, and I was looking forward trying to enable it on Linux. I have no idea what is required for it to work though (installed libraries, etc). There are only few platform-dependent calls that need to be subsituted with something else on Linux.

**Comment by ivan-mogilko** [comment]
Should be fixed with 2510d6fbfd231588688f108005d4ff6fbc2ef951

**Comment by cedricbu** [comment]
yes, ☺ works for me! thanks!

**Comment by monkey0506** [comment]
This was fixed some time ago, right?
