### ISSUE TITLE
[Windows 10] Unable to get My Documents dir: GetShortPathNameW failed

### ISSUE THREAD

**Issue by rocifier** [adventuregamestudio/ags#417]
In Windows 10, a message box displays every time I run a game created with AGS. This includes games I make from the editor 3.4.0 and exes. The error message is:

    Unable to get My Documents dir: GetShortPathNameW failed

This is related to saved games as seen [in this code](https://github.com/adventuregamestudio/ags/blob/19cab6c05af56624a257b2a456e226fce777cb51/Engine/platform/windows/acplwin.cpp#L578).

My use account has a My Documents directory. This error message doesn't seem to affect the game, and clicking OK resumes the loading of the game, and all the saved games work perfectly in each game.

**Comment by rocifier** [comment]
Update: I have been looking through my file system, and I actually don't have a "My Documents" folder. The closest equivalent I can find is in C:\Users\XXX\Documents however it doesn't contain much of anything interesting so I wouldn't expect saved games to go there.

From my experience, app / game data usually should get stored locally under C:\Users\XXX\AppData\Local\AppName

Can anyone second this?

**Comment by ivan-mogilko** [comment]
AGS saves to "My Documents" only on Windows XP, on Windows 7 and higher it saves games to %USERPROFILE%/Saved Games/<Name of the game>, or correspondent alternative. This is the path returned by FOLDERID_SAVEDGAMES, I think.

The problem could originate from CSIDL_PERSONAL returning something unexpected on Windows 10. Although, to be honest, this is the first time such problem is reported for Windows 10.

I will see if I can change the code so that it won't check for paths compatible with old Windows versions unless newer version was not detected.

**Comment by rocifier** [comment]
I'm not sure what my alternative would be since I don't have a saved games folder. I will see what these paths return when I get home.

**Comment by rocifier** [comment]
Looking at the code after your comment it is not doing precisely what you said. First it is getting My Documents dir every time as a fallback, and then trying to get the Saved Games dir after that.

**Comment by monkey0506** [comment]
@ivan-mogilko stated, "I will see if I can change the code". Clearly the code hasn't been magically fixed retroactively.

**Comment by monkey0506** [comment]
And "%USERPROFILE%/Saved Games" is a standard system path.

**Comment by rocifier** [comment]
@ivan-mogilko are you still working on AGS then? I'd be happy to make a contribution. I just ask because I saw your announcement from April

**Comment by ivan-mogilko** [comment]
> Looking at the code after your comment it is not doing precisely what you said. First it is getting My Documents dir every time as a fallback, and then trying to get the Saved Games dir after that.

I will clarify myself. AGS *looks up* for those folders always. But it *saves* to existing path depending on operating system (or at least supposed to).

> @ivan-mogilko are you still working on AGS then? I'd be happy to make a contribution. I just ask because I saw your announcement from April

I am planning to finish the 3.4.1 release, which needs few bug-fixes, including this error. I was busy recently, but going to attend this issue later this week. Of course we also accept pull requests and patches. If you want to try it yourself, please make one on top of "release-3.4.1" branch, so that it gets into 3.4.1 (master branch already contains additional changes that I do not want to put into 3.4.1).

**Comment by rocifier** [comment]
Okay cool. I might give another go at getting the code compiling. I got stuck with the allegro libraries and referencing allegro from allegro font, and which include directories to add, etc. I was getting errors from the allegro config header about it not being able to find the allegro sub-headers.

**Comment by ivan-mogilko** [comment]
I have precompiled libraries for Windows here (release-3.4.1 requires MSVS 2008 SP1 and master branch requires MSVS 2015 or anything compatible):

https://www.dropbox.com/s/4p6nw6waqwat6co/ags-prebuilt-libs.zip?dl=0

**Comment by rocifier** [comment]
@ivan-mogilko thanks! That will speed things up tonight.

**Comment by ivan-mogilko** [comment]
Should be fixed with 3d5f02b69d2b20a647c7ec6c326d652ca9f253a7.
