### ISSUE TITLE
Severe "gcc" Warnings under Gentoo Linux

### ISSUE THREAD

**Issue by leycec** [adventuregamestudio/ags#418]
On bumping [the Gentoo ebuilds](https://github.com/leycec/raiagent/tree/master/games-engines/ags) housed at [my third-party overlay](https://github.com/leycec/raiagent) to the most recent stable release of the CLI AGS engine (*3.4.0.16*), I couldn't help but squelch a shudder of nausea. Post-installation Gentoo checks detected the following quasi-fatal `gcc` warnings:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * libsrc/alfont-2.0.9/alfont.c:889:21: warning: implicit declaration of function ‘wcslen’ [-Wimplicit-function-declaration]
 * libsrc/alfont-2.0.9/alfont.c:32:16: warning: implicit declaration of function ‘malloc_usable_siz ’ [-Wimplicit-function-declaration]
 * ac/dynobj/cc_dynamicarray.cpp:35:40: warning: NULL used in arithmetic [-Wpointer-arith]
 * debug/debug.cpp:55:29: warning: converting to non-pointer type ‘long int’ from NULL [-Wconversion-null]

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: 
 * 	http://www.adventuregamestudio.co.uk
 * 	https://github.com/adventuregamestudio/ags
```

The two "implicit declaration of function" warnings in the `alfont` codebase are particularly concerning and, to my lazy eye, might better be converted into fatal errors. Or maybe not? <sup>*Who needs standards compliance anyway!*</sup>

While these warnings are *probably* all ignorable for now, their mere existence will *probably* prevent us from adding AGS to [Gentoo Portage](https://packages.gentoo.org) (i.e., our official package tree). That would be unfortunate, because AGS is otherwise awesome and deserves everyone's full attention.

Thanks for the valiant hard work, all! I espy a [significant cleanup of legacy code](https://github.com/adventuregamestudio/ags/issues/403) underfoot, which I can't help but proudly salute. You do the Gods' own work, @AlanDrake. 🖖

**Comment by rofl0r** [comment]
`implicit declaration of function ‘malloc_usable_siz ’` - using malloc_usable_size() is a bug in itself since it's not portable (GNU only) and hints at a misguided approach. generally, there's no good reason whatsoever to poke at libc malloc internals.

`implicit declaration of function ‘wcslen’ ` - #include <wchar.h> will fix it.

**Comment by ivan-mogilko** [comment]
Do I understand correctly, that malloc_usable_size is basically for learning size of C array? From the looks of the code it is used only in one place, as a workaround for checking size of the provided output buffer. I suspect someone was modifying the library code and not willing to change library function prototype.

Since this code is integrated into our program I think it should not be a problem to add another function argument for the buffer size instead.

**Comment by ivan-mogilko** [comment]
Hmm, no, I was too hasty; alfont.c is only used for Linux build, Windows build is linking actual library, hence change to function declaration would require more patching. I think I'd rather add necessary includes for now.

**Comment by rofl0r** [comment]
was that recently added ? since that would break my build on sabotage linux - or maybe it works because we dont build the integrated allegro copy.
usually ppl use malloc_usable_size() to do hacks such as stuffing more things into an allocation than previously requested, to "optimize out" use of realloc, or because they want  some layer on top of malloc, but are too lazy to the bookkeeping of the allocated sizes themselves.

**Comment by ivan-mogilko** [comment]
No it was not added recently, according to git history this code comes from the initial commit f0cdf9c2afadc4f34ceadc50879a14b88c76a12c and corresponds to alfont 2.0.9, This is also very old code, somewhere from early 2000-ies.

**Comment by rofl0r** [comment]
well if the code gets linked, the linker will throw an error if the function is not available in the libc, regardless of whether the code using it will ever be used or not. the only way it could fail at runtime as you suggest would be if the program tried to `dlopen("libc.so", ...)` and then use the function via `dlsym()`.

**Comment by ivan-mogilko** [comment]
I tried to replace uses of malloc_size in the code, but there is a lot of things going on there, buffer pointers being assigned and swapped between two or three variables, which is not easy to track without thorough investigation. I'd hate to spend time on this considering the function is not even used by program, and rather inclined to just remove or disable it.

**Comment by rofl0r** [comment]
imo it's not really an issue - ags works fine with vanilla allegro4 so there's not even a need to compile this.
if you want to solve it anyway, it might make sense to look at current allegro sources and if the code is no longer there see which commit in their git repo removed/fixed it.

**Comment by ivan-mogilko** [comment]
I think there is a misunderstanding, it is not a part of allegro, it is a separate library. It has not been updated since 2004, I think. This source file - alfont.c - is a part of compilation on Linux (and some mobile ports). You may see it is mentioned in the Makefile-objs.

**Comment by ivan-mogilko** [comment]
Oh, right, another issue I've forgotten about :(.

To update:
In the past I have disabled code which used non-standard malloc_usable_size: 7b19ffba2600d8f84530d7267d838abfbf2622fe
And supposedly fixed implicit declaration of wcslen: 5c66c61c4bc6900e7bd31b182266dd9beac50192

Two more warnings from original report remains:
<pre>
 * ac/dynobj/cc_dynamicarray.cpp:35:40: warning: NULL used in arithmetic [-Wpointer-arith]
 * debug/debug.cpp:55:29: warning: converting to non-pointer type ‘long int’ from NULL [-Wconversion-null]
</pre>
*NOTE:* this should be now fixed in release-3.4.1 branch.

**Comment by ivan-mogilko** [comment]
Oh, apparently the other two warnings mentioned in the first post were also fixed around same time:
11c54f0779c4b5925c544f4901ce97071dd3647e, 146891a3f51a89f1fcd0d3ef19e71a8c273c111f.

@leycec , did you have a chance to test that out?

**Comment by ivan-mogilko** [comment]
Closing, reporter did not reply, but it's been too long and new version is almost out.
