### ISSUE TITLE
tons of warnings with -Wall -Wextra

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#46]
http://sprunge.us/hVVL

most of them are because of unused args
if you don't use args, you can make the warning go away like this

```
void func(int arg) {
  (void) arg; // removes the unused warning
}
```

**Comment by ivan-mogilko** [comment]
I took some liberty in deleting old comments under this issue because that discussion went off-topic very quickly.

The issue is very old and unfortunately there was little enthusiasm for fixing these.

A quick look at current situation shows that majority of "unused arg" warnings today are related to the script API wrappers which have identical prototype but their implementations are made with the use of macros mostly, and not all of the arguments are used every time. Fixing that will be a big step towards reducing the warning count.

**Comment by rofl0r** [comment]
the pastebin link has been replaced with unrelated content in the meantime though.
