### ISSUE TITLE
Add Git integration

### ISSUE THREAD

**Issue by CisBetter** [adventuregamestudio/ags#468]
As discussed in #463, it is very difficult to do parallel development in AGS. It requires a ridiculously complex workflow and merging parallel changes in binary room files is almost impossible.

### I suggest:

- finally getting rid of big binary files that function as a cache for other binary files. (See #469)
  - Merging changes in a binary file is hard enough. It is impossible when all the project's binary files are merged in a single file.
- adding a Git integration to the AGS editor. *(Plugin)*
- adding some kind of user interface to AGS that allows easy management of the project's git repository. *(Plugin)*

### Ideas:

**UI**: Something like Eclipse's Git integration or [gitg](https://wiki.gnome.org/action/show/Apps/Gitg)?
**Files**: A single XML file functioning as an index file and several `.agsasset` files containing preprocessed  assets (as far as I know, Unreal Engine uses this way).

## Required:

- [x] Change game project's Rooms to open format: #469

## Tasks:

- [ ] Implement Plugin
    - [ ] Explore current state of source control API

**Comment by gurok** [comment]
This feels like the role of an editor plugin to me.

**Comment by CisBetter** [comment]
Indeed, the user interaction in the editor could be provided by an editor plugin.
Changing the file formats for room files and sprite caches, however, should be implemented in AGS 4 as plugins are not meant to replace essential functionalities of the Editor.

**Comment by ivan-mogilko** [comment]
Added separate task for Room format: #469

**Comment by persn** [comment]
I looked into this years ago but I had to give it up because of certain restrictions, and also because I was a rookie programmer. Since the editor .NET version is upgraded we can use [libgit2sharp](https://github.com/libgit2/libgit2sharp). I remember my conclusion at the time was that the source control interfaces being designed around certain ideas that didn't mesh well with git, like doing registry lookups to verify that the source control system was installed, but maybe my memory is just a little fuzzy. I don' think it matters much, the only source control support I know that was developed for AGS was MSVCVSVS or whatever the acronym is, which was discontinued many years ago so we can probably take that out(have to anyway to get cross platform editor). Breaking comparability with already existing plugins is probably safe since there probably is none. (Maybe?)

I agree that this should be developed as a editor plugin. Should the plugin be hosted directly on the repository or should it have a dedicated repository?

**Comment by persn** [comment]
> Change game project's Rooms to open format: #469

Could the be taken out of the first post? It's a separate issue and it's only vaguely related to the goal of making a git integration for the editor.

**Comment by persn** [comment]
I wonder if it would be acceptable to just remove the source control API altogether and just let the plugin control everything? The idea behind the API seems to be to provide a standardized UI for source control solutions, the problem is however it makes a lot of assumptions on what kind of functionality a source control system provides. Checking out individual files and disconnecting the source control server for instance isn't something git does. I also think this may be a too an ambitious task for most because it requires insight into how multiple source control systems work, which I don't think most people have. The existing UI is also somewhat lackluster, there's a ton that has to be added to make git user friendly. There are some alternatives here

1. Remove the source control API and related code. Let plugin handle everything.
2. Redesign the source control API to be more generic. Back end is provided in plugin, front end is provided by editor
3. Remove the source control API and related code. Make a new API.

**Comment by CisBetter** [comment]
@persn I moved

> Change game project's Rooms to open format: #469

to a new section instead of taking it out entirely.   
However, I would argue that in order to implement any system that tries to allow multiple developers to work simultaneously AGS must support merging changes in sprite index and other binary files first.

So in my opinion, creating a plugin that adds this integration is only useful if AGS itself supports basic source control features by not creating unmaintainable binary files in project directories.

**Comment by ivan-mogilko** [comment]
> AGS must support merging changes in sprite index and other binary files first.

For the sake of reference, the mergeable sprite system is under work: #526 (solves large part of the issue when done).

**Comment by ericoporto** [comment]
Just commenting here to remind myself of @CisBetter tutorial, and to point to the [gitinore](https://github.com/github/gitignore/pull/2935/files) file in case someone finds this thread.

**Comment by CisBetter** [comment]
@ericoporto. I think it's a good idea that after forgetting about my “little tutorial” for more than two years I give it another go. The only problem is that I don't quite remember what I wanted to add (I'm currently stuck with a folder of screenshots and a slightly modified version of my tutorial in Markdown).

Once finished, I'll upload the tutorial to the AGS Forums and post a link to it in #463.

PS: Thanks for submitting a .gitignore via [2935](https://github.com/github/gitignore/pull/2935) :grinning:

**Comment by ivan-mogilko** [comment]
> I wonder if it would be acceptable to just remove the source control API altogether and just let the plugin control everything?

I suppose

**Comment by ivan-mogilko** [comment]
As per @persn's [comment](https://github.com/adventuregamestudio/ags/issues/468#issuecomment-437497566), I suppose that it would be best couse to remove the current "source control integration" from AGS Editor altogether, and then later consider to re-add a more barebones generic editor plugin API if such need arises (that is - if anybody will want to actually write such plugin).

The reasons are:
- Different source control systems have different concepts and workflow;
- Maintaining source control mechanism in the Editor codebase is going to be additional burden. It's likely that existing implementation had already been broken, because some things in the project have changed, but nobody remember to update the "source control integration".
- In these years nobody have written such plugin, it seems.

**Comment by ericoporto** [comment]
I imagine when making it as a plugin the issues related to #1041 will appear when updating script structured. Syncing the project with the project itself in version control may be a challenge.
