### ISSUE TITLE
Editor: new preferences are serialized separately for separate installations of the same version of application

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#481]
Since I am running Editor from different locations on my computer, such as normal installation, and couple of source code locations, I noticed that user preferences in these do not match each other, even though the program versions do.

I checked the directory where these settings are now saved, and it looks like Editor creates *separate* group of setting files for each program location (URL).

Is this meant to be like this, and also is it actually preferred way for same program to not share config if it's run from another place?

**Comment by morganwillcock** [comment]
As far as I know, it will only differentiate between different versions, but what it uses as an identifier isn't the 'human readable' version number, but an ID related to the built assemblies. If there are no code changes between multiple installations you shouldn't have multiple settings (changes would include building against a different framework version). That said, I don't knowing what would happen if you could open two copies of the same application build (if the application itself allowed it), presumably you'd get locking issues in the SettingsProvider.

**Comment by ivan-mogilko** [comment]
Sorry for the delay. I've made an actual test, and confirm that separate settings are created for each program's location.

Steps:
1. Compile 3.4.2. Editor in the ags3 branch. Make two precise copies of the output in folders A and B.
2. Run the one from the folder A and change Preferences in certain way, also may open some projects to fill in "last projects" list.
3. Close app in folder A and run app in folder B. Instead of taking last config saved by app instance in A, it will instead import old preferences from version 3.4.1.

**Comment by morganwillcock** [comment]
Okay, so the path is made up like this:
> <companyname\>\\<appdomainname\>\_<eid\>\_<hash\>\\<version\>

where:
- `<companyname>` is the CompanyNameAttribute value, if available. Otherwise, ignore this element.
- `<appdomainname>` is the AppDomain.CurrentDomain.FriendlyName. This usually defaults to the .exe name.
- `<eid>` is the URL, StrongName, or Path, based on the evidence available to hash.
- `<hash>` is a SHA1 hash of evidence gathered from the CurrentDomain, in the following order of preference:
    - StrongName
    - URL
    - If neither of these is available, use the .exe path

So I think the solution is either to:
- modify the installer to not use the version number in the path (this doesn't fix people moving installations around though, unless using this as a way to separate settings would actually be useful),
- set a 'StrongName' for the assembly ([how-to-sign-an-assembly-with-a-strong-name](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name)) in the build options
- override/replace the underlying settings provider (this removes all the magic)

I can't find any references to the URL, but I imagine that is either ASP.net only or related to a specific type of installer (e.g. ClickOnce), so setting that wouldn't be an option.

**Comment by ivan-mogilko** [comment]
I'd vote for anything that makes config location independent. But I do not know how this "StrongName" works, will it add any complications?

**Comment by morganwillcock** [comment]
I think StrongName is just to provide a unique identify, which gives you some extra options:
[https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies#why-strong-name-your-assemblies](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies#why-strong-name-your-assemblies)
> If you are an open-source developer and you want the identity benefits of a strong-named assembly, consider checking in the private key associated with an assembly into your source control system.

**Comment by morganwillcock** [comment]
Thinking about it a little more, if it restricts how the assembly is loaded, if it is going to break something it would break the unit test project that I've got on another branch. I'll try it out and see what happens.

**Comment by morganwillcock** [comment]
It works, but the restriction of only being able to load signed assemblies means that each project must be signed, plus any external dependencies. So for my unit test project, it was fine (I just permitted the public key of the test project to access the built Editor assembly), but for AGS.Native.dll I am using a prebuilt version which isn't signed with a strong name (since this is mixed mode I can't recompile it to add the signing, so it would have to be signed when it is built). For Nuget packages there are some tools to sign them as part of the build.

Positives are:
- a key is just added to each project, so just one extra file
- key management tool is built-in (`sn.exe -Tp <KEYPATH>` gives you the public key)

Negatives are:
- each NuGet package needs signing (probably through the use of another NuGet package)
- NoNative solution will only work with a signed copy of AGS.Native.dll

So since there is quite a lot to deal with here, I'll also check ways of customising the settings provider.

**Comment by morganwillcock** [comment]
I've setup a VM to build on, and created and assigned a key to each project. This seems to have standardised the path:
<pre>dir /b %APPDATA%\..\Local\AGS\AGS*

AGSEditor.vshost.exe_StrongName_mqpdv5kqypl2dezfmjnjxse4zvfvse2h
AGSEditor.vshost.exe_Url_twzmkwmcupg0pwhrpsozps3dbzsqjejd</pre>

I could also build the NoNative solution after this.
I'll open a PR including the keys, and in theory that should build and start using the same path.

**Comment by morganwillcock** [comment]
The settings path now references the 'strongname' instead of the Editor path, so this should remain consistent as long as the same keys are used.
