### ISSUE TITLE
AGS 4 build error on Arch Linux (error: ‘size_t’ has not been declared)

### ISSUE THREAD

**Issue by RoqueNE** [adventuregamestudio/ags#505]
Trying to build on Manjaro (Arch based) with Kernel 4.18.5-1.

Error: 
```
../Common/ac/wordsdictionary.h:39:64: error: ‘size_t’ has not been declared
 extern void read_string_decrypt(Common::Stream *in, char *buf, size_t buf_sz);
                                                                ^~~~~~
compilation terminated due to -Wfatal-errors.
```

Adding `#include <stddef.h>` to wordsdictionary.h fixes it.

**Comment by ivan-mogilko** [comment]
Oh, it's in master branch, which is "ags 4", it's just that the version number was not raised yet (since we had not prepare a release).

**Comment by RoqueNE** [comment]
ah my bad. i changed the title. thanks

**Comment by ivan-mogilko** [comment]
Yes, our master branch is a "little" messy at the moment, I am hoping to begin fixing it very soon.

**Comment by ivan-mogilko** [comment]
I made commit: 7683ff86e5d8a4e0cc71a13993a499d151ea1f4b

But I still won't suggest using master branch for anything except testing yet, unless you are sure about what you do, because there may be mistakes related to data format (and when these are fixed old "incorrect" data format won't be supported anymore). If you are using the engine strictly for playing existing games I recommend building from latest release tag instead.
