### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by persn** [adventuregamestudio/ags#531]
It's sad that there's no CI for this project. We should do something about that. Previously there were TeamCity but that requires hardware and someone has to maintain that hardware, which I think is the reason it was taken down? Something that requires maintenance like that doesn't fit well with this project I think seeing as people generally don't have the time to work on it every week.

But maybe we can consider free for open source alternatives like Appveyour, Travis, others?

**Comment by morganwillcock** [comment]
@ericoporto are the AppVeyor and Travis CI accounts that are building the manual linked back to the Github organisation, or are they managed separately? I'll add scripts to build the Engine and Editor, if I know where to add them.

**Comment by ivan-mogilko** [comment]
I heard @ericoporto is trying to make Travis builds for some of the win engine's dependencies with plans on trying the engine next.

**Comment by ericoporto** [comment]
Hey here it is for lib-allegro, but I wasn't sure if it was ok to do PR 

https://github.com/ericoporto/lib-allegro

**Comment by ericoporto** [comment]
These are the macro tasks I think will be needed

- [x] Build allegro for Windows (AppVeyor) and Linux (Travis-CI)
- [ ] Store needed artifacts of allegro (using Github Releases)
- [ ] Build needed dependencies of AGS Engine for Windows (AppVeyor) and Linux (Travis-CI)
- [ ] Build AGS Engine for Windows (AppVeyor) and Linux (Travis-CI)
- [ ] Store AGS Engine for Windows and Linux (using Github Releases)
- [ ] Build AGS Editor for Windows (AppVeyor)
- [ ] Store AGS Editor for Windows (using Github Releases)
- [ ] Fully Automate Releasing AGS Editor directly from Github Releases (AppVeyor)

**Comment by ericoporto** [comment]
These are the macro tasks I think will be needed. @ivan-mogilko do you have input on that?

- [x] Build allegro for Windows (AppVeyor) and Linux (Travis-CI)
- [ ] Store needed artifacts of allegro (using Github Releases)
- [ ] Build needed dependencies of AGS Engine for Windows (AppVeyor) and Linux (Travis-CI)
- [ ] Build AGS Engine for Windows (AppVeyor) and Linux (Travis-CI)
- [ ] Store AGS Engine for Windows and Linux (using Github Releases)
- [ ] Build AGS Editor for Windows (AppVeyor)
- [ ] Store AGS Editor for Windows (using Github Releases)
- [ ] Fully Automate Releasing AGS Editor directly from Github Releases (AppVeyor)

**Comment by ericoporto** [comment]
These are the macro tasks I think will be needed. @ivan-mogilko do you have input on that? Also @tzachshabtay , I noticed you did CI on MonoAGS, so maybe you also have suggestions on this.

- [x] Build allegro for Windows (AppVeyor) and Linux (Travis-CI)
- [ ] Store needed artifacts of allegro (using Github Releases)
- [ ] Build needed dependencies of AGS Engine for Windows (AppVeyor) and Linux (Travis-CI)
- [ ] Build AGS Engine for Windows (AppVeyor) and Linux (Travis-CI)
- [ ] Store AGS Engine for Windows and Linux (using Github Releases)
- [ ] Build AGS Editor for Windows (AppVeyor)
- [ ] Store AGS Editor for Windows (using Github Releases)
- [ ] Fully Automate Releasing AGS Editor directly from Github Releases (AppVeyor)

I created a new user for having access to this (because of the need of token and all that yadda yadda that I just think is kind of bad design on these systems...) -> [github.com/ags-ci-user](https://github.com/ags-ci-user)

**Comment by tzachshabtay** [comment]
One suggestion: check out Azure Devops. It allows building on Windows, mac and linux, so no need to maintain 2 different build systems. I've been wanting to do that for MonoAGS as well. It also allows you to have a build pipeline and a release pipeline for deploying.

**Comment by tzachshabtay** [comment]
> Appveyor still has one advantage, you can get artifacts on a per commit base.

Azure DevOps can do that too (unless I misunderstood what you mean) -> you can setup your build to trigger on each push to a specific branch, and each build can have artifacts.

> I also feel AzureDevops enforces a GUI instead of YAML files in the project repo.

Not true: When you create a new build template, their first option is "configuration as code" which will create a yaml file in the repo.

> This is how the TeamCity configuration got lost. I feel even if Travis/Appveyor dies, their scripts have enough information to ressurect the build.

What I saw a lot of other projects do, is that they write their build script in bash/powershell/python, and then have the CI system just call that script. So you minimize your dependency on your CI system.

>  Travis also support Windows

Ah, interesting, I think that's new. At least, it wasn't an option when I started using it. If it works well, then, it's just as good as azure devops, and I would consider using either of those exclusively and ditching appveyor. Appveyor builds are very slow from my experience (not the build itself, but the waiting time until your build actually starts), and the burden of maintaining two CI systems (they tend to break often) is big. 

> I don't understand what you mean by build pipeline and release pipeline for deploying.

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/what-is-release-management?view=vsts
Though it might be too advanced for what AGS needs.

**Comment by ericoporto** [comment]
[build_ags_windows.cmd.zip](https://github.com/adventuregamestudio/ags/files/2678290/build_ags_windows.cmd.zip)

sometime ago @morganwillcock sent me this script he made for building AGS on Windows. I am adding it here so it's not forgotten. OpenGL headers tend to update very often, so they fail to sync with the md5sum provided in the script - I looked around and couldn't find an easy solution, like stable releases of it! We can like, [embrace a random static commit from the github repository for the headers](https://github.com/KhronosGroup/OpenGL-Registry/tree/master/api/GL) and that's pretty much as far as I could get. The directx used to build is kind old, and [while there appear to be ways to not depend on it](https://blogs.msdn.microsoft.com/chuckw/2015/03/23/the-zombie-directx-sdk/), it may be easier to tolerate it - but the installer isn't really supposed to be unassisted. Unfortunately I know very little about Windows but I do believe a magic script of sorts should exist somewhere inside the repository.

**Comment by ivan-mogilko** [comment]
@ericoporto, have you tried contacting @sonneveld? He was maintaining previous build server for AGS.

**Comment by ericoporto** [comment]
Sorry, mixed too much information at the same sentence.Ignore Directx, this will diverge the issue.

The script I think should exist is the evolution of this one created by morgan so that AGS can be automatically built. This is the first step for CI.

**Comment by ivan-mogilko** [comment]
@ericoporto , by the way, not sure if I mentioned before, we have certain Python scripts for packaging AGS distribution (editor); they are found in Scripts dir and Windows/Installer.

**Comment by morganwillcock** [comment]
It seems the build scripts for minpsp no longer work:
> svn: E170013: Unable to connect to a repository at URL 'svn://svn.ps2dev.org/psp/trunk/psptoolchain/patches'
svn: E000110: Can't connect to host 'svn.ps2dev.org': Connection timed out

...and I'm having trouble finding any existing binaries for this (other than for Windows, but the build process for Windows doesn't cover the libraries) or the M33 SDK (to be honest, I'm not even sure what version of this I'm trying to find). I do actually have a PSP to check the build, but I'm probably stuck without finding the missing files.

Has anyone else ever built this?

**Comment by ivan-mogilko** [comment]
PSP is very low priority to be honest. I recall we were trying this out with Nick Sonneveld few years ago and although it was building most of games did not run at all. I don't think there is a big demand for it either.

**Comment by ericoporto** [comment]
Think I found a proper way to get the GL headers:

	git init gl_headers
	cd gl_headers/
	git remote add origin git@github.com:KhronosGroup/OpenGL-Registry.git
	git config core.sparseCheckout true
	echo "api/GL/*" >> .git/info/sparse-checkout
	git pull --depth=1 origin master
	move api/GL/* .
	rmdir /S /Q api .git/

@morganwillcock , in your script, is there a reason for prefering the 32 bit version of git and 7-zip?

Also I think in the end, that Azure is probably the best choice for building AGS, I believe the packaging part that deals with versions and things will be manual, and Azure offers pipelines with pretty good controls.

**Comment by morganwillcock** [comment]
>PSP is very low priority to be honest. I recall we were trying this out with Nick Sonneveld few years ago and although it was building most of games did not run at all. I don't think there is a big demand for it either.

I did find all the relevant bits but it seems that changes over the last few years mean that it doesn't work with the older version of GCC that is used for the PSP build environment.  Presumably there is no easy way to switch things like pointer types?

>@morganwillcock , in your script, is there a reason for prefering the 32 bit version of git and 7-zip?

It assumed that the OS being used was 64 bit, so using 32 bit versions meant that it only has to check in one place in the registry to see if the application is installed.

>Here is my first attempt trying to understand, building ags with Morgan's script on AzureDevOps.

If I open a PR, do you know if this would this also trigger a build?

**Comment by ericoporto** [comment]
@morganwillcock open a PR and we will find out :D (maybe I have to configure something there too, but easier to findout by trying!)

**Comment by ivan-mogilko** [comment]
> Presumably there is no easy way to switch things like pointer types?

Do you mean C++11 features, smart pointers like shared_ptr/unique_ptr? I definitely would not like to abandon these, that would be a step back. Writing our own implementations or using some library could be an option if you really want to support this platform, but frankly I would not like to spend my own time on that.

**Comment by morganwillcock** [comment]
Yes, it was the change to newer pointer types that stopped it, as far as I know. To be honest I only hoped to build it, to then raise the question of removing the port entirely for AGS 4, so perhaps this points to the answer.

**Comment by morganwillcock** [comment]
> @morganwillcock open a PR and we will find out :D (maybe I have to configure something there too, but easier to findout by trying!)

I think this will have to be split into different parts rather than run everything in the batch file, because it looks like no environment variables are set to build directly, and it probably has to go via one of the 'Tasks' such as [this one](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=vsts). This would mean the same setup can't build anything locally (since this would become a settings file for the build service), but trying to maintain something custom that works in both places is probably going to be a bad time.

**Comment by ericoporto** [comment]
We need to build some stuff in the C++ world, and some stuff in the .NET Desktop world. Azure Pipelines use the sam .Net Desktop environment for building both - [from the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/cpp?view=vsts). So this is solved.

I think we have should separate getting dependencies (allegro comes to mind) and dependencies that we won't be getting but will write about in the README (git,some VS tools). Of those that we will assume the reader finds a way to get, we will insert YAML entry in the pipelines if needed, but looking the available tasks, it will probably be easier to batch script this part - since I think this is pretty much already scripted.

Now a different task, building allegro - we could just get this prebuilt once a new release comes out, but looks like it's easier to integrate. (Visual Studio Build)

Another task, building the AGS engine. (Visual Studio Build)

And another task building AGS Editor. (Visual Studio Build)

We will probably be using either [Visual Studio Build](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=vsts) or [MSBuild](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=vsts).

Here is another thing, a repo CAN have multiple azure pipelines (have Android builds, which is possible through Azure), useful if a single pipeline becomes to confusing to maintain or has a limitation. I think they can also be serialized - for instance the Linux build be available to be distributed with the AGS Editor. To send binary data between pipelines, it can use internally Pipeline Artifacts.

**Comment by morganwillcock** [comment]
Is it best to just build allegro and alfont independently then, and then try to download the latest build from some kind of storage? On the newest run it looks like allegro did build but alfont did not.

**Comment by ericoporto** [comment]
We can get directly from Github Release - I think this [PR](https://github.com/adventuregamestudio/lib-allegro/pull/3) maybe will solve this. :)

**Comment by ivan-mogilko** [comment]
> We can get directly from Github Release - I think this PR maybe will solve this. :)

Oh shoot, I somehow missed that one...

**Comment by ericoporto** [comment]
No worries, just a reminder. I didn't said anything before, because I was also hopeful that lib-allegro would get a new release when the patches were merged :O

**Comment by ivan-mogilko** [comment]
> I didn't said anything before, because I was also hopeful that lib-allegro would get a new release when the patches were merged

So, probably there will be some progress soon: https://github.com/liballeg/allegro5/pull/972#issuecomment-450089246
we may wait a bit more if it's okay.

**Comment by ericoporto** [comment]
We still need to build and provide binary releases for alfont - since we are the first result on Google for it, I don't think someone else will.

**Comment by ivan-mogilko** [comment]
@ericoporto were you able to build alfont?

**Comment by ericoporto** [comment]
Unfortunately I am driving all day today, but I have previously built it for Linux, MacOS and Android I think :D. I never built for Windows, I think I used one you or someone else provided me when I need. :O

**Comment by ivan-mogilko** [comment]
@ericoporto , as far as I remember you need to build alfont for anything but Windows, because AGS includes full patched alfont source for non-Windows ports: https://github.com/adventuregamestudio/ags/tree/ags3/Engine/libsrc/alfont-2.0.9

And this is mentioned in makefile-objs: https://github.com/adventuregamestudio/ags/blob/master/Engine/Makefile-objs#L62

**Comment by ericoporto** [comment]
I didn't knew libalfont was just for Windows. I have forked, to provide Windows builds for it, but couldn't figure out how to build that. 

The problem with building on Windows was that the build on Azure failed for lack of v100 build tools on alfont. I haven't tested on AppVeyor. Azure seems to build faster then AppVeyor, but I had trouble with Azure documentation.

I also am ridiculously bad at Windows - I could never actually build AGS for Windows. What I was using was a script @morganw provided that appears to just work - on AppVeyor, but it didn't work on my Windows machine.

Doing the TravisCI for Linux build is something I can do since it's easier - requires apt install dependencies and a make on engine directory. And I already do it to provide the Snap AGS build, but in this case the actual binaries are built on Canonical cloud to provide arm binaries too.

I have a forever waiting pr on the allegro repo to get allegro pre-built too - for Windows, it's needed. 

Also there are some googletests I don't know yet what they are used for.

Life would be MUUUUUCH easier if Github Releases had actual binaries, so we could build one repo on the binary of the other - and build times would be a lot faster. Github supports up to 2GB binaries per file and it's never down.

**Comment by ericoporto** [comment]
Wrote [a small guide on Travis here](https://github.com/adventuregamestudio/ags/issues/628). Still need to figure out the appveyor part for Windows builds, which will be a little more complex.

**Comment by ericoporto** [comment]
Appveyor, Azure Pipelines, TravisCI, and CircleCI here

https://github.com/ericoporto/ags

**Comment by morganwillcock** [comment]
Just to reiterate, the script was meant to run on a complete empty Windows VM and download and install all required parts (taking the path of least resistance, e.g. using vcpkg) so there are likely some shortcuts it can take and places where it needs to be more efficient. For instance, if we could host some of the downloads somewhere I'd feel happier about it repeatedly hitting servers to download things on every commit.

Some of the parts could be available in Chocolatey too, which might still just be external downloads, but the responsibility is then moved to the package author.

**Comment by ericoporto** [comment]
Erh, to reiterate my idea then, we could have a script hosted in a repo like, ags-win-env, where the Github Release is the binary produced by this script, which would be a big zip file with all the dependencies packed. And then the script would get the env from this Github Release, which theoretically would be downloaded faster.

**Comment by morganwillcock** [comment]
Hopefully this is temporary, but the system that bootstraps the old Debian releases won't function at the moment. I've just found I have similar problems when trying to update existing installations.

https://lists.debian.org/debian-mirrors/2019/03/msg00009.html

**Comment by morganwillcock** [comment]
This is now re-implemented on one provider where build artifacts can be downloaded by subsequent tasks, and the majority of dependencies are pre-built and cached in Docker containers:

https://cirrus-ci.com/github/adventuregamestudio/lib-allegro
https://cirrus-ci.com/github/adventuregamestudio/ags

It should be able to upload a release. The only part missing is the Android build, but I am unable to build this locally (following the existing instructions). So I'll close this now, since there is now build sequence for everything that I consider functional, in every build configuration that I could specify.
