### ISSUE TITLE
Linking anything against allegro-4.4.2 fails on linux with gcc-5.2.0 [solved]

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#534]
Really simple patch needs to be applied on lib-allegro, or build will fail on newer gcc on Linux. I'm adding here since lib-allegro has no issue tracker.

[50_fix_get_value_gcc_5.patch.zip](https://github.com/adventuregamestudio/ags/files/2621848/50_fix_get_value_gcc_5.patch.zip)
```
--- a/addons/jpgalleg/src/decode.c	2008-02-13 14:04:57.000000000 +0100
+++ b/addons/jpgalleg/src/decode.c	2015-09-03 14:57:57.888485546 +0200
@@ -477,7 +477,7 @@
  *  Reads a string of bits from the input stream and returns a properly signed
  *  number given the category.
  */
-INLINE int
+static INLINE int
 get_value(int category)
 {
 	int result = get_bits(category);
```

source: https://sourceforge.net/p/alleg/bugs/398/

**Comment by ivan-mogilko** [comment]
I will add an issue tracker in lib-allegro of course.

Is this patch applied to the head of the 4.4 branch in their official repository? I deliberately chose to branch off the 4.4.2 tag being wary of any new compatibility issues, but we may as well advance our patched branch to theirs if its worth it.

**Comment by rofl0r** [comment]
interesting. i've built both allegro 4.4.2 and ags without issues using GCC 6.4.

**Comment by ivan-mogilko** [comment]
There is this comment from library maintainer:
> I applied the patch to the 4.4 branch on GitHub. Please direct any bug reports/comments to GitHub from now on.

Could you clarify, what repository/branch are you building exactly?
Perhaps we simply need to update our fork.

**Comment by ericoporto** [comment]
The patch is just addition of the keyword `static` in a specific variable in a specific file.

I needed on my computer but I don't need it on Travis - but they are the same version of things, so why? I don't know, but it's a known bug with easy fix. 

I use the same ags patch branch as is configured as main on the fork. I just found the patch on allegro issue tracker.

**Comment by ivan-mogilko** [comment]
> I use the same ags patch branch as is configured as main on the fork

The thing is that the ags-patch branch is meant for Windows version only, it was never meant for other systems.

**Comment by ivan-mogilko** [comment]
Only to clarify my stance here, this 'allegro-4.4.2-agspatch' is something I *had* to do specifically for the Windows version of AGS, because it required certain changes inside the library for historical reasons. I may find a ticket that explains this later.

Ideally I think we should be using offical Allegro repository whenever possible. I was sending them few patches over time that AGS also needed (the ones that were generally useful) and they have them in 4.4 branch already. Those specific changes I mentioned above are mainly for old plugin support, and in theory AGS 4 (which drops it) may already use main library repository instead.

**Comment by ericoporto** [comment]
>I guess most Linux users who compile programs for themselves still use official library repository?

https://github.com/ericoporto/ags-snap/blob/master/snapcraft.yaml

Since I didn't knew about that I just build using the patched lib-allegro for distributing on Ubuntu :/

**Comment by ivan-mogilko** [comment]
Well, the readme for Linux never mentiones using our own repository, it was really a compelled measure, and mostly for Windows.
I found the ticket that explains things: #388
On a side note, there is a separate branch for Android patch called allegro-4.4.2-android, but it is not used directly as of now, instead there is a *.patch file created from it in the Android/ dir.

**Comment by ivan-mogilko** [comment]
Alright, to sum up related information, since there are new contributors who may not be aware of this.

1. There was a number of changes that had to be done to Allegro library for AGS. These changes may be divided in general (suitable for all library users) and AGS-specific (required to keep compatibility with plugins that used DirectX on Windows).
These changes were originally done by Chris Jones, and the reasons for them are explained in notes to following tickets:
#383
#388

2. For those general changes I've made number of patches to the main Allegro repository, you may find some my commits in their recent 4.4 branch:
https://github.com/liballeg/allegro5/commits/4.4

3. The AGS-specific changes for Windows build were not needed in the main library version, so I made our own liballeg fork and branch to add our patches there. This branch is based of 4.4.2 tag.


Now, here comes the issue with Linux build which is still not resolved properly. I am not a very experienced Linux user, but my impression was that on Linux people prefer to get official library distributives, or checkout and build from official repository. The thing is that although I sent necessary patches to Allegro, they are still not included in any actual official release. Latest formal release is still 4.4.2 (several years old). If you use that, my patches won't be yet included.

For that reason I tried to make AGS engine to work without them. For example, there is [this commit](https://github.com/liballeg/allegro5/commit/b01e2b58ca154538b1cc2d296d7bd48c7f6fbb9e) that adds load_midi_pf function to Allegro. I had to duplicate the function in AGS for the time being: https://github.com/adventuregamestudio/ags/blob/master/Engine/libsrc/allegro-4.2.2-agspatch/midi.c

In another case there was [second function I had to write](https://github.com/liballeg/allegro5/commit/57996ace03e504c5c2a6ffdb9a7198a2c83b92ac) - play_fli_pf. At first I thought I could also duplicate it in AGS engine, but the amount of code I'd need to copy from the library was big, so I was reluctant. Here is the related discussion: #407
To clarify: this means that if you make Linux build using Allegro 4.4.2 tag, then FLIC playback won't work as expected.

This situation is rather ugly. I hoped there will be a new Allegro 4.4.* release made after a while, but it still not happened. So, I am open for suggestions how to proceed from this point.

**Comment by rofl0r** [comment]
sounds like it makes sense to lobby allegro maintainers in producing a release then, but only after all of your improvements have been merged.

**Comment by ivan-mogilko** [comment]
> sounds like it makes sense to lobby allegro maintainers in producing a release then, but only after all of your improvements have been merged.

I've just got the very last patch merged to their branch, and asked about possible releases. This is what their maintainer answered:
https://github.com/liballeg/allegro5/pull/962#issuecomment-445512802

**Comment by rofl0r** [comment]
wow that's good news, and a little bit `o.0` about them having lost their release scripts.. :)
but i guess it could be a quite fulfilling task into helping them, as a new allegro 4 release is probably highly anticipated from several communities.

**Comment by ericoporto** [comment]
if patches are merged, the only trouble is building the library from source as it was done before for the patched version. I think this can be closed.
