### ISSUE TITLE
ColourWise: text window borders stay on screen during fade-out

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#54]
This bug only occurs when using 3D renderers (Direct3D, OpenGL).

Found in versions: 3.1.1 - 3.6.0.

When the fade-out starts right after text window was displayed (e.g. during room transition) the middle of the text window is removed, but the borders stay on screen. This looks confusing, like the contents of the window turn transparent, but its actually the borders that failed to be removed, or maybe the part of the screen is not repainted properly. If you run original game, it could be noticed, that text windows are removed a moment after fade-out starts.

Easiest way to reproduce: start any level and press SPACE to restart. The message "One more time" appears before the level reset. Click mouse or press any key, and observe the issue.

**Comment by ericoporto** [comment]
There's a chance this was fixed already.

**Comment by ivan-mogilko** [comment]
I tested it few months ago and it is not.

**Comment by ivan-mogilko** [comment]
The only explanation I have for this bug (not tested yet, but I am fairly certain it may be the case):
* Direct3D and OpenGL renderers put sprite stack on screen, and this sprite stack is updated each frame.
* The exception from above is when it does blocking room transitions, in this case it remembers last frame's stack and puts on screen over and over again while fading it out.
* Supposedly for some reason the text window's frame stays in that stack, but somehow the middle section does not.
* OR, the middle section's z-order gets it below fade effect (not sure if may be a case).

**Comment by ivan-mogilko** [comment]
I just wanted to get to the bottom of this, and finally did it, 9 years later (consider me crazy).

So, it's not a mistake of 3D renderers at all, but a mistake of software renderer + imperfect game scripting.

The "text window" in question is not a single object, but two (or more objects): the main part with the text is an overlay created with DisplayAt, while the borders are not the part of the same overlay, but a separate GUI with a hole or black rect in the center. Why it's done so is a mystery, but guess the game authors had their reasons.

What happens in reality is that as player clicks, the text overlay is removed, but script does not remove the GUI, leaving borders in place. Then comes the room transition (fadeout). So, 3D renderers do everything correctly, it just looks wrong because it's not scripted well.

The thing about software renderer is that somehow it misses one final screen refresh before the fade-out. So when fade-out comes, it still has the already removed overlay drawn over the virtual screen.

So, really, what should be fixed is software renderer that does not redraw the screen in the case when the blocking message is followed by fadeout or room transition. Which is a completely separate issue.
