### ISSUE TITLE
AGS 3: support recreating sprites that were imported from clipboard

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#542]
This is related to the problem of sprites (among few other things) being stored in a binary blob (#463) which makes it difficult to treat them individually under source control.
#526 has made it possible to recreate/reimport tiled sprites from the source. Now AFAIK the only problem remaining is sprites imported from the clipboard. Such sprites do not leave any actual source behind so if compiled sprite pack is lost they also cannot be restored.

The only solution that comes to my mind is to generate bitmaps in a certain directory inside the game project and link these as import sources to the new sprites. Or maybe even create them first and import them normally as if they were chosen in the import dialog.

What's required for this:
1. Define directory name and bitmap naming convention.
2. Run bitmap export after sprite is imported from clipboard.
3. After bitmap(s) are successfully created, link them to the new sprites.

Questions:
* If user does tiled import from clipboard, should we save full image or only individual tiles?

See Also: #1281

**Comment by morganwillcock** [comment]
> 1. Define directory name and bitmap naming convention.
> 2. Run bitmap export after sprite is imported from clipboard.
> 3. After bitmap(s) are successfully created, link them to the new sprites.

You could potentially do this manually after import. If there will be a function to export the entire sprite cache to disk, one of the options on it could be 'export all sprite which have no source file', with a second option 'set exported files as source'. This way you don't need to pick a specific directory and everything would align with how the other sprites are managed, you would only need pick a filename format for the export process itself. Tokens for all the data retrievable from the spritecache would probably do:

e.g. "%spritenumber%_%width%x%height%.%format%" exports as "120_320x200.bmp" for sprite number 120 that is 320px wide and 200px tall.

Also, those tokens could then be used anywhere in the path (so sprite number could be created as a directory, for example).

> If user does tiled import from clipboard, should we save full image or only individual tiles?

The reload for tiles would expect the full image as the logic is just a rectangle generator, unless there was metadata available that described the image. But if storing metadata, it is probably better to define the spritesheet selections for the full image rather than identify a piece of an image.

**Comment by ivan-mogilko** [comment]
> You could potentially do this manually after import. If there will be a function to export the entire sprite cache to disk, one of the options on it could be 'export all sprite which have no source file', with a second option 'set exported files as source'.

What I wish the editor to do is a uniform sprite handling where every sprite is stored similarily no matter where it came from. The idea was to gradually move to having sprites on disk as a primary source rather than the packed sprite cache.

If the sprites from clipboard would require manual export to create sources on disk, then, first of all, that would mean that some sprites are disconnected from this system, and secondly, that would put extra burden on users who would need to remember doing this operation every time if they are, for example, using source control.

We may perhaps combine the solutions and on one hand have an export operation which you suggested that users may call from menu, and on another hand call this operation automatically when sprites are imported from clipboard.
Maybe have an option to turn this automatic action on and off (not sure if that's a good idea), or an option to set the directory where the sprites will be exported automatically.

In any way the final goal is to make sprite cache "unnecessary" for the game project and only a part of compilation.

**Comment by morganwillcock** [comment]
This isn't just for sprites that are pasted from the clipboard, anything which came from the previous spritesheet import will have no source, and it may be that any sprite's source file may no longer be present. So this is for 'recreating sprites', not for importing from scratch.

I'm not sure how importing would work in some future version, but if primarily interested in things being on the disk, and these things may be source control, does it make sense to keep the ability to paste images? If it prompts for a save path it would be safer to export to disk in the program where the image is coming from, if it is automatic it isn't going to align to existing sprites locations (since there are currently no restrictions).

**Comment by ivan-mogilko** [comment]
Oh, I understand what you mean now. Yes, fixing sourceless sprites from the old projects is important and I wanted to open a separate issue for that but forgot. This particular ticket is dedicated for importing sprites in the new editor.

So, the first question is whether it makes sense to keep import from clipboard then.
I don't know if many people use this, personally I find it convenient to quickly import some mockup sprites when did not want to bother saving them in files first. Hmm, and also maybe I found it easier to cut out a sprite in a paint program than in old sprite import window.

**Comment by ivan-mogilko** [comment]
> If it prompts for a save path it would be safer to export to disk in the program where the image is coming from, if it is automatic it isn't going to align to existing sprites locations (since there are currently no restrictions).

My thinking was to set up a path to a subfolder inside project folder (like "_Sprites" or whatever) and maybe let users configure this. Naturally that won't align if users keep regular sprites somewhere outside, but I thought that will be their own choice. Those who use source control and/or work in teams perhaps store sprites in project subfolders anyway now since editor keeps relative paths for these.

**Comment by ivan-mogilko** [comment]
I guess we won't (or should not) have any big changes to sprite storage in the project until #1281, which should address this issue as well (or forbid pasting from clipboard).

The only idea that i have, about making an easier workaround, is to add a menu command "Export sprite to file and make new source", which would export the sprite to the file on disk and then set that new file as a source reference; thus allowing to restore the sprite in case the acsprset.spr would be deleted.

**Comment by AlanDrake** [comment]
Might not be necessary, although not as convenient it's already possible to export and manually point to the sprite files.
The open format will solve all of it in one fell swoop.

**Comment by ivan-mogilko** [comment]
Forgot to mention, the alternative command idea is "Save all sprites without sources...", where you point to a *folder*, and then all sprites without sources will save there and link to files on disk. Then user dont have to scan sprites for this, and this works as a quick fix for the project.

**Comment by AlanDrake** [comment]
I won't stop you. It is a useful feature for rebuilding the cache , after all.
Personally, I'd go with the user triggered option.

**Comment by messengerbag** [comment]
> Forgot to mention, the alternative command idea is "Save all sprites without sources..." (or "sourceless sprites")

Would this also check the file references to see if they are valid? (And recreate them/change the reference if not.) If so, that would be quite useful. If there was also an option to include all file sources with absolute file paths (whether or not they are valid) and change them to point to a copy on a relative path inside the project, it would be a complete solution for converting projects to the future open format.

**Comment by morganwillcock** [comment]
I think that the current export has a checkbox to skip exporting sprites where a file exists at the source path, and has an option to rewrite the source path to point to the export files, so recovering just the files with missing source paths is something the existing functions can do.

https://github.com/adventuregamestudio/ags/blob/1d321947974e7a94aafd2cafd0283af0b09c487d/Editor/AGS.Editor/Utils/SpriteTools.cs#L460

The user interface on the exporter is not good though.

**Comment by ivan-mogilko** [comment]
> I think that the current export has a checkbox to skip exporting sprites where a file exists at the source path, and has an option to rewrite the source path to point to the export files, so recovering just the files with missing source paths is something the existing functions can do.

Ah. So, this is already present then.
![spriteexport](https://user-images.githubusercontent.com/1833754/166560618-e365290d-8eeb-48b2-b513-a0e59de3498e.png)

So, checking points from @messengerbag 's proposal -
> Would this also check the file references to see if they are valid?
- Yes; it does test not only the presence of source property, but tests whether the file itself present on disk.

> If there was also an option to include all file sources with absolute file paths (whether or not they are valid) and change them to point to a copy on a relative path inside the project, it would be a complete solution for converting projects to the future open format.
- No, this may be added then.

**Comment by ivan-mogilko** [comment]
BTW, i think i found a bug: when the Export updates source link, it does not append extension to the path, making it impossible to restore from source from this point on.
