### ISSUE TITLE
Steam overlay in Windows sends clicks to game in background

### ISSUE THREAD

**Issue by vga-256** [adventuregamestudio/ags#557]
Witnessed some interesting behaviour with monkey0506's steam plugin. 
In Linux and Mac (both running different OpenGL implementations) when a game is running in Steam, and the overlay is loaded, the overlay captures mouse clicks correctly and does *not* forward the clicks to the game running in the background. This is correct and expected behaviour. (The only strange that is that the in-game mouse pointer follows the overlay mouse pointer, but that's something I can live with).

In Windows - both in Direct3D and OpenGL mode - the game running in the background captures mouse clicks intended for the Steam overlay. E.g. clicking on a friend's name in the overlay can accidentally trigger an in-game menu item.

**Comment by ericoporto** [comment]
https://partner.steamgames.com/doc/features/overlay

either [IsOverlayEnabled](https://partner.steamgames.com/doc/api/ISteamUtils#IsOverlayEnabled) (easier) or [GameOverlayActivated_t](https://partner.steamgames.com/doc/api/ISteamFriends#GameOverlayActivated_t) (harder because I think plugins can't create events) could be added to monkey's Steam Plugin to provide an interfaces to check for the overlay and pause appropriately.

**Comment by ivan-mogilko** [comment]
You actually can send events (sort of) from plugin using CallGameScriptFunction and QueueGameScriptFunction, which of course implies that there are such functions in script to receive the "message".

Would not it be ideal if the engine itself paused the game completely in this case, not relying on game script? If only there was a way to tell it somehow.

**Comment by ivan-mogilko** [comment]
This is a very old report, I think we should ask users to retest this with the newest engine (3.6.0 and later) to see if this is still an issue. @vga-256 , can you do that?

Then decide whether this is a engine's problem or plugin's problem; is it even possible for plugin to intercept events, etc.

**Comment by ericoporto** [comment]
This doesn't happen anymore but the `shift+tab` overlay in Steam has changed a lot since, so not sure if it's ags or steam that changed. I did test with my game and only on Windows.

The result is that using until 3.5.x releases, the mouse movements doesn't pass to the background but clicking does, you can leave the mouse in a position with a button, hit `shitf+tab` to bring the overlay and click to see it go through.

Now using 3.6.x releases, again mouse movements doesn't pass to the background but now clicking also doesn't pass.

So, from my tests, this is fixed. Tried until the latest 3.6.1 release.

**Comment by ivan-mogilko** [comment]
Okay, I will close this, don't recall hearing about this problem in a while. It may be reopened or new ticket created if it appears again.
