### ISSUE TITLE
3.5.0 engine's Windows XP support

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#558]
As we switched to VS2015 and using v140 toolset when building Window version of the engine (that makes engine depend on Windows 8 SDK), Windows XP can no longer run AGS engine (and compiled games).
This may be fixed by switching to v140_xp toolset, that will make engine use Windows 7.1 SDK which is still compatible with XP.

Apparently modern versions of Windows may still be able to run the engine built with v140_xp. But I do not know if that will rise any compatibility issues in the future.

I think possible options here are:
1. Switch to v140_xp toolset completely and stay there unless something goes wrong;
2. Build a separate configuration with v140_xp toolset and ship it with the AGS as "acwin_xp.exe" like we did with "no mp3" version. We may even implement a separate "Build target" in the Editor for convenience.
3. Drop Windows XP support for **games** made with AGS 3.5.0 and higher.

**Comment by morganwillcock** [comment]
Since there is also v141_xp for the newer build tools, and Win32 programs tend to keep working, probably option 1 unless there is something that actually works differently?

**Comment by sonneveld** [comment]
I suggest we drop Windows XP support. It's no longer a supported operating system.

We have to draw the line somewhere, and it's better for us if we can use the latest Visual Studio tools. (which target Win7 and up)

**Comment by SuperDre** [comment]
I would also suggest dropping Windows XP support. People should really upgrade to (at least) Windows 7 or higher or just move to Linux. Microsoft has ditched XP already for a long LONG time, and you cannot expect developers of new games to keep those few people  in mind who still want to run XP. Has anyone actually tested if the build with v140 doesn't run on XP? Same also applies to other older OSses which has been superseeded by many already (ofcourse if there's a problem). If people really want XP support, let them fork their own version and keep it running themselves. But then again, if using v140_xp makes developing newer versions not even the slightest more painfull, and with it it still runs on XP without any adjustments or needing to keep track of things, then ofcourse it's also an option (but again, you can always leave it up to someone to fork it and create a version for XP).
So IMHO I agree with Sonneveld, drop support for an OS that's not safe anymore and not supported by the creator (and let's not forget, they still have an older version of AGS that works with their OS).

**Comment by rofl0r** [comment]
even though XP is no longer supported by M$, some people still need to use it or its API, for example people using reactOS, which targets compatibility with windows 2003 server (roughly identical to XP). when i recently tried out reactOS, i was amazed how well it works, and on the other hand appalled that i wasn't able to get a **single** modern browser working on it, because they all dropped XP support due to similar reasoning than above 2 comments.

**Comment by morganwillcock** [comment]
To clarify my position, I'm saying keep support if it is trivial to do so, otherwise drop it. Windows 7 is about to become unsupported (9 months to go) so matching OS support to the tool-chain seems pretty reasonable, especially now that Windows is effectively on a rolling upgrade model. I'd also worry that mandating the old API might get games rejected from store submissions, if API access is provided by a sandbox.

**Comment by ivan-mogilko** [comment]
Hmm looks like we decided to stick with standard v140 toolset.

I made another test just in case, and confirm that it's still _possible_ to build XP-compatible engine using v140_xp toolset. Therefore in case of need we may build it as an alternate engine version specifically to run on XP.
