### ISSUE TITLE
add the option to start animation at any frame of the loop

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#560]
at the moment the Animate command resets the animation. SetView lets you set a frame from a loop but then starting the animation with that loop leads to stuttering when the loop jumps to frame 0.

**Comment by selmiak** [comment]
expanding on that, I mean adding a "frame" property to Animate, but then when a specific frame that is not 0 is set within SetView then Animate without that property set should start from that frame set in setview.

**Comment by ivan-mogilko** [comment]
I guess this means adding 1 argument to Object.Animate and Character.Animate functions, e.g.:
Animate (loop, frame, ...other params...).

Besides that, maybe investigate if it's worth to bring these functions to the similar argument list with Button.Animate, which lets you set view as well. (Not sure about this tbh, since characters have special rules about Views).

**Comment by selmiak** [comment]
okay, thinking about it, it would be better to set the starting frame with SetView and maybe a final argument for Animate that is eReset or eContinue to say start from current from of the object or reset to frame 0 of the loop.

**Comment by ivan-mogilko** [comment]
> after some thinking about it, I think it would be better to set the starting frame with SetView and maybe a final argument for Animate would be needed that is eReset or eContinue to say start from the current frame of the object or reset to frame 0 of the loop.

My thinking is that "frame" argument in Animate() would be more universal:
* if you want to reset you pass 0,
* if you want to continue from current one you pass Character.Frame,
* if you want to begin from any random one, you pass that number.

**Comment by ivan-mogilko** [comment]
> Hard to say what is best. That's why I suggested adding this with the setview. But this tears it apart some more, also not good.

The thing about SetView's loop and frame parameters is that they were not really meant as a starting point for Animate. It is rather a coincidence that SetView function is used for 2 separate purposes: to set a view before animation and to set certain static frame as a new object's sprite.
If you compare with character's functions, there you have to call LockView which only set "view" but not "loop" or "frame" (these may be locked too but with different functions like LockViewFrame).

If we make Animate follow SetView's frame, then more questions arise: what's the point of having "loop" parameter in Animate (we could also use one from SetView), and more importantly why we have to call 2 functions every time to start animation from particular frame instead of just 1?

The way to place a new parameter in Animate is non-trivial problem of course; currently I don't see other option than to create a new function where frame is not optional. The previous function is either left (then the new one needs to be called differently, like AnimateEx etc), or called deprecated and only available in backwards compatibility mode.

**Comment by ivan-mogilko** [comment]
Hmm, I wrote a reply here first, but then realized I am missing something about how Animate may be used in practice if started from random frame, so I need to think more about this.

> (btw that manual entry makes me wonder if repeatstyle for button.Animate is optional or not?)

No, it's not optional, maybe an oversight. Also, blocking style and direction are not supported in the Button either. I think it may be a good idea to add at least direction there.

**Comment by ivan-mogilko** [comment]
A shame this did not make it into 3.5.0, because this would be _trivial_ from technical perspective.

The only issue here imho is choosing a good API, that is - where to place this parameter. Personally I was leaning to placing frame in the middle after "loop", as selmiak noted in his last comment above:
> the most logical place to put this would be behind loop, like
(int loop, optional int frame, int delay, ...)

but indeed that would require either make delay optional as well, or shift frame further to right along parameter list.

But another issue with new parameter is that it makes it hard to maintain backwards compatibility. Unless new parameter is _last in the list_ it will break all the old scripts.

There's actually an alternative to just add another function, e.g. called AnimateEx or AnimateFrom.

**Comment by ivan-mogilko** [comment]
Done by #929
