### ISSUE TITLE
Audiofiles: Add Length Property to Properties in the editor

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#566]
right under the source file name would be a good place to show this info.

**Comment by morganwillcock** [comment]
I had a look at some of this today:

- when using irrklang I couldn't find a way to validate the file before returning any information. If you import an image with an mp3 extension it still presents valid format data, but it just doesn't play (although even the lack of playback doesn't occur fast enough to check validity immediately after playing, although the logic will be correct with a breakpoint inserted)
- because the AudioClip class is outside of the editor project, it is difficult to get the length into the property grid, and data like clip length probably shouldn't be serialised to be loaded from elsewhere

So overall, this doesn't seem trivial to change and I'd probably point it (in my opinion) as an example of something I think is handled better with a 'project browser' that is interested in what is on the disk, and handing off to an actual audio tool.

**Comment by ivan-mogilko** [comment]
> because the AudioClip class is outside of the editor project, it is difficult to get the length into the property grid, and data like clip length probably shouldn't be serialised to be loaded from elsewhere

The serialization may be prevented using attribute `[AGSNoSerialize]`, and I'd suspect that the property itself set by the Editor when the clip is opened for a preview.

**Comment by ivan-mogilko** [comment]
Probably resolved by #1966
