### ISSUE TITLE
add icon to the github organization

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#570]
Hey guys, [bakudas](https://twitter.com/bakudas) did this icon of the AGS Big Blue Cup that I really liked.

![bluecup_icon](https://user-images.githubusercontent.com/2244442/50565896-dd065000-0d1a-11e9-9ae5-af6b8e87674a.png)

[bluecup_icon.zip](https://github.com/adventuregamestudio/ags/files/2718794/bluecup_icon.zip)

I think it's just perfect for the [github organization page](https://github.com/adventuregamestudio).

**Comment by morganwillcock** [comment]
I guess it depends if it would just be for here, or used everywhere. Or to phrase the question differently, if AGS suddenly acquired a new logo that everyone liked, would people want to replace this one with a new one?

For just here, I think this one is fine, but the shape might be too complex to use everywhere (as a general logo) as the cup handle might not work too well when scaled down (at least, when I tried with my limited skills and GIMP, the scaled gradients and handle didn't mix too well because of the lack of contrast).

**Comment by selmiak** [comment]
I made some variant. Seems like I can't upload to github for some reason, here is a link?
https://i.imgur.com/rxn0jci.png
https://drive.google.com/open?id=1n5I2GGycSA9bK3Sk2K1A6qdeel3v95ho

**Comment by ivan-mogilko** [comment]
For some reason I tend to agree with people who suggested to use pixelated "low-res" style icons for ags, because it's more in line with its roots and history.

Also, I agree with @morganwillcock in the sense that we have too many different icons in this project. Editor has a newer one since 3.4.0, windows engine has another (older 3.0 style), this is going to be the third one.

**Comment by morganwillcock** [comment]
I'd also say that having a 3D style icon for a 2D game engine is a little misleading. There is also the issue of the text / font, having a nice cup doesn't help too much when you also need to write the program name.

Perhaps the thing to do is to hold some kind of contest for a logo and logo +  text, as a vector, and with bitmap variants for all common resolutions. It wouldn't have to literally scale for all sizes, just have an equivalent logo.

As an example, here is the vector Wintermute logo:
https://en.wikipedia.org/wiki/Wintermute_Engine#/media/File:Wme_logo_small.svg

And here is a low resolution variant that someone made for their Kickstarter video:
https://www.kickstarter.com/projects/1988474932/foxtail?ref=video
![wintermute](https://user-images.githubusercontent.com/14958747/52440505-36318280-2b16-11e9-9f7b-2441ddf61923.png)

**Comment by morganwillcock** [comment]
As a experiment of what works when scaled and what doesn't, I used an online logo generator and then scaled the images down and up (in bulk, so this probably looks worse than it needs to). I don't know if this is useful, but I thought I may as well show someone.

![test_joined](https://user-images.githubusercontent.com/14958747/52669154-4b8b2000-2f0d-11e9-8f97-d54610ae4324.gif)

**Comment by ericoporto** [comment]
![square_bluecup_x8](https://user-images.githubusercontent.com/2244442/52673227-2d222600-2f07-11e9-8c31-ef0529759860.png)
![square_bluecup_x4](https://user-images.githubusercontent.com/2244442/52673234-301d1680-2f07-11e9-982e-aa70f1eb11be.png)
![square_bluecup_x2](https://user-images.githubusercontent.com/2244442/52673238-327f7080-2f07-11e9-8316-a299c7526c4d.png)
![square_bluecup_x1](https://user-images.githubusercontent.com/2244442/52673240-34493400-2f07-11e9-8e31-fbcb479c62a2.png)

Remade the square cup as a pixelart and took some liberties with it :]

**Comment by selmiak** [comment]
that's a nice collection of blue cups you have there! :)


You forgot about the favicon of the website, but this is the cup from ags-manual template html template with a white outline ;)

I like the very last, the forum icon the most. For people coming from the forums this heap of pixels is like a familiar face to greet them, I'd use that for familiarity, consistency and kind of streamlining things.

**Comment by rofl0r** [comment]
i like these 2

![1](https://user-images.githubusercontent.com/2244442/52677915-f48a4880-2f16-11e9-86f2-e21a0561348b.png)

![2](https://camo.githubusercontent.com/bd5a5e8aefeb8239771d5fe69ca3e4ca3710bff1/687474703a2f2f7368617474656e2e736f6e6f7265732e64652f77702d636f6e74656e742f75706c6f6164732f323031382f30362f6167735f636c61737369635f6375702e706e67)

in the end, the latter is probably preferable due to it being a vector graphic.

**Comment by morganwillcock** [comment]
I'd say that the upscaled CJ cup is in a unique position, where you can do everything from a favicon to a large logo with it, but perhaps it isn't a clear enough depiction of a cup that the average person on the street would know what it was.

![eriocup](https://user-images.githubusercontent.com/14958747/53132827-f6808700-3568-11e9-939e-58a1b6fb37c3.png)

I do like this one too, and for website purposes this is already pretty complete. Maybe someone would be able to create a vector version that captured the same spirit, in-case someone needed a variant for their 4K AGS game, although because the shading is done with a checked pattern it should also upscale pretty cleanly as-is.

I do like the 'CI USER' cup too, although that is more for its slightly wonky charm.

**Comment by ericoporto** [comment]
![web_hi_res_512](https://user-images.githubusercontent.com/2244442/53138029-b23eb800-3563-11e9-8292-9f80fe2bdf2e.png)
![blue_tea_cup](https://user-images.githubusercontent.com/2244442/53138066-caaed280-3563-11e9-8692-da45da6574eb.png)
[ic_launcher.zip](https://github.com/adventuregamestudio/ags/files/2887311/ic_launcher.zip)

Ok, just for fun made an additional one inspired by the classic Tea cup with the AGS tea bag.

**Comment by ericoporto** [comment]
![web_hi_res_512](https://user-images.githubusercontent.com/2244442/53168879-75ea7680-35ba-11e9-9708-afa6de46b2ff.png)
 just fixed some pixels.

**Comment by rofl0r** [comment]
> just fixed some pixels.

that looks really nice, congrats

**Comment by morganwillcock** [comment]
Is the text for "Adventure Game Studio Engine" just drawn manually, or was this a font?

**Comment by ericoporto** [comment]
@morganwillcock it's a font: [MOTOI03x5r2 by MOTOIKenkichiC2012](www.pentacom.jp/pentacom/bitfontmaker2/gallery/?id=476).

**Comment by selmiak** [comment]
![cuppp](https://user-images.githubusercontent.com/22618469/53291753-9e3fc400-37b8-11e9-9ec9-a8edc817aca7.png)

just for the sake of completeness and to make the decision even harder, here is the cup used in the awards ceremony client for the animation on the big screen!

**Comment by ericoporto** [comment]
![splash-original](https://user-images.githubusercontent.com/2244442/53291808-0631e280-3798-11e9-8409-e80c42d0b014.png)

Well, here is another one then.

**Comment by selmiak** [comment]
let's distill the bluecupness out of them all

**Comment by selmiak** [comment]
![flat](https://user-images.githubusercontent.com/22618469/53292027-ca5d4400-37bc-11e9-8b1e-57f199616b4f.png)
![flat2](https://user-images.githubusercontent.com/22618469/53292030-cc270780-37bc-11e9-861e-3384ed70fbe0.png)

some more...

**Comment by ericoporto** [comment]
I think these are all the ones left in the current Editor. :stuck_out_tongue_closed_eyes: 
![ags_ico](https://user-images.githubusercontent.com/2244442/53292076-f3b9a800-379b-11e9-99ca-de15e9aaa8c0.png)
![ags_game_ico](https://user-images.githubusercontent.com/2244442/53292087-3d09f780-379c-11e9-95d5-87f018a63a89.png)
![menu_help_about_ags_over](https://user-images.githubusercontent.com/2244442/53292088-3f6c5180-379c-11e9-97f6-e5e6c42c0869.png)

**Comment by selmiak** [comment]
![flat3](https://user-images.githubusercontent.com/22618469/53305954-c64a2880-3887-11e9-9ebd-67ed1f175fcc.png)
wild idea

**Comment by selmiak** [comment]
![flat4](https://user-images.githubusercontent.com/22618469/53306320-ff849780-388b-11e9-9c74-378e631f0776.png)
refining...

**Comment by selmiak** [comment]
![flat5](https://user-images.githubusercontent.com/22618469/53307529-e08d0200-3899-11e9-88b2-86e886af4722.png)
what about this :)

**Comment by selmiak** [comment]
![flat5](https://user-images.githubusercontent.com/22618469/53308520-54330d00-38a2-11e9-9932-0fa50386ebfe.png)

what about this?

**Comment by ericoporto** [comment]
I like that @selmiak :smile: looks good too!

**Comment by selmiak** [comment]
thanks erio, took long enough to make...

**Comment by rofl0r** [comment]
wow, loading this thread takes ages every time... could we finally enter the voting stage? ;)
i'd suggest everyone gets to choose a single favorite graphics, and ivan's voice counts double or triple since he does most of the work here.

**Comment by ivan-mogilko** [comment]
So, which ones are even the valid candidates? there are so many above, including weird ones.

Ok, let's say, I choose this one for myself: https://camo.githubusercontent.com/bd5a5e8aefeb8239771d5fe69ca3e4ca3710bff1/687474703a2f2f7368617474656e2e736f6e6f7265732e64652f77702d636f6e74656e742f75706c6f6164732f323031382f30362f6167735f636c61737369635f6375702e706e67

The main reason that it looks like the merge of two generations, the modern background and pixelated cup is the original gfx from first AGS template games as far as I know.

Or, you may look at this with a self irony if you like: it's an engine that tries to become modern but has an old awkward code in the core.

**Comment by selmiak** [comment]
good that there is some movement in this now.

I like your reasons for chosing this one @CW 
As an artist I still want to add something of my own. Like the colors of my latest version with the old chris jones cup:
https://i.imgur.com/9pSoQtw.png

have fun :)

**Comment by morganwillcock** [comment]
Does anyone know of a font that will match this future-retro cup?
If this is the final choice I'll put it on the manual web page.

**Comment by selmiak** [comment]
how about this:
https://www.dafont.com/de/pixelade.font
https://www.dafont.com/de/04b-03.font

**Comment by ivan-mogilko** [comment]
Ok, I added icon.

**Comment by ericoporto** [comment]
Wuhu :D

**Comment by selmiak** [comment]
YAY!
