### ISSUE TITLE
change cChar.FaceDirection keywords

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#583]
I figured when typing and writing eDirectionLeft or eDirectionRight you have to either type out "direction" everytime before you can specify the direction by typing the first letter and accepting. you can either move over to the arrow keys and chose or move the hand even farther and use the mouse. 
typing eRightDirection or eLeftDirection is faster with autocomplete as you just type e+first letter + enter. Some diagonal movements are more complicated but when do you use these when you turn your character around? I make him turn around sometimes in dialog as if he was thinking, sometimes look at something he is talking about, but mostly left, right, up, down are used.
So my suggestion is to change the keywords this way. But this is probably in conflict with some AGS naming conventions. I'd welcome this change. Or is it bullcrap what I'm thinking about the workflow?
my concern is, does turning around the naming scheme confuse the autocomplete so much that it wouldn't know what to suggest?

**Comment by ericoporto** [comment]
I think things that are group go at left and things that are a smaller group goes at right.

e -> enum
Direction -> group of directions, under enum
Right -> a direction under a group of directions.

Maybe if it was like eDirRight, eDirLeft... Would be faster to type? Direction is clearer than dir, since dir is associated with directory in the Windows command line. Maybe having both possibilities, solving for the same value, would favor discoverability and still provide some shortcut for experienced ags developers?

I think I usually just type eDir and use the down keyboard arrow to select the direction, since I think it takes 4 letters for autocomplete kick in.

**Comment by ivan-mogilko** [comment]
Not meaning to say anything on naming at the moment, but in regards to script compatibility, renaming may be supported using SCRIPT_API_vXXX and SCRIPT_COMPAT_vXXX macros. You may [see the example here](https://github.com/adventuregamestudio/ags/blob/ags3/Editor/AGS.Editor/Resources/agsdefns.sh#L169) where I changed Alignment values.

This gives a user an ability to keep old scripts unchanged if they switch to lower script API level (at the cost of not using newer API).

**Comment by tzachshabtay** [comment]
The proper solution would be to support fuzzy searching for auto complete, so ULDR will work even for the current names.

**Comment by AlanDrake** [comment]
We won't be changing the naming convention any time soon.
But you can wrap the original function using an enum type of your own to do what you suggest.
