### ISSUE TITLE
Android SDK updated and dropped lots of things

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#587]
I am trying to build the ndk the binaries, and it's not possible since Android SDK updated minimum plataform API to 16 instead of 14, and dropped mips architecture. The scripts below need to be updated. Another change is the lack of gcc in Android SDK now.

[buildall.sh.zip](https://github.com/adventuregamestudio/ags/files/2775622/buildall.sh.zip)
[makestandalones.sh.zip](https://github.com/adventuregamestudio/ags/files/2775623/makestandalones.sh.zip)

The `arm-linux-androideabi-gcc` included in the android ndk toolchain is a lie, it's a weird link to clang and it is failing in the config tests for freetype...
![screenshot from 2019-01-19 12-50-06](https://user-images.githubusercontent.com/2244442/51428263-cb60eb80-1be8-11e9-8979-3930fd29b56a.png)

```
./buildall.sh 
~/git/ags/libsrc ~/git/ags/Android/buildlibs
allegro-4.4.2.tar.gz: OK
dumb-0.9.3.tar.gz: OK
freetype-2.4.12.tar.bz2: OK
libogg-1.3.2.tar.gz: OK
libtheora-20150828-gfbb2758.tar.bz2: OK
libtheora-20160525-g50df933.tar.bz2: OK
libtremor-20150108-r19427.tar.bz2: OK
libvorbis-1.3.5.tar.gz: OK
lua-5.1.5.tar.gz: OK
~/git/ags/Android/buildlibs
~/git/ags/Android/buildlibs/armeabi ~/git/ags/Android/buildlibs
~/git/ags/Android/buildlibs/armeabi/freetype-2.4.12 ~/git/ags/Android/buildlibs/armeabi

FreeType build system -- automatic system detection

The following settings are used:

  platform                    unix
  compiler                    /platforms/android-16/arm/bin/arm-linux-androideabi-gcc
  configuration directory     ./builds/unix
  configuration rules         ./builds/unix/unix.mk

If this does not correspond to your system or settings please remove the file
`config.mk' from this directory then read the INSTALL file for help.

Otherwise, simply type `make' again to build the library,
or `make refdoc' to build the API reference (the latter needs python).

Generating modules list in ./objs/ftmodule.h...
* module: truetype  (Windows/Mac font files with extension *.ttf or *.ttc)
* module: type1     (Postscript font files with extension *.pfa or *.pfb)
* module: cff       (OpenType fonts with extension *.otf)
* module: cid       (Postscript CID-keyed fonts, no known extension)
* module: pfr       (PFR/TrueDoc font files with extension *.pfr)
* module: type42    (Type 42 font files with no known extension)
* module: winfnt    (Windows bitmap fonts with extension *.fnt or *.fon)
* module: pcf       (pcf bitmap fonts)
* module: bdf       (bdf bitmap fonts)
* module: sfnt      (helper module for TrueType & OpenType formats)
* module: autofit   (automatic hinting module)
* module: pshinter  (Postscript hinter module)
* module: raster    (monochrome bitmap renderer)
* module: smooth    (anti-aliased bitmap renderer)
* module: smooth    (anti-aliased bitmap renderer for LCDs)
* module: smooth    (anti-aliased bitmap renderer for vertical LCDs)
* module: psaux     (Postscript Type 1 & Type 2 helper module)
* module: psnames   (Postscript & Unicode Glyph name handling)
done.
cd builds/unix; /bin/sh ./configure  '--host=arm-linux-androideabi' '--prefix=/home/erico/git/ags/Android/nativelibs/armeabi' '--without-zlib' '--disable-shared'
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking for arm-linux-androideabi-gcc... /platforms/android-16/arm/bin/arm-linux-androideabi-gcc
checking whether the C compiler works... no
configure: error: in `/home/erico/git/ags/Android/buildlibs/armeabi/freetype-2.4.12/builds/unix':
configure: error: C compiler cannot create executables
See `config.log' for more details
builds/unix/detect.mk:86: recipe for target 'setup' failed
make: *** [setup] Error 77
```

A different issue of Freetype with NDK is reported here -> https://github.com/android-ndk/ndk/issues/614

I can say building GCC with NDK toolchain is a waste of time because the errors a too cryptic. [If someone is crazy they can find it here](https://android.googlesource.com/toolchain/gcc/+/master/) but I totally don't recommend it.

Edit: Noticed Google mantains their Freetype here : https://android.googlesource.com/platform/external/freetype/

Edit2: Some more interesting reading https://mortoray.com/2012/08/21/android-ndk-cross-compile-setup-libpng-and-freetype/

**Comment by ivan-mogilko** [comment]
Regarding the output you posted, I thought something like this happens when the process could not find a proper toolchain? Does following path really exist on your machine: `/platforms/android-16/arm/bin/arm-linux-androideabi-gcc` ?

**Comment by ivan-mogilko** [comment]
Another thing that we forgot to add to readme is that if you are going to build Java apps from command line using "ant", then you need to download old SDK tools package because newer Android SDKs don't include ant anymore.

https://stackoverflow.com/questions/42912824/the-ant-folder-is-suddenly-missing-from-android-sdk-did-google-remove-it

Dl link: https://dl.google.com/android/repository/tools_r25.2.5-linux.zip

**Comment by ivan-mogilko** [comment]
Ok I've got all the native parts compiled, but when compiling Java app I keep getting error that was mentioned by one user several months ago but never resolved:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=44768.msg636590069#msg636590069

<pre>
[ launcher_list]$ ant debug
Buildfile: <HOME>/ags/Android/launcher_list/build.xml
  [taskdef] Could not load definitions from resource anttasks.properties. It could not be found.
  [taskdef] Could not load definitions from resource emma_ant.properties. It could not be found.
 
-set-mode-check:
 
-set-debug-files:
 
-check-env:
 
BUILD FAILED
<HOME>/android/sdk/tools/ant/build.xml:396: Problem: failed to create task or type checkenv
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
</pre>

**Comment by ivan-mogilko** [comment]
Just confirming: I was able to build APK in ags3 branch.

Following information needs to be added to readme:
1. Need to use older NDK r16b, may be downloaded here: http://developer.android.com/ndk/downloads/revision_history
2. Need to make 3 toolchains using commands like:
`$NDK/build/tools/make_standalone_toolchain.py --arch arm --api 14`; same for "x86" and "mips".
If you don't specify "--install-dir" this will create archives in a working dir. Anyway the contents of toolchain should be copied to directories $NDK/platforms/android-14/arm, x86, mips.
3. Following tools must be installed in system to build native libs: **autoconf**, **automake**, **cmake**, **libtool**.
4. In order to build Java apps, you need to have installed: Android SDK for Android 4,1 (api level 16); this may be done through Android Studio's SDK manager.
5. Install **ant** and **openjdk**.
6. Download deprecated tools here: https://dl.google.com/android/repository/tools_r25.2.5-linux.zip and copy the contents of "tools" directory to "Android/Sdk/tools" (skipping existing files).

That's it, I think.

**Comment by ericoporto** [comment]
Found my error:

https://github.com/adventuregamestudio/ags/blob/master/Android/buildlibs/makestandalones.sh#L8

This rewrites my ndk home. So I was using:

https://github.com/adventuregamestudio/ags/blob/master/Android/README.md#native-3rd-party-libraries

And my NDK_HOME was being ignored
