### ISSUE TITLE
Documentation should be updated from "debian" to "Linux"

### ISSUE THREAD

**Issue by scottchiefbaker** [adventuregamestudio/ags#596]
Before I create a pull request I wanted to ask if renaming the `debian` directory to `Linux` would break anything. The `debian` directory appears to only contain documentation and scripts for how to build `ags`. Originally the documentation was only for Debian, but it's been expanded to support other flavors of Linux. 

If I create a pull request to change the `debian` directory to `Linux` and update the appropriate HTML links to the documentation will that be accepted? Or should I just leave it as it is because it's tied in to other things?

**Comment by ivan-mogilko** [comment]
Unfortunately I do not know full history of these files. I'd like some of the previous maintainers, such as @tobihan comment on this, because I am not convinced that everything in that directory relates to just any Linux. TBH I am not sure that all of them belong to ags repository. For example, "changelog", "compat" and "control" files were probably supposed to be a part of AGS distribution on Debian and similar systems (unless I am mistaken).

**Comment by erenes** [comment]
It's not just documentation, the debian directory almost exclusively contains scripts to build the .deb package for AGS (not scripts to build it for other distributions), so I do think the directory name to be accurate. 

Perhaps a better solution would be to pull the linux build instructions somewhere more global and only describe how to create the .deb package in the readme.md in the debian folder?

**Comment by ivan-mogilko** [comment]
Returning back to this after a while, what if we make Linux dir, and place debian inside?
Linux dir could contains general readme for linux, while debian subdir would have only debian-related scripts and additional readme if necessary.

**Comment by rofl0r** [comment]
> if renaming the debian directory to Linux would break anything

renaming in git repos is always a pain as it breaks git log/git blame functionality and requires an enormous effort to figure out where a change came from. this error was committed repeatedly in the past with this repo, and everytime i have to hunt down where a change to e.g. room loading code or script compiler came from i have to trace back over like 4 rename operations, each one requiring to scroll over huge diffs to find out how the file was named previously, and then starting the git blame/log process all over on the now inexistant file.

**Comment by ivan-mogilko** [comment]
> the most elegant solution would be a symlink linux -> debian, but since that's not supported on windows a linux directory containing a small text file mentioning that the content in debian/ should be checked (due to a historical mistake) could solve the issue without breaking the git log.

There are already quite a few directories in the repository's root, that's why I suggested to make debian a subdir inside linux.

This project was originally not very well organized, and for example we started with splitting 3-4 huge code files into like 30 small ones spread across several directories, no wonder things are moved and renamed as code gets refactored.

Is there a meaning in keeping a git history of what is inside debian directory though? It's mostly build scripts that refer to particular code state + some files necessary for creating of deb package, these did not change at all probably.

**Comment by rofl0r** [comment]
```$ git log debian/ | grep commit | wc -l
112
```
there are 112 changes to those files, certainly someone trying to track down an issue could make use that history. i personally never needed to look there, mostly because 1) i don't use debian and 2) when i first i used ags source in 2012 (the only time i looked inside there) the description of engine build process was straightforward and hasn't changed since.

**Comment by ivan-mogilko** [comment]
Actually I might be wrong in assumption that debian dir could be moved inside another, as current dir structure may be in accordance to some rule that debian maintainers follow....

**Comment by ivan-mogilko** [comment]
Alright, I guess it may work if we create a Linux dir, and then either
* move README.md there;
* put its own README.md which only has generic linux instructions inside;
* put a note telling to look into debian/

**Comment by morganwillcock** [comment]
I think this is effectively linked to the issue that the overall build processes for all components is fairly loose in definition on where files are destined to end up and for what purpose. The only feasible way to do the initial CI setup was to embed a lot of scripting into it that replaces what was being done manually. The Debian folder is probably a good example of something that shouldn't be in the repository at all: any downstream packaging can act on a source release or a tag and shouldn't need any other type of visibility or privilege to be functional. At the moment the CI build steps do rely on the Debian build being there because part of the release packaging uses its output and the 'B00_copy_libs.sh' script, but I don't think this is the correct thing to do.

So I think the proper solution is to:
- integrate the creation of source releases and binary releases into the build system, to remove the dependency on the Debian packaging existing here, and also to remove the needs to use multiple environments to create a binary release.

Then do one of the following:
- move the Debian packaging into its own repository which can be built via CI by invoking Debian specific tooling
- delegate the Debian packaging to the build system (dependent on the build system supporting the process)
- delegate the Debian packaging to a 3rd party build service (e.g. https://openbuildservice.org/)

Possibly the most controversial decision would be which build system to insert the build logic into, although probably best to save that discussion for a ticket where someone actually wants to work on improving the build system.

**Comment by ivan-mogilko** [comment]
So, what do you all say if for now I just make a "Linux" dir, place a README.md there with instructions necessary for building on Linux, and in "debian" dir's README leave only instructions related to building "deb" packages and those specialized binaries (make_ags+libraries.sh)?

Then we'll have a clearly visible "Linux" dir, and "debian" will contain strictly deb-related stuff, unless someone adjusts the build system.

**Comment by rofl0r** [comment]
sometimes no action == best action

**Comment by ivan-mogilko** [comment]
Alright, I'll close this then.
