### ISSUE TITLE
Update to Allegro 4.4.3

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#607]
Allegro 4.4.3 was finally released which includes our patches too:
https://www.allegro.cc/forums/thread/617731/1041144

Following changes are necessary on our side to update:

* Remove **load_midi_pf** from [the engine code](https://github.com/adventuregamestudio/ags/tree/ags3/Engine/libsrc/allegro-4.2.2-agspatch) (now implemented in the library).
* For Linux: enable the use of **play_fli_pf** ([see here](https://github.com/adventuregamestudio/ags/blob/ags3/Engine/media/video/video.cpp#L183)).
* For Windows: sync our fork with upstream, rebase the patched branch to the new tag and only have
AGS-specific hacks there (exposure of certain global variables).
* For Android and iOS: update library building scripts, remake patch files to correspond to new library version.

**Comment by tobihan** [comment]
Allegro 4.4.3 is not in Debian yet and came out a little bit too late to be even in the next Debian release (buster). Even when it will be in Debian unstable, the deb from unstable may or may not work on Debian jessie. So if it has to be Allegro 4.4.3 any time soon, the way to go is to build it in the chroots before building ags.

**Comment by ivan-mogilko** [comment]
Allegro 4.4.3 source tarball link: https://github.com/liballeg/allegro5/releases/download/4.4.3/allegro-4.4.3.tar.gz

I'd imagine 3.4.1 and 3.4.3 would require exactly same changes to the engine code.

**Comment by 256colour** [comment]
@tobihan OK great. I'll start working on learning how to build in the chroots before building the rest. Thanks!

Will keep this thread updated if I have success with it.

**Comment by ivan-mogilko** [comment]
Regarding changes to the engine, I was thinking we could perhaps use allegro version macro if it's still available to let compile against both 4.4.2 and 4.4.3.

**Comment by 256colour** [comment]
I forgot to update this thread over a month ago. I was able to successfully build my own chroots from scratch, and compile Allegro from scratch in them. Happy to share the setup if that helps anyone else.

**Comment by sonneveld** [comment]
I've started work on merging the ios/android/macos patches into our allegro branch.  This should help keep things up to date. 

I ignored the psp patches as I think we've decided to drop it.

**Comment by morganwillcock** [comment]
Just to confirm, for Linux it is still the upstream version that is used?

**Comment by sonneveld** [comment]
> Just to confirm, for Linux it is still the upstream version that is used?

Good question. We could make it a build option but it would mean we need to keep the hacks arounds.

**Comment by morganwillcock** [comment]
Given that there would eventually be the official release and the modified version (which gradually gains new features such as alternative audio and video backends), I guess building two sets of libraries would be preferable? Or would there be 3 versions if the one with SDL2 needs to be maintained separately of any other changes?

The purpose of the question is more from a CI perspective, trying to find a way that engine builds could incorporate all of the backends to make something that is runnable.

**Comment by ivan-mogilko** [comment]
I have a question, what do you decide about systems like debian where people prefer to use official stable packages, is it still okay to use our own Allegro version (e.g. patched 4.4.3 one), and if yes, how do we set that up in repository?

**Comment by morganwillcock** [comment]
> what do you decide about systems like debian where people prefer to use official stable packages

These normally just request a minimum version of the dependency, so installing the .deb package would just install the OS packaged Allegro (although potentially a user could take a newer backported package to fulfil the same dependency, but this is outside the scope of the package if you aren't mandating the use of that newer version).

> is it still okay to use our own Allegro version (e.g. patched 4.4.3 one), and if yes, how do we set that up in repository?

I think @256colour was saying that he just used the existing script to make the tar archive, and then swapped the Allegro components for newer ones that he built in the same environment.

> what is the plan in regards to make_ags+libraries.sh, if there's one?

Well, I only modified it recently because I found it to not function at all, but it seems to work well enough to build the archive. I've updated #718 to use it, and I think that would generate a build artefact once there is a tag applied, which would match what you would generate in your VM.

My question is to try and work out how to end up with a runnable release. If it is safe to swap Allegro components after the build, and newer Allegro components are also built in the same way, then potentially part of the release could be optional libraries that you can use in-place of the ones in the main tar file. Ideally though, you'd want the build process to generate something that is directly releasable and runnable:

e.g.

ags-linux-al442.tar.xz
ags-linux-al443.tar.xz
ags-linux-sdl2.tar.xz

Using the existing script it would be tricky to assemble the files this way, but there other approaches that could be taken.

>I've never researched how chroots are built now, is there a way to automate building them using our allegro fork?

It wouldn't be a problem to build something, but I'm not clear on what on the purpose of the Allegro fork is now that there is a new Allegro release. Will this get synced with the upstream Allegro 4 release and the SDL2 variant will always be a separate branch?

**Comment by ivan-mogilko** [comment]
> It wouldn't be a problem to build something, but I'm not clear on what on the purpose of the Allegro fork is now that there is a new Allegro release. Will this get synced with the upstream Allegro 4 release and the SDL2 variant will always be a separate branch?

The branch I am refering to ([allegro-4.4.3.1-agspatch](https://github.com/adventuregamestudio/lib-allegro/commits/allegro-4.4.3.1-agspatch)) is based of that newer 4.4.3 release and has all our platform specific patches added on top. In regards to Linux, I think main addition is the SDL2 audio driver built-in Allegro. I am currently mainly interested in that driver because some people having troubles with audio on Linux (this problem may be many years old, just random).

I'd actually like to switch to using 4,4.3 completely. If my understanding is correct, then at the moment this issue with deb packages and related (building with chroots) is the main obstacle.

**Comment by ivan-mogilko** [comment]
Regarding our 4.4.3 allegro's branch, I did a test and SDL audio driver solved sound problems for a user and also fixed strange sound noises I had on my Ubuntu VM.

Note that Allegro supports modular solution (at least on Unix systems) when it can load up driver implementations dynamically from provided shared objects and modules.lst config file. This makes it possible to make SDL2 driver optional if wanted (make it a separate distributive).
I _think_ it makes it possible to even build SDL2 driver separately from the rest of Allegro (or rather take Allegro built from other sources and add separately built SDL2 driver library).

For me the big question still is how to set up compilation of prebuilt binaries for Debian/Ubuntu. If we won't be able to use stable Allegro deb from Debian's servers (they still dont have 4.4.3), this means that we have to create own our chroot with custom Allegro. I haven't tried that myself yet. If that's simple enough to do then perhaps someone may set things up every time they need to do a release. If it's complicated, then would it be possible to either write a script that does that for you, or even keep a chroot package somewhere to download?

**Comment by rofl0r** [comment]
> Debian's servers (they still dont have 4.4.3)

best option is probably to lobby the maintainer of the package to bump it (with the hint that it's a bugfix release)

**Comment by morganwillcock** [comment]
I don't think the Debian packaging is relevant, except as a way to get prebuilt 4.4.2 libraries conveniently. The build environments are purposefully old and Debian would only take something for an old release unless it is a security update. The next Debian release is already frozen so the update window has been missed, but even if it was there I think I'm right in saying that it wouldn't be backwards compatible.

Unless there is an alternative method to build with a low glibc version, I think the easiest solution is just turn on CI builds for the Allegro branches - then either assemble all the parts into archives as a separate scripted process, or make the Allegro builds available to where the engine is built.

**Comment by sonneveld** [comment]
Our allegro patches also introduce SDL2 audio, which debian maintainers probably won't accept as a patch.   Can we just statically link allegro instead?

**Comment by ivan-mogilko** [comment]
> Can we just statically link allegro instead?

What will that change in current circumstances?

**Comment by sonneveld** [comment]
> What will that change in current circumstances?

It would meant that the produced debian package would be self contained and wouldn't have to rely on work arounds to support older versions of allegro4

**Comment by ivan-mogilko** [comment]
Ok, I am getting confused, what debian package is this?
My original question was referring to the linux package with prebuilt binaries we supply along with the Editor and that is used to distribute games on Debian and similar systems. The building process is currently run by a script that compiles engine in what is probably a virtual enviroment. If we are building our own version of Allegro, then we need to set up its compilation in that enviroment as well. This is what I was asking about.

**Comment by rofl0r** [comment]
if i understood correctly, ags binaries which are shipped on the homepage and as part of the editor, include shared libraries of some components. so until modern allegro 4 hits the debian repos, you could simply bundle the allegro 4.4.3 you built from sources using the CI or whatever, just as you did in the past with the custom-patched allegro 4.4.2.

**Comment by ivan-mogilko** [comment]
To sum up, I'd like to clarify was anyone planning to keep support of Allegro 4.4.2 for some reason? If so, then is it strictly the "stock" library?

There are only slight differences in library api, but if we require engine to support official 4.4.2 then load_midi_pf function must remain in the code, and play_fli_pf be disabled on Linux.
If we drop 4.4.2 support, **or** require our patched version anyway, then we may remove load_midi_pf 
 and enable play_fli_pf since these will be in the library. So this is important to know, at least to me now.

In regards to 4.4.3, I think on Linux the difference between official and our versions is only essential if we do static linking and want SDL audio driver (in which case we should build ours). If we do dynamic linking, then it's possible to use either main library and supply SDL driver *.so as an option.

**Comment by morganwillcock** [comment]
If you drop support for Allegro 4.4.2 then it means the actual AGS .deb package needs the dependency raised to 4.4.3, but there would be no official Debian package providing it. So effectively this makes the Debian package itself redundant unless there is a 3rd party also providing a .deb for Allegro 4.4.3 or the person builds and installs it themselves.

Not that I think this should necessarily mean keeping support for 4.4.2; AGS itself is not shipped with Debian so there is no downstream breakage, and 4.4.3 is preferable because it actual helps to make the game playable. As long as the release archive works the end result is not much different to a self-installed .deb file.

Personally I would say to favour the experience of the game: mandate the use of Allegro 4.4.3 and just distribute the archives that include it,  as well as an SDL option. If people want a packaged version because they want something external to a game that can self update from a verified source, @ericoporto has a working snap package (maybe this should be adopted into the Github organisation) which works on Debian and Ubuntu. Making an AppImage bundle doesn't look too difficult either, and in theory this works like an .exe file on Windows (the dependencies are containerised inside it).

**Comment by ivan-mogilko** [comment]
I forgot to mention that it's possible to use allegro version macro to switch the code belonging to 4.4.2 and 4.4.3. (which I believe would be needed only in couple of places mentioned above).

**Comment by morganwillcock** [comment]
I've looked into a little more and as long as we can tell the difference between a PR and a release tag we should be able to authenticate the release builds to use the Github API to pickup URLs for built copies of Allegro, whilst skipping the release packaging for a PR (so these are checked for build success only and don't create any release files).

Assuming using Travis-CI to build the engine release (because that it what was already enabled) the build environment has a variable called `TRAVIS_PULL_REQUEST` which is set to the pull request number if the current job is a PR build, or false if it’s not.

So if this value is false:
- take the Allegro version from a variable
- clone the source relating to this version (to build against it)
- download the built library files to use for packaging

To produce builds with multiple Allegro/SDL options, we just run multiple builds with different Allegro versions passed in. I don't think this would run any differently if you wanted to build it locally on your own computer - CI specific variables would always be unset.

Can anyone point out a problem I might not have thought of?
(other than where to get SDL2 libraries from)

**Comment by ericoporto** [comment]
@morganwillcock just a quick note, appveyor need a webhook in the settings of the repo for allegro to be there, right now appveyor can't tell when stuff is pushed there. There is a branch for allegro 4.4.3.1 on lib-allegro, but I can't tell which actual allegro is that (with sdl or the original source). Anyhow, triggering a release should store the built libraries in the release tag.

**Comment by morganwillcock** [comment]
@ericoporto I've added a webhook for push and pull_request, so hopefully it will start doing something now.

**Comment by ivan-mogilko** [comment]
Note: I pushed 371c84de67f54a36b3ae5403f884368ec5457c57 that should allow to link either Allegro 4.4.2 or 4.4.3 with the engine.

**Comment by ericoporto** [comment]
@ivan-mogilko , the only thing holding this is deciding the default, is this correct?

**Comment by ivan-mogilko** [comment]
I made engine being able to compile and link to either 4.4.2 or 4.4.3, so this is not a big issue anymore.

**Comment by morganwillcock** [comment]
The way it is being built at the moment (in terms of testing the CI workflow), I'm:

- building Allegro 4.4.3 separately and making a Github release from this
- building the engine as normal
- replacing the Allegro files with the ones from the 4.4.3 release
- adding the SDL2 audio module to the bottom of the module list

So the end result is:
https://cirrus-ci.com/task/6025700618797056

**Comment by morganwillcock** [comment]
The Android library build (`Android/buildlibs/buildall.sh`) is still using Allegro 4.4.2. I'm not sure what the plan is for this, or whether the Android port is not going to be part of the official release if it is crashing, but the main problem for automated building is that I by running the existing build script it'll increase @sonneveld's AWS bill.

**Comment by ericoporto** [comment]
Erh, we can store the libs in a new repo here and just download from it instead of AWS, what blocks this?

**Comment by ivan-mogilko** [comment]
Android may keep 4.4.2 libs, but updating to 4.4.3 is a question of rebasing patch onto 4.4.3 branch, which in theory should not take much effort.

**Comment by i30817** [comment]
Does this new version of allegro has a sane way to  specify the `patches.dat` file (for the DIGI driver)? Currently you have to remember to place it in $HOME which is a very awkward place. I'd like to place it in the root of my current filesystem and forget about it; that is something like this on the config files:

`patches_dir=..`

where that path is expanded to a absolute path (if relative) created from the game dir, thus:

`patches_dir=/media/i30817/Ags/Blackwell/..`

This would allow me to share that file and still keep it in the filesystem and thus 'portable'.

**Comment by morganwillcock** [comment]
I don't think that this version changes anything regarding how a patches files is located, but you can already specify a shared location by setting the environment variable `ALLEGRO` to an absolute path. A game may ship with custom patches, so forcing global overrides or (config changes in general) in all cases may be problematic.

**Comment by ivan-mogilko** [comment]
I think it's possible to specify patches.dat location in allegro.cfg. It's just that I don't remember where allegro.cfg is being searched for. Also, if there's one in game's dir it may override global one.

**Comment by i30817** [comment]
Ah... but they can't ship with custom patches. Patches files on the game dir aren't picked up (and i tried it). Otherwise i'd do a hardlink for all the games with digital audio.

**Comment by ivan-mogilko** [comment]
> Patches files on the game dir aren't picked up (and i tried it).

This is very strange, I may be mistaken but I remember doing this on Linux and it worked. May look into this again when I have time (not soon).

Also, sorry for nagging, but could the patches problem be put into separate ticket too?

**Comment by i30817** [comment]
Sure. I'll retest it since it was some months ago just to be sure then open a issue.

**Comment by ivan-mogilko** [comment]
I think I will close this, source code is made to be compatible with either 4.4.2 and 4.4.3, and updating separate ports to use 4.4.3 by default could be separate task.
