### ISSUE TITLE
Remove limit of 20 Timers

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#610]
why is there this limit? Will it make the CPU the game is running on explode?
Raise the limit to 100 timers per game then?

**Comment by ivan-mogilko** [comment]
IMO there are two separate issues here: the limit on timer IDs, which often is a real problem ([as noted in my another comment](https://github.com/adventuregamestudio/ags/issues/612#issuecomment-461197935)), and limit on simultaneously running timers.

**Comment by AlanDrake** [comment]
The builtin Timers add nothing of value to current AGS, perhaps we should remove them from ags4 branch?
They would be more interesting if you could bind a function as a parameter and they returned the ID instance instead of bool, instead they're DIY and may trick newbies into using them and regretting it.

**Comment by ericoporto** [comment]
Binding a function requires passing a function as a parameter, which is not possible yet on AGS Script.

They could return a eEventTimerEnded with data as the timer ID though.

**Comment by ivan-mogilko** [comment]
Closed in favor of #1958
