### ISSUE TITLE
Allow or decriptive names for timers instead of numbers

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#612]
It is just annoying to keep track of what number will be next and reusing a number can introduce bugs you find way too late. Especially when you have debug-jump points in bigger games. 
Happend to me, I tested the timer by jumping to the new room and it worked. But when playing the complete game the timer gets set earlier and this breaks the function in the later room that works just perfect when directly jumping to the room. Having a unique descriptive name will prevent that and will make the code more human readable.

SetTimer(Delay_CustomAnimation, 2000);

is easier to read than

SetTimer(1, 2000); //delays the custom animation

**Comment by rofl0r** [comment]
why don't you simply use a macro or variable name ? PEBKAC

**Comment by ivan-mogilko** [comment]
The problem here is not much that timers are identified with a number, but that these IDs are all sharing same "namespace". You are not creating your own timers, you are reusing same ones from the single list of timer "slots". And there is little way to guarantee that you do not start timer N in another place while the previously created timer N is still running. This is very bug prone and makes it hard to work with timers in large projects. Additionally, that complicates using timers in the modules and templates (module writer would have to let people customize timer ID's to make sure they don't conflict with anything in game).

**Comment by ericoporto** [comment]
@ivan-mogilko I am a great fan of your Timer module and use that in all my projects instead of current ags Timer api.

**Comment by ivan-mogilko** [comment]
Closed in favor of #1958
