### ISSUE TITLE
ags3 linux: can't open datafiles in path with utf8 chars

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#662]
to reproduce:
- launch linux
- extract this game: https://0x0.st/zouS.rar (agsarchives.com/bicycle/mmm/MMM\ 016\ -\ Meteor\ Family\ -\ Die\ Rückkehr\ des\ Meteoriten.rar) with `7z x filename.rar`
- cd into the resulting directory
- `rm *.lnk ; mv Files/* .`
- ags mmgui.exe

results in 
```
Game data file could not be found. Search path used: '/home/rofl/games/ags/mmm/Maniac Mansion Mania 016 - Meteor Family - Die R�ckkehr des Meteoriten/mmmgui.exe'
ERROR: Unable to find game data files. The necessary files are either missing or are of unsupported format.Usage: ags [OPTIONS] [GAMEFILE or DIRECTORY]
```
it seems the utf8 sequence `R\303\274ckkehr` is transformed into `R\374ckkehr` during the code leading to search_for_game_data_file (filename=...)
    at main/engine.cpp:303

i see 2 issues here:
1) the obvious bug of modifying the path string
2) the usage of a full path rather than just `.` for the directory or even just the plain filename without any directory components, as passed on the command line

**Comment by ivan-mogilko** [comment]
> the usage of a full path rather than just . for the directory or even just the plain filename without any directory components, as passed on the command line

May this be a problem on its own, if we forget about utf-8 paths for a second? I do not remember why, but at some point of development I found it might be easier to store absolute paths, so this is what I do.

Regarding utf-8, storing relative path may fix things in your case, but it won't be a universal solution because someone could pass an absolute path or relative path containing utf8 names too.

Trying to get to the bottom of this, allegro 4 is run in U_ASCII mode from the very beginning, so when it converts command-line argument into the absolute path it already supposed to respect that when working with paths and strings in general.
So my question is this: do filesystem functions on Linux understand ascii paths constructed like this at all (i.e. having '\123' sequences?)

(For instance, on Windows we also convert paths got from command line, there's a special WinAPI function that returns a ascii version of a Unicode path, aka DOS-path.)

If everything else is okay, then I have an idea where it may incorrectly change a path containing '\'.

**Comment by rofl0r** [comment]
> So my question is this: do filesystem functions on Linux understand ascii paths constructed like this at all (i.e. having '\123' sequences?)

linux is quite smart: you can throw anything at it, in any encoding, malformed or not, and it will store it. the only 2 characters which are special are '/' as a path separator and '\0' to terminate the string. that way there can be no issues with encoding. so if AGS would simply always store the original path string and never modify it (apart from maybe adding path components to it), it will always work.

**Comment by ivan-mogilko** [comment]
A small update. I think some of my previous fixes to game search actually affected this issue as well, because right now if you run ags from the game's folder and at least provide gamefile name, like `ags mmmgui.exe`, then the game is successfully found and launched.

The problem resurfaces if you *do not tell* path to game data, forcing ags to search around. In such case it fails. This is because at certain point it begins testing paths using Allegro4 functions. But since AGS works in U_ASCII mode, these either fail at unknown characters or convert paths to ASCII simply by replacing all unknown symbols with '^'.

So, for example, if you call game directory "Rückkehr", cd there and just run `ags`, you will still get error like:
`ci_find_file: cannot change to directory: /home/....../R?ckkehr`.

`ci_find_file` is the engine's compatibility function that does case-insensitive file search on systems with case-sensitive filesystems (https://github.com/adventuregamestudio/ags/blob/release-3.5.0/Common/util/misc.cpp#L84).

I did not do thorough research yet, but perhaps if it could be prevented from converting the path the problem would be fixed also.

**Comment by rofl0r** [comment]
thanks for the update. i just want to comment on this quote from your prev comment:

> but at some point of development I found it easier to store and use absolute paths, so this is what I do

the only reason i can think of to do this would be if the engine uses `chdir()` or something to switch active directory, which seems like a bad idea, so if the engine does it revising this might lead to improvements.
