### ISSUE TITLE
Remake engine tests as google test project (similar to compiler)

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#664]
There's a bunch of semi-automatic tests written inside the engine, which are currently simply ran at startup if program is built with _DEBUG flag.

They should be moved out and remade as a google test project, similar to the one we have for script compiler. Then we will be able to configure them as a job for one of our CI tools.

These are mostly basic utility class and function tests, so should not be a big problem in extracting them out (they don't need actual game to run).

**Comment by sonneveld** [comment]
I started looking at this in the cmake PR. It should be relatively easy if we just have large single function test cases to begin with (and add fine grained asserts later)

**Comment by ericoporto** [comment]
I did this in a commit here: https://github.com/ericoporto/ags/commit/4c931cf9879dd8f51d80377e2e1e4b2186353154 (the branch has the CI too but nothing on the other OSes)

The problem is the google test is an actual executable with it's own main, while this is simple in CMake (a new target), in `.vcxproj` I couldn't find a different way but reorganizing to have three `.vcxproj` files, a Engine.Lib, and Engine.App and Engine.Test, and placing these in the solution file. The Engine.Test generates the necessary `.exe` file to run the test.

About running in the CI, the Google Test won't run in the Windows on CirrusCI since it has no graphics driver and crashes at load when it fails to find the required Directx dlls (similar to https://forum.unity.com/threads/player-with-server-build-silently-fails-on-windows-server-core.898337/) - it may be easier to run just in Linux for the CI.

**Comment by ivan-mogilko** [comment]
>  I couldn't find a different way but reorganizing to have three .vcxproj files, a Engine.Lib, and Engine.App and Engine.Test, and

No, that's too radical, and most probably unnecessary.
There has to be a simplier way: to just include cpp files that are necessary for compilation of those tests.

For example, this is how I did this with standalone tools:
https://github.com/ivan-mogilko/ags-refactoring/tree/ags3tools--roomscheader

**Comment by ivan-mogilko** [comment]
Created Engine.App.Tests solution and moved String tests there (in master branch): d2413d63f55adab65d865452a84678d9547fb438

I'll move other tests too soon, but need to check out dependencies for some of these. Few probably depend on Allegro, but since we have a stripped Allegro source this hopefully won't be a big issue.

**Comment by ivan-mogilko** [comment]
Apparently I did a mistake with this, because build_windows task in CI is trying to do full solution build, which includes the tests project, and this particular task does not load googletest submodule, which results in a compilation error.

What would be the best approach here?
* exclude certain project in the Engine solution from building, and only build this project in a separate test task;
* build it along with the rest of the solution, but download the module;
* remove this project from Engine solution and create a separate one meant only for running tests?

**Comment by ericoporto** [comment]
I recommend changes to the CI be done through a PR, some things have a really unintuitive behavior.

That said, this is the line that adds the submodule for Googletest:
https://github.com/adventuregamestudio/ags/blob/60642232f267080ab54b20aeb096d1c1c48af64f/.cirrus.yml#L304

I was thinking last night about just adding a new flag for disabling DirectX and OpenGL drivers at build, I haven't had the time to test yet in the CI, but theoretically I think this would allow ags to run - I think you are building with common but I was thinking this for the actual engine. I think X dependency on Linux can be removed too, since SDL loads it dynamically I don't think we use anything from it that requires us to link to it - again, hadn't had the time to check this.

**Comment by ivan-mogilko** [comment]
Very well, I will revert and make a Common.Test instead.
