### ISSUE TITLE
Support toggleable VSync with 3D renderers

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#675]
This is years old, changing [System.VSync](https://github.com/adventuregamestudio/ags-manual/wiki/System#systemvsync) property at runtime in script does not affect Direct3D and OpenGL renderers. Need to find out how it is possible to apply new setting at runtime. E.g. for OpenGL it might be simple call to glSwapIntervalEXT.

**Comment by ivan-mogilko** [comment]
As of 3.6.0, software renderer also no longer supports this, as its changed to using SDL_Renderer.
According to the SDL docs, there's function [SDL_RenderSetVSync](https://wiki.libsdl.org/SDL_RenderSetVSync) that toggles the mode, but it's available since 2.0.18, while we are still linking SDL 2.0.12 at the time of writing (if i am correct).

**Comment by ivan-mogilko** [comment]
Additionally, in the future versions it may be worth to add a property that tells whether vsync is supported.
Alternatively, we may plan a more generic function that tells if something is supported by passing a string name of the feature (e.g. `System.GetSupported(const string feature_name)`).

**Comment by AlanDrake** [comment]
This was addressed on ags4 branch by [#1741](https://github.com/adventuregamestudio/ags/pull/1741) though it's still unclear if it's effective for all ports.

**Comment by ivan-mogilko** [comment]
Also backported to 3.6.0, seemingly working on Windows and Linux at least.
