### ISSUE TITLE
AGS fails to start on Ubuntu: missing libpng12.so.0

### ISSUE THREAD

**Issue by FTPlus** [adventuregamestudio/ags#693]
The following error was shown when starting AGS on Ubuntu 18.10:
`error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory`

*Reason:*
Ubuntu has dropped support for libpng12 which the libfreetype library supplied by AGS requires.

*Temporary solution:*
The needed library can be found here: https://packages.ubuntu.com/xenial/libpng12-0
After installation the problem should be resolved.

*Better solution:*
FreeType has two dependencies: libz and libpng. Since libfreetype is provided as a shared object to AGS builds, and both libs are rather small, I suggest they are linked statically to the freetype .so and have future AGS versions come with this.

**Comment by ivan-mogilko** [comment]
May be relevant: #690

**Comment by rofl0r** [comment]
the freetype version in #690 (2.1.3) does not require libpng, at least when built in the default configuration, which is sufficient for our purposes. this seems to be a packaging bug of debian/ubuntu.

> shown when starting AGS on Ubuntu 18.10

did you compile AGS from sources or use an existing package?

> libfreetype library supplied by AGS requires

which library (version) would that be and how did you aquire it?

**Comment by FTPlus** [comment]
This dependency comes from the .so packaged with AGS version 3.4.3.1 (at least the 64 bits version). That is `libfreetype.so.6` just to be clear. This the version that is copied over when an AGS project is build by the editor.

**Comment by rofl0r** [comment]
what, you got your AGS binaries by clicking "build" in the editor ? i wasn't even aware that the editor can be executed on linux.

**Comment by ivan-mogilko** [comment]
> what, you got your AGS binaries by clicking "build" in the editor ? i wasn't even aware that the editor can be executed on linux.

Perhaps this was badly phrased. These binaries are created by running debian/make_ags+libraries.sh.
Then we distribute them with the Editor which let user to package the game for Ubuntu/Debian with these prebuilt libs.

**Comment by FTPlus** [comment]
... copied over ...

**Comment by rofl0r** [comment]
i was trying to download the official ags distribution from the ags website in order to inspect the files (like libfreetype.so.6) with readelf, objdump et al. however, the "package" is shipped in what looks like a self-extracting .exe archive, so unfortunately i'm unable to open it, as i do not own a windows PC.

**Comment by ivan-mogilko** [comment]
> i was trying to download the official ags distribution from the ags website in order to inspect the files (like libfreetype.so.6) with readelf, objdump et al. however, the "package" is shipped in what looks like a self-extracting .exe archive, so unfortunately i'm unable to open it, as i do not own a windows PC.

I distribute this linux pack separately too, lately they were attached to releases on github and called e,g, "AGS.3.4.3.1.Editor.Linux.Pack.zip"

https://github.com/adventuregamestudio/ags/releases/download/v.3.4.3.1/AGS.3.4.3.1.Editor.Linux.Pack.zip

**Comment by rofl0r** [comment]
unfortunately there's no version number stored in the libfreetype.so.6, but since the only version alfont-hack was written for is 2.1.3 (as in my PR), which is so ancient it can not even be found on the freetype website, i highly doubt that the .so was built from that version. it's probably a random freetype version that was at some point considered "good enough". using instead any random modern freetype version that ships with debian would probably fix this issue here, but not the issue with some fonts such as the LucasFan font, which my PR addresses (and would fix once and for all, since the freetype objects are statically linked against AGS).

**Comment by ivan-mogilko** [comment]
Need to find out if this is fixed after merging #690.

**Comment by ivan-mogilko** [comment]
@FTPlus please tell if this problem was fixed for you now when freetype lib is linked statically with the linux port?

**Comment by morganwillcock** [comment]
I've checked in a Ubuntu 18.10 VM (minimal install) and this is now fixed.
