### ISSUE TITLE
Editor: autocomplete list on multiple monitors

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#704]
Report from the user:

> i have three monitors setup
i work on the middl emonitor, but my main monitor is to my right
when i drag my AGS window to the monitor i work on
you know when editing a script theres a little drop down box with all the autocompletes?
well that shows up on my main monitor(to my right)

**Comment by 256colour** [comment]
User is running 3.4.1 fwiw

**Comment by morganwillcock** [comment]
I can't see that the editor is actually defining the position of the pop-up, only passing messages to Scintilla, where apparently this issue was already identified.

The version in the repository is 1.71 (from 2006), and [this issue was fixed](https://sourceforge.net/p/scintilla/bugs/979/) in version 2.20 (from 2010).

**Comment by morganwillcock** [comment]
It seems that half of this is implemented with what _was_ ScintillaNet in AGS.Controls, with the actual version of Scintilla built into AGS.Native. Scintilla is now 3 major versions newer (but with a [long term support branch](https://www.scintilla.org/LongTermDownload.html) one major version behind that), and what is _now_ ScintillaNET is actually a rewrite to give better Unicode support.

In the short term perhaps it is better to just apply the specific patch, to stay in sync with whatever version of ScintillaNet is in AGS.Controls. Then long term, update to the newer ScintillaNET which comes with packaged libraries instead of building it into AGS.Native. The background behind the changes and packaging are on the Github page: https://github.com/jacobslusser/ScintillaNET. It isn't 100% clear how active the project is though as it isn't tracking the latest Scintilla releases.

**Comment by ivan-mogilko** [comment]
There's also one bug in Scintilla that annoys the hell out of me: in Debug configuration nearly every time you mark and delete a chunk of text it calls "assert" for some reason and aborts execution. This happens often to me when I test editor under debugger.

**Comment by morganwillcock** [comment]
This should now be fixed, I could recreate the problem and test that the linked patch fixed it.
