### ISSUE TITLE
Editor: disable "Remap palette" import checkbox for non-8bit sprites

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#705]
I have a suggestion to disable "Remap palette" checkbox when importing non-8bit sprites and also default it to false state in this case, to prevent possible confusion.

**Comment by morganwillcock** [comment]
This isn't possible at the moment, since this option is considered for all images that are imported and for all frames within those images. The existing situation is better than the previous one, where bulk import settings were not even visible, but whilst importing through the native proxy I think this is best it can get (the checkbox label indicates when it will function).

I think this is another item which is better suited by building the spritecache at a later stage (remap at preview or compile time), and each image may have metadata that overrides default import behaviour.

**Comment by ivan-mogilko** [comment]
Did not realize you can import several sprites at once withing same window.

**Comment by ivan-mogilko** [comment]
Hmm, one question though, is it possible to disable it if we know that neither of chosen images are 8-bit?

**Comment by morganwillcock** [comment]
At this point it only has the list of filenames, direct from the file selection dialog box.
