### ISSUE TITLE
master: Deleting (lots of?) lines in the program editing pane makes the Editor explode

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#809]
To be more specific, it makes the Editor hit a failed assertion, which terminates the application.

- I'm building the latest version (commit ab662ebc) of master.
- I call up the Editor and set it to compile the game included below.
- I open GlobalScript and hit CTRL-A DEL (select all the lines and delete them).
- The Editor crashes on the assertion `PLATFORM_ASSERT(line < pdoc->LinesTotal());` in Editor.cxx line 1932.
[Temp02.zip](https://github.com/adventuregamestudio/ags/files/3245603/Temp02.zip)

**Comment by ivan-mogilko** [comment]
This problem persists for years and seems to be a bug in Scintilla.NET component (the script editor).
It only happens when editor is built in Debug configuration.

I could never find spare time to look into this properly, so simply commented the assertion out in my local copy.
The Scintilla version we are using is very old, and this bug could have been fixed in newer versions since.

**Comment by fernewelten** [comment]
> It only happens when editor is built in Debug configuration.

The halt is caused by a failing assertion so this would be the case. I bet Scincilla turns assertions off for production configurations. In this case, the condition would continue to be true in production in the same circumstances that it is in debug, only the assertion code wouldn't halt execution because of it.

Well, the code obviously seems to work without the assertion, so the assertion itself seems to be wrong.
Right, I'll comment out the assertion.

**Comment by ivan-mogilko** [comment]
I have pushed this changed to all active branches, this hopefully will prevent anyone else getting into this problem.

**Comment by fernewelten** [comment]
Thank you!
