### ISSUE TITLE
AGS3: Investigate other methods of linking games to save game data

### ISSUE THREAD

**Issue by sonneveld** [adventuregamestudio/ags#812]
@ivan-mogilko :
> I think there might be better ways to do same thing, like write game's GUID instead, then preload game file's header and check for GUID. This is something to consider.

> And I'd rather consult with game developers who use this multigame technique first before deprecating anything, because they might want to use same behavior on Linux or other platforms.

**Comment by ivan-mogilko** [comment]
TBH I've been thinking about doing this with a new save format but perhaps forgot when started implementing it. It is doable right now, and only requires a tiny update to save format.

For the long-term development it may also make sense to review the whole multi-game concept in AGS, because right now there are few other awkward moments. From the top of my head, iirc all games will reuse same config settings, and will be using same audio and speech packs together since they all have to be located in same directory.

**Comment by ivan-mogilko** [comment]
Partially solved by 4283256a4e16f24cc90c4207e5321f2b31d9a2ac, this makes it use game GUID to test if save belongs to the game, which is much more reliable.

What's left perhaps is, if game does not match, then engine should scan the same directory for other game files and check their GUIDs. This is doable, need to write a function that preloads necessary data, similar to existing preload_game_data (may factor out some code).

But then there's another problem, old pre-3.* games do not feature GUID, they have some "uniqueid" integer (I don't remember how it's generated so idk how unique it is). If we want to be also able to match these we need to append this "uniqueid" into save  file header where GUID currently is.

**Comment by ivan-mogilko** [comment]
Should be resolved with 13296721deb5bebc9ec8b624eea5b9bd3eba2c54, 34945b9c8d7b4670640dc33a7c4132274375d346, f713561f0e7f8b1c5f15485247e708bb4e7e89b1

With these changes savegame format now has enough information to identify the game (using new GUID or legacy uniqueid field). If the ones found in save's header do not match current game, then it will search for other game packs within same directory. Thus multi-game collections still should be working as before.
For old format saves which do not include neither ID there's still a relatively unreliable fallback which compares data file names. It should remain so long as engine supports older save format.
