### ISSUE TITLE
MAXSAVEGAMES  50

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#816]
with quest for infamy, i'm constantly hitting this limit. this is pretty annoying, i constantly have to delete old savegames.

the gui part even seems to be unable to display more than the latest 20 savegames (macro gets redefined). can't really figure out a good reason why it shouldn't be possible to display all savegames in the listbox.

**Comment by ivan-mogilko** [comment]
This is one of those things that continiously get postponed because they are "less important". (This limit only persists if developer used built-in functions to fill the save list)

Should be trivial to remove though.

**Comment by ivan-mogilko** [comment]
> It should be trivial to remove this limit.

Hmm... ok, not so trivial, because of this: https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/game.cpp#L2504

**Comment by sonneveld** [comment]
Is it possible for the game to determine if there's enough space for a new save game? Or does it have to rely on an error message occurring on save?

**Comment by ivan-mogilko** [comment]
> Is it possible for the game to determine if there's enough space for a new save game? Or does it have to rely on an error message occurring on save?

Do you mean a disk space, an available save slot, or available slot in the internal array?

**Comment by sonneveld** [comment]
> Do you mean a disk space, an available save slot, or available element in the internal array limited by MAXSAVEGAMES?

I guess all of the above. I know some games already check if the savegamelist has 50 items so they can show their own message.

**Comment by sonneveld** [comment]
`The SaveGameDialog function uses slots numbered from 1 to 20` <-- from the manual, is this still true?

**Comment by sonneveld** [comment]
Also, some games use custom save slot numbers (like 101, or maybe even 21) for auto save. They can pick these numbers because the engine dialog reserves slots 1-20.

**Comment by ivan-mogilko** [comment]
MAXSAVEGAMES is an arbitrary limit only used in default API functions which display list of saves. Probably intended to emulate old Sierra games.
AGS itself technically supports save slots from 0 to 999, with 999 usually reserved for automatic checkpoint.
I don't think it tests for available disk space before trying to save.


> Also, some games use custom save slot numbers (like 101, or maybe even 21) for auto save. They can pick these numbers because the engine dialog only reserves slots 1-20.

Yes, I did not consider that at first. This could be a real problem.
Removing the list limit itself is not that hard, but this has to be somehow consistent with the script API.
Game developers must be able to limit what is shown in these automatic dialogs.

Also, there's no way to predict game expectations about reserved slots without practical experiment.

On a quick thought, what may be possible to do for now is:
- remove array limit in code
- enforce the limit of 20/50 saves by default
- add a config option to override it (there's an "override" section in config for similar purposes).

Above would allow to have more saves in legacy games. This config option has to be annotated with a warning that this is not compatible with reserved save slots and should be used with care.

This is as much as I can suggest right now. But guess ideal solution is to revise savegame API by e.g. allowing developers to tell the range of slots shown in the listbox.

**Comment by ivan-mogilko** [comment]
PS. Actually, the obvious workaround (which I used myself in some games, even in old Sierra games like QFG) is to move older saves to subdirectories and copy them back when necessary.

**Comment by sonneveld** [comment]
> * add a config option to override it (there's an "override" section in config for similar purposes).

Instead of a config option, we could search scripts to see if they use `SaveGameSlot` or `FillSaveGameList`. If not used, then we could allow more saves in the save game dialog.

> I don't think it tests for available disk space before trying to save.

Currently we check if at least 2 meg is available. Which isn't quite enough for larger games. Refer to https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/game.cpp#L1096

**Comment by sonneveld** [comment]
PS. It's on my list to investigate using zlib to compress the games, so instead of saves being 2-8 megs, they're only 64k to 700k.

**Comment by ivan-mogilko** [comment]
How does the save size and disk space is relevant to this particular request?

> Instead of a config option, we could search scripts to see if they use SaveGameSlot or FillSaveGameList. If not used, then we could allow more saves in the save game dialog.

This would require to run through all the script modules and all the room scripts, parse the byte code, and resolve import fixups.

**Comment by sonneveld** [comment]
> How does the save size and disk space is relevant to this particular request?

It's another variable that can determine the max save game limit. Sorry, wasn't trying to derail discussion.



> This would require to run through all the script modules and all the room scripts?
> Also plugins may call these script functions too.

Ah I didn't consider plugins. I guess if plugins exist, you can't expand either.  But I thought scripts only had the function imports they used?  At least from the scripts I've looked at. It's how I was able to determine which functions were used over time.

**Comment by ivan-mogilko** [comment]
> we could search scripts to see if they use SaveGameSlot or FillSaveGameList. If not used, then we could allow more saves

I'm afraid this kind of detection also does not have much sense, because it is FillSaveGameList that has 50 slots limit, the one that is suggested for removal. Such detection would leave only SaveGameDialog() with 20 saves which is not used often in recent games.

**Comment by rofl0r** [comment]
> Is it possible for the game to determine if there's enough space for a new save game?

this is a valid concern, but it shouldn't be necessary for the game itself to deal with it.
it's sufficient to know for the game whether `SaveGame()` or however the script api function is called fails or succeeds. the game can then display something along the lines of "saving failed, check disk space and write permissions".

> A IsSpaceAvailableForSave() or something.

that would be prone to race conditions e.g. some other process writes to disk and when you call IsSpaceAvailableForSave() it would return true, but when you then try to actually write it could fail because the other process just happened to write some more bytes between the 2 calls.

**Comment by morganwillcock** [comment]
Some platforms don't have valid free space checks.
https://github.com/adventuregamestudio/ags/blob/ags3/Engine/platform/linux/acpllnx.cpp#L141-L144

**Comment by rofl0r** [comment]
> Some platforms don't have valid free space checks.

right. the only valid way to check for this is to simply try to write, and if it fails, one can look at errno to determine the cause, if one really wants to.

**Comment by morganwillcock** [comment]
>right. the only valid way to check for this is to simply try to write, and if it fails, one can look at errno to determine the cause, if one really wants to.

Yes I agree, because otherwise you also have to accomodate differences in how different filesystem report freespace as well as how you would establish that the location is writeable.

**Comment by ivan-mogilko** [comment]
So, to sum up, there are following relevant problems:

 **Legacy API.**

1. There's an internal array (50 slots) that stores "file indexes", a result of of the *last* call to FillSaveGameList script function. This array is a part of legacy API, it is exported to scripts as "savegameindex" global array. Array was used along with functions like ListBoxSaveGameList and contained save slot indexes corresponding to save names in list box. (This information may be found in old manuals)
This array may be either replaced with std::vector or simply expanded to 1000 slots because right now AGS has 1000 save slots max (0 - 999). If it's turned into a vector, then it's manager should also be replaced into a new variant of StaticArray class which translates legacy memory access (won't go into details much here, but examples may be found in code).
Of course if old games impose same limit in their own script, they won't be able to use more slots unless you hack these scripts.

2. There's storage limit (20 slots) for built-in Save/Load dialogs called with SaveGameDialog() and RestoreGameDialog() functions, but this storage seem to be completely disconnected from anything else, and therefore may be easily changed to dynamic array or std::vector, hence allowing any number of save slots.

---

**Contemporary API**

3. There's arbitrary limit (50 slots) when filling list box using ListBox.FillSaveGameList, but because ListBox itself is no longer limited by number of items it may contain that slot restriction may be trivially removed.

---

**Logical problem**

4. The problems above are all technical, but even if they are solved there's still a logical problem. As @sonneveld noted earlier, some games may take this old 20/50 slots limit into account and use any above slots for special use: such as automatic checkpoints or even storing "game levels" as saves (I've seen this couple of times before).

This leads to two questions:
* how to deal with this in new games? Apparently script API has to be adjusted to either allow to limit number of saves filled with the call to ListBox.FillSaveGameList, or changed further and separate "regular" slots and special slots which do not mix. Or maybe save slot system may be revamped into something different in the future versions (but that's an issue for another day).
* how to deal with this when running old games, if you want engine to override their saves limit. What I suggested earlier is a config option that would tell engine to just ignore this constraint. Of course in particular games this may lead to unconventionally used slots also getting in this list, but this can't be helped and player just should be aware of this and be careful.

**Comment by sonneveld** [comment]
> that would be prone to race conditions e.g. some other process writes to disk and when you call IsSpaceAvailableForSave() it would return true,

I agree there's an issue with race conditions, but that's assuming there are other processes writing to disk :)

**Comment by ivan-mogilko** [comment]
Fixed by #2541.

Among other things added a new config setting:
```
[override]
max_save=N
```
where N will be the topmost save used in standard save/restore dialogs.
