### ISSUE TITLE
future backwards compatible modifications to game file layout

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#828]
while working on [agsutils](https://github.com/rofl0r/agsutils), i constantly run into errors with newer games due to modifications to the game file headers. hunting these down requires a lot of effort, single-stepping through ags engine and my code at the same time.

e.g.:
https://github.com/rofl0r/agsutils/commit/5f042f82ab511f2a893c8415c58f884848796d1c
https://github.com/rofl0r/agsutils/commit/6d679e24178bc6e47e1520c260a19d5a39984cd0

i would suggest a method to keep gamefile modifications backwards compatible.
current gamefiles have an array of 17 reserved ints:

```cpp
    in->ReadArrayOfInt32(reserved, NUM_INTS_RESERVED);
```

for future engine versions, we could use int1 of the struct to signify total bytes of extensions added (`int total_extension_bytes`), and the extensions itself would be placed at the end of the existing header, i.e. straight after views are read.
the next int in the reserved block (`extension_count`) could signify how many extensions are added.
each extension itself could then start with an int `extension_length` signifying the total length of this single extension, followed by a string of a hardcoded length of e.g. 16 containing the name of the extension. for example "ExtSpriteInfo".
the engine can then determine whether it has code for handling "ExtSpriteInfo" extensions, and if not just skip the extension_length bytes to the next extension and so on. the data in the block after the extension name could be entirely extension-specific that way.

a tool like agscriptxtract would simply read `total_extension_bytes` from reserved[0] and skip the bytes after parsing the rest of the header.

**Comment by ivan-mogilko** [comment]
> hunting these down requires a lot of effort, single-stepping through ags engine and my code at the same time.

I am curious why this is necessary. Cannot you refer to new format constants and find out where they are used instead?

**Comment by rofl0r** [comment]
> Cannot you refer to new format constants

it's not that easy. in recent ags code, the code to read gamefiles is spread over several files, often there is use of >= with a higher revision etc. i tried this too the last time, after i realized via single-stepping in which area of the code roughly an error happens.

anyway, i think my proposal above is pretty sound from a technical perspective, and it could even allow to play newer games with older engines, by skipping extensions that are not recognized (in case the extension is not critical, the game could still work - ofc a warning should be printed). what's your impression?

**Comment by ivan-mogilko** [comment]
Well, yes, having an information about data ahead is ofcourse a good thing.
The way to organize this is something that need a good thought, especially if we consider long term. Also, there are numerous object types in game, each of which may be expanded in theory (not only in global game data, but also in rooms).

**Comment by ivan-mogilko** [comment]
I'd also like to note that extensions do not cover all cases, sometimes we remove or replace data too. For example, if something is not needed anymore, or was replaced by something of a better concept. Or when we removed arbitrary limits of N elements per array.

**Comment by rofl0r** [comment]
> sometimes we remove or replace data too

good point. if they had been implemented as i proposed though, they could simply be left out of the extensions blob.

as far as removal of existing functionality is concerned, i'd argue that it would be best to keep the data structure untouched. saving e.g. 4kb overall isn't really worth the trouble to add new special case code, when most modern games are several hundred MBs anyway...

**Comment by ivan-mogilko** [comment]
> as far as removal of existing functionality is concerned, i'd argue that it would be best to keep the data structure untouched. saving e.g. 4kb overall isn't really worth the trouble to add new special case code, when most modern games are several hundred MBs anyway...

I don't know, it seems like a "dirty" solution to me.

For example, room data is currently saved as a sequence of "blocks", where each has got a "meta" header, and afaik there's table of contents (or it's possible to write one).
Newest savegame format is structured in a similar way.

In this case you'd only parse a "block" if you supports its version and skip otherwise (because it won't make sense to read anyway).
And if you need to extract only particular data you can use TOC to seek there.

Main game data could be also made same way.

**Comment by sonneveld** [comment]
> For example, room data is currently saved as a sequence of "blocks", where each has got a "meta" header, and afaik there's table of contents (or it's possible to write one).
> Newest savegame format is structured in a similar way.

Yeah the room blocks structure is a nice generalised system for skipping data you don't want.

If you really want a nice future compatible format, we could support the xml game.agf file, or a json version. With compression, it wouldn't be too big.

**Comment by rofl0r** [comment]
> nice ... xml

are you serious? XML is the worst format for everything. parsing it is so hairy you can't do it without an external library, and even those XML libraries that are around since decades still get a couple new CVE's every year...

> One option, out of many, could be https://google.github.io/flatbuffers/

your eagerness to throw well-working code over board to use random new 3rd party stuff instead never ceases to amaze....

my proposal is to make the current format future proof with a tiny change that would add at most 50 lines of support code (if efficiently written), not throwing everything over board for a worse-is-better rewrite.

> Yeah the room blocks structure is a nice generalised system for skipping data you don't want.

i will take a look, but i doubt it will be much different/better/simpler than my idea.

**Comment by sonneveld** [comment]
> Why XML?

I actually suggested XML or JSON, so I was suggesting we investigate some sort of text based format instead of extending our own binary format. I agree that XML has its problems but we already have a working structure in the the game editor xml source format, so that might mean less bike shedding initially if we try to work within the confines of an original format. XML and JSON already have many C and C++ implementations.

> XML is difficult to parse without an external library.

I have no problem using external libraries for these common formats. They're written by people who are much more familiar with the topic and they have the time to find and patch CVEs, which we don't have eyes to find or time to fix when we write our own parsing libraries.

> my proposal is to make the current format future proof with a tiny change that would add at most 50 lines of support code 

I think a lot of us are tired of trying to put in new features into the current code base, so I was thinking ahead for what it would look like for the next version of AGS. Most likely we would not use the current gamefile format at all.  

What feature are you trying to add right now that requires a change to the game format?

Perhaps new features could be configured with their own data file (text or otherwise) that is bundled alongside the main game data file in the clib. This allows you to be extensible without having to modify working code.  Clib already lets us have named multiple sections in the form of files, so why not rely on that?

> Why would you prefer to use an external library instead of modifying our current code?

We're a small group of developers. Why are we reinventing the wheel for storing binary data and resources. These are problems that have been mostly solved in the last couple of decades. In the future, why not generate our game data in JSON or a standardised binary format, saved alongside all other resources in a zip file?

Flatbuffers is one of many similar libraries out there. Instead of having to manually write parsing/generation code for different languages (C++, C#, python, etc), you would define a schema once and rely on generated code to parse our game data.

**Comment by fernewelten** [comment]
A low-maintenance alternative would be to **not** provide any backward compatibility whatsoever. 

There would be a standalone converter that re-writes Game.agf to the newest version, renaming the original old file to Game.agf.old on the way. That would be the one and only place anywhere that caters to old game file versions.

All the other parts of AGS, the Engine in particular, start with checking the format and refuse all formats except for the newest shiniest current one. All code anywhere in any AGS component that deals with old versions would be cut out of the respective component and relocated to the converter.

For future AGS versions onwards, the converter could be limited to accepting formats that are at most, say, two years old. Any older files would have to be converted in a daisy chain until they reach the current version.

**Comment by sonneveld** [comment]
> There would be a standalone converter that re-writes Game.agf to the newest version, renaming the original old file to Game.agf.old on the way. That would be the one and only place anywhere that caters to old game file versions.

I've actually been thinking about a migration tool of some sort. Right now we have that tool in the form of upgrading game source to the current version in the editor, but it's not as useful for compiled games.

**Comment by sonneveld** [comment]
> are you serious?



> your eagerness to throw well-working code over board to use random new 3rd party stuff instead never ceases to amaze....



> not throwing everything over board for a worse-is-better rewrite.



> but i doubt it will be much different/better/simpler than my idea

I tried to address your comments above without mentioning your tone.  I'm happy to have a technical discussion with you, but it makes it 10x harder when I have to separate your arguments from your attitude.

**Comment by rofl0r** [comment]
> I tried to address your comments above without mentioning your tone.

then why do you do now ?

**Comment by sonneveld** [comment]
> then why do you do now ?

I wanted to give everyone a chance to talk about the ticket first.

**Comment by ivan-mogilko** [comment]
Something overdue, I wanted to add to this discussion for a long time but kept forgetting.

If I understand correctly, @rofl0r 's primary reason to bring this up was this that he has to maintain a script extracting tool, and because bytecode is packed inside a bigger file containing various data. When that data format expands, the script appears on another offset which requires to adjust the program.

While having a format that describes its extensions is a good thing on its own, and definitely should be considered for the future (I wish we'd considered this years ago), the problem with scripts in particular may be solved much easier: by saving them as separate asset entries inside the game package. This will make it 100% futureproof because independent of other data formats. And also will go well along with the separation of building tools, since they won't have to merge scripts with other game data as an extra build step, but just add script object files into the package.

**Comment by rofl0r** [comment]
> saving them as separate asset entries inside the game package

what's the difference to how it's done now? would it mean that e.g. room scripts are then saved in game28.dta too ?

> let engine to load compiled scripts directly from directory (unpacked)

that's ok for me, but there's a reason these files were packed into a container to begin with:
many small files waste harddisk space because they're saved in clusters/inodes that are a multiple of 4KB, and some filesystems have problems with a huge number of files (e.g. FAT32)

**Comment by ivan-mogilko** [comment]
> > saving them as separate asset entries inside the game package
> 
> what's the difference to how it's done now? would it mean that e.g. room scripts are then saved in game28.dta too ?

Maybe you have got an idea opposite to what my meaning was. When I say "game package" I mean CLIB format (like game.ags files). game28.dta is an asset inside the clib package, it contains basic game settings. The main scripts are currently stored inside game28.dta. I suggest to store scripts as separate assets in clib instead, so that one could extract them directly without meddling with game28.dta.

*In theory* similar thing could be done for room scripts too, although there's more to consider there (how convenient that would be etc).

**Comment by rofl0r** [comment]
> When I say "game package" I mean CLIB format

ah ok. there's so many encapsulations layer that i got confused, and i didn't look at the code since quite a while.

>  I suggest to store scripts as separate assets (files) in clib instead, so that one could extract them directly without meddling with game28.dta.

that sounds reasonable.

still, i do think that my initial idea allows a path to add extension without implementing new ad-hoc solution every time. in the context of agsutils i sometimes do need to parse more than just script objects, for example when i added the sprite extraction tool.

**Comment by rofl0r** [comment]
> for example when i added the sprite extraction tool

speaking of it, i recall the thread about bmp mask saving issues done by .net -> winapi -> wine. when i implemented agsprite i evaluated almost all popular image formats and found .tga to be the simplest by far, while being quite powerful. i think one could support it in about 200-300 lines of native C++ code and write/read images directly without relying on external libraries. it supports 8,16,24,32 bits, rle-encoding and palettes or rgb.

**Comment by ivan-mogilko** [comment]
> there's so many encapsulations layer that i got confused, and i didn't look at the code since quite a while.

That's true, the above solution will also remove 1 layer of encapsulation for scripts.

> still, i do think that my initial idea allows a path to add extension without implementing new ad-hoc solution every time

Yes I understand, still keeping this in mind.

**Comment by ivan-mogilko** [comment]
Alright, I am probably going to try implementing this, primarily for ags4, but should probably add this into ags3 branch too just in case (only the code necessary to detect extensions, as it's planned to have no data additions there).
In regards to ags4, maybe we'll eventually have different data formats, globally, but this is not something that can be done in a rush, so we could still use something simple for a time being.

I'd like to implement "data blocks" identical or similar to current room format, which is also very similar to @rofl0r 's suggestion, and hopefully just reuse same code for both game data and rooms.

These extension blocks could be then expected after the end of current game data if the format id is higher than 3.5.0.<br>
I was re-reading original suggestion above, and it sais
> the extensions itself would be placed at the end of the existing header, i.e. straight after views are read

but don't quite understand the reasoning behind this, maybe we see this format differently. Like, what is the "header" in this context, why the views data serve as an insert mark, and why not have extensions after everything that currently exists?
With extensions in the very end you also don't need to have "total_extension_bytes" written there, as everything after main data will be considered extensions. Unless I miss some potential problems here.

In regards to changing existing data, something I had in mind, if an object fields has to undergo significant changes, too many old ones deprecated and replaced, the solution could be to set *old "object num"* field to 0, don't write object array on the old place, and instead write everything in the extension. This is like saying that we don't have objects of old type and have only objects of new type.<br>
I was specifically considering this for parts of data which were written as memory aligned structs in the old engine; currently we use special type of stream to read these with automatically calculated paddings.<br>
But then again, maybe just leave these as they are, until a bigger format overhaul happens someday.

**Comment by ivan-mogilko** [comment]
TODO for myself: assuming this is resolved by #1183, but still need to write a wiki page explaining how it works, so that devs have some guidelines for adding new data.

**Comment by ivan-mogilko** [comment]
Wrote wiki page: https://github.com/adventuregamestudio/ags/wiki/Extending-game-and-room-data-format

**Comment by rofl0r** [comment]
thanks. the wiki page mentions string is `(present only if numeric ID == 0).`.
does that mean the 16 byte block of the string is missing ?
also, does the string need to be zero-terminated ?

**Comment by ivan-mogilko** [comment]
String ID will not be present if legacy numeric id is > 0, and string does not have to be null-terminated (if it fills all 16 bytes that is).
I'll add this to wiki too.

**Comment by ivan-mogilko** [comment]
I also backported reading extension format to ags3 branch, just in case, to let it detect them maybe, or in case someone will be using this for reference.
