### ISSUE TITLE
3.5.0: find out Editor's dependencies

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#860]
Couple of users have reported that AGS.Native.dll fails to load up on their Windows 10, presumably the reason is that they do not have necessary dependencies installed, such as proper VC runtime.

Previously AGS was built using MSVS 2008 and demanded respective runtime library, but now we use MSVS 2015 and toolset, and they impose different runtime dependency.

We need to find out which are these, and document their official names and download links.

**Comment by morganwillcock** [comment]
I imagine it will be this one:
https://github.com/saltstack/salt-winrepo-ng/blob/master/ms-vcpp-2015-redist_x86.sls

Were these originally meant to be bundled with the installer, rather than downloaded?

**Comment by ivan-mogilko** [comment]
> Were these originally meant to be bundled with the installer, rather than downloaded?

Right, they probably should come with installer and suggested in case not found on user's system (like it does with 2008th VC runtime now).
But also they should be mentioned along with download links because many people prefer to download AGS in ZIP archive instead.

**Comment by ivan-mogilko** [comment]
I just gave these links to a person on Windows 10 and he/she tells that first link worked.
(Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24215)

**Comment by morganwillcock** [comment]
Later runtime is backwards compatible and everything also includes the 'universal' components too. So the requirement is the based on the minimum runtime version rather than a specific one. i.e. installing Visual C++ 2019 redistributables will also work.

Based on the VC++ 2015 runtime that was linked above (https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe), the minimum is major version '14.0' and build version '24215'.

For .NET 4.5, minimum requirement is the version 4 release number 378389, as described here:
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed
