### ISSUE TITLE
Define rules regarding current working directory

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#966]
Currently the role of the "current working directory" in the engine is somewhat messed up (so I marked this ticket as a bug). In practice it works well so long as either -
* you run the game from its own directory;
* you pass game's path as a command-line argument; in this case ags switches cwd to that path.

Problems arise if you run the game binary outside of its directory, like `./mygame/agsgame`.

First of all, `installDirectory` variable is initialized as '"."' (current dir), which means anytime it's used cwd will be referenced. This includes files opened with script commands like `File.Open("$INSTALLDIR$/myfile.dat");` and some other occasions.

Secondly, numerous platform-specific paths also default to "current dir" (unless current platform driver specifies actual value), which includes savegame, shared data, user config and log path.

Default game config is also being looked for in cwd.

**So, the questions are:**
1) Should anything in the engine rely on cwd at all? If not, then perhaps there should be explicit paths to all places important for the engine initialized at startup, and any relative path converted to derivative of one of those paths.
2) Should initial cwd mean anything for the engine or be ignored and replaced with e.g. game location?

**Note that there are at least two known special cases for cwd:**
1) When the game is run from the IDE engine is supposed to keep initial cwd, as it contains some of the raw (unpacked) project files, while the `installDirectory` is set from command line args and will actually be referring to Compiled/Windows folder. This is done to allow engine read from both places.<br> I think this may be replaced with passing multiple data paths and registering them all in the AssetManager as noted in the addition to #965.
2) Default config file found in cwd may contain "datadir" path, which is a path to where data files are located. So it is assumed that engine at least supposed to read default config file from initial cwd. Frankly, I do not remember any actual game that would use this in practice, so don't know if supporting this is even required. Perhaps there could be other ways to achieve similar result.

**Comment by ivan-mogilko** [comment]
I'd like to add a tip, just in case, if you are debugging this using an IDE, like MSVS, then you cannot run the engine from the solution folder, because as noted above:

> In practice it works well so long as either -
you run the game from its own directory;
you pass game's path as a command-line argument; in this case ags switches cwd to that path.
Problems arise if you run the game binary outside of its directory, like ./mygame/agsgame.

In order to replicate the problem the debugged engine should be copied to the game's folder, and run by setting it a debug target directly. You *should not* pass game location as an argument.

**Comment by ivan-mogilko** [comment]
Did some changes to this. Mainly related commits are: 02c74db1634d9950d823c5ca7187897faec9ea9e, 33124e9874489b28ba6dba00b7133caff70a12df, c57ff51a660fc0d37349f9c2a51811ceb2054ba1 .

Now engine does not change cwd at all on its own. Instead it resolves any relative paths using following rules:

* Input paths from command line are resolved as relative to cwd;
* Input paths from config options are resolved relative to main data dir;
* Paths defined in engine or script are resolved relative to main data dir.

Running game binary using a relative path from another working dir suppose to have same effect as running it from its own dir.

**Comment by ivan-mogilko** [comment]
As an extra note, there's still the #662 which describes a problem on Linux where Allegro file functions may turn paths with utf8 characters into garbage when turning relative paths into absolute ones, because they are relying on unicode conversion rules set in program. I was planning to take a look at this, maybe it could be possible to bring utf8 support at least for filepaths in the engine.
