### ISSUE TITLE
In graphic renderers replace SpriteBatch list with a SceneNode tree

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#967]
Sprite batches were added in 3.5.0. SpriteBatch is a parent entity of a group of sprites, which defines their global render transformation: offset, scaling and rotation (latter not supported in practice yet), and few others. This transformation is merged with each child sprite's own.
SpriteBatch may be thought as a "directory" for sprites, which applies shared settings.
Currently sprite batches are stored sequentially in a linear list, and rendered in the same order.

This system has limitations, and for some situations it may be more convenient to allow child sprite batches inside the parent. Also there's currently no expliciy way to end the list of sprite batches (it's reset automatically when final Render is called).

Thus the suggestion is following:

1. Have a generic struct called "Scene Node", "Node" or "Scene". The SpriteEntry is either derived of that Node struct or merged with one (whichever seem convenient).
2. Remake list of sprite batches into the tree, where each node may be a parent of more nodes, and you may have sprite entries and "group" nodes on the same level.
3. When deciding on the final sprite's transform, SpriteEntry/Node's transformations are applied from bottom to top (logically, actual matrix order is renderer-specific).
4. The preferred API is not clear at this point, and there is also #969 that may affect its selection, if get accepted. But I believe that there should be a way to mark beginning and ending of the scene, for explicitly indicating when we begin sending data for the next render step and when we finish doing so. This should make it clear throughout the engine code where scene begins being constructed and where it ends.

**Comment by ericoporto** [comment]
What is the usage of an 'EndSpritreBatch'?

Also, in the SceneNode tree, suppose we have two viewports in a game, and they, point to the same camera, or point to a different camera. I am trying to understand the order the transformations are supposed to be applied, is each viewport a node, and both has all things in the room as children, and the window itself is a root node? I am having some difficulty understanding the tree without a drawing :/

**Comment by ivan-mogilko** [comment]
> What is the usage of an 'EndSpriteBatch'?

Hypothetically, tell renderer that you finished adding items to current sprite batch.

> Also, in the SceneNode tree, suppose we have two viewports in a game, and they, point to the same camera, or point to a different camera. I am trying to understand the order the transformations are supposed to be applied, is each viewport a node, and both has all things in the room as children, and the window itself is a root node? I am having some difficulty understanding the tree without a drawing :/

The tree is simply a way to organize multiple children in the same node. For an individual object the tree structure may be ignored, and instead you have a line which goes through all its parents up to the root node, for example:

Window <- Game screen <- Room viewport <- Camera <- Room object

**Comment by ericoporto** [comment]
gl has the idea of [pushing and popping a transform matrix](https://community.khronos.org/t/push-and-pop-matrixes/55892/2). For the API, pushing and popping a node handler/identifier could be a way to construct the API so that a leaf node and it's group of nodes are clearly different.

**Comment by ivan-mogilko** [comment]
An possible implementation of the "scene node" tree in the renderer does not have to be a literal tree. Because the batches (nodes) will be passed into the renderer sequentially, and child nodes will always concede parent ones, more optimal variant may to have a linear vector. In this case the child nodes may refer to their parents simply using this list's index, if necessary.

When rendering these nodes, renderer will merge transformation matrixes and other parameters from parent to child, that's easy. In theory it could do a counter operation when ending current node level. This may work for a transformation matrix, but it's not clear whether this may work for other settings, such as transparency, because these may be clamped. If that's the case, then the solution would be to recreate current level's "parent matrix" from top to bottom each time a level changes upwards (we go one tree level back). For that we'd have to use that child->parent reference to be able to track the relation back.

As per renderer's interface, as noted before, with the tree structure there has to be a corresponding function to end the batch, as having only BeginSpriteBatch/Node will be insufficient to distinguish "begin child batch" from "begin sibling batch".
I.e. a graphics renderer should have
- BeginSceneNode;
- EndSceneNode;
where BeginSceneNode will create a sub-node of the current node, while EndSceneNode will return the "cursor" to the parent node.

**Comment by ivan-mogilko** [comment]
Technically this is resolved within #1393 now.
