### ISSUE TITLE
Missing translation for String::Format parameters

### ISSUE THREAD

**Issue by adm244** [adventuregamestudio/ags#990]
Parameters that are being passed into String::Format function are never translated except the format specifier.

Some games like Dustbowl use String::Format to get result strings like "`<Name>:[<Text>`". TRS file is populated with `<Name>` and `<Text>` parts separately. AGS only searches for translation of "`%s:[%s`" (format specifier) and a result (like "`Joe:[Hello, World!`") strings which are missing in TRS file.

Here's a sample code demonstrating an issue:
```ags-script
function SpeakAsFormat(this Character *,  String format)
{
  String formattedText = String.Format(format, this.Name);
  this.Say(formattedText);
}

function SpeakAsFormatPart(this Character *, String text)
{
  String formattedText = String.Format("%s: %s", this.Name,  text);
  this.Say(formattedText);
}

function room_AfterFadeIn()
{
  player.Say("Normal player say. Works fine.");
  player.SpeakAsFormat("%s: Text as a format string. Works fine, too.");
  player.SpeakAsFormatPart("Text as a part that goes into a format string. Broken.");
}
```

Potential fix. Wrap `p` in `get_translation` here:
https://github.com/adventuregamestudio/ags/blob/8791da72b35ac151f025636f1bc05a3655b6336a/Engine/script/script_api.cpp#L214

**Example game**
Here's example game built in *AGS 3.5.0.20 RC4*.
Runtime: [TranslationBug_runtime.zip](https://github.com/adventuregamestudio/ags/files/3861367/TranslationBug_runtime.zip)
Source: [TranslationBug_source.zip](https://github.com/adventuregamestudio/ags/files/3861368/TranslationBug_source.zip)

Runtime contains game executable, tra file with a work-around and patched acwin that fixes an issue.

**Comment by ivan-mogilko** [comment]
This is not a bug. Scripter is supposed to use GetTranslation for those format arguments that are supposed to be translated, because not all of the strings should be translated.

**Comment by ivan-mogilko** [comment]
This is not a bug, but done intentionally. For instance, you could also test any previous version of AGS and observe same results.

The reason arguments are not translated automatically most probably is that AGS cannot know which of these are _supposed_ to be translated. This may depend on gamedev's intentions.

This is what GetTranslation function was made for. Normally, game scripter is supposed to wrap a string argument into GetTranslation, e.g.:
<pre>
String formattedText = String.Format("%s: %s", GetTranslation(this.Name), GetTranslation(text));
this.Say(formattedText);
</pre>

This may be not convenient, and suggested for future discussion, but definitely not a bug.

Note that there are other places where AGS intentionally does not do auto translation, like few more String functions, such as CompareTo or IndexOf and so on.

**Comment by ivan-mogilko** [comment]
To elaborate on above, a good example why automatic translation of arguments may be not wanted: argument values could be not a literal string, but a variable, constructed according to some rules, or even player's input.

**Comment by ivan-mogilko** [comment]
I'd like to amend, just for reference, in case this question will arise once more in the future (and because I am not fully happy with my first response).

The reason why the low-level utility functions, like String.Format, _should not_ be automatically translated is that not only we don't know the meaning of formatting arguments, but also because we do not know the _purpose of the resulting string itself_.
* It could be a human-readable text displayed on screen, and even then, maybe it's a kind of message that supposed to remain unchanged; e.g. it's written in a pseudo-language of a game universe.
* It could be encrypted.
* It could have utility function: storing custom game data, writing data to file.
* It could be utility name, like filename, actually, and so on.

For this reason, on contrary, I'd rather question why String.Format translates the formatting string. Guess this was done for convenience, and also because it's usually a literal string that will be found in TRS and thus could be controlled (left untranslated if necessary); but IMHO that's still not formally correct.
I guess, in the future it may be worth discussing ways to improve AGS translation system.

**Comment by fernewelten** [comment]
I don't think that that's how the localization functionality works, anyway. 

As far as I can see, the strings that are offered for localization are simply all the string literals in the sources . In other words, the functionality simply scans the sources for characters that are enclosed in quote marks. (Additionally, it adds some data that is set in the Editor, e.g., the "name" entries for objects, inventory icons etc., but this isn't relevant here.)

So the `String.Format` function is a red herring. The reason that `"%s:%s"` is offered for translation is simply that it happens to be a string literal, not that it is in a certain parameter position of some `String.Format` function call.

You could have the following in the code:
```
function DontSayAnything()
{
    String IAmCompletelySuperfluous = "###%s:%s###";
}
```
… and `###%s:%s###` will still end up in the .trs file -- simply because it happens to be quoted in a source file.

**Comment by adm244** [comment]
@fernewelten I must add to this that a literal string `###%s:%s###` will end up in the TRS file, but it won't be translated unless it is passed into a function that calls `get_translation` (and not all of them do).

Let's be honest, current translation implementation is just garbage. You have to hack your way around it all the time even if you're a developer and have a full source access. Metaphobia devs made an attempt translating it in German, it got so frustrating they never finished it. Dustbowl can't be translated without patching either engine or game script like many other games out there (i.e. Blackwell Epiphany). There's no Unicode support, so forget about languages like Chinese. Want to translate textures? Go and mess with sprindex file at runtime or replace original graphics. There's just so many issues with it that you don't want to touch it, it smells.

Btw, there's also was (not sure if still is) an issue with substrings. For example, you animate text so it appears on screen character-by-character. Well, bad news, Johnny, there are no substings of that string in TRS file, so it won't get translated until animation is finished.

**Comment by rofl0r** [comment]
> Want to translate textures? Go and mess with sprindex file at runtime or replace original graphics.

this can now actually be done with `agsprite` of agsutils. :)

> There's no Unicode support

what exactly is missing there? support in alfont engine? it should be possible to save UTF8 encoded strings using current string handling routines.

**Comment by ivan-mogilko** [comment]
> Metaphobia devs made an attempt translating it in German, it got so frustrating they never finished it

What happened to them? German and some other European languages seem to be relatively easy to add. AFAIK there's whole bunch of games done in German originally (Maniac Mansion Mania series).

> Btw, there also was (not sure if still is) an issue with substrings. For example, you animate text so it appears on screen character-by-character. Well, bad news, Johnny, there are no substings of that string in TRS file, so it won't get translated until animation is finished.

This issue may be solved on dev's side with getting translation of a full string before cutting it down to letters/parts, using GetTranslation, so you animate already translated string.

**Comment by ivan-mogilko** [comment]
> There's no Unicode support

> what exactly is missing there? support in alfont engine? it should be possible to save UTF8 encoded strings using current string handling routines.

One has to replace all string operations with the ones that assume utf8, in both engine and editor (where it's lacking).
TBH I cannot immediately tell if there will be any further problems, could be not too difficult, it just has to be thoroughly investigated first.

**Comment by adm244** [comment]
> This issue has to be solved on dev's side

Among many other things. The question is how much games are actually programmed that way? Judging by amount of games that have those issues, the answer is -- virtually none. Devs either don't know how to solve it or they don't care.

> What happened to them? German and some other European languages seem to be relatively easy to add.

If you don't have to replace tons of images, because you've made a poor decision of implementing buttons as pictures, which they did. The fact is, they left tons of if statements to check if current translation file is `German` and then something like `btnNewGame.NormalGraphic = 123`. They also left a little suprise for anyone who's attempting to finish what they did not -- `Game.ChangeTranslation("")` in `game_start()`.

**Comment by rofl0r** [comment]
> PS. From the top of my head, the script API would have to be adjusted to have different "character" type.

why? utf-8 uses one byte-per-character for ascii, and multi-byte for international, but all multibyte chars have top bit set. so it's compatible with char* based string pointer handling functions, like strcmp, strlen etc. so it keeps working just fine with ascii stuff, and only when you actually need to detect a single multi-byte character as such, a little code doing bit ops is required. this would be needed if you e.g. manually render a text, but not if you just pass it to a utf-8-aware font rendering library.

**Comment by messengerbag** [comment]
> If you don't have to replace tons of images, because you've made a poor decision of implementing buttons as pictures, which they did. The fact is, they left tons of if statements to check if current translation file is German and then something like btnNewGame.NormalGraphic = 123.

That sounds like bad coding without any consideration for translation, more than an issue with the translation system. And I don't think it should be a design goal for AGS to make it as easy as possible for third-party groups to replace game graphics.

While the translation system could certainly be improved, just getting Unicode support would fix 99% of the problem of producing non-English games and localizations.

**Comment by messengerbag** [comment]
> so it keeps working just fine with ascii stuff, and only when you actually need to detect a single multi-byte character as such, a little code doing bit ops is required.

Well, for full support, the AGS editor would need to accept and correctly store Unicode string literals. `IndexOf()`, `String.Length` and any string manipulation function that depends on index would have to be updated to work with multi-byte characters (ensuring that this doesn't introduce bugs based on the assumption that a string's character length + 1 = byte length), and `String.Chars` could no longer be a `char[]` (or the char type would have to be updated to a multi-byte type, with all the complications this would lead to). Also, `UpperCase()`, `LowerCase()` and string "equality" become a lot more complicated (some letters don't have uppercase/lowercase versions in some languages, they convert to letter combinations, or have variable conversion depending on context, and some variations are considered equivalent, and these rules can differ between languages _for the same letter_).

There are also issues of rendering text that doesn't follow the left-to-right, top-to-bottom reading order, since AGS layout functions assume that text will be laid out horizontally, and break if it exceeds a certain width. Sizing textboxes etc. would probably have to be changed. (I'm not even sure how listboxes usually work in languages that write vertically.)

I would imagine that Unicode support would happen gradually, dealing with some of these issues if and when they actually became a problem.

**Comment by ivan-mogilko** [comment]
> Among many other things. The question is how much games are actually programmed that way? Judging by amount of games that have those issues, the answer -- virtually none. Devs either don't know how to solve it or they don't care.
> If you don't have to replace tons of images, because you've made a poor decision 
> That sounds like bad coding without any consideration for translation, more than an issue with the translation system.

I guess there are two problems here.

Dev's bad idea of coding their game and making it impossible to translate by a third party is one thing, and it's related more to being able to hack someone's game without access to source (decompiling, etc). While that could be improved technically, this is not directly related to translation system (and some game developers will definitely disagree with such approach towards their games, esp. commercial ones).
Guess, there are numerous ways to screw things up for the translators, badly coding image assignment is simple, but to take this to extreme - think of raw-painting letters with DrawingSurface API, for example, how that could be possibly translated without rescripting the game? And then it's possible to have sound-based puzzles that may rely on particular language as well.

So, IMHO this goes down to second problem, and potential solution: AGS should provide a more clear translation API that would **encourage** developers to program their game correctly and make it "translator-friendly".

**Comment by ivan-mogilko** [comment]
**PS** Personally, I believe that for best results engine should support full asset overriding, including scripts and parts of scripts (like overriding selected functions), by loading from an external package. But idk how to balance this with dev's wish to protect their game from undesired hacks.

**Comment by rofl0r** [comment]
> ensuring that this doesn't introduce bugs based on the assumption that a string's character length + 1 = byte length

ensuring that there are no bugs is always a good idea. :)

> String.Chars could no longer be a char[] (or the char type would have to be updated to a multi-byte type, with all the complications this would lead to).

depends whether the access needs to be done in O(1). [] operator could be overridden to just scan the string from the beginning and return pointer to desired byte/sequence (or return it as wchar_t). due to the efficient way utf8 works, this should be fast enough except when dealing with megabyte-big strings.

what i'm trying to point out here is that utf-8 is really effective and can be used without further ado with existing string handling routines, only accessing a single character by char offset rather than byte offset needs a little code (can be implemented in about 20 lines, iirc).
when one instead uses e.g. the horrible UCS2 which m$ selected for windows internals, you basically need to rewrite every function dealing with strings from scratch, and double memory usage for ordinary english games, while not even being able to express all unicode codepoints.
(i wanted to point this out because in the past many bad ideas from M$ made their way into the engine...)

so if adding support for unicode is on the table at some point, it should use UTF-8.

**Comment by ivan-mogilko** [comment]
We do have utf8 in plans, that choice is not a big problem on its own.

**Comment by fernewelten** [comment]
What I'd like to add, from the vantage point of a translator:

By now, **standardized translation file formats** have become the norm that translators are accustomed to. Software that supports the professional translator can deal with those files directly. (Examples for such translator software: TRADOS Studio [market leader], memoq, Deja Vu, OmegaT etc.) .

Unfortunately, the trs files that AGS outputs don't adhere to any standard at all, presumably because AGS predates those standards by far.

For instance there is the very well known and common **"Gettext" translation standard** that deals with so-called "PO files". The current AGS trs files are *nearly* PO files, but not quite.  I don't think it would be hard to make AGS output standard PO files instead of TRS files.

Basically, a PO file is a sequence of translation pairs. Each pair consists of  the source string, prefixed with `msgid`, and then the translated string  prefixed with `msgstr`. A PO file can also have comments that are prefixed with `#`, in particular pointers to where the text came from (start with `#:`) and notes to translators (start with '#.')

That's all there is to a PO file, so those files are still very easy to translate with simple text editors.

Here's a snippet from a PO file that has been partially translated:
```
#: GlobalScript.asc Line 45
msgid "Save game"
msgstr ""
⁠
#. TRANSLATORS: These are fish scales, not bathroom scales although Room 1 is a bathroom!
#: Room 1 object 2
msgid "Scales"
msgstr "Schuppen"
⁠
#:  room302.asc Line 47
msgid "I cant catch the robber![He's too fast for me."
msgstr "Ich kann den Räuber nicht erwischen![Er ist einfach zu schnell."
```

The standard is from the GNU project, but I don't necessarily suggest using any of their code -- ony to adhere to the *standard*.

If we could make AGS output standard PO files instead of non-standard TRS files, some of the advantages would be
* Easier for translators
* Fits into standard workflows
* Automated notes that show the context of the string, i.e., where the string came from 
* Possibility for manually added translator's notes

PS. The most modern and most standardized format for translation files nowaday is XLIFF, but it would be very hard to make the AG studio output XLIFF files.  Moreover, XLIFF files are cumbersome to deal with if you do NOT want to use a translation program or if you just have a text editor. (XLIFF files are XML files that obey specific rules.)

**Comment by fernewelten** [comment]
Perhaps the easiest way to deal with _all_ literal strings to be translated: Make the game engine deal with it. 

Currently, all the strings that are set in the Editor end up as literal strings  in automatically generated source files. So the strings of the Editor basically are a special form of string literals. 

During compilation,  the compiler gets all the source files. It collates all the literal strings and puts them into a special strings memory block.  It also converts all the program commands into a special sequence of low-level machine codes, a Bytecode.

At runtime, an Engine is given the bytecode to interpret it, and this engine is also given the block of collated literal strings. In the bytecode, some memory adresses are specially marked: Those are taken to be relative to the start of strings block.

So here's what I would suggest to deal with translations, say to German:
Collate all the *translated* strings into another memory block, a "German" memory block. Also build a lookup table that says, e.g., that the offset 47 of the "Original" block corresponds to the offset 669 in the "German" block.

The Engine behaves in the usual way when it it set to "Original". However, there is a way to set it to "German"  instead, and when it does, it  converts all offsets into the Original strings block into the corresponding offsets into the German strings block and uses those.

So ALL the strings would be translated in ALL the AGS functions in one fell swoop. No need for special C++ coding in functions such as Character.Say() or String.Format(); they'd all automatically get the already translated strings as their parameters. No possibility for bugs due to someone forgetting to add such special C++ coding somewhere.

If certain strings should NOT be translated, well, then the "German" strings block would simply contain an untranslated copy of those strings.

**Comment by ivan-mogilko** [comment]
@fernewelten 
> Currently, all the strings that are set in the Editor end up as literal strings in automatically generated source files.

This is not accurate, the strings are not only in script, they also are in property fields, which are never put into compiled script.

**Comment by ivan-mogilko** [comment]
Also, may I suggest to split up this discussion to a separate ticket(s)? This is a bug ticket and it's closed.
There are multiple topics discussed here already (unicode, translating strings, case of game logic preventing translators from translating the game, etc), so I am concerned this will end up as a mess of unrelated replies.

**Comment by adm244** [comment]
> The Engine behaves in the usual way when it it set to "Original". However, there is a way to set it to "German" instead, and when it does, it converts all offsets into the Original strings block into the corresponding offsets into the German strings block and uses those instead.

That's almost a good idea. But as Crimson said, not all of the literal strings are end up in a .strings section of compiled script (they are all over the place). If AGS had some sort of string interning system, so all literal strings would be stored in a single memory blob, then you could easily "replace" it at runtime or just populate from some kind of a source that you can swap if needed.

> Also, may I suggest to split up this discussion to a separate ticket(s)? This is a bug ticket and it's closed.

Sure. A separate ticket for each problem would be useful. And leave this ticket just as a reference.

**Comment by rofl0r** [comment]
> PS. The most modern and most standardized format for translation files nowaday is XLIFF

woot? it's the first time i hear of it. and i maintain a linux distro with > 1000 packages.
there are 2 standardized translation systems, one is GNU gettext (which i wrote a drop-in replacement for [here](https://github.com/sabotage-linux/gettext-tiny/)), and POSIX catgets, which is currently only used by 3 packages total (and i mean world-wide, not my distro). so the adoption of GNU gettext in real world software packages is close to 99.99%. adding yet another new incompatible tool/format just makes life worse for everyone having to deal with this stuff.
